### ISSUE TITLE
[Bug] SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by jianyaoo** [cornerstonejs/cornerstone3D#1006]
### Describe the Bug

When using the @cornerstonejs/nifti-volume-loader library to load nifti files in a non-security context, an error SharedArrayBuffer is not defined will be reported

### Steps to Reproduce

1.  In the http environment
2. The nifti file is loaded using the @cornerstonejs/nifti-volume-loader library
3. In the type judgment of the invertDataPerFrame function, a ReferenceError is thrown because the constructor of SharedArrayBuffer on the global object is hidden
<img width="832" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/51156464/cc384a5c-6dc4-4931-b704-6cc1c1cbcf6b">

### The current behavior

SharedArrayBuffer is not defined
ReferenceError: SharedArrayBuffer is not defined

### The expected behavior

In http environment, avoid Referenceerrors

### OS

MAC OS

### Node version

16.17.0

### Browser

Chrome 120.0.6099.216

**Comment by haoxl3** [comment]
> ### Describe the Bug
> When using the @cornerstonejs/nifti-volume-loader library to load nifti files in a non-security context, an error SharedArrayBuffer is not defined will be reported
> 
> ### Steps to Reproduce
> 1. In the http environment
> 2. The nifti file is loaded using the @cornerstonejs/nifti-volume-loader library
> 3. In the type judgment of the invertDataPerFrame function, a ReferenceError is thrown because the constructor of SharedArrayBuffer on the global object is hidden
> 
> <img alt="image" width="832" src="https://private-user-images.githubusercontent.com/51156464/297292246-cc384a5c-6dc4-4931-b704-6cc1c1cbcf6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjk1OTcsIm5iZiI6MTcxMDgyOTI5NywicGF0aCI6Ii81MTE1NjQ2NC8yOTcyOTIyNDYtY2MzODRhNWMtNmRjNC00OTMxLWI3MDQtNmNjMWMxY2JjZjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2MjEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTM5YzVlMTlkMzZlOWQ2NmMxNjM5YTRhNzRjNDA2NDliYjZmZDA0MmY3Y2NhNjBhZTBhZGIzNGMzMThjMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lMSKapsXUfSgi5mCe5gjjoh1QFrdP_cHU0xAF0mPFrA">
> ### The current behavior
> SharedArrayBuffer is not defined ReferenceError: SharedArrayBuffer is not defined
> 
> ### The expected behavior
> In http environment, avoid Referenceerrors
> 
> ### OS
> MAC OS
> 
> ### Node version
> 16.17.0
> 
> ### Browser
> Chrome 120.0.6099.216

I have the same problem. How did you solve it？

**Comment by sedghi** [comment]
you should see here, how you can turn it off https://docs.ohif.org/faq/#what-if-my-setup-does-not-support-the-shared-array-buffers-api

but basically it is about the `init` function inside cornerstone3D core

**Comment by feng-1** [comment]
I have the same problem, have you solved it?

**Comment by sedghi** [comment]
you can turn off the SAB, take a look at the pacakges/core/src/init

**Comment by feng-1** [comment]
> you can turn off the SAB, take a look at the pacakges/core/src/init

`setUseSharedArrayBuffer(csEnums.SharedArrayBufferModes.FALSE)` 
Still an error.
`
headers: {
      "Cross-Origin-Embedder-Policy": "require-corp",
      "Cross-Origin-Opener-Policy": "same-origin",
    }
`
Setting this does not cause an error, but it does not display the image.

**Comment by sedghi** [comment]
We have moved away from shared array buffers. You can take a look at the migration docs [https://www.cornerstonejs.org/docs/migration-guides/intro](https://www.cornerstonejs.org/docs/migration-guides/intro)
