### ISSUE TITLE
Add some more read doc like before for dev

### ISSUE THREAD

**Issue by 1009058470** [cornerstonejs/cornerstone3D#1020]
### What feature or change would you like to see made?

Is there any render pipeline and example for dev to understand how this work?

### Why should we prioritize this feature?

because it is import for other dev who are instersting on this can read and make some change for this repo

**Comment by sedghi** [comment]
we tried our best here, https://www.cornerstonejs.org/docs/category/concepts

**Comment by 1009058470** [comment]
> we tried our best here, https://www.cornerstonejs.org/docs/category/concepts

thanks a lot
