### ISSUE TITLE
[Feature Request] ROI Annotations : get the exact position in image

### ISSUE THREAD

**Issue by CYB3RL1F3** [cornerstonejs/cornerstone3D#1022]
### What feature or change would you like to see made?

Hello,
I'd like to get the exact position of annotation in rendered image (and not only the canvas).
I'd like to have a function like _worldTocanvas(point3)_, but with the exact image. 
World2Canvas doesn't take in count the margin between the border of the image and the border of the canvas. It doesn't take in count zoom, rotation, and pan as well.
Is it possible to implement a _worldToRenderedImage(point: Point3)_ function in viewport? Or tell me if this already exists and where?
Thank you!

### Why should we prioritize this feature?

I need to get exact positions of annotations, especially RectangleROI :) 
I need an equivalent of "lastpoints" in cornerstone 2D!
Thanks!

**Comment by lizhih** [comment]
there is an util function [worldToImageCoords](https://www.cornerstonejs.org/api/core/namespace/utilities#worldToImageCoords)

**Comment by CYB3RL1F3** [comment]
Ha yes thanks!
