### ISSUE TITLE
[Bug?] StackViewport and VolumeViewport using same imageIds

### ISSUE THREAD

**Issue by Sergey1888888** [cornerstonejs/cornerstone3D#1051]
### Describe the Bug

I have `StackViewport` with `imageIds` and I can switch it to `VolumeViewport` with `createAndCacheVolume`. When I open my project it starts with `StackViewport`. After loading `imageIds` I can switch it to `VolumeViewport`, all works good at this time. But when I switch from `VolumeViewport` to `StackViewport` it something strange happend, like here in [issue](https://github.com/cornerstonejs/cornerstone3D/issues/1045) my `StackViewport` starts show me something like that, my images but with strange pixels. The `VolumeViewport` is changed to `StackViewport` using `setStack`.
I found out that after I switch `StackViewport` to `VolumeViewport`, in `cache._imageCache` `VolumeViewport` changed original `pixelData`. And the strange one is that image have `smallestPixelValue = -2048` but after all above damaged `StackViewport` image have same `smallestPixelValue` but `pixelData` includes `-15104`.
Maybe my switch logic wrong, or it's a bug.

### Steps to Reproduce

1. Create `StackViewport`;
2. Switch it to `VolumeViewport` with `createAndCacheVolume` with same imageIds;
3. Switch it back to `StackViewport`.

### The current behavior

Images in the `StackViewport` become pixelated when switch from `VolumeViewport` with same images.

### The expected behavior

Images in the `StackViewport` not changed when switch from `VolumeViewport` with same images.

### OS

Windows 10

### Node version

18.18.2

### Browser

Chrome 120.0.6099.216

**Comment by Sergey1888888** [comment]
Even if I clone right version of cached images `getPixelData()` return wrong values.

**Comment by Sergey1888888** [comment]
I fixed this by saving the same data separately in the cache, but adding symbols for the `VolumeViewport` to the `imageId`. I also have to make a fake `metaDataProvider` to take metadata from the original `imageId`. Thus, `VolumeViewport` edits `imageIds` created specifically for it, but does not touch the original ones for `StackViewport`. But this is more of a hack than a solution.

**Comment by Sergey1888888** [comment]
@sedghi Can you explain, please?

**Comment by sedghi** [comment]
For conversions use the new convertStackToVolumeViewport and vice versa utilities

packages/core/src/utilities/convertStackToVolumeViewport.ts

**Comment by jlopes90** [comment]
> For conversions use the new convertStackToVolumeViewport and vice versa utilities
> 
> packages/core/src/utilities/convertStackToVolumeViewport.ts

https://github.com/cornerstonejs/cornerstone3D/issues/1045

**Comment by Sergey1888888** [comment]
> For conversions use the new convertStackToVolumeViewport and vice versa utilities
> 
> packages/core/src/utilities/convertStackToVolumeViewport.ts

Somehow it is possible to create 3 orientations at once from one "viewport"? This is some very inconvenient function in my case.

**Comment by Sergey1888888** [comment]
And another problem is that my element is changing. And during conversion, the viewport will refer to the previous element.

**Comment by Sergey1888888** [comment]
@sedghi  Is it possible to change element of existing viewport?

**Comment by Sergey1888888** [comment]
@sedghi I did it with this utilities and my stack viewport still pixelated and now my `VolumeViewport` become pixelated after I switch viewport from `Stack` to `Volume` two times.

**Comment by Sergey1888888** [comment]
The more I switch, the larger(?) the pixels become, as if something isn't being undone each time and the calculations are being based incorrectly.

**Comment by Sergey1888888** [comment]
I think yes
