### ISSUE TITLE
cornerstone.annotation.state.removeAllAnnotations() should dispatchEvent for ANNOATION_REMOVED

### ISSUE THREAD

**Issue by cclevengeratmyhelo** [cornerstonejs/cornerstone3D#1056]
### What feature or change would you like to see made?

cornerstone.annotation.state.removeAllAnnotations() should dispatchEvent for ANNOATION_REMOVED

### Why should we prioritize this feature?

It's the expected behavior of the code. It makes sense for ANNOTATION_REMOVED to fire when an annotation is removed.

**Comment by ChandlerClevenger** [comment]
I have this done on a branch. Am now trying to figure out how to push and do a pull request.

**Comment by sedghi** [comment]
Maybe create another PR? I don't know how to get you access

**Comment by ChandlerClevenger** [comment]
Sorry for any confusion. I initially was trying to create a branch on this repo instead of making a fork. I was reading the "How to contribute" incorrectly initially but the PR above is valid.
