### ISSUE TITLE
[Bug] dicomParser.readFixedString: attempt to read past end of buffer and CORNERSTONE_IMAGE_VOLUME_LOADING_COMPLETED RangeError: Invalid typed array length: 65536

### ISSUE THREAD

**Issue by atrusch** [cornerstonejs/cornerstone3D#1069]
### Describe the Bug

Sometimes after calling decodeImageFrame in createImage.ts the pixelData are cleared (array buffer empty).
My current workaround is to copy the buffer before to call decodeImageFrame :
```
  const decodePromise = decodeImageFrame(
    imageFrame,
    transferSyntax,
    pixelData.slice(0),
    canvas,
    options,
    decodeConfig
  );
```

### Steps to Reproduce

Download https://keycloak.e-media.fr/keys/dicom/index.ts
Replace tutorial/index.ts by the downloaded file
Run tutorial (yarn example tutorial)
A stack is displayed, when all images are loaded we try to create a volume for a MPR
Errors are triggered 
- 'dicomParser.readFixedString: attempt to read past end of buffer'
- error in event listener of type:  CORNERSTONE_IMAGE_VOLUME_LOADING_COMPLETED RangeError: Invalid typed array length: 65536

### The current behavior

Errors triggered

### The expected behavior

No errors

### OS

Windows 11

### Node version

20.9.0

### Browser

Chrome Version 121.0.6167.161 (64 bits)

**Comment by dima9911** [comment]
+1 for this issue
<img width="594" alt="Снимок экрана 2024-03-22 в 15 25 32" src="https://github.com/cornerstonejs/cornerstone3D/assets/10125278/66d745c8-4f05-4e60-a18c-38b1cf5444cb">

this
<img width="802" alt="Снимок экрана 2024-03-22 в 15 25 56" src="https://github.com/cornerstonejs/cornerstone3D/assets/10125278/49c2e60f-dbe4-4384-9103-4e728575e136">

**Comment by JonathanGilyadov** [comment]
+1 for this issue

**Comment by AmrGablla** [comment]
+1 for this issue
It happend when i render 3 viewports for MPR and the first viewport throw this error.

**Comment by woaihengniu** [comment]
+1

**Comment by sedghi** [comment]
can you try latest ?<br>Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)

**Comment by woaihengniu** [comment]
> can you try latest ?Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?
> 
> Here are the migration guides:
> 
> Try OHIF locally: https://viewer-dev.ohif.org/localbasicTry Cornerstone3D 2.0 locally: https://www.cornerstonejs.org/live-examples/local.html
> 
> https://docs.ohif.org/migration-guide/3p8-to-3p9/

The latest version is ready to render
