### ISSUE TITLE
[Feature Request] How to obtain scalar data in the coronal or sagittal plane？

### ISSUE THREAD

**Issue by IrvingLu** [cornerstonejs/cornerstone3D#1106]
### What feature or change would you like to see made?

I can delete the contour in the cross-section through the calculation of scalar data. How can I obtain the scalar data of the coronal plane

### Why should we prioritize this feature?

I think the treatment of volume should not only focus on the axial

**Comment by sedghi** [comment]
if oblique you can't, if just orthogonal sag and coronal you have the scalarData from the volume (cache.getVolume), and you have each viewport position (viewport.getSliceIndex) then you can slice into the correct dimension
