### ISSUE TITLE
[Bug] Annotation Tools are always synchronised across viewports

### ISSUE THREAD

**Issue by mihir-rego** [cornerstonejs/cornerstone3D#1114]
### Describe the Bug

While using tools across multiple viewports, the annotations tools will draw across all viewports. This isn't the case with manipulation tools like pan, zoom, w/l, etc.

I have tried creating multiple RenderingEngines, but doesn't fix it. But I'm not sure if multiple RE's are the way to go.

### Steps to Reproduce

I have used 'volumeViewportSynchronization' in the cs3d examples to reproduce the issue, mapped the Secondary Button to Length Tool, and the Primary to W/L. 

In the screens below, you can see sync is off, and the W/L levels change for each viewport, but in the case of the LengthTool, drawing on one viewport will mirror the annotation on the other viewports.

### The current behavior

Annotation Tools  (Probe, Length, CobbAngle) are being synchronized across multiple viewports, even when sync is off. Screenshot below.

![length tool sync](https://github.com/cornerstonejs/cornerstone3D/assets/126229503/30019e04-1c71-4fad-9cc1-f5140a3c7d02)

### The expected behavior

Annotations should only appear on the viewport being modified, in case of multiple viewports, unless synchronized.

![window level sync](https://github.com/cornerstonejs/cornerstone3D/assets/126229503/c17ba265-20bf-440f-b491-c9d7aba59090)

### OS

Ubuntu 22.04

### Node version

20.11.1

### Browser

Brave v1.62.165

**Comment by sedghi** [comment]
so do you want it to not appear in the other viewports? volume viewports by design will show (not only the same series) but also if other seires are in the same position in the space, if you don't need MPR you can use stack viewports
