### ISSUE TITLE
How can I get updated frames/dicoms and POST them?

### ISSUE THREAD

**Issue by olexanax** [cornerstonejs/cornerstone3D#1119]
### Describe the Bug

I need to change frames in a dicom file and then get the updated file to send to the backend.
I can't find examples or articles on this topic(

Perhaps you can tell me? The logic is as follows: I changed the file using tools (for example, RectangleROITool) and then on Submit I have to send the changed dicom to the database via POST request

### Steps to Reproduce

--

### The current behavior

--

### The expected behavior

--

### OS

--

### Node version

--

### Browser

--

**Comment by sedghi** [comment]
you can make use of the dicomn SR, for that you can look into how OHIF is handling that https://github.com/OHIF/Viewers/
