### ISSUE TITLE
[Bug] Cannot access 'InterpolationManager' before initialization

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D#1120]
### Describe the Bug

Using version 1.64.1 (before it was version 1.63.5 and it works)

![image](https://github.com/cornerstonejs/cornerstone3D/assets/50026015/216b24d0-8228-4361-b5de-02be83472529)

**Comment by sedghi** [comment]
is it an error that blocks anything? or just an error in console

**Comment by jlopes90** [comment]
I updated version 30 then the error appears in the console

**Comment by lambacini** [comment]
> is it an error that blocks anything? or just an error in console

yes, it prevents the application from starting.

**Comment by jlopes90** [comment]
For example like this:

`import { adaptersSEG } from '@cornerstonejs/adapters';`

And it gave this error in the console.

**Comment by jlopes90** [comment]
I updated the new [v1.64.3](https://github.com/cornerstonejs/cornerstone3D/releases/tag/v1.64.3) and it works, no error appears in the console.

**Comment by sedghi** [comment]
Noice
