### ISSUE TITLE
[Bug]  StackScrollMouseWheel has already been added globally

### ISSUE THREAD

**Issue by HuangJia-Le** [cornerstonejs/cornerstone3D#1121]
### Describe the Bug

我需要执行init()函数多次，来加载不同的nifti图像，但是init()函数中会涉及到对工具的载入

### Steps to Reproduce

1. init()函数中涉及多工具的载入`//先判断工具是否已经加入，如果已经加入则不再加入
    addTool(StackScrollMouseWheelTool);
    addTool(ZoomTool);`，同样涉及到nifti图像的加载
2. 我想实现，我上传一个nifti文件，重新执行init()函数，将nifti文件替换为新传入的文件，就会执行init()函数
3. init()中涉及对工具的载入，就会报错StackScrollMouseWheel has already been added globally

### The current behavior

在多个页面中，由于使用工具的重复，同样会报错工具已经全局注册

### The expected behavior

我想实现如果可以不全局注册该工具，或者说可以实现我上述的功能？

### OS

windows11

### Node version

18.17.0

### Browser

Chrome120.0.6099.217

**Comment by xiaoluGood** [comment]
有addTool ，也有removeTool,在你执行初始化之前remove 就可以解决问题

**Comment by HuangJia-Le** [comment]
已解决
