### ISSUE TITLE
[Bug] loadImageFromImageLoader: no image loader for imageId

### ISSUE THREAD

**Issue by David2k13** [cornerstonejs/cornerstone3D#1132]
### Describe the Bug

volumeLoader.createAndCacheVolume(ctVolumeId, {
    imageIds
  })

imageIds  scheme is wadouri
debuger：The imageIds array randomly removes some wadouri of imageIds each time, causing the scheme to be recognized as HTTP

version: 
    "@cornerstonejs/core": "1.65.1",
    "@cornerstonejs/streaming-image-volume-loader": "1.65.1",
    "@cornerstonejs/tools": "1.65.1",
    "@kitware/vtk.js": "29.7.0",

### Steps to Reproduce

1:
 volumeLoader.createAndCacheVolume(ctVolumeId, {
    imageIds
  })

2:
 ![image](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/2235521e-e289-4ee3-8895-58ffc9c637c3)

### The current behavior

mageIds mageId modified
![image](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/cc4e6dc0-e4cd-4e15-936a-395364e3feb6)
![image](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/562a34cd-3185-4974-8df8-a075bb281c9f)
![image](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/4d9a61fb-9aa4-421b-946b-09f2a770777c)
![image](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/139a9046-0cef-4707-a5cd-098752923197)

### The expected behavior

mageIds mageId not modified

### OS

mac 14.2.1

### Node version

16.14.0

### Browser

Chrome  122.0.6261.57

**Comment by kundanashish** [comment]
Hi @David2k13 

I am facing the same error. Did you get any solutions for this?

Pls advise

**Comment by bearxy** [comment]
@David2k13
     I had the same problem as you, but it didn't exist when I was working on another project: vite+ 1.13.2.


 ` "@cornerstonejs/core": "^1.13.2",
    "@cornerstonejs/dicom-image-loader": "^1.13.2",
    "@cornerstonejs/streaming-image-volume-loader": "^1.13.2",
    "@cornerstonejs/tools": "^1.13.2"`

**Comment by bearxy** [comment]
@David2k13
     I had the same problem as you, but it didn't exist when I was working on another project: vite+ 1.13.2.


 ` "@cornerstonejs/core": "^1.13.2",
    "@cornerstonejs/dicom-image-loader": "^1.13.2",
    "@cornerstonejs/streaming-image-volume-loader": "^1.13.2",
    "@cornerstonejs/tools": "^1.13.2"`

**Comment by David2k13** [comment]
> @David2k13 我遇到了和你一样的问题，但是当我在另一个项目：vite+ 1.13.2 上工作时，它不存在。
> 
> ` "@cornerstonejs/core": "^1.13.2", "@cornerstonejs/dicom-image-loader": "^1.13.2", "@cornerstonejs/streaming-image-volume-loader": "^1.13.2", "@cornerstonejs/tools": "^1.13.2"`

yes，I have already returned to v1.23.2

**Comment by ahlaughland** [comment]
I'm seeing the same error for `dicomfile` as well on OHIF beta-62.

**Comment by sedghi** [comment]
I'm working on cornerstone3D 2.x and have made progress in removing circular dependencies and publishing the types for the DICOM image loader. I'm trying to make it work with Vite, but there are numerous issues with Vite in `dev` mode, which are not directly related to Cornerstone. Multiple mentions of Vite problems with `import.meta.url`, web workers, and WebAssembly can be found on the Vite GitHub repository:

https://github.com/vitejs/vite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+import.meta.url

I have started a template project for Vite, React, and cornerstone3D beta 2.x here. I appreciate your help in making it work.

https://github.com/cornerstonejs/vite-react-cornerstone3d

**Comment by sedghi** [comment]
I have the full recipe with official 2.0 in the same repo, check it out please
