### ISSUE TITLE
[Bug] when modifying the fusion image of CT and PT,  Unable to change windowLevel of PT

### ISSUE THREAD

**Issue by sunao0920** [cornerstonejs/cornerstone3D#1149]
### Describe the Bug

When I was modifying the fusion image of CT and PT, I wanted to change the windowLevel of PT separately. When addingTool, I added volumeId to the configuration configuration. I found that when I get the targetId in the code, I always get the default actor UID, but I can't get it. To the volumeId of PT, the windowLevel of CT is always modified.

### Steps to Reproduce

![step1](https://github.com/cornerstonejs/cornerstone3D/assets/49636550/d95e7b5d-6780-41e5-978f-4bda69514874)
![step2](https://github.com/cornerstonejs/cornerstone3D/assets/49636550/dbe447b2-5140-4cde-bd73-d63621511662)
![Step3](https://github.com/cornerstonejs/cornerstone3D/assets/49636550/287a932b-f2cc-44af-a723-b7205921f78b)
![step4](https://github.com/cornerstonejs/cornerstone3D/assets/49636550/ae3589ca-e92f-44a2-9173-f5cb93470f64)

### The current behavior

What I hope to change is the windowLevel of PT, The windowLevel of CT is indeed changed

### The expected behavior

What I hope to change is the windowLevel of PT

### OS

Windows 11 

### Node version

18.17.1

### Browser

chrome 121.0.6167.85

**Comment by sunao0920** [comment]
getTargetId() This method will always get the uid of the first actor, using the volumeId of CT

**Comment by sedghi** [comment]
you can add the volumeId of the pet when configuring the window level tool, check out the ptCT example https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/tools/examples/petCt/index.ts#L378

**Comment by sunao0920** [comment]
![2](https://github.com/cornerstonejs/cornerstone3D/assets/49636550/89942660-ce81-4cc1-be75-b369837987d9)
I added the first picture above of this configuration. I debugged the internals of the library and found that after adding volumeId, this volumeId always obtains the ID of the first volume. Because of the logic in getTaegetId, my screenshot above can be See

**Comment by sunao0920** [comment]
![5png](https://github.com/cornerstonejs/cornerstone3D/assets/49636550/99bf5b34-18ae-46ee-a4e0-be41b621bc92)
这个地方我已经添加了 volumeId 的配置
