### ISSUE TITLE
[Bug] Can't scroll on NIFTIs

### ISSUE THREAD

**Issue by CYB3RL1F3** [cornerstonejs/cornerstone3D#1151]
### Describe the Bug

Can't scroll niftis since version 1.47

Fix available here just need to merge and deploy it!!

https://github.com/cornerstonejs/cornerstone3D/pull/1143 

### Steps to Reproduce

1. Load a NIFTI
2. Try to scroll 
3. Constat it fails

### The current behavior

It doesn't scroll nor work with any tool

### The expected behavior

to work like before 1.47...

### OS

Mac OS 

### Node version

20.0.0

### Browser

Chrome

**Comment by sedghi** [comment]
i think this is fixed now, can you try again?
