### ISSUE TITLE
[Bug] OES_texture_float_linear

### ISSUE THREAD

**Issue by longuto** [cornerstonejs/cornerstone3D#1152]
### Describe the Bug

It reports this error when running on the phone. But running it on a computer is normal
![Dingtalk_20240315164407](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/eaf76107-5f86-479a-93a7-753bf61fff71)

![Dingtalk_20240315164838](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/91be58e6-7d39-418f-aec7-4c5f7a08a1ef)

### Steps to Reproduce

It reports this error when running on the phone. But running it on a computer is normal

### The current behavior

It reports this error when running on the phone. But running it on a computer is normal

### The expected behavior

It reports this error when running on the phone. But running it on a computer is normal

### OS

Android WebView

### Node version

16.14.0

### Browser

Chrome

**Comment by sedghi** [comment]
maybe check this https://github.com/OHIF/Viewers/issues/3207

**Comment by longuto** [comment]
Perhaps this is the reason

[https://github.com/Kitware/vtk-js/issues/3030](Kitware/vtk-js#3030)

**Comment by longuto** [comment]
Perhaps this is the reason

[https://github.com/Kitware/vtk-js/issues/3030](vtk-js)

**Comment by longuto** [comment]
It seems to be related to this issue, I have this similar error.
[Kitware/vtk-js#3030](https://github.com/Kitware/vtk-js/issues/3030)
