### ISSUE TITLE
[Bug] Could not find a declaration file for module '@cornerstonejs/dicom-image-loader' in Angular 17

### ISSUE THREAD

**Issue by ArnaudAgixis** [cornerstonejs/cornerstone3D#1155]
### Describe the Bug

When I try to reproduce an example that use dicom-image-loader like this one : [DICOM P10 from local file system](https://www.cornerstonejs.org/live-examples/local.html ), the package is not found.
I try to install it with npm and yarn. I install the lastest versions.
`"@cornerstonejs/core": "^1.66.6",
    "@cornerstonejs/dicom-image-loader": "^1.66.6",
    "@cornerstonejs/streaming-image-volume-loader": "^1.66.6",
    "@cornerstonejs/tools": "^1.66.6",`
All the packages are correctly installed inside the node_modules, or seems to be.

### Steps to Reproduce

1. Setup your new angular 17 project
2. add with npm or yarn, cornerstone
3. then cornerstone dicom image loader
4. import cornerstoneDICOMImageLoader from '@cornerstonejs/dicom-image-loader'; inside a ts file of a component

### The current behavior

Could not find a declaration file for module '@cornerstonejs/dicom-image-loader'. 'c:/Users/user/testAppCornerstone3D/node_modules/@cornerstonejs/dicom-image-loader/dist/cornerstoneDICOMImageLoader.bundle.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/cornerstonejs__dicom-image-loader` if it exists or add a new declaration (.d.ts) file containing `declare module '@cornerstonejs/dicom-image-loader';`ts(7016)

### The expected behavior

to be able to import @cornerstonejs/dicom-image-loader

### OS

Windows 10

### Node version

v20.11.1

### Browser

Firefox 123.0.1

**Comment by RadteamBaoDA** [comment]
I'm using angular 17 like you and i can import this library like this.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/154402858/09238b0c-4252-47d2-80c6-bb2fee219d13)
and add cornerstone config in services file without any error
![image](https://github.com/cornerstonejs/cornerstone3D/assets/154402858/7bd07fa8-459e-42e2-bc2f-f32ebb2ae839)

**Comment by sedghi** [comment]
it is odd, search in the cornerstone github, there are some discussions for related issues in `vite`

**Comment by ArnaudAgixis** [comment]
I have tried your solution and still have the problem

**Comment by tonitomystery** [comment]
try copying the cornerstoneDICOMImageLoader.bundle.min.js found in node_modules/@cornerstonejs/dicom-image-loader/dist , to the path src/assets, then including it in the project's index.html
   <script src="assets/cornerstoneDICOMImageLoader.bundle.min.js"></script>

**Comment by sedghi** [comment]
I'm working on cornerstone3D 2.x and have made progress in removing circular dependencies and publishing the types for the DICOM image loader. I'm trying to make it work with Vite, but there are numerous issues with Vite in `dev` mode, which are not directly related to Cornerstone. Multiple mentions of Vite problems with `import.meta.url`, web workers, and WebAssembly can be found on the Vite GitHub repository:

https://github.com/vitejs/vite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+import.meta.url

I have started a template project for Vite, React, and cornerstone3D beta 2.x here. I appreciate your help in making it work.

https://github.com/cornerstonejs/vite-react-cornerstone3d

**Comment by wlorencesancsoft** [comment]
Are there any updates on this? I'm seeing the exact same problem described here while trying to use Angular 18 and Cornerstone packages `1.86.0`. 

Trying to import with `import cornerstoneDICOMImageLoader from '@cornerstonejs/dicom-image-loader';` and getting a TypeScript compiler error.

```
X [ERROR] TS7016: Could not find a declaration file for module '@cornerstonejs/dicom-image-loader'.
```

```
"dependencies": {
    ...
    "@cornerstonejs/core": "^1.86.0",
    "@cornerstonejs/dicom-image-loader": "^1.86.0",
    "@cornerstonejs/streaming-image-volume-loader": "^1.86.0",
    "@cornerstonejs/tools": "^1.86.0",
    ...
}
```

**Comment by sedghi** [comment]
soon https://github.com/cornerstonejs/cornerstone3D/pull/1400

**Comment by sedghi** [comment]
Cornerstone3D 2.0 is published with all types
