### ISSUE TITLE
[Bug] Is there way to load nifti files without sharedarray bufer enabled on the browser side

### ISSUE THREAD

**Issue by SachidanandAlle** [cornerstonejs/cornerstone3D#1156]
### Describe the Bug

Currently its complaining about sharedarraybuffer not enabled.. 
is there any other solution than adding following headers which are kind of breaking changes (due to iframes etc..) in existing system

``
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

@sedghi 

### Steps to Reproduce

Running non localhost and load nifti file

### The current behavior

shared array buffer is required

### The expected behavior

render without shared array buffer on https non localhost

### OS

Any

### Node version

Any

### Browser

Any

**Comment by SachidanandAlle** [comment]
@sedghi can you help? is there a way we can communicate over slack or something else..?

**Comment by sedghi** [comment]
you can turn that off 

https://docs.ohif.org/faq/#what-if-my-setup-does-not-support-the-shared-array-buffers-api

inside cornerstone, you should look into the init function and set it not to use the SAB

**Comment by SachidanandAlle** [comment]
FYI..

https://build.nvidia.com/nvidia/vista-3d

**Comment by sedghi** [comment]
yeah saw that, looks great!
takes a lot of time to load the data (network) maybe we should optimize it, like pre-loading or stuff

**Comment by SachidanandAlle** [comment]
https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone/src/init.tsx#L56

**Comment by sedghi** [comment]
I see then it should follow this logic here 

packages/core/src/utilities/generateVolumePropsFromImageIds.ts
