### ISSUE TITLE
[Bug] how to connect to dcm4chee

### ISSUE THREAD

**Issue by l5769389** [cornerstonejs/cornerstone3D#1157]
### Describe the Bug

i use the example and pacs use orthanc :
```
  const params = {
    StudyInstanceUID: '1.2.2046.7929.09.1.20230724.105506.19135',
    SeriesInstanceUID: '1.2.2046.7929.09.1.20230724.105506.07036',
    wadoRsRoot: '/dicom-web',
  }
  const imageIds = await createImageIdsAndCacheMetaData(params);
```
and i proxy /dicom-web to  http://127.0.0.1:8042/ . that works well.  

but now i change pacs to dcm4chee 。what should i do can get the data? 

### Steps to Reproduce

like above

### The current behavior

like above

### The expected behavior

like above

### OS

window11

### Node version

20

### Browser

firefox

**Comment by sedghi** [comment]
you can check out ohif docs https://docs.ohif.org/configuration/dataSources/dicom-web
