### ISSUE TITLE
[Bug]  Getting error after upgrading from cornerstone3D v1.53.0 To  v1.54.0

### ISSUE THREAD

**Issue by idemopacs** [cornerstonejs/cornerstone3D#1161]
### Describe the Bug

I have upgraded Cornerstone3D v1.53.0 To  v1.54.0  in my application which is developed in HTML and Javascript. I am using Webpack V5.81.0. 
While compiling application I am getting following error

> ERROR in ./node_modules/@icr/polyseg-wasm/dist/ICRPolySeg.wasm 1:0
> Module parse failed: Unexpected character '' (1:0)
> The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.
> BREAKING CHANGE: Since webpack 5 WebAssembly is not enabled by default and flagged as experimental feature.
> You need to enable one of the WebAssembly experiments via 'experiments.asyncWebAssembly: true' (based on async modules) or 'experiments.syncWebAssembly: true' (like webpack 4, deprecated).
> For files that transpile to WebAssembly, make sure to set the module type in the 'module.rules' section of the config (e. g. 'type: "webassembly/async"').
> (Source code omitted for this binary file)
>  @ ./node_modules/@icr/polyseg-wasm/dist/index.js 2:0-37 21:17-21
>  @ ./node_modules/@cornerstonejs/tools/dist/esm/workers/polySegConverters.js 4:0-43 23:31-41 50:34-44 97:34-44
>  @ ./node_modules/@cornerstonejs/tools/dist/esm/stateManagement/segmentation/polySeg/registerPolySegWorker.js 9:15-11:10
>  @ ./node_modules/@cornerstonejs/tools/dist/esm/stateManagement/segmentation/polySeg/computeAndAddRepresentation.js 6:0-64 9:4-25
>  @ ./node_modules/@cornerstonejs/tools/dist/esm/stateManagement/segmentation/polySeg/Surface/computeAndAddSurfaceRepresentation.js 2:0-77 6:11-38
>  @ ./node_modules/@cornerstonejs/tools/dist/esm/stateManagement/segmentation/polySeg/index.js 1:0-98 5:0-155
>  @ ./node_modules/@cornerstonejs/tools/dist/esm/stateManagement/segmentation/index.js 13:0-44 14:0-305
>  @ ./node_modules/@cornerstonejs/tools/dist/esm/index.js 10:0-63 14:0-1209
>  @ ./scripts/initCS.js 5:0-70 22:10-21
>  @ ./scripts/ViewerMain.js 1:1-34 90:18-24 300:18-24
> 
> webpack 5.81.0 compiled with 1 error in 4957 ms

Getting same issue with latest v1.66.7 also.

### Steps to Reproduce

upgraded Cornerstone3D v1.53.0 To  v1.54.0

### The current behavior

Compilation error

### The expected behavior

No error

### OS

Windows 10

### Node version

v16.17.1

### Browser

Chrome 114.0.5735.134

**Comment by jlopes90** [comment]
https://github.com/cornerstonejs/cornerstone3D/issues/1067

**Comment by jlopes90** [comment]
```javascript
// Webpack
module.exports = {
  experiments: {
    asyncWebAssembly: true,
  },
  resolve: {
    alias: {
      "@cornerstonejs/tools": "@cornerstonejs/tools/dist/umd/index.js"
    }
  }
};
```

**Comment by idemopacs** [comment]
@jlopes90  Thanks.
Issue resolved with suggested settings.
