### ISSUE TITLE
Cannot find module '@cornerstonejs/adapters' or its corresponding type declarations

### ISSUE THREAD

**Issue by haoxl3** [cornerstonejs/cornerstone3D#1171]
### Describe the Bug

when I import @cornerstonejs/adapters  and dcmjs, I got error
![image](https://github.com/cornerstonejs/cornerstone3D/assets/15046133/82310633-c576-4c39-854d-df8523315bce)

### Steps to Reproduce

import { adaptersSEG, helpers } from '@cornerstonejs/adapters';
import dcmjs from "dcmjs";

const { Cornerstone3D } = adaptersSEG;
const { downloadDICOMData } = helpers;

//"@cornerstonejs/adapters": "^1.66.9",
// "dcmjs": "^0.31.0"

### The current behavior

Error printed in browser console: ×
TypeError: Cannot read properties of undefined (reading 'toolName')

### The expected behavior

Expect to be able to use dcmjsand @cornerstonejs/adapters normally.
The editor prompts me about missing TypeScript type declarations.

### OS

macOS 12.5

### Node version

v18.18.2

### Browser

Chrome 122.0.6261.112（正式版本） (arm64)

**Comment by sedghi** [comment]
Fixed this recently can you update ypur version
