### ISSUE TITLE
[Bug] Using image scrolling will increase the memory footprint constantly

### ISSUE THREAD

**Issue by xiaoluGood** [cornerstonejs/cornerstone3D#1175]
### Describe the Bug

Repeated use of the image switching function, memory continues to increase
![Snipaste_2024-03-27_10-45-43](https://github.com/cornerstonejs/cornerstone3D/assets/8968472/1578c3be-9cd0-4d86-a08b-2a914397f13f)
Using the test link [https://www.[cornerstonejs.org/live-examples/webloader](https://www.cornerstonejs.org/live-examples/webloader)](url)

### Steps to Reproduce

as above

### The current behavior

 as above

### The expected behavior

 as above

### OS

win10

### Node version

16

### Browser

chrome 110

**Comment by sedghi** [comment]
We cache images, so that you don't network request when going back.

**Comment by xiaoluGood** [comment]
> We cache images, so that you don't network request when going back.
I know that the image will be cached, the above example has already cached the image, the memory of the image after caching will not be larger than 100M, if the scrolling operation above is continued, the memory will be stacked indefinitely, more than 2G, when scrolling the image, is it repeated to load the image that did not get the cached image? You can test based on the above example, thanks.

**Comment by sedghi** [comment]
I don't see the reported issue anymore in Cornerstone3D 2.0

<img src="https://uploads.linear.app/e0b640a9-3fd8-4513-bc84-af25921e5dc8/e05dc769-9ab8-4161-b488-d64ac877a090/24e8d40d-96f7-4930-8ed6-60984d4b0202?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UwYjY0MGE5LTNmZDgtNDUxMy1iYzg0LWFmMjU5MjFlNWRjOC9lMDVkYzc2OS05YWI4LTQxNjEtYjQ4OC1kNjRhYzg3N2EwOTAvMjRlOGQ0MGQtOTZmNy00OTMwLThlZDYtNjA5ODRkNGIwMjAyIiwiaWF0IjoxNzMwOTE5ODMzLCJleHAiOjMzMzAxNDc5ODMzfQ.ZchSltLIz_UM-c4hKoleNbltl41YK9x2xdjXHdn51MM " alt="CleanShot 2024-11-06 at 14.03.34@2x.png" width="482" height="492" />
