### ISSUE TITLE
[Bug] Can't set lineWidth for ProbeTool

### ISSUE THREAD

**Issue by kubanm3** [cornerstonejs/cornerstone3D#1181]
### Describe the Bug

When setting lineWidth for ProbeTool nothing happens.

In ProbeTool there is only color being passed to drawHandles as option.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/22613738/98b2dc27-3016-4f85-91b6-699bae750923)

### Steps to Reproduce

Create ProbeTool annotation.
Set styles with annotation.config.style.setAnnotationStyles(annotationUuid, {lineWidth: 4}).

### The current behavior

Nothing happens

### The expected behavior

Probe should change it's width.

### OS

Linux

### Node version

20

### Browser

Brave

**Comment by sedghi** [comment]
We didn't think it is useful, we can add it

**Comment by kubanm3** [comment]
That'd be appreciated. I'm using it to highlight annotation on dicom after it's hovered over on a list of all annotations. And probe tool was one not working.

**Comment by AdilZahid** [comment]
@kubanm3  Did you manage to cater to this change? Like hovering on the List of probe Annotations.
What I'm trying is, I'm showing the initial probe annotations with textBoxVisibility: false. I want to show values when hovering over any annotation. But I didn't find any hovering event for that specific case.
