### ISSUE TITLE
[Bug]  Volume viewports not working on ios

### ISSUE THREAD

**Issue by mauricio-cdr** [cornerstonejs/cornerstone3D#1184]
### Describe the Bug

Hello, how are you?

Volume viewports do not work on ios on any version of IOS 17.0 or higher

![image](https://github.com/cornerstonejs/cornerstone3D/assets/17281855/67edf16e-aad9-42e5-b968-f71bb2bb0595)

### Steps to Reproduce

1. Go to any example that includes a volume viewport. e.g. https://www.cornerstonejs.org/live-examples/volumeannotationtools .

### The current behavior

The images are not displayed and in the console you can see the following message.

![Captura de Pantalla 2024-04-04 a la(s) 14 30 42](https://github.com/cornerstonejs/cornerstone3D/assets/17281855/bf09551e-ff6a-4d5e-818d-2913f0f90c80)

![image](https://github.com/cornerstonejs/cornerstone3D/assets/17281855/67edf16e-aad9-42e5-b968-f71bb2bb0595)

### The expected behavior

Make it work the same way it works on IOS 16.x.x or less.

![Captura de Pantalla 2024-04-04 a la(s) 14 34 03](https://github.com/cornerstonejs/cornerstone3D/assets/17281855/e5a297de-638b-4d1e-b991-091d50c5b3e2)

### OS

IOS 17.0 , 17.1.4 , 17.2,  17.4.1

### Node version

18.13.0

### Browser

Chrome 90+

**Comment by sedghi** [comment]
I created this PR which would be good enough for a lot of use cases (except the PT Scaled data)

https://github.com/cornerstonejs/cornerstone3D/pull/1212
