### ISSUE TITLE
[Feature Request] yarn example with port

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D#1185]
### What feature or change would you like to see made?

I would prefer to run example two or more, but I can't because the address already exists or is repeated.

### Why should we prioritize this feature?

I would like to use `port` for example:

`yarn example segmentationStack port=3005`

**Comment by sedghi** [comment]
It is already there, take a look at PORT

**Comment by jlopes90** [comment]
https://github.com/cornerstonejs/cornerstone3D/blob/21f9869a43912ca4a1eb70391d439e9e11252f07/utils/ExampleRunner/template-config.js#L94

```bash
set CS3D_PORT=3005
```

and

```bash
yarn example segmentationStack
```

👍
