### ISSUE TITLE
[Bug] out of memory int16Array@[native code]

### ISSUE THREAD

**Issue by gosvig123** [cornerstonejs/cornerstone3D#1196]
### Describe the Bug

When trying to load large CTA's using the Nifti volume loader on mobile i get the following error.
The same setup works just fine for NCCT nifti images that are significantly smaller, and works just fine loading the CTA on desktop.

out of memory
int16Array@[native code]

This only happens on mobile and with CTA's.

### Steps to Reproduce

Try to load a large (120mv +), compressed CTA  on mobile using the nifti volume loader.

### The current behavior

The client  retreives all of the image, but once loading it - the error appears.

### The expected behavior

To render the image after retrieving it.

### OS

IOS 17.1.1

### Node version

v18.19.1

### Browser

Chrome or Safari (tested both)

**Comment by Congritulation** [comment]
I have the same problem. IOS17, Out of memory, CTA images. Hope somebody to fix it quickly.

**Comment by sedghi** [comment]
Cornerstone3D 2.0 has been released. It comes with:

- New Segmentation Architecture: Segmentations are now treated as first-class data structures, not just tools. This allows for greater flexibility and support for advanced visualization, such as multi-representational views, viewport-specific customizations, and easier management within MPR layouts.

- Introduction of VoxelManager: A more memory-efficient and streamlined approach to voxel data handling, replacing traditional scalar arrays with a unified, image-based system. This change reduces memory usage, enhances data clarity, and simplifies data access across stacks and volumes.

For more details on these updates and to guide you through the migration, please refer to our [Migration Guide](https://www.cornerstonejs.org/docs/migration-guides/intro).
