### ISSUE TITLE
[Feature Request] How to rotate labelmap segmentation

### ISSUE THREAD

**Issue by Qwd2017** [cornerstonejs/cornerstone3D#1206]
### What feature or change would you like to see made?

1.add labelmap segmentation to viewport,
2.rotate labelmap to a custom degree(not viewport rotation)

### Why should we prioritize this feature?

we can set deformation to segmentation

**Comment by IrvingLu** [comment]
I have the same problem, not only with rotation, but also with deformation and scaling

**Comment by sedghi** [comment]
Can explain more about it? You want to rktate the underlying image too?

**Comment by Qwd2017** [comment]
> Can explain more about it? You want to rktate the underlying image too?

Hi, I just want to do geometric transformations on segmentation, like translation and rotation。
I have tried the following ,but it doesn't work
const floatActor = viewport?.getActor(segmentId);
const floatVolume = floatActor?.actor as VolumeActor;
floatVolume.setUserMatrix(transformMatrix);

**Comment by sedghi** [comment]
Hmm, the user matrix may not be the solution. It likely only manipulates camera-related aspects. If the goal is translation only, you should be able to change the `origin` volume to achieve that. Rotation is more complex, but you should be able to modify the `direction` cosines.

**Comment by Qwd2017** [comment]
> Hmm, the user matrix may not be the solution. It likely only manipulates camera-related aspects. If the goal is translation only, you should be able to change the `origin` volume to achieve that. Rotation is more complex, but you should be able to modify the `direction` cosines.

Thanks for your tips. Here is my solution:
const dicomOri = cache.getVolume("imageVolumeId").origin;
const transform = vtkTransform.newInstance();
transform.setMatrix(userMatrix);
const transformedOri = vec3.create();
transform.transformPoint(dicomOri, transformedOri);

const userQuat = quat.create();
mat4.getRotation(userQuat, userMatrix);

const userMat3 = mat3.create();
mat3.fromQuat(userMat3, userQuat);

segmentationVolume.imageData?.setOrigin(transformedOri as Vector3);
segmentationVolume.imageData?.setDirection(userMat3);
