### ISSUE TITLE
[Bug]  ﻿ @cornerstonejs-CWnWevAx.js:171 Uncaught ReferenceError: Cannot access 'kL' before initialization

### ISSUE THREAD

**Issue by IrvingLu** [cornerstonejs/cornerstone3D#1241]
### Describe the Bug

I used vite5+vue3+cs3D to package and deployed errors reported by IIS or nginx：@cornerstonejs-CWnWevAx.js:171 Uncaught ReferenceError: Cannot access 'kL' before initialization

There are no issues during development。
I can also use vite4 for packaging, but vite4 uses@ icr@polySeg Packaging failed, so I chose 5

### Steps to Reproduce

1、npm run  build 
2、Deploy in IIS

### The current behavior

@cornerstonejs-CWnWevAx.js:171 Uncaught ReferenceError: Cannot access 'kL' before initialization at @cornerstonejs-CWnWevAx.js:171:12754
![20240509-180321](https://github.com/cornerstonejs/cornerstone3D/assets/26640655/cb92c595-d1bc-48a7-9c32-321934b55108)
KL was used before definition

### The expected behavior

I can run my project normally

### OS

windows10

### Node version

1.61.5

### Browser

Chrome

**Comment by IrvingLu** [comment]
https://cn.rollupjs.org/configuration-options/#output-manualchunks

in vite.config.ts:

build: {
    rollupOptions: {
      output: {
        manualChunks: {
          cornerstonejs: ["@cornerstonejs/core", "@cornerstonejs/tools"],
        },
      },
    },
    commonjsOptions: {
      requireReturnsDefault: "namespace",
    },
  },

**Comment by sedghi** [comment]
Take a look at other vite issues, you need to copy the wasm files manually with copy plugin. Please search vite in the issues
