### ISSUE TITLE
[Bug] StackViewport alone with VolumeViewport3D breaks images rendered in StackViewport

### ISSUE THREAD

**Issue by shunia** [cornerstonejs/cornerstone3D#1242]
### Describe the Bug

I was trying to implement a custom image loader and found this and tried so hard that I still can not get through, and actually I think this might be two bugs.

Just put a `StackViewport` alone with a `VolumeViewport3D`, and use the normal apis to load the images for both viewports, without any preloading of images or metadatas

The first bug:
The images except the ones that is prefetched by `volumeLoader` renders with wrong voiRange inside of the `StackViewport`.

Possibly the second bug:
If prefetch images use `StackViewport.loadImages` before `volumeLoader`, the images rendering inside of the `StackViewport` is as normal, but the `VolumeViewport3D` only shows bone model (CT dataset), and I don't know how to change it to chest or lung or any other.

I have a working repro [here](https://stackblitz.com/edit/vitejs-vite-apbxtb?file=index.js) you guys can tweak with, **uncomment line 106 will lead to the second bug**. If I have described the bug well, you can check the codes directly.

### Steps to Reproduce

1. creates a `StackViewport` and a `VolumeViewport3D` at the same time;
2. use `volumeLoader.createAndCacheVolume` to load the volume for the `VolumeViewport3D`;
3. use `stackViewport.setStack` to load the images for the `StackViewport`;
4. attach a `StackScrollMouseWheelTool` to scroll the images inside of the `StackViewport`;

### The current behavior

1. the `VolumeViewport3D` will load and render as normal;
2. the `StackViewport` will load and render **the first image** as normal;
3. scroll inside the `StackViewport`, all the images except the prefetched ones by the `volumeLoader` will render with wrong voiRange(ww/wl);

### The expected behavior

all of the images are loaded and rendered as normal

### OS

Windows 10

### Node version

18+, 20+

### Browser

Various browsers includes newest edge, newest chrome, and other chromium based browsers

**Comment by shunia** [comment]
I believe https://github.com/cornerstonejs/cornerstone3D/issues/1223 is the same root cause here, under the hood, if a volume is created and loaded, the stackviewport will use images loaded or cached by the volume ranther than loading by itself through imageLoader, but the images created by the volume is not suitable for stack rendering.

The loading process is different when loading from imageLoader and volumeLoader because they are providing different loading options , the loading options then will affect how the image data is created and transferred.

**Comment by hiren3897** [comment]
@shunia I am also facing the same error!!

To add more:
- I have a list of studies with `CT` & `DX` Modality
- So when I go first on the CT study the createAndCacheVolume is executed and the volume is loaded (everything is fine until here )
- When change to `DX` study the stackViewport is created but the imageIds are not rendered
- Also, when I move back to `CT` study from `DX` or `CT` the volume is loaded but then it says 
  - `WebGL: INVALID_OPERATION: texSubImage3D: no texture bound to target`
  - `WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context`

**Comment by shunia** [comment]
@hiren3897 I just find out that upgrading to a newer version fixes my problem, I was using 1.70.x, tried 1.72.x and the white image gone away.

**Comment by hiren3897** [comment]
Hello @shunia, Thanks for the response
Yes, the issue was fixed by upgrading to `1.74.1`.
