### ISSUE TITLE
[Bug] rendering is white

### ISSUE THREAD

**Issue by longuto** [cornerstonejs/cornerstone3D#1251]
### Describe the Bug

His rendering is white, and the body rendering is also incorrect. But the last one after the middle one is normal. Wadouri used

### Steps to Reproduce

His rendering is white, Wadouri used

### The current behavior

His rendering is white, Wadouri used

### The expected behavior

His rendering is normal
![Dingtalk_20240516164901](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/ac4f4343-06c2-48dd-bba0-1e91746fbe22)

### OS

windows 10

### Node version

18.20.0

### Browser

chrome 83.0.4103.116

**Comment by sedghi** [comment]
Can you check if my recent fix has resolved your issue as well?

https://github.com/cornerstonejs/cornerstone3D/pull/1254

**Comment by longuto** [comment]
It has been resolved, but npmjs.org does not have version 1.73.1
![Dingtalk_20240517094327](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/e03a21b7-6548-42c6-9cdd-a0fa14dae11d)
![Dingtalk_20240517094539](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/8115c163-a1ec-4d88-b2a0-ff6cba411751)

**Comment by longuto** [comment]
![Dingtalk_20240517094327](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/f7ce162a-56c8-4015-b6d2-a8e70fde4298)
![Dingtalk_20240517094539](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/e0772217-d046-46e1-820d-97fc1cc60df9)

**It has been resolved, but npmjs. org does not have version 1.73.1**

**Comment by longuto** [comment]
![Dingtalk_20240517100426](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/fb182b3f-7cbd-43a4-879a-00e25014eeab)

**I rotated the volume rendering for a while, and it turned out like this**

**Comment by sedghi** [comment]
please create another issue so that we can close this

**Comment by sedghi** [comment]
@longuto I fixed the resolution issue in the 3d viewport
