### ISSUE TITLE
[Bug] New version report exception

### ISSUE THREAD

**Issue by cnszpeak** [cornerstonejs/cornerstone3D#1252]
### Describe the Bug

when visit official example: https://www.cornerstonejs.org/live-examples/dicomimageloaderwadouri
console log error as following image:
![image](https://github.com/cornerstonejs/cornerstone3D/assets/57037466/63acbfdd-733a-4f3f-9b66-354f28c25819)

### Steps to Reproduce

1.Open Edge,and  visit https://www.cornerstonejs.org/live-examples/dicomimageloaderwadouri
2.Selected file: CTImage.dcm_JPEG2000LosslessOnlyTransferSyntax_1.2.840.10008.1.2.4.90.dcm
3.Press F12 key

### The current behavior

report error

### The expected behavior

no error

### OS

window 11

### Node version

v20.12.2

### Browser

Edge 125.0.2535.37

This error occur frequently,specially when using stack.  
It's a fatal error that can stop the app.Would you please fix it  as priority? 
The same bug was mentioned  in issue 1174,1195,1270,1272

**Comment by sedghi** [comment]
This is fixed now i guess
