### ISSUE TITLE
Build error with WebPack 5

### ISSUE THREAD

**Issue by Celian-abd** [cornerstonejs/cornerstone3D#126]
Hi there,

we just wanted to warn that Cornerstone3D has a build issue with Webpack 5 due to the detect-gpu library

The issue is raised here : https://github.com/pmndrs/detect-gpu/issues/89

For those working with react 18 with create-react-app will have this issue. 

I put this here because once detect-gpu will be fixed it will need to upgrade cornerstone 3d dependencies

Salim & Celian

**Comment by gabriellebaudy** [comment]
Hello,

We found and submitted a fix, available [here](https://github.com/pmndrs/detect-gpu/pull/94).

I hope it can be merged soon!

**Comment by sedghi** [comment]
Is your problem resolved now? @Celian-abd
