### ISSUE TITLE
Crosshair position synchronization to volume3D

### ISSUE THREAD

**Issue by vincent1996** [cornerstonejs/cornerstone3D#1263]
### What feature or change would you like to see made?

Is it possible to drag the crosshair in the MPR viewport to locate it in the 3D volmue viewport？

![新建 BMP 图像](https://github.com/cornerstonejs/cornerstone3D/assets/16411793/27dea2ee-3ef6-4d00-8d44-1a45d55cefd1)

### Why should we prioritize this feature?

Can we add a position synchronizer to synchronize changes in camera position and marking crosshairs

**Comment by sedghi** [comment]
There is no synchronization for crosshairs and 3d viewport currently

**Comment by zjhhy1314** [comment]
I need this feature, too

**Comment by zjhhy1314** [comment]
> ### 您希望看到什么功能或改变？
> 是否可以拖动 MPR 视口中的十字线以将其定位在 3D 体积视口中？
> 
> ![新建BMP图像](https://private-user-images.githubusercontent.com/16411793/332642980-27dea2ee-3ef6-4d00-8d44-1a45d55cefd1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTg0NjEsIm5iZiI6MTcxNzc1ODE2MSwicGF0aCI6Ii8xNjQxMTc5My8zMzI2NDI5ODAtMjdkZWEyZWUtM2VmNi00ZDAwLThkNDQtMWE0NWQ1NWNlZmQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDExMDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2OGEwYjEwZWI2YWU2YTc0YzMwMTc4Y2MyNTNjNGQ4OWU5YzNmYTUyMTZiYzY3NmE4MGVkZjMzNTIzZGQ1MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qPJ-DXViGNzy_fCtzf2V8PjW1mJNADeo_G8K0oovTPE)
> 
> ### 为什么我们应该优先考虑这个功能？
> 我们可以添加位置同步器来同步摄像机位置和标记十字线的变化吗

你搞出这个功能了吗

**Comment by zjhhy1314** [comment]
<img width="327" alt="2024-06-07_192610" src="https://github.com/cornerstonejs/cornerstone3D/assets/31243395/f012d08e-fc1c-4d04-be14-26385fe28fa8">
我现在搞成这样了，但重置和换工具后，旋转就有问题
