### ISSUE TITLE
[Bug] Copy annotation from stack viewport to another stack viewport(s) with different series (for Time-intensity curves)

### ISSUE THREAD

**Issue by dima99112** [cornerstonejs/cornerstone3D#1265]
### Describe the Bug

I want to copy my annotations EllipticalROI from active viewport and dublicate it to another viewports. And then calculate MEAN property from all (Time-intensity curves). 
Series in this viewports different, but FrameOfReferenceUID equal.

from
![photo_2024-05-22 14 30 02](https://github.com/cornerstonejs/cornerstone3D/assets/70155803/aec22b30-b4dd-4097-9357-52ac108fe4d9)
to
![photo_2024-05-22 14 30 04](https://github.com/cornerstonejs/cornerstone3D/assets/70155803/e33ca3c5-53e1-46c4-8e66-8c74435b961f)

i use cornerstoneTools.state.annotation.getAnnotations() method, and then replace info at metadata such as annotationUID, FrameOfReferenceUID, referencedImageId (from viewport currentImageIndex and imageIds array) but it not work

Can you create new method "copyAnnotation" for this issue?

### Steps to Reproduce

1. open 2 (and more) stack viewports with different series
2. at first viewport draw ellipse
3. try to use addAnnotation for another viewports
4. nothing happened

### The current behavior

ellipses after addAnnotation NOT appear to another viewports.

i use cornerstoneTools.state.annotation.getAnnotations() method, and then replace info at metadata such as annotationUID, FrameOfReferenceUID, referencedImageId (from viewport currentImageIndex and imageIds array) but it not work

Can you create new method "copyAnnotation" for this issue?

### The expected behavior

ellipses after addAnnotation appear to another viewports

### OS

macos sonoma 14.0

### Node version

16.20.2

### Browser

124.0.6367.209

**Comment by dima99112** [comment]
@sedghi

**Comment by sedghi** [comment]
Fir these type of use cases you need to use the volume viewport

**Comment by dima99112** [comment]
@sedghi how volume viewport can help with programatically create annotations?

annotations state from first viewport can be copied to another viewports as is i wrote if viewports type a volume?

**Comment by sedghi** [comment]
You can take a look at this example which shows how to programmatically add annotations: https://www.cornerstonejs.org/live-examples/dynamicallyaddannotations. Additionally, there is a guide available here: https://docs.ohif.org/faq/technical#how-to-dynamically-load-a-measurement.

**Comment by dima99112** [comment]
@sedghi thank you. I looked at the first link, but unfortunately the example is not working in the error console

**Comment by sedghi** [comment]
This works for me 

![CleanShot 2024-06-21 at 11 04 14@2x](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/33d878be-22c3-40a4-bd89-281e59033dd1)

**Comment by dima99112** [comment]
@sedghi right, now it works, thanks!
is the way do this for EllipticalROITool (at example i seen LenghtTool)?

is exist any docs?

**Comment by sedghi** [comment]
It is really the same thing, if you look at the example you will see
