### ISSUE TITLE
[Bug] Exception thrown when retrieving enabled element before the completion of asynchronous 'setStack()' call. [Cannot destructure property 'imagePositionPatient' of 'imagePlaneModule' as it is undefined]

### ISSUE THREAD

**Issue by Sanoj-thomas** [cornerstonejs/cornerstone3D#1270]
### Describe the Bug

- When attempting to retrieve the enabled element using the **'getEnabledElement()'** method before the asynchronous **'setStack()'** call has completed, an **exception is thrown** due to imagePlaneModule being undefined.

### Steps to Reproduce
1. Go to https://www.cornerstonejs.org/live-examples/dicomimageloaderwadouri
2. Open console.
3. Select image CTImage.dcm_JPEGProcess14SV1TransferSyntax_1.2.840.10008.1.2.4.70.dcm from the list.
4. Observe the error logged to the console.

OR

1. Execute the provided code snippet.
2. Ensure that the setStack() method call is not awaited.
3. Attempt to retrieve the enabled element using the getEnabledElement method immediately after initiating the setStack() call.
``` ts
    useEffect(() => {
        const element = document.getElementById(
            props.identifier,
        ) as HTMLDivElement | null;

        // No need to proceed if the HTML element is invalid.
        if (null === element) {
            return;
        }

        // No need to proceed if the rendering engine is invalid.
        if (!props.renderingEngine) {
            return;
        }

        //Enabling the viewport.
        props.renderingEngine.enableElement({
            element: element,
            viewportId: props.identifier,
            type: ViewportType.STACK,
        });

        const viewport = props.renderingEngine?.getViewport(
            props.identifier,
        ) as StackViewport;

        // No need to proceed if the viewport is invalid.
        if (!viewport) {
            return;
        }

        // Adding images to the viewport stack.
        // To reproduce the bug we are not awaiting the call.
        viewport
            .setStack(props.seriesImageList, latestImageIndex.current)
            .then(() => {
                CsToolsUtilities.stackPrefetch.enable(
                    document.getElementById(props.identifier),
                );
            });

        // Following line will throw an exception.
        const enabledElement = getEnabledElement(element);
        console.log('The enabled element is ', enabledElement);
    }, [
        props.identifier,
        props.renderingEngine,
        props.renderingEngineId,
        props.seriesImageList,
    ]);
```

### The current behavior

- Attempting to retrieve the enabled element using getEnabledElement immediately after initiating the asynchronous setStack() call throws an exception with the message:

```
Uncaught TypeError: Cannot destructure property 'imagePositionPatient' of 'imagePlaneModule' as it is undefined.
    at StackViewport.getImagePlaneReferenceData
    at StackViewport.getFrameOfReferenceUID
    at getEnabledElementByIds
    at getEnabledElement 
```

This occurs because imagePlaneModule is undefined at the time of the attempted destructuring.

### The expected behavior

- The code should not throw an exception when attempting to retrieve the enabled element using getEnabledElement before the asynchronous setStack() call has completed.
- Given that getEnabledElement() is a commonly used method, this scenario presents a significant risk of breaking the application if not addressed.

### Cornerstone version

**@cornerstonejs/core :** 1.74.5
**@cornerstonejs/tools:** 1.74.5

### OS

Windows 11

### Node version

20.12.0

### Browser

Chrome 124.0.6367.210

**Comment by heyflynn** [comment]
I got this exception when updating from 1.66.11 to 1.74.7

I walked through the last few weeks of versions and identified the exception was introduced in 1.71.5

1.71.4 works
https://github.com/cornerstonejs/cornerstone3D/compare/v1.71.4...v1.71.5

**Comment by Sanoj-thomas** [comment]
@sedghi 

- Could you kindly verify whether the solution proposed [**here**](https://github.com/cornerstonejs/cornerstone3D/issues/1174#issuecomment-2116935905) addresses the mentioned bug? 
- If further investigation seems necessary, would you mind assigning someone to delve deeper? I believe this bug has the potential to be a showstopper. 

Thank you in advance for your assistance.

**Comment by Sanoj-thomas** [comment]
@sedghi 

- I believe the PR [#1291](https://github.com/cornerstonejs/cornerstone3D/issues/1270) will address the following issues as well. You **can close them** once it's done.
  - #1272
  - #1252

- However, I don't think this PR solves the following issue. The report suggests it's similar, but the fix might be needed elsewhere in the code for solving the below issue. 
  - #1174
