### ISSUE TITLE
[Bug] VolumeRotateMouseWheelTool stop rotate the whole body

### ISSUE THREAD

**Issue by amr-rology** [cornerstonejs/cornerstone3D#1300]
### Describe the Bug

When using VolumeRotateMouseWheelTool to rotate the body, it is back and not contuie to show the all body.

https://drive.google.com/file/d/18WCEP5DdP8HYudF_o4QovSYm9FjXHR85/view?usp=sharing

### Steps to Reproduce

Open PET-CT or TMTV on OHIF 
Use mouse wheel to rotate the PET MIP 

### The current behavior

It is rotate from the left to the right and not show the patient posterior 

### The expected behavior

Rotate the patient whole body 360 degree.

### OS

Ubuntu 24.04 LTS

### Node version

14.20.1

### Browser

Version 125.0.6422.112 (Official Build) (64-bit)

**Comment by sedghi** [comment]
It is working as expected, it is rotating. Notice the head and the brain.
