### ISSUE TITLE
[Bug] Scrolling a zoomed StackViewport, resets the zoom to 1

### ISSUE THREAD

**Issue by vrassouli** [cornerstonejs/cornerstone3D#1301]
### Describe the Bug

When I zoom a stack viewport (on some of series), and start to scroll in the stack, the zoom resets at some specific indexes.
This does not happen for all the series, but for some

### Steps to Reproduce

I'm using the latest version - 1.77.3

I attach an anonymized series which has this issue.
[Stack Zoom Issue - Anonymized3.zip](https://github.com/user-attachments/files/15530346/Stack.Zoom.Issue.-.Anonymized3.zip)

### The current behavior

if you zoom at image#1 (index 0), and scroll the series, the zoom will be reset at image#4 (index 3)

### The expected behavior

The zoom should remain the same for the stack

### OS

Windows 11

### Node version

v22.0.0

### Browser

Edge

**Comment by sedghi** [comment]
I understand the situation. We reset the properties if we detect a difference between the previous image and the current image (metadata: rows, columns, orientation). However, we can simply discard the pixel data and orientation while retaining the zoom and pan settings. We will investigate this further.

**Comment by idemopacs** [comment]
I am also facing the same issue, after stack scroll zoom , window level, pan, orientation everything resets.

**Comment by sedghi** [comment]
This occurs for some datasets where the viewport detects discrepancies. For example, from one slice to another, the pixel data size might have changed, or the orientation might have shifted, or there might be other inconsistencies. However, I understand that this might not be the desired behavior in some situations. Do you have your anonymized data to share?

**Comment by idemopacs** [comment]
[images.zip](https://github.com/user-attachments/files/16228392/images.zip)

Please see attached images.

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)
