### ISSUE TITLE
[Bug] Trying to show the point's data on hover/mouse move.

### ISSUE THREAD

**Issue by AdilZahid** [cornerstonejs/cornerstone3D#1303]
**Trying to show the point's data on hover/mouse move.** 

I am displaying probeTool Annotations when the image loads. You can see image#1 for reference. As you can see, there are a lot of probe points so I'm showing them with "textBoxVisibility: false".  In the Next step, I'm trying to show each point's data when hovering over the point. 

I tried the MOUSE_MOVE event but this event keeps occurring with no annotation details like Annotation UID to set  "textBoxVisibility: true".

I tried ANNOTATION_RENDERED Event too because this event successfully occurs when you hover over the point. But the issue with the event is, that it still doesn't have the Annotation details like UID so that I can reset "textBoxVisibility: true".

I explored other events too but neither worked. 

Is there any other way to achieve this?  Or any other event that lets me know that this point got hovered with annotation details (UID). I tried the community forum too but did not get any response. 

Image#1
![image](https://github.com/cornerstonejs/cornerstone3D/assets/40502642/5b896a89-8cb9-4d32-86d7-e314e2eb849e)

Image#2
![image](https://github.com/cornerstonejs/cornerstone3D/assets/40502642/2044d1fd-4860-4046-b399-4cd3509d0b4e)

### Steps to Reproduce

...

### The current behavior

I tried MOUSE_MOVE and  ANNOTATION_RENDERED Events to show point data only when the mouse moves on that point But they are not returning any annotation details like (UID) to the annotation textBoxVisibility: true.

### The expected behavior

I want to show point data only when the mouse moves on that point after setting textBoxVisibility: true using the annotation UID.

### OS

Ubunutu

### Node version

18

### Browser

Chrome

**Comment by AdilZahid** [comment]
@sedghi, Can you please look at this?

**Comment by sedghi** [comment]
What happened? Did you figure it out?
