### ISSUE TITLE
[Bug] Memory leak in stack viewport in cornerstone 1.43.0 onwards

### ISSUE THREAD

**Issue by ganeshiyer-ms** [cornerstonejs/cornerstone3D#1309]
### Describe the Bug

I have a simple example where I have a stack viewport, upon toggling images the RAM keeps increasing everytime the image is rendered. Note this is not just the initial load size but every time it's rendered the memory increases.

This was introduced in `cornerstonejs/core` version 1.43.0 where vtk.js was updated to 29.3.0 from 27.3.1 which seems to be the culprit.

### Steps to Reproduce

```main.js
import { useEffect, useRef, useState } from "react";
import dicomParser from "dicom-parser";

import React from "react";
import ReactDOM from "react-dom/client";
import { RenderingEngine, StackViewport, init } from "@cornerstonejs/core";
import { Enums } from "@cornerstonejs/core";
import * as cornerstone from "@cornerstonejs/core";
import * as cornerstoneDICOMImageLoader from "@cornerstonejs/dicom-image-loader";

const images = [
  /* Provide a list of DICOM files here with wadouri: prefix*/
];

export default function initCornerstoneDICOMImageLoader() {
  cornerstoneDICOMImageLoader.external.cornerstone = cornerstone;
  cornerstoneDICOMImageLoader.external.dicomParser = dicomParser;

  cornerstoneDICOMImageLoader.configure({
    useWebWorkers: true,
    decodeConfig: {
      convertFloatPixelDataToInt: false,
    },
  });

  let maxWebWorkers = 1;

  if (navigator.hardwareConcurrency) {
    maxWebWorkers = Math.min(navigator.hardwareConcurrency, 7);
  }

  var config = {
    maxWebWorkers,
    startWebWorkersOnDemand: false,
    taskConfiguration: {
      decodeTask: {
        initializeCodecsOnStartup: false,
        strict: false,
      },
    },
  };

  cornerstoneDICOMImageLoader.webWorkerManager.initialize(config);
}

function App() {
  const [selectedImage, setSelectedImage] = useState(images[0]);
  const [renderingEngine, setRenderingEngine] = useState(null);
  const viewerRef = useRef<HTMLDivElement>(null);

  const viewportInput = {
    viewportId: "my-viewport",
    type: Enums.ViewportType.STACK,
    element: viewerRef.current!,
    defaultOptions: {
      backgroud: [0.1, 0.2, 0.3],
    },
  };
  const [initialized, setInitialized] = useState(false);
  useEffect(() => {
    const r = async () => {
      await init();
      initCornerstoneDICOMImageLoader();
      const engine = new RenderingEngine();
      setRenderingEngine(engine as any);
      setInitialized(true);
    };
    r();
  }, []);

  useEffect(() => {
    if (!initialized) return;
    const rendering = async () => {
      renderingEngine.enableElement(viewportInput as any);
      const viewport = renderingEngine.getViewport(
        viewportInput.viewportId
      ) as StackViewport;
      await viewport.setStack([selectedImage]);
      viewport.render();
    };
    rendering();
  }, [renderingEngine, selectedImage, initialized]);

  return (
    <div className="App">
      {images.map((image, index) => (
        <button
          style={{ display: "block" }}
          key={index}
          onClick={() => setSelectedImage(image)}
        >
          {image} {selectedImage === image ? "(selected)" : ""}{" "}
        </button>
      ))}
      <div ref={viewerRef} style={{ width: "600px", height: "600px" }} />
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

```index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cornerstonejs/title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
```

1. Populate the images array with a few dicom images and run the app
2. Click through all the images and take a heap snapshot -> M1 (All images should be in the cornerstone cache now)
3. Repeat for n times and take note of heap snapshots -> M2, M3...Mn

Mn >>... M3 >> M2 >> M1

The memory snapshot increases linearly with the size of the images

### The current behavior

When image is loaded first time memory increases, however upon re-rendering the images the memory should remain constant

### The expected behavior

Memory keeps increasing. 

### OS

Windows

### Node version

16.20

### Browser

Edge Version 125.0.2535.85

**Comment by sedghi** [comment]
![CleanShot 2024-06-14 at 13 20 29@2x](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/6a1c7af4-9127-49e7-9163-4cf38f9dc0f5)


Can you provide reproducible steps without React? I can't reproduce this issue in our examples, so it might be related to your React code.

https://www.cornerstonejs.org/live-examples/stackmanipulationtools

**Comment by ganeshiyer-ms** [comment]
Hi @sedghi i'm able to reproduce this issue with cornerstone's examples

I think it's only happening with `wadouri`. Try this example https://www.[cornerstonejs.org/live-examples/dicomimageloaderwadouri](https://www.cornerstonejs.org/live-examples/dicomimageloaderwadouri). 
1. Select first image -> do a heap snapshot
2. select second image -> do a heap snapshot,
3. Now go back to first image -> do a heap snapshot
4. Keep doing this for first 2 images
![image](https://github.com/cornerstonejs/cornerstone3D/assets/89279620/a8dd5714-4a8d-4528-b53a-76499ceb65b1)

**Comment by sedghi** [comment]
we will look thanks for reproducing steps

**Comment by NivethithaHemachandran** [comment]
@sedghi Any update on this issue. We are facing a similar issue where the browser memory footprint keeps increasing as we scroll

**Comment by sedghi** [comment]
Cornerstone3D 2.0 has been released. It comes with:

- New Segmentation Architecture: Segmentations are now treated as first-class data structures, not just tools. This allows for greater flexibility and support for advanced visualization, such as multi-representational views, viewport-specific customizations, and easier management within MPR layouts.

- Introduction of VoxelManager: A more memory-efficient and streamlined approach to voxel data handling, replacing traditional scalar arrays with a unified, image-based system. This change reduces memory usage, enhances data clarity, and simplifies data access across stacks and volumes.

For more details on these updates and to guide you through the migration, please refer to our [Migration Guide](https://www.cornerstonejs.org/docs/migration-guides/intro).
