### ISSUE TITLE
[Feature Request] Use CrossHairs and WindowLevel tools simultaneously

### ISSUE THREAD

**Issue by cnszpeak** [cornerstonejs/cornerstone3D#1311]
### What feature or change would you like to see made?

Use WindowLevel tools as active tool and use crosshairs as passive tool:
Use left mouse for winlevel and when I need to change the center point i can drag the center.
(current version need to swich the tools to active between winlevel and crosshairs.When corsshairs actived,mouse down leads to change the center point.When winlevel actived,I can not move then center)

### Why should we prioritize this feature?

Use CrossHairs and WindowLevel tools simultaneously:
When set window level tool actived and cross hairs tool passived,I can drag the center point of cross hairs,NO NEED TO SWITCH BETWEEN TOOLS。

**Comment by zjhhy1314** [comment]
我也需要这个功能

**Comment by sedghi** [comment]
So you are saying right now you can't set the window level as active and crosshairs as passive?

**Comment by cnszpeak** [comment]
> So you are saying right now you can't set the window level as active and crosshairs as passive?
I can.
But I can't drag the center of crosshairs when in passive mode.
