### ISSUE TITLE
[Bug] Can't add PlanarFreehandROITool when 2 or more viewports with shared frame of reference are present

### ISSUE THREAD

**Issue by kubanm3** [cornerstonejs/cornerstone3D#1316]
### Describe the Bug

When trying to use PlanarFreehandROITool it produces error when 2 or more vieports with shared frameofreference are present. PlanarFreehandROITool has to have calculate stats set to true for error to occur.

### Steps to Reproduce

Open 2 vieports with shared frameofrerence
add PlanarFreehandROITool annotation

### The current behavior

Yuo get error in console and tool gets frozen. cant add annother annotation.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/22613738/8247a5f3-e4ca-4ecd-8f7c-d462077ea9ed)

### The expected behavior

Annotation is added

### OS

Ubutnut

### Node version

20

### Browser

Brave

**Comment by sedghi** [comment]
I apologize, but I am unable to reproduce the steps you provided. Could you please record a video demonstrating the issue? This would help me better understand and assist you.
