### ISSUE TITLE
[Bug] - Chrome bug when render more of 3 volumes

### ISSUE THREAD

**Issue by MrWerton** [cornerstonejs/cornerstone3D#1318]
### Describe the Bug

Hello, everyone! How's it going?

Recently, I've been trying to render a list of volumes, but I'm encountering a bug in Google Chrome when the quantity exceeds three. In Brave, it renders without any issues.

Below are the videos demonstrating the problem and my code. If anyone could help fix this or suggest ways to avoid this issue, I would greatly appreciate it!

### Steps to Reproduce

My code is here: https://github.com/MrWerton/cornerstone3d-view

### The current behavior
Chrome

https://github.com/cornerstonejs/cornerstone3D/assets/95698369/a4ac86dd-7a3d-4a8b-ad1e-c7b1d941dafb

### The expected behavior
Brave 

https://github.com/cornerstonejs/cornerstone3D/assets/95698369/0a4f15e9-d041-465e-88af-f7dbace4b89f

### OS

Windows 11

### Node version

18

### Browser

Chrome

**Comment by sedghi** [comment]
Try chrome canary?

**Comment by MrWerton** [comment]
@sedghi No, but I tried using Opera and encountered the same issue. I also tested it on a weaker PC (i5 with 8GB of RAM), and the problem occurs with a single volume. In this pc, the issue is consistent across all browsers (Opera, Chrome, Brave, Edge...). This only work without bug in my mac

**Comment by sedghi** [comment]
Maybe it is related to the webgl backend, take a look at pinned issues, there is one talking sbout windows issues

**Comment by MrWerton** [comment]
Hi @sedghi,



@sedghi  Thank you for the solution! It works perfectly on my local machine. However, it will only work locally because I set the flag. How can this be corrected in the deployment scenario?

Thanks again!

**Comment by sedghi** [comment]
That i dont know, so basically the issue is intel integrated gpu driver

See if updating your os drivers help

Otherwise you need to wait until they fix the driver

**Comment by MrWerton** [comment]
@sedghi Thank you very much! I will see how this behaves in deployment

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic) Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)
