### ISSUE TITLE
Crosshair position synchronization to volume3D

### ISSUE THREAD

**Issue by zjhhy1314** [cornerstonejs/cornerstone3D#1319]
### What feature or change would you like to see made?

What feature or change would you like to see made?
Is it possible to drag the crosshair in the MPR viewport to locate it in the 3D volmue viewport？
![332642980-27dea2ee-3ef6-4d00-8d44-1a45d55cefd1](https://github.com/cornerstonejs/cornerstone3D/assets/31243395/15b7df18-3906-48da-a437-65f6d5ca940c)

### Why should we prioritize this feature?

Why should we prioritize this feature?
Can we add a position synchronizer to synchronize changes in camera position and marking crosshairs

**Comment by sedghi** [comment]
It's unclear how to achieve this since 3D volume rendering doesn't have a clear reference. Do you want to display crosshairs overlaid on the 3D volume on the left?

**Comment by zjhhy1314** [comment]
For example, the mip diagram of the fourth box, the cross-line positioning function between the lesions
![Uploading 2024-06-18_171004.png…]()

**Comment by zjhhy1314** [comment]
@sedghi 
<img width="870" alt="2024-06-18_171004" src="https://github.com/cornerstonejs/cornerstone3D/assets/31243395/e19cfba1-b1e5-493f-aa5b-b72b349e23aa">

For example, the mip diagram of the fourth box, the cross-line positioning function between the lesions

**Comment by vincent1996** [comment]
> ### 您希望看到什么功能或更改？
> 您希望看到什么功能或更改？是否可以拖动 MPR 视口中的十字准线以在 3D volmue 视口中定位它？ ![332642980-27DEA2EE-3EF6-4D00-8D44-1A45D55CEFD1](https://private-user-images.githubusercontent.com/31243395/339305504-15b7df18-3906-48da-a437-65f6d5ca940c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTc3MjYsIm5iZiI6MTcyMTYxNzQyNiwicGF0aCI6Ii8zMTI0MzM5NS8zMzkzMDU1MDQtMTViN2RmMTgtMzkwNi00OGRhLWE0MzctNjVmNmQ1Y2E5NDBjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAzMDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNGQ2Zjc1ZWZiMzc2ZDUyMzdmZTViYmZmNDM0NTdhM2Q0MzE5NTlkOTVlMDdlNWM5OTcwNGNkOTMzODdlZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RyE-rrZfe-mlOwX7S-o4y-4k90voPihWIIplrYPO99Q)
> 
> ### 为什么我们应该优先考虑此功能？
> 为什么我们应该优先考虑此功能？我们是否可以添加一个位置同步器来同步相机位置和标记十字准线的变化

@zjhhy1314 
![0F9A4D61](https://github.com/user-attachments/assets/d1448b1d-d116-4110-85b2-0b4726ba22c4)
Hehe, it seems this is my browser. I am researching this feature. Do you have any good suggestions?
