### ISSUE TITLE
[Feature Request] Passing multiple volume Ids to `createAndCacheDerivedSegmentationVolume()`

### ISSUE THREAD

**Issue by prerakmody** [cornerstonejs/cornerstone3D#1331]
### Task
To perform segmentation on a scan and check them on a different scan. Check scan swapping on this [netlify](https://6671130a1ab67c00089daea3--beamish-palmier-e62bae.netlify.app/) example. On that:
 - Make a label map segmentation using "Enable Circle Brush" button on the CT scan.
 - Switch to PET scan by clicking "Show PET" (_the segmentations dont show up_)

### Requirement
Ability to pass multiple volumeIds to `createAndCacheDerivedSegmentationVolume()`. Currently (core - v1.78.1) it only supports one volumeId string ([ref](https://github.com/cornerstonejs/cornerstone3D/blob/v1.78.1/packages/core/src/loaders/volumeLoader.ts#L577))

### Sample snippet
 - Check the commented line at the bottom
```javascript
// Step 1 - Load volumes
const imageIdsCT = await createImageIdsAndCacheMetaData(searchObjCT);
volumeCT = await cornerstone3D.volumeLoader.createAndCacheVolume(volumeIdCT, { imageIds:imageIdsCT });
volumeCT.load();
        
const imageIdsPET = await createImageIdsAndCacheMetaData(searchObjPET);
volumePT = await cornerstone3D.volumeLoader.createAndCacheVolume(volumeIdPET, { imageIds: imageIdsPET });
volumePT.load();
        
// Step 2 - Set volume for viewports
await cornerstone3D.setVolumesForViewports(renderingEngine, [{ volumeId:volumeIdCT, callback: setCtTransferFunctionForVolumeActor }], viewportIds);
        
// Step 3 - Set segmentation on volume(s)
await cornerstone3D.volumeLoader.createAndCacheDerivedSegmentationVolume(volumeIdCT, {volumeId: segmentationId,});
// await cornerstone3D.volumeLoader.createAndCacheDerivedSegmentationVolume([volumeIdCT, volumeIdPET], {volumeId: segmentationId,}); // (to implement) For multiple volumes
```

### Why should we prioritize this feature?

Clinicians often do segmentations on multi-modality settings (e.g. CT + PET, CT + MR) and hence its useful to have this feature to drive adoption of cornerstone.

#### Caveat
There is an [example](https://www.cornerstonejs.org/live-examples/multivolumeapi) that shows swapping between CT and PET, but unfortunately I was unable to get the same visual output when using the `setPetColorMapTransferFunctionForVolumeActor.js`([link](https://github.com/cornerstonejs/cornerstone3D/blob/v1.77.13/utils/demo/helpers/setPetColorMapTransferFunctionForVolumeActor.js)) file

**Comment by sedghi** [comment]
So what you're describing already exists in our pipeline. Basically, a segmentation can be rendered on viewports regardless of the reference resolution. Our example probably doesn't have that set up, but in the following example, you can see that the same segmentation is rendered on both CT and PET. What you're describing is about rendering, and we already have that set up.

https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463

**Comment by prerakmody** [comment]
I think I get what you are saying. Thanks!
