### ISSUE TITLE
[Bug]  Error importing tools.utilities.polyDataUtils.getPolyDataPoints in a .worker.ts file in a Vite 4 environment

### ISSUE THREAD

**Issue by robustNan** [cornerstonejs/cornerstone3D#1333]
### Describe the Bug

I updated the dependencies from 1.51.5 to 1.78.1 and one of the previous .worker.ts files is not working properly all over. The cause of the problem is that the .worker.ts file uses tools.utilities.polyDataUtils.getPolyDataPoints and throws an unexpected error message. I'm sure I'm not using VideoRedactionTool in my project.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/f57659cf-c43d-40b6-8902-b564e1f982c1)

### Steps to Reproduce

1. Create a .worker.ts file and introduce it in the project
![image](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/4865e376-6dca-42c1-8bc7-2bce37c9716e)

2. Introducing tools.utilities in the .worker.ts file
![image](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/30d1e95c-6e1d-4898-a0aa-fc164fa07599)

3. Executing the worker in the project

### The current behavior

Cannot execute and throws an error

### The expected behavior

executes normally and returns the points data

### OS

Windows 11

### Node version

18.20.3

### Browser

Edge 125.0.2535.92 (x64)

**Comment by sedghi** [comment]
I'm working on fixing the vite stuff soon, but i will target vite 5

**Comment by sedghi** [comment]
I'm working on cornerstone3D 2.x and have made progress in removing circular dependencies and publishing the types for the DICOM image loader. I'm trying to make it work with Vite, but there are numerous issues with Vite in `dev` mode, which are not directly related to Cornerstone. Multiple mentions of Vite problems with `import.meta.url`, web workers, and WebAssembly can be found on the Vite GitHub repository:

https://github.com/vitejs/vite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+import.meta.url

I have started a template project for Vite, React, and cornerstone3D beta 2.x here. I appreciate your help in making it work.

https://github.com/cornerstonejs/vite-react-cornerstone3d

**Comment by robustNan** [comment]
Thanks for your help, I referenced the template you created and upgraded my Vite environment to v5 and the problem is solved!
