### ISSUE TITLE
more doc for viewport 

### ISSUE THREAD

**Issue by 1009058470** [cornerstonejs/cornerstone3D#1339]
### What feature or change would you like to see made?

I have find [oblique Volume Slice](https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/core/examples/multiVolumeAPI/index.ts) like this

case orientationOptions.oblique:
        // Some random oblique value for this dataset
        viewUp = [-0.5962687530844388, 0.5453181550345819, -0.5891448751239446];
        viewPlaneNormal = [
          -0.5962687530844388, 0.5453181550345819, -0.5891448751239446,
        ];

        viewport.setCamera({ viewUp, viewPlaneNormal });
        viewport.resetCamera();
        break;
I want to know how this two param（viewUp and viewPlaneNormal） work?
Any help?

### Why should we prioritize this feature?

we want to doc for viewport that can show different clip image in 3d
now this is to easy for that 

[now doc](https://www.cornerstonejs.org/docs/concepts/cornerstone-core/viewports)

**Comment by sedghi** [comment]
You can look at vtk book to know more about camera https://vtk.org/vtk-textbook/

But basically 

viewUp is the vector that points from camera focal point to the up
ViewPlaneNormal is a vector from focal point to the camera position

What is your use case? Regardless of these two options, what orientation do you want to render?

**Comment by 1009058470** [comment]
> You can look at vtk book to know more about camera https://vtk.org/vtk-textbook/
> 
> But basically
> 
> viewUp is the vector that points from camera focal point to the up ViewPlaneNormal is a vector from focal point to the camera position
> 
> What is your use case? Regardless of these two options, what orientation do you want to render?

I want to do render cpr using cornerstone3D like [this](https://github.com/djelouze/vtkKinship)

**Comment by sedghi** [comment]
Can you share a video?

**Comment by 1009058470** [comment]
![image](https://github.com/cornerstonejs/cornerstone3D/assets/30902531/0bb78174-0fbd-46ea-8cd4-5bc95da20526)
![B T%F4$79{RC5@_5Z)NAC41](https://github.com/cornerstonejs/cornerstone3D/assets/30902531/d3f20846-12de-4eeb-b57b-ac43773198ab)


something like this 
using [this](https://vtkjournal.org/browse/publication/838)

**Comment by sedghi** [comment]
What you are describing is curved planar reconstruction. Unfortunately, it is not in the immediate roadmap.

**Comment by 1009058470** [comment]
> What you are describing is curved planar reconstruction. Unfortunately, it is not in the immediate roadmap.
Is this possible through cornerstone3d using vtk.js ? i want to have a try

**Comment by sedghi** [comment]
Yes it will use vtk.js

**Comment by abarbermate** [comment]
Hi @sedghi,

I'm also very interested in CPR (Curved Planar Reformation) functionality within Cornerstone.js.
I am planning to implement this for a cephalometric annotation and analysis tool as part of my Master's thesis.

Do you have any updates on the roadmap for native CPR support in Cornerstone3D?
Any guidance or timeline would be greatly appreciated!

You can reach me at [mate1024@gmail.com](mailto:mate1024@gmail.com)
