### ISSUE TITLE
[Feature Request] use wadors imageLoader by dicom file

### ISSUE THREAD

**Issue by 934556826** [cornerstonejs/cornerstone3D#1348]
### What feature or change would you like to see made?

I migrated from the old version of cornerstone2D, and now there are tens of terabytes of dicom files on OBS, and it is impossible to separate such a large amount of metaData from pixel data. Now I want to use dicom file links for imageId on top of wadors
For example: imageIds: [' wadors:... s1i1. dcm', 'wadors:... s1i2. dcm']
How can I modify wadors to get pixel data from the dicom file after downloading the file?
Or is there a better way? Thank you very much

### Why should we prioritize this feature?

For users of the cornerstone2D version, OBS stores a large number of dicom files, which is difficult to convert all to wadors protocol compliant data

**Comment by sedghi** [comment]
Hmmm, wadors is not designed for that, what you are explaining is wadouri which we have support for it as well.

**Comment by 934556826** [comment]
Thank you very much for your reply. I didn't know enough about my problem before. Since I'm using cloud storage to store dicom files, not the Dicom Web server, I can only use the wodouri loader for now. 
But now there's an error see: https://github.com/cornerstonejs/cornerstone3D/issues/1069
I'm using lossless compression

> 嗯，wadors 不是为此设计的，你解释的是 wadouri，我们也支持它。

**Comment by 934556826** [comment]
Based on wadouri Loader
Problem description:
stackviewport loads normally,
enabled stackContextPrefetch, after The whole SeriesInstanceUID was loaded, and then MPR was opened and displayed normally,
Disable stackContextPrefetch, open MPR, load error
![1719804215955](https://github.com/cornerstonejs/cornerstone3D/assets/55786312/7b5cb764-1be1-401b-ba9b-b640d2a11033)

**Comment by sedghi** [comment]
Can you open the issue on OHIF ? here is not the place for this
