### ISSUE TITLE
How to remove the bed board in volumeViewport3D

### ISSUE THREAD

**Issue by keguoquan** [cornerstonejs/cornerstone3D#1350]
### What feature or change would you like to see made?

![image](https://github.com/cornerstonejs/cornerstone3D/assets/80510582/79d5a338-df56-49f8-853d-7ce1bea06f62)

How to remove the bed board in volumeViewport3D?

### Why should we prioritize this feature?

How to remove the bed board in volumeViewport3D?

**Comment by sedghi** [comment]
One of our collaborators have agreed to open source a image cropper that might solve your issue, stay tuned

**Comment by keguoquan** [comment]
Okay, I will continue to follow and thank you very much for responding to my questions!

**Comment by keguoquan** [comment]
When can expect to provide this image cropper?
