### ISSUE TITLE
[Bug] StackViewport not cancelling scroll debounce timer when the Image Set is not fully Loaded

### ISSUE THREAD

**Issue by rbartonmedweb** [cornerstonejs/cornerstone3D#1355]
### Describe the Bug

When scrolling through a stack of images that has not completely loaded, Cornerstone appears to "prefer" displaying "Loading" images vs "Loaded". While working on a separate issue, I came across this following code in StackViewport:
```
    if (imageAlreadyLoaded || !debounce) {
==>clearTimeout(this.debouncedTimeout)<== missing?
      this.setImageIdIndex(newTargetImageIdIndex);
    } else {
      clearTimeout(this.debouncedTimeout);
      this.debouncedTimeout = window.setTimeout(() => {
        this.setImageIdIndex(newTargetImageIdIndex);
      }, 40);
    }
```
It seems that we are missing a clearTimeout() in the case when an image is already loaded. Since we don't clear, after immediately going to the Loaded image, the scheduled timeout callback will reset the Viewport to the last "Loading" image.

### Steps to Reproduce

1. Assume you have a Stack where images 17, 18, 19 are not Loaded, but 20 is Loaded
2. Scroll through 17->18->19-20 and stop at 20
3. Observe 20 loads, Observe 20 is immediately replaced by 19 with a "Loading" message
Note: This is almost impossible to do, sorry.

### The current behavior

When scrolling through a mixture or Loaded and Loading images in a StackViewport, there appears to be a subtle preference for displaying Loading images. If we scroll through a Loading image, to a Loaded image, we ultimately display the Loading image.  I believe this behavior, while certainly subjective, is perhaps noticeable.

### The expected behavior

Once scrolling to a Loaded Image, we should cancel the Timer so that a "Loading" image does not replace the Loaded Image after <40ms. By displaying the Loaded Image immediately, we should perceive a subjective "preference" for displaying the Loaded image over Loading images, as was intended by the code originally.

### OS

Mac

### Node version

v18.17.1

### Browser

Chrome 125.0.6422.142

**Comment by sedghi** [comment]
Can you create a mini example for us to replicate this? maybe a video at least?

**Comment by sedghi** [comment]
How can I reproduce it? Do you have the steps to do so?

**Comment by EstebanVictorio** [comment]
@sedghi not sure if you're replying to OP, but for my case, the issue was on my end, closed https://github.com/cornerstonejs/cornerstone3D/issues/1481 👌

**Comment by sedghi** [comment]
Yeah thanks, I wanted to see if @rbartonmedweb can reproduce it anymroe

**Comment by rbartonmedweb** [comment]
Thanks for fixing it! I will look at your code for #1481.

I fixed that problem on my end by ensuring that only the Active Viewport was added as a source to the Sync Group.

Regarding the Timer issue, I noticed that the Mouse Wheel and Scroll Bar have different internal implementations. The later lacking a debounce mechanism. I changed the Scroll Bar work more like the Mouse Wheel.
