### ISSUE TITLE
[Bug] Desired resource size is greater than max texture size

### ISSUE THREAD

**Issue by lambacini** [cornerstonejs/cornerstone3D#1360]
### Describe the Bug

Image size 640x2060x48 (Coronal AP)
MAX_TEXTURE_SIZE = 16384
MAX_3D_TEXTURE_SIZE = 2048 

The image loads fine as a stack, but when i want to load volume (3d segmentation) i'm getting errors 
"texImage3D: width, height or depth out of range " and "Desired resource size is greater than max texture size "
Is there any chance that i can downsample if the image size is larger than the max texture size? 

<img width="1366" alt="Screenshot 2024-06-27 at 18 27 05" src="https://github.com/cornerstonejs/cornerstone3D/assets/943188/c25b2f36-d980-446b-a1a2-b12e19204b4a">

### Steps to Reproduce

Load image dimensions , bigger than MAX_3D_TEXTURE_SIZE

### The current behavior

cannot load images with a size larger than MAX_3D_TEXTURE_SIZE as a volume.

### The expected behavior

Can it be loaded? 

### OS

MacOS 10.15.7

### Node version

20.14.0 LTS

### Browser

any browser

**Comment by sedghi** [comment]
Ooops you are almost 20 voxels bigger, 
You can downsample at the source using tools like ITK, I suppose. Currently, there are no browser-based options available.

**Comment by lambacini** [comment]
Thanks for the answer.
I will try resampling with wasm
