### ISSUE TITLE
[Bug] Issue in runtime useing @vue/cli-service building tool after upgrade cornerstone libs.

### ISSUE THREAD

**Issue by AmrGablla** [cornerstonejs/cornerstone3D#1361]
### Describe the Bug

I got this error after upgrade to 1.81.0 versions in my vue2 project:

The error:
VolumeProperty.js:209 Uncaught TypeError: Cannot read properties of undefined (reading 'FAST_LINEAR')
    at 37801 (VolumeProperty.js:209:40)
    at n (bootstrap:19:32)
    at 90956 (chunk-vendors.18561ab7.js:90:347282)
    at n (bootstrap:19:32)
    at index.js:1:104
    at 9616 (index.js:1:2)
    at n (bootstrap:19:32)
    at 88735 (app.91ee32ab.js:26:544626)
    at n (bootstrap:19:32)
    at startup:4:87
    
    
    My vue.config.js file:
    const { defineConfig } = require("@vue/cli-service");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const path = require("path");

module.exports = defineConfig({
  transpileDependencies: ["vuetify"],
  devServer: {
    headers: {
      "Cross-Origin-Opener-Policy": "same-origin",
      "Cross-Origin-Embedder-Policy": "credentialless",
    },
  },
  outputDir: "vue-build/viewer-build/dist",
  assetsDir: "viewer-assets-dir",
  configureWebpack: {
    externals: {
      experiments: {
        asyncWebAssembly: true,
      },
    },
    resolve: {
      //alias: require('./aliases.config').webpack
      alias: {
        "@cornerstonejs/dicom-image-loader":
          "@cornerstonejs/dicom-image-loader/dist/dynamic-import/cornerstoneDICOMImageLoader.min.js",
        "@cornerstonejs/tools": "@cornerstonejs/tools/dist/umd/index.js",
      },
    },
    plugins: [
      new CopyWebpackPlugin({
        patterns: [
          {
            from: path.join(__dirname, "node_modules/@cornerstonejs/dicom-image-loader/dist/dynamic-import"),
            to: path.join(__dirname, "vue-build/dist/viewer-assets-dir/js"),
            toType: "dir",
          },
        ],
      }),
    ],
  },
});
 

### Steps to Reproduce

1. Upgrade to leatest cornerstone versions.
2. Run build command from webpack -vue cli service-
3. You got the error on the runtime.

### The current behavior

Project stop from work.

![image](https://github.com/cornerstonejs/cornerstone3D/assets/12821376/70f6db58-5bab-4e0d-a897-0ac86c4e523b)

### The expected behavior

Must load and work 

### OS

Ubuntu 24.04 LTS

### Node version

v14.20.1

### Browser

Chrome 125.0.6422.112 (Official Build) (64-bit)

**Comment by sedghi** [comment]
I'm not really sure what is the issue, hmmm

**Comment by AmrGablla** [comment]
It is solved by using webpack version 5.89.0
It is looks like there are error with versoin after that.
