### ISSUE TITLE
[Bug] Memory Leaks on inter cpu computer

### ISSUE THREAD

**Issue by xionghailong1205** [cornerstonejs/cornerstone3D#1370]
### Describe the Bug

I am currently developing a dicomviewer, The program works fine on AMD CPU and Apple chip Mac, but when I use my colleague's inter CPU laptop, memory leaks occur on more than one laptop. 

### Steps to Reproduce

Create a volume with about 200 dicom slices
View Resource Manager

### The current behavior

On AMD laptops and apple core mac:

![comman_view](https://github.com/cornerstonejs/cornerstone3D/assets/77221108/ab250004-9ceb-4e61-9360-57c890e7b5a2)
![common_memory](https://github.com/cornerstonejs/cornerstone3D/assets/77221108/4bccd911-e70a-4085-a4cf-f9ad8684cb2f)

On inter laptop, More than this one:

![unexpect_memory](https://github.com/cornerstonejs/cornerstone3D/assets/77221108/36edade8-7aa8-484b-b6e0-64b7bfc305c0)
![unexpect_view](https://github.com/cornerstonejs/cornerstone3D/assets/77221108/59acefd7-2897-44bb-b68c-8e70d86fc337)

### The expected behavior

On inter-CPU computers, too much memory is used, which may be a memory leak.

### OS

window 11

### Node version

20.12.2

### Browser

chrome 126

**Comment by David2k13** [comment]
Update the browser and driver to the latest or https://github.com/OHIF/Viewers/issues/3207

**Comment by xionghailong1205** [comment]
> Update the browser and driver to the latest or [OHIF/Viewers#3207](https://github.com/OHIF/Viewers/issues/3207)

I upgraded the driver but still can't render volumes, I turned off gpu acceleration and the computer crashed. Do you have an inter cpu computer? Is this a common problem?

**Comment by xionghailong1205** [comment]
> Update the browser and driver to the latest or [OHIF/Viewers#3207](https://github.com/OHIF/Viewers/issues/3207)

thanks i solve this problem by setting the angle backend as opengl.

**Comment by ksdhyPro** [comment]
Some computers cannot set the angle to OpenGL, and it is also inconvenient for users to adjust the open option. I have encountered this problem and still haven't solved it. My DICOM data consists of 600 slices, and the memory can reach 10GB+
