### ISSUE TITLE
[Bug] generateVolumePropsFromImageIds allocates an Int16Array if rescale or intercept is negative, which is incompatible with texSubImage3D

### ISSUE THREAD

**Issue by abustany** [cornerstonejs/cornerstone3D#1379]
### Describe the Bug

Cornerstone release: 1.81.2

`generateVolumePropsFromImageIds` will use an `Int16Array` instead of a `Uint16Array` to store the image data if the rescale/intercept parameters are negative and `preferSizeOverAccuracy` is `true`. ([relevant code](https://github.com/cornerstonejs/cornerstone3D/blob/c55fb0b168e05da4f89ab24a207adc54a15e076b/packages/core/src/utilities/generateVolumePropsFromImageIds.ts#L38)). As far as I understand, the `texSubImage3D` method used by VTK when streaming image data into a volume does not accept `Int16Array` ([MDN reference](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texSubImage3D#pixels)). This in turns leads to an error being thrown: `INVALID_OPERATION: texSubImage3D: type HALF_FLOAT_OES but ArrayBufferView is not NULL and not Uint16Array`.

### Steps to Reproduce

1. Init Cornerstone with `preferSizeOverAccuracy` set to true
1. Load a CT stack where the rescale intercept parameter (DICOM tag 0028,1052) has a negative value into the streaming volume loader

### The current behavior

`INVALID_OPERATION` thrown by the code

### The expected behavior

The volume renders

### OS

Linux

### Node version

20

### Browser

Chrome 126

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by sedghi** [comment]
Please check the latest cornerstone3D; we might have resolved the issue.

**Comment by sedghi** [comment]
This is fixed in Cornerstone3D 2.0
