### ISSUE TITLE
[Bug] 使用volumeLoader.registerVolumeLoader("nifti", cornerstoneNiftiImageVolumeLoader);加载图像出现Bug

### ISSUE THREAD

**Issue by HuangJia-Le** [cornerstonejs/cornerstone3D#1389]
### Describe the Bug

我的代码中使用了volumeLoader.registerVolumeLoader("nifti", cornerstoneNiftiImageVolumeLoader);来加载Nii.gz文件，但是当我传入了本地的肠癌的nii.gz文件时，解析之后显示的图像似乎不正确，会发生倾斜，具体表现如下：
![屏幕截图 2024-07-11 202412](https://github.com/cornerstonejs/cornerstone3D/assets/53884902/17140ba2-686d-4d78-8e44-7792c9842c68)

我使用itk-snap打开之后的表现如下：
![image](https://github.com/cornerstonejs/cornerstone3D/assets/53884902/829000b6-c076-4ccf-b8d3-a90df5be38bc)

### Steps to Reproduce

XXX

### The current behavior

XXX

### The expected behavior

我希望使用CornerStone3D来正确显示肠癌的图像，不要发生倾斜

### OS

windows11

### Node version

18.17.0

### Browser

Chrome120.0.6099.217

**Comment by sedghi** [comment]
I apologize, but I cannot read the language you've used. Could you please try translating it into English?

**Comment by ManWang2019** [comment]
I encountered the same problem，the image displayed after parsing seems to be incorrect, causing tilt/incomplete display
![1729653257926](https://github.com/user-attachments/assets/56268522-d2ec-4e14-a376-434d22633979)
[Uploading Huashan-PcaLabel-557_0000.nii.gz…]()

**Comment by ManWang2019** [comment]
I encountered the same problem，the image displayed after parsing seems to be incorrect, causing tilt/incomplete display

![1729653257926](https://github.com/user-attachments/assets/8b5ce48f-333a-4cec-8515-6a5f16410bd9)

[Huashan-PcaLabel-557_0000.nii.gz](https://github.com/user-attachments/files/17484619/Huashan-PcaLabel-557_0000.nii.gz)

**Comment by sedghi** [comment]
Nifti loading has changed considerable for good, please check cornersone3D 2.0

**Comment by nagychris** [comment]
> Nifti loading has changed considerable for good, please check cornersone3D 2.0

Hi @sedghi, could you please point to a documentation link or some example where I can see an updated version on how to use the `cornerstoneNiftiImageVolumeLoader` from the `@cornerstonejs/nifti-volume-loader` package after the 2.0 update? I  could not find such a guide in the current [docs](https://www.cornerstonejs.org/docs), nor in the [PR](https://github.com/cornerstonejs/cornerstone3D/pull/696) the functionality was apparently introduced. Thank you!

**Comment by sedghi** [comment]
See the example here packages/nifti-volume-loader/examples/niftiWithTools/index.ts
