### ISSUE TITLE
[Bug] First image rendered by the volume loader is not the first instance in series

### ISSUE THREAD

**Issue by jyotirmayzamre** [cornerstonejs/cornerstone3D#1391]
### Describe the Bug

I'm using Orthanc as a Dicom-Web server to store an anonymized CT study with 361 instances that I got from the internet and I am fetching that study to display in a volume viewport. Everything is working fine except that the first instance that is rendered by the volume loader is instance no. 181. When I switch to sagittal/coronal, it loads instance no. 257.  Also, suppose I scroll to instance number 2 in the axial orientation and when I change to sagittal, it goes back to instance 257. I am using the createImageIdsAndCacheMetaData function from demo/helpers. Any idea as to what the issue could be? Maybe it isn't fetching the images in the correct order?

### Steps to Reproduce

I am following the volume viewport API example with a personal Orthanc server as a dicom-web server.

### The current behavior

Volume loader doesn't load the first instance in the series first, it waits till the 181th instance.

### The expected behavior

Volume Loader should load the first instance first.

### OS

Windows 10

### Node version

20.14.0

### Browser

Brave 1.67.123

**Comment by sedghi** [comment]
By default, volume viewports i guess load the middle, you can change that 

csToolsUtils.jumpToSlice(viewport.element, {
        imageIndex,
      });

**Comment by jyotirmayzamre** [comment]
Thank you for the reply! I think I missed this in the documentation. Should I include this line before viewport.render()? or immediately after?
