### ISSUE TITLE
Rendering .nii file error

### ISSUE THREAD

**Issue by scorpio921** [cornerstonejs/cornerstone3D#1396]
### Describe the Bug

The code used in this path   packages/nifti-volume-loader/examples/niftiBasic/index.ts  

### error
![image](https://github.com/user-attachments/assets/3ffecdea-653d-4514-9e9e-f6578981fc97)

### Steps to Reproduce

xxx

### The current behavior

xxxxx

### The expected behavior

xxxxxx

### OS

window 10

### Node version

18.13.0

### Browser

chrome  126.0.6478.127

**Comment by sedghi** [comment]
Please check out the latest nifty example, it will show you what you need to do. [https://github.com/cornerstonejs/vite-react-cornerstone3d/blob/main/src/Nifti.tsx](https://github.com/cornerstonejs/vite-react-cornerstone3d/blob/main/src/Nifti.tsx)
