### ISSUE TITLE
[Bug] It takes too long to unload any memory used for previously cached images or volumes

### ISSUE THREAD

**Issue by jyotirmayzamre** [cornerstonejs/cornerstone3D#1407]
### Describe the Bug

I have a React component which uses cornerstone 3D for a viewer interface. I am fetching a study from an Orthanc server and displaying the images. I am using purgeCache() and I am destroying all created volumes in ComponentWillUnmount. However, I have noticed two things. If I load the webpage that contains the component, the JS heap size shoots to around 30 Mb. This is to be expected. If I refresh the page, the heap size temporarily shoots up to around 55-60 Mb but then comes back down to 30 Mb. This is probably the browser garbage collecter's doing (or maybe something else).

If I redirect to a different route in my web app and open the page with the component again, it shoots up to 60 Mb and stays there for quite some time (roughly 15 minutes) before it unloads previous memory and comes back down to around 30. I am using Brave.

Is this an issue with how I'm unloading the cache? or maybe something in my web app? I am just caching the image metadata and the volumes that get created. Ideally, the unmount function should run whenever I go to a different route.

Any help would be appreciated.

  

### Steps to Reproduce

I cannot give steps to reproduce without giving all of my code. I will post some snaps of the memory size before and after.

When first loaded:
![image](https://github.com/user-attachments/assets/e7a642e4-cb73-4017-829a-4e7b57e6de1b)

After redirecting and opening page again:
![image](https://github.com/user-attachments/assets/556bf79d-9663-4e34-825c-1499b869959f)

### The current behavior

Memory is taking too long to unload when I redirect and come back to the interface.

### The expected behavior

I am purging the cache so it should come back down to around 30 Mb quickly.

### OS

Windows 10

### Node version

v20.14.0

### Browser

Brave

**Comment by sedghi** [comment]
I don't think this exists anymore after the release of Cornerstone 3D 2.0. I'm going to close this, but feel free to reopen it if it's still an issue.
