### ISSUE TITLE
[Bug] Images fail to render on some Android devices

### ISSUE THREAD

**Issue by arturojain** [cornerstonejs/cornerstone3D#1408]
### Describe the Bug

Images show as blank or a gray square on some Android devices.

### Steps to Reproduce

1. Open a file on an Android devices, exact device is difficult to pin point but it happens on many older devices.

### The current behavior

Shows blank or gray square.

### The expected behavior

Show the image.

### OS

Android

### Node version

20

### Browser

Chrome

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)

**Comment by sedghi** [comment]
This is fixed in cs3d 2.0
