### ISSUE TITLE
[Bug] createVOISynchronizer signature is incorrect

### ISSUE THREAD

**Issue by jeremygau** [cornerstonejs/cornerstone3D#1431]
### Describe the Bug

Hello,
The signature of the createVOISynchronizer function is incorrect. The options should be optional because they are assingned in the body of the function but currently they are required so Typescript throw an error when we don't provide them.

### Steps to Reproduce

Use the createVOISynchronizer function with typescript

### The current behavior

```javascript
createVOISynchronizer(
  synchronizerName: string,
  options: VOISynchronizerOptions
)
```

### The expected behavior

```javascript
createVOISynchronizer(
  synchronizerName: string,
  options?: VOISynchronizerOptions
)
```

### OS

macOs

### Node version

21.7.3

### Browser

All

**Comment by sedghi** [comment]
I believe this is fixed with the latest release. Please reopen if the issue persists.
