### ISSUE TITLE
[Feature Request] Accessing DICOM Tags

### ISSUE THREAD

**Issue by vrassouli** [cornerstonejs/cornerstone3D#1439]
### What feature or change would you like to see made?

It would be great to have an API to access all DICOM tags, like PatientName, PatientID, Institution Name, and so on.
There are some metadata providers for getting PatientName (for example), but some tags are missing like InstitutionName.

### Why should we prioritize this feature?

In cases of existence of multiple studies from multiple sources for a specific patient, it's important and vital to display some tags, to the end user, to prevent miss understandings.

**Comment by sedghi** [comment]
Retrieve the metadata from `metadataModules` using `metaData.get('moduleName', imageId)`.

**Comment by vrassouli** [comment]
But which module has the 'InstitutionName' for example?
I checked all the module names, but couldn't find 'InstitutionName'

**Comment by vrassouli** [comment]
> But which module has the 'InstitutionName' for example? I checked all the module names, but couldn't find 'InstitutionName'

I iterate through all modules, but could not find institution name:

`
        for (let item in MetadataModules)
        {
            console.log('Module: '+item);
            let meta = metaData.get(item, viewport.getCurrentImageId());
            console.log(meta);
        }
`

**Comment by sedghi** [comment]
Check the file at `packages/dicomImageLoader/src/imageLoader/wadors/metaData/metaDataProvider.ts`: [metaDataProvider.ts](https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/dicomImageLoader/src/imageLoader/wadors/metaData/metaDataProvider.ts).

Review the locations and note the type system here: [MetadataModuleTypes.ts](https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/core/src/types/MetadataModuleTypes.ts).

If anything is missing, feel free to submit a PR to add it to the `metaDataProvider`.
