### ISSUE TITLE
[Feature Request] Get the silhouette of surface actor.

### ISSUE THREAD

**Issue by Qwd2017** [cornerstonejs/cornerstone3D#1443]
### What feature or change would you like to see made?

![2024-08-27_135341](https://github.com/user-attachments/assets/4193cf14-44e6-46fb-9488-4b7def8ed0e2
Firstly, we create a VOLUME_3D viewport with parallel projection off.
Secondly, we add a surface actor to the 3D viewport.
Finally, we want to get the silhouette of surface actor

### Why should we prioritize this feature?

In radiotherapy, physicists need to observe the projection silhouette of ROI on DRR

**Comment by sedghi** [comment]
We have surface to contour converters [https://www.cornerstonejs.org/live-examples/polysegwasmsurfacetocontour](https://www.cornerstonejs.org/live-examples/polysegwasmsurfacetocontour)
