### ISSUE TITLE
[Bug] When I create labelmap segmentation, the image will automatically jump to the center

### ISSUE THREAD

**Issue by IrvingLu** [cornerstonejs/cornerstone3D#1451]
### Describe the Bug

When I create label segmentation, the image will automatically jump to the center，I think it's correct for the image to stay at the current layer。
Contour type segmentation does not have this situation

### Steps to Reproduce

1、Image flipping
2、Create  Labelmap Segmentation
await volumeLoader.createAndCacheDerivedSegmentationVolume(
    primaryMprVolumeId,
    {
      volumeId: segmentationId,
    }
  );
  segmentation.addSegmentations([
    {
      segmentationId,
      representation: {
        type: csToolsEnums.SegmentationRepresentations.Labelmap,
        data: {
          volumeId: segmentationId,
        },
      },
    },
  ]);
  const representationIds = await segmentation.addSegmentationRepresentations(
    mprToolGroupId,
    [
      {
        segmentationId: segmentationId,
        type: csToolsEnums.SegmentationRepresentations.Labelmap,
      },
    ]
  );

### The current behavior

 The image will automatically jump to the center。

### The expected behavior

The image stays at the current layer

### OS

windows10

### Node version

1.61.5

### Browser

Chrome

**Comment by IrvingLu** [comment]
![20240903165211_rec_](https://github.com/user-attachments/assets/ffef097e-6181-4f4c-9ad7-14bd3299c442)

**Comment by sedghi** [comment]
It is because it switch to volume viewport, we are working to fix it in cornerstone3D 2.0

**Comment by SooyoonJi** [comment]
how can I prevent it? (it means prevent to go center)
is there any cheat or something?

**Comment by IrvingLu** [comment]
> how can I prevent it? (it means prevent to go center) is there any cheat or something?

Remember it, then jump back

**Comment by SooyoonJi** [comment]
> how can I prevent it? (it means prevent to go center) is there any cheat or something?
> 
> Remember it, then jump back

I am curious about the timing of back it to the center.
When should I jump back? 
After the SEGMENTION_REPENSION_MODIFIED event is triggered? or anything else?

**Comment by IrvingLu** [comment]
> I am curious about the timing of back it to the center.
> When should I jump back?
> After the SEGMENTION_REPENSION_MODIFIED event is triggered? or anything else?

I think you don't need to dwell on this issue, CS3D will help you handle it in version 2.0.  
After the SEGMENTION_REPENSION_MODIFIED event is triggered，It's the right approach

**Comment by SooyoonJi** [comment]
> > I am curious about the timing of back it to the center.
> > When should I jump back?
> > After the SEGMENTION_REPENSION_MODIFIED event is triggered? or anything else?
> 
> I think you don't need to dwell on this issue, CS3D will help you handle it in version 2.0. After the SEGMENTION_REPENSION_MODIFIED event is triggered，It's the right approach

I need a temporary solution right now before the coronerstone3D 2.0 version release.
I handled it in CAMERA_RESET event hanlder. 
Thanks for your tips 🙂

**Comment by sedghi** [comment]
You should getPresentation and getViewReference before and set it after 
something like this packages/core/src/utilities/convertStackToVolumeViewport.ts

```
import type {
  IStackViewport,
  IStreamingImageVolume,
  IVolumeViewport,
  Point3,
} from '../types';
import { setVolumesForViewports } from '../RenderingEngine/helpers';
import {
  createAndCacheVolume,
  getUnknownVolumeLoaderSchema,
} from '../loaders/volumeLoader';
import type { OrientationAxis } from '../enums';
import { Events, ViewportType } from '../enums';
import uuidv4 from './uuidv4';

/**
 * Converts a stack viewport to a volume viewport.
 *
 * @param params - The parameters for the conversion.
 * @param params.viewport - The stack viewport to convert.
 * @param params.options - The options for the conversion.
 * @param [params.options.volumeId] - The volumeId that will get generated, it should have the volume loader schema defined if not we will use the default one.
 * @param [params.options.viewportId] - The viewportId that will get used for new viewport. If not provided, the stack viewport id will be used.
 * @param [params.options.background] - The background color of the volume viewport.
 * @returns The converted volume viewport.
 */
async function convertStackToVolumeViewport({
  viewport,
  options = {},
}: {
  viewport: IStackViewport;
  options?: {
    volumeId?: string;
    viewportId?: string;
    background?: Point3;
    orientation?: OrientationAxis;
  };
}): Promise<IVolumeViewport> {
  const renderingEngine = viewport.getRenderingEngine();

  let volumeId = options.volumeId || `${uuidv4()}`;

  // if there is no loader schema for the volume Id, we will use the default one
  // which we can get from the volume loader
  if (volumeId.split(':').length === 0) {
    const schema = getUnknownVolumeLoaderSchema();
    volumeId = `${schema}:${volumeId}`;
  }

  const { id, element } = viewport;
  const viewportId = options.viewportId || id;

  const imageIds = viewport.getImageIds();

  // It is important to keep the camera before enabling the viewport
  const prevViewPresentation = viewport.getViewPresentation();
  const prevViewReference = viewport.getViewReference();

  // this will disable the stack viewport and remove it from the toolGroup
  renderingEngine.enableElement({
    viewportId,
    type: ViewportType.ORTHOGRAPHIC,
    element,
    defaultOptions: {
      background: options.background,
      orientation: options.orientation,
    },
  });

  // Ideally here we should be able to just create a local volume and not use the
  // volume louder but we don't know if the stack is already pre-cached for all its
  // imageIds or not so we just let the loader handle it and we have cache
  // optimizations in place to avoid fetching the same imageId if it is already
  // cached
  const volume = (await createAndCacheVolume(volumeId, {
    imageIds,
  })) as IStreamingImageVolume;

  volume.load();

  // we should get the new viewport from the renderingEngine since the stack viewport
  // was disabled and replaced with a volume viewport of the same id
  const volumeViewport = renderingEngine.getViewport(
    viewportId
  ) as IVolumeViewport;

  await setVolumesForViewports(
    renderingEngine,
    [
      {
        volumeId,
      },
    ],
    [viewportId]
  );

  const volumeViewportNewVolumeHandler = () => {
    volumeViewport.render();

    element.removeEventListener(
      Events.VOLUME_VIEWPORT_NEW_VOLUME,
      volumeViewportNewVolumeHandler
    );
  };

  const addVolumeViewportNewVolumeListener = () => {
    element.addEventListener(
      Events.VOLUME_VIEWPORT_NEW_VOLUME,
      volumeViewportNewVolumeHandler
    );
  };

  addVolumeViewportNewVolumeListener();

  volumeViewport.setViewPresentation(prevViewPresentation);
  volumeViewport.setViewReference(prevViewReference);

  volumeViewport.render();

  return volumeViewport;
}

export { convertStackToVolumeViewport };

```

**Comment by sedghi** [comment]
This issue does not occur in the latest OHIF 3.9, which defaults to stack segmentation. I'm closing it, but feel free to reopen if problems persist.
