### ISSUE TITLE
[Feature Request] How to customize the input annotation pop-up event of ArrowAnnotateTool？

### ISSUE THREAD

**Issue by 934556826** [cornerstonejs/cornerstone3D#1461]
### What feature or change would you like to see made?

![image](https://github.com/user-attachments/assets/17950b36-2137-4647-ac18-df7a1defa9e7)

### Why should we prioritize this feature?

like OHIF
![image](https://github.com/user-attachments/assets/eb04e00f-6317-4dd6-b857-c8c548533223)
Thanks

**Comment by sedghi** [comment]
This is OHIF please post there
