### ISSUE TITLE
Viewer not working for Philips machine MRI images

### ISSUE THREAD

**Issue by kundanashish** [cornerstonejs/cornerstone3D#1462]
### Describe the Bug

Viewer not working for Philips machine MRI images.

I am loading the files using wadouri which is giving me Error: "The pixel data is missing"
I have tried the same in ohif as well to douvble check but it is not loading in there as well.

I have attached a sample Dicom file for reference.
[image-000001.zip](https://github.com/user-attachments/files/16963646/image-000001.zip)

### Steps to Reproduce

try to load the dicom file

### The current behavior

it is giving error as "The pixel data is missing"

### The expected behavior

the file should display in viewer

### OS

NA

### Node version

NA

### Browser

All

**Comment by sedghi** [comment]
This looks fine on latest

[https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

<img src="https://uploads.linear.app/e0b640a9-3fd8-4513-bc84-af25921e5dc8/35332d0f-51bd-472c-a133-422e4eede23c/401c960d-6055-4509-b518-5b1d7077429d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UwYjY0MGE5LTNmZDgtNDUxMy1iYzg0LWFmMjU5MjFlNWRjOC8zNTMzMmQwZi01MWJkLTQ3MmMtYTEzMy00MjJlNGVlZGUyM2MvNDAxYzk2MGQtNjA1NS00NTA5LWI1MTgtNWIxZDcwNzc0MjlkIiwiaWF0IjoxNzMxNjIwMjExLCJleHAiOjMzMzAyMTgwMjExfQ.I62CRV-qHbiykMnUhbJe7Oxn8WaF82FyygWL5LT4G6Y " alt="CleanShot 2024-11-14 at 16.36.29@2x.png" width="1862" height="1092" />
