### ISSUE TITLE
Angular Viewer Component

### ISSUE THREAD

**Issue by yanqzsu** [cornerstonejs/cornerstone3D#1493]
### What feature or change would you like to see made?

I have created an open-source project [ng-cornerstone](https://github.com/yanqzsu/ng-cornerstone) based on CornerstoneJS, which is an Angular component that facilitates integration with various Angular projects and can also serve as a reference. 

During the development process, I have resolved many issues related to the integration with Angular, and I hope this can be helpful to fellow Angular developers.

Welcome to try it out and provide suggestions for improvement.

[Online DEMO](https://angular-cornerstone-demo.netlify.app/)

### Why should we prioritize this feature?

not a bug nor feature

**Comment by kubanm3** [comment]
Nice, good job. Will find it handy

**Comment by sedghi** [comment]
Great stuff! i will add it to our docs

**Comment by sedghi** [comment]
Can you help fix the Angular template? The promises are converting to zoneAwarePromise, and I need help debugging this issue.
https://github.com/cornerstonejs/angular-cornerstone3d

**Comment by yanqzsu** [comment]
> Can you help fix the Angular template? The promises are converting to zoneAwarePromise, and I need help debugging this issue. https://github.com/cornerstonejs/angular-cornerstone3d

Sure. I will try it
