### ISSUE TITLE
no volume loader for volumeId

### ISSUE THREAD

**Issue by haoxl3** [cornerstonejs/cornerstone3D#150]
I use the imageIds for this case, [click here](https://www.cornerstonejs.org/live-examples/crosshairs), but I got an error
<img width="694" alt="image" src="https://user-images.githubusercontent.com/15046133/179750081-ea56fc48-8655-48f1-8d6f-8ec320a25dad.png">
my code is [here](https://github.com/haoxl3/ct-label-3d/blob/main/src/pages/crossHairs.tsx)
What type of data should it be?

**Comment by sedghi** [comment]
You most likely have not initialized the CornerstoneWADOImageLoader, see `initWADO...` in our code base

**Comment by haoxl3** [comment]
> 
no, I have init...

**Comment by IbrahimCSAE** [comment]
I think you forgot to register an image loader to cornerstone3D, you can do the following like this

```
import * as cornestone3DVolumeLoader from "@cornerstonejs/streaming-image-volume-loader";
import * as cornerstone3D from "@cornerstonejs/core";

      cornerstone3D.volumeLoader.registerUnknownVolumeLoader(
        cornestone3DVolumeLoader.cornerstoneStreamingImageVolumeLoader
      );
      cornerstone3D.volumeLoader.registerVolumeLoader(
        "cornerstoneStreamingImageVolume",
        cornestone3DVolumeLoader.cornerstoneStreamingImageVolumeLoader
      );
      cornerstone3D.imageLoader.registerImageLoader(
        "streaming-wadors",
        cornestone3DVolumeLoader.sharedArrayBufferImageLoader
      );
```

**Comment by alex644715** [comment]
> > 
> 
> no, I have init...

have you address this issue? :(

**Comment by sedghi** [comment]
Take a look at init function in the examples to see how to register the volume loaders
utils/demo/helpers/initDemo.js
