### ISSUE TITLE
[Bug] ReferenceLinesTool can render with solid line style rather that dashed line style

### ISSUE THREAD

**Issue by John-Skinner** [cornerstonejs/cornerstone3D#1500]
### Describe the Bug

When using arrowAnnotateTool when ReferenceLineTool is active, toggling between viewports can cause the ReferenceLineTool to become solid.

### Steps to Reproduce

1. load Neptune mrn 0000002 (part of the set used by viewer.ohif.org) with [basic viewer] mode
2. switch layout to 2x1 (ie 2 across) scout will be in left, axial in right
3. select length tool
4. draw in scout
5. select w/l tool
6. click on axial
7. The scout will now have a solid line rather than dotted line.  Not expected.

### The current behavior

without using length tool above, one sees dotted reference line rather than solid reference line.
Dotted reference line is always expected.
Using length tool and switching to axial viewport causes the reference line to be solid.  That is not expected.

### The expected behavior

The reference line is expected to be dotted line style at all times.

### OS

Ubuntu

### Node version

20

### Browser

chrome Version 129.0.6668.100 (Official Build) (64-bit)

**Comment by John-Skinner** [comment]
Issue reproduced with viewer.ohif.org on 14-oct-2024 
https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095258.1

**Comment by sedghi** [comment]
I think this belong in OHIF, can you post it there please?

**Comment by sedghi** [comment]
I have a PR for this
