### ISSUE TITLE
[Feature Request] Standalone minimal Cornerstone3D example

### ISSUE THREAD

**Issue by EugeneQilo** [cornerstonejs/cornerstone3D#1506]
### What feature or change would you like to see made?

It will be very beneficial to have a standalone example showing how to initialize and load a resource with the bare minimum code needed. The examples provided in the repo are great but they are buried deep with too much stuff. Trying to extract the code gives all kinds of errors especially with types

### Why should we prioritize this feature?

Having this is essential for new developers to adapt and get started with this project. The way current documentation is set is very convoluted making it very difficult to create a "Hello world" program.

**Comment by sedghi** [comment]
check this one out https://www.cornerstonejs.org/docs/tutorials/basic-stack
