### ISSUE TITLE
multiple segmentation representations warning logged incorrectly

### ISSUE THREAD

**Issue by LeoReubelt** [cornerstonejs/cornerstone3D#1510]
### Describe the Bug

'Multiple segmentation representations detected for this tool group. The first one will be used.' is logged when it shouldn't be.

In the function below, which is in ContourSegmentationBaseTool.ts,   `segmentationState.getSegmentationRepresentations(this.toolGroupId).length > 1` should be `validSegmentationRepresentations.length > 1`

```
  private _getSegmentationRepresentation(segmentationId) {
    const segmentationRepresentations =
      segmentationState.getSegmentationRepresentations(this.toolGroupId);

    const validSegmentationRepresentations = segmentationRepresentations.filter(
      (representation) => representation.segmentationId === segmentationId
    );

    if (!validSegmentationRepresentations) {
      console.warn(
        `No segmentation representation found for toolGroupId: ${this.toolGroupId}`
      );
      return;
    }

    if (
      segmentationState.getSegmentationRepresentations(this.toolGroupId)
        .length > 1
    ) {
      console.warn(
        'Multiple segmentation representations detected for this tool group. The first one will be used.'
      );
    }

    return validSegmentationRepresentations[0];
  }
```

### Steps to Reproduce

1. Add multiple segmentation representations to a single toolgroup id.

### The current behavior

Despite having different segmentation ids, adding multiple segmentation representations causes the above warning to be logged repeatedly.

### The expected behavior

The warning should only be logged if there are more than one segmentation representation with the same segmentation id.

### OS

macOS 15.0.1

### Node version

v16.14.0

### Browser

Version 129.0.6668.103

**Comment by sedghi** [comment]
The segmentation system and its representations have been redesigned to improve architecture. Check the migration guides at https://www.cornerstonejs.org/docs/migration-guides/2x/tools
