### ISSUE TITLE
[Feature Request] Option to align the DICOM image to a specific edge of Viewport

### ISSUE THREAD

**Issue by wadevs** [cornerstonejs/cornerstone3D#1515]
### What feature or change would you like to see made?

Hi,
Currently the initial position and zoom of the image is "fit-to-screen", according to [this documentation page](https://www.cornerstonejs.org/docs/concepts/cornerstone-core/viewports/#initial-display-area).
In some use cases, as for instance with mammographs, it would be interesting to align the image with an edge of the viewport. I assume this case could be handled using the "initial display area" but there doesn't seem to be an "easy-to-use" option such as "top", "bottom", "left" or "right" and neither could I achieve the desired result with this functionality.

Example of the proposed alignment to the "right" of the viewport :
![image](https://github.com/user-attachments/assets/8c57c496-541a-4e5e-a864-a2ebeef238ae)

Thank you for considering this feature suggestion.

### Why should we prioritize this feature?

The proposed feature should not interact with other features as it should only affect the initial display state as "fit-to-screen" does.

**Comment by sedghi** [comment]
I wish i could do it in cornerstone3D 2.0, but then it became even a bigger migration guides, since all tests would fail, so i decided to keep it for later. 

You can see how you can achieve so using this example for now https://v1.cornerstonejs.org/live-examples/stackPosition
