### ISSUE TITLE
[Bug] @cornerstonejs/tools tool group, should setToolActive deactived other active binding?

### ISSUE THREAD

**Issue by fancyoung** [cornerstonejs/cornerstone3D#1517]
### Describe the Bug

When I dynamic change tool active, I found "setToolActive" didn't deactived previous active tool, so it will not working.
Although I can loop to deactive all tools by `toolGroup.setToolPassive(k, { removeAllBindings: true })` manually.

I thought `setToolActive` should do this automatically?

### Steps to Reproduce

```
toolGroup.setToolActive('Zoom', {
    bindings: [ { mouseButton: MouseBindings.Primary } ],
});
toolGroup.setToolActive('WindowLevel', {
    bindings: [ { mouseButton: MouseBindings.Primary } ],
});
```

### The current behavior

```
toolGroup.toolOptions = {
    "WindowLevel": {
        "bindings": [
            {
                "mouseButton": 1
            }
        ],
        "mode": "Active"
    },
    "Zoom": {
        "bindings": [
            {
                "mouseButton": 1
            }
        ],
        "mode": "Active"
    }
}
```

Then the operation is not working.

### The expected behavior

Should only one active operation.

### OS

macOS

### Node version

v18.19.0

### Browser

Chrome 129

**Comment by sedghi** [comment]
No, it doesn't set that automatically. Should we do it, @wayfarer3130?

**Comment by wayfarer3130** [comment]
No, it is entirely possible to have multiple active tools.  What you are looking for is whether it binds the primary mouse button as the active setting.  It is supposed to rebind the primary mouse button, but often things like zoom are active on other buttons, and are thus still active.  If you were binding a secondary button, then you would want it to automatically remove the old binding on that button, and that is something I think we should do
