### ISSUE TITLE
[Bug] Can't display dicoms with transfer syntaxes 1.2.840.10008.1.2.4.91 and 1.2.840.10008.1.2.4.90 in Volume Viewport

### ISSUE THREAD

**Issue by tokyobordel** [cornerstonejs/cornerstone3D#1520]
### Describe the Bug

Can't display dicoms with transfer syntaxes 1.2.840.10008.1.2.4.91 and 1.2.840.10008.1.2.4.90 in Volume Viewport. 
I use the following images: https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEG2000TransferSyntax_1.2.840.10008.1.2.4.91.dcm
https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEG2000LosslessOnlyTransferSyntax_1.2.840.10008.1.2.4.90.dcm

The error is as follows: 
`Uncaught (in promise) dicomParser.readFixedString: attempt to read past end of buffer`

Images load fine in Stack Viewport, but since I need MPR, Volume Viewport is required. I upload images via wadouri. Other images (with other transfer syntaxes) load fine in both Volume and Stack viewports. Inside dicomParser I found that my byteArray was suddenly empty, but it happened before it got to readFixedString. Where exactly it happens I'm not sure.

### Steps to Reproduce

1. Create viewport with type Volume:
```
const viewportInput = {
    viewportId,
    type: ViewportType.ORTHOGRAPHIC,
    element: input,
    defaultOptions: {
      orientation: projection
    },`
};
```
`this.renderingEngine.enableElement(viewportInput);`
`this.viewport =  this.renderingEngine.getViewport(viewportId) as Types.IVolumeViewport;`
2. Load image ids via volumeLoader:
```
const volumePromise = volumeLoader.createAndCacheVolume(volumeId, {imageIds}).then(volumeLoaded => {
    volumeLoaded.load()
    this.volume = volumeLoaded;
    this.viewport.setVolumes([
        { volumeId },
    ]);

    this.viewport.render();
});
```

### The current behavior

`Uncaught (in promise) dicomParser.readFixedString: attempt to read past end of buffer`

### The expected behavior

Image is loaded and displayed

### OS

Win 10

### Node version

20.15.1

### Browser

Chrome 130.0.6723.70

**Comment by sedghi** [comment]
which version of cs3d is this? last night i released 2.0

**Comment by sedghi** [comment]
Could you explain what happened with your issue before you marked it as completed for future reference?

**Comment by tokyobordel** [comment]
@sedghi sorry, forgot about this. I updated to 2.0.0 and my probleme is gone

**Comment by sedghi** [comment]
That is great to hear!
