### ISSUE TITLE
[Bug] build 

### ISSUE THREAD

**Issue by wzf5166** [cornerstonejs/cornerstone3D#1523]
### Describe the Bug

![087f5e562cd0f1139e562c513ac936ea](https://github.com/user-attachments/assets/f0d7c857-573e-4d66-a52f-4f6eef42cbd1)

### Steps to Reproduce

pnpm build

### The current behavior

pnpm build

### The expected behavior

pnpm build

### OS

windows 10

### Node version

v18.19

### Browser

Firefox

**Comment by sedghi** [comment]
increase heap allocation cross-env NODE_OPTIONS=--max_old_space_size=32384

**Comment by wzf5166** [comment]
> 增加跨环境的堆分配 NODE_OPTIONS=--max_old_space_size=32384

eee，of no use，I have ‘node --max-old-space-size=12288 node_modules/vite/bin/vite.js build’，but ‘  resolve: {
            alias: {
                '@': path.resolve(__dirname, 'src'),
                '@cornerstonejs/tools': path.resolve(__dirname,
                    'node_modules/@cornerstonejs/tools/dist/umd/index.js'),
                '@cornerstonejs/core': path.resolve(__dirname,
                    'node_modules/@cornerstonejs/core/dist/umd/index.js'),
                // 'vue-i18n': 'vue-i18n/index'
            }
        },’，issue was settled
