### ISSUE TITLE
[Bug] I'm having trouble using imageLoader.loadImage

### ISSUE THREAD

**Issue by qiaozhi-4** [cornerstonejs/cornerstone3D#1524]
### Describe the Bug

First of all, thank you very much for your project
I was a novice.
I'd like to ask some questions.
I'm using imageloader. There is a problem with loadimage, it has an error "Cannot read properties of undefined (reading '0')"

### Steps to Reproduce

1.The framework I use is nuxt3;
2.Error occurred in 'await imageLoader.loadImage(imageIds[0])'
3.The error is "Cannot read properties of undefined (reading '0')"

`
import type { Types } from '@cornerstonejs/core';
import { Enums, imageLoader, init as csRenderInit, RenderingEngine } from '@cornerstonejs/core';
import { init as csToolsInit } from '@cornerstonejs/tools';
import cornerstoneDICOMImageLoader from '@cornerstonejs/dicom-image-loader';

const route = useRoute();
onMounted(async () => {
  /*创造图片展示区*/
  const content = document.getElementById('content');
  const element = document.createElement('div');
  element.style.width = '500px';
  element.style.height = '500px';
  content?.appendChild(element);

  /*初始化*/
  csRenderInit();
  await csToolsInit();
  cornerstoneDICOMImageLoader.init({
    maxWebWorkers: navigator.hardwareConcurrency || 1,
  });
  console.log('初始化完成');

  // const imageIds = ['wadouri:http://172.27.0.1:3000/dicom/56364408.dcm'];
  const imageIds = ['wadouri:http://192.168.110.49:3000/dicom/56364408.dcm'];
  // const imageIds = ['wadouri:http://192.168.110.49:3000/dicom/202001110048.dcm'];
  await imageLoader.loadImage(imageIds[0])
  console.log('加载图片完成');

  // 实例化一个渲染引擎
  const renderingEngineId = 'myRenderingEngine';
  const renderingEngine = new RenderingEngine(renderingEngineId);
  const viewportId = 'CT_STACK';

  const viewportInput = {
    viewportId,
    type: Enums.ViewportType.STACK,
    element: element,
  };

  renderingEngine.enableElement(viewportInput);

  const viewport = renderingEngine.getViewport(viewportId) as Types.IStackViewport;

  // const stack = [imageIds[0]];

  // viewport.setStack(stack)
  await viewport.setStack(imageIds);

  viewport.render();
  console.log('渲染');
});
`

### The current behavior

[
![image](https://github.com/user-attachments/assets/0b0aa140-b811-433d-a6db-ce0741b33d5e)
](url)
TypeError: Cannot read properties of undefined (reading '0')
    at RequestPoolManager.addRequest (http://192.168.110.49:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-MTKSKRDC.js?v=8d285b6a:4694:31)
    at http://192.168.110.49:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-CYLWABI2.js?v=8d285b6a:44912:30
    at new Promise (<anonymous>)
    at CentralizedWorkerManager.executeTask (http://192.168.110.49:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-CYLWABI2.js?v=8d285b6a:44878:12)
    at processDecodeTask (http://192.168.110.49:3000/_nuxt/node_modules/@cornerstonejs/dicom-image-loader/dist/esm/imageLoader/decodeImageFrame.js?v=8d285b6a:12:29)
    at decodeImageFrame (http://192.168.110.49:3000/_nuxt/node_modules/@cornerstonejs/dicom-image-loader/dist/esm/imageLoader/decodeImageFrame.js?v=8d285b6a:28:20)
    at createImage (http://192.168.110.49:3000/_nuxt/node_modules/@cornerstonejs/dicom-image-loader/dist/esm/imageLoader/createImage.js?v=8d285b6a:71:27)
    at dataSetPromise.then.reject.error.error (http://192.168.110.49:3000/_nuxt/node_modules/@cornerstonejs/dicom-image-loader/dist/esm/imageLoader/wadouri/loadImage.js?v=8d285b6a:24:34)

### The expected behavior

Display image

### OS

Windows11

### Node version

20.17.0

### Browser

Chorme 130.0.6723.70（正式版本） （32 位）

**Comment by sedghi** [comment]
Did you try cornerstone3D 2.0? it is awesome

**Comment by qiaozhi-4** [comment]
> 你试过 cornerstone3D 2.0 吗？它棒极了

Yes, I am using cornerstone3D 2.0,
This is the dependency I use:
    "@cornerstonejs/core": "2.0.0-beta.30",
    "@cornerstonejs/dicom-image-loader": "2.0.0-beta.30",
    "@cornerstonejs/tools": "2.0.0-beta.30",

**Comment by qiaozhi-4** [comment]
> 你试过cornerstone3D 2.0吗？它棒极了

I think my card in the 'createImageIdsAndCacheMetaData' : 'const instances = await client. RetrieveSeriesMetadata (studySearchOptions); ';
Because I'm not an example of a standard server;
I directly through an HTTP request 'http://192.168.110.49:3000/dicom/56364408.dcm' access to a file, I don't know how to convert him to 'instances'

**Comment by sedghi** [comment]
I see, seems like you are doing wadouri, take a look at wadouri example in our codebase

**Comment by AlexMold** [comment]
@sedghi Could you point to the robust example of manipulating local(uploaded by user) `.dcm` files?
And one more question, how can I distinguish the projection of the uploaded file?

**Comment by sedghi** [comment]
You can check this example of local files packages/tools/examples/local/index.ts

**Comment by qiaozhi-4** [comment]
> 我明白了，好像你正在做 wadouri，看看我们代码库中的 wadouri 示例

Hello, is there a clear path?
I compare the packages/tools/examples/local/index. The ts sample, Found only do more cornerstoneDICOMImageLoader. Wadouri. FileManager. Add (response. The blob ()), I did, however, Still has been waiting for await cornerstoneDICOMImageLoader. Wadouri. LoadImage (imageIds [0]). The promise

**Comment by qiaozhi-4** [comment]
Problem solved, is my dependence, add rely on "dicomParser. ReadFixedString: attempt to read past the end of buffer"; And using viteCommonjs() in vite.config.ts, thanks for your help
