### ISSUE TITLE
[Bug] Failed to execute 'structuredClone' on 'Window': #<Object> could not be cloned.

### ISSUE THREAD

**Issue by virtualman333** [cornerstonejs/cornerstone3D#1527]
### Describe the Bug

![image](https://github.com/user-attachments/assets/f365fe0a-e7e9-4ade-b6b8-65156018850d)
![image](https://github.com/user-attachments/assets/4cc03413-fae2-4700-a69b-f2a6f471c880)
![image](https://github.com/user-attachments/assets/ea42f408-d421-4a1b-accc-75f7e290be05)

### Steps to Reproduce

1. let viewportArray into vuex(store)
2.
store.state.renderingEngine = new RenderingEngine(
      store.state.renderingEngineId,
  ); //创建渲染引擎
  for (let i = 0; i < store.state.viewportInputArray.length; i++) {
    store.state.viewportInputArray[i].element = document.getElementById(store.state.viewportInputArray[i].viewportId);
  }
  store.state.renderingEngine.setViewports(store.state.viewportInputArray);
3.
errror

### The current behavior

throw error  <Failed to execute 'structuredClone' on 'Window': #<Object> could not be cloned.>

### The expected behavior

success setviewport

### OS

window11

### Node version

22

### Browser

Chorme 130.0.6723.70

**Comment by virtualman333** [comment]
I understand the cause of this problem and have resolved it. StructuredClone() can only allow deep copying of the original object, but the object I passed in was encapsulated by a proxy, causing this error.

I don't think structuredClone should be used to implement deep copy in this section. In modern frameworks such as Vue3, many variables that need to be reused are encapsulated by proxies, which can result in the inability to set Viewports.

To solve it, as shown in the figure below, I have to create a new array to pass in.
![image](https://github.com/user-attachments/assets/08e9126e-f6e0-4ffd-b04e-7454dc89e62d)

**Comment by sedghi** [comment]
Thanks for the report, i will fix it

**Comment by sedghi** [comment]
you can use the library deepClone instead of structuredClone which can handle it
