### ISSUE TITLE
[Bug] 2.0: while initializing DICOM image loader: invalid URL at workerFn

### ISSUE THREAD

**Issue by sgielen** [cornerstonejs/cornerstone3D#1532]
### Describe the Bug

In my application, when I initialize the DICOM image loader using `cornerstoneDICOMImageLoader.init({})`, I get the following error:

```
Failed to construct 'URL': Invalid URL
```

I can see that [vue-cornerstone3d](https://github.com/cornerstonejs/vue-cornerstone3d) repo does the same thing and works normally, so I'm not sure yet what's different between that and my application.

### Steps to Reproduce

For me, simply calling `cornerstoneDICOMImageLoader.init({})` reproduces the issue.

### The current behavior

The issue seems to be [here](https://github.com/cornerstonejs/cornerstone3D/blob/v2.1.2/packages/dicomImageLoader/src/imageLoader/init.ts): 
```
const workerFn = () => {
  const instance = new Worker(
    new URL('../decodeImageFrameWorker.js', import.meta.url),
    { type: 'module' }
  );
  return instance;
};
```

In my debugger, I've already found that `import.meta.url` has a value in the Chrome devtools (`http://localhost:8080/node_modules/.q-cache/vite/spa/deps/@cornerstonejs_dicom-image-loader.js?v=6c391554`), but when I `console.log` it, I get `undefined`.

If I run `new URL('../decodeImageFrameWorker.js', undefined);` I get the same exception, so that tracks. When I run `new URL('../decodeImageFrameworker.js', 'http://localhost:8080/node_modules/.q-cache/vite/spa/deps/@cornerstonejs_dicom-image-loader.js?v=6c391554');` the result is `http://localhost:8080/node_modules/.q-cache/vite/spa/decodeImageFrameWorker.js` and this doesn't give the contents of the `dicomImageFrameWorker.js` but rather 404, so I'm not sure how that's supposed to work.

I don't really understand the magic behind `import.meta.url`, so I'm not sure how to proceed from here.

### The expected behavior

`cornerstoneDICOMImageLoader.init({})` returns normally and registers the image loaders, metadata provider and web worker.

### OS

macOS 15.0.1

### Node version

v22.8.0

### Browser

Chrome 130.0.6723.70 (amd64)

**Comment by trust96** [comment]
having the same problem

**Comment by sgielen** [comment]
I can get `init` to work by including [this in my vite conf](https://github.com/cornerstonejs/vue-cornerstone3d/blob/main/vite.config.ts#L50-L59):

```
  optimizeDeps: {
    exclude: [
      "@cornerstonejs/dicom-image-loader",
      "@cornerstonejs/codec-charls",
      "@cornerstonejs/codec-libjpeg-turbo-8bit",
      "@cornerstonejs/codec-openjpeg",
      "@cornerstonejs/codec-openjph",
    ],
    include: ["dicom-parser"],
  },
```

Or rather, since I'm using Quasar, including this in my Quasar config:

```
      extendViteConf(viteConf) {
        viteConf.optimizeDeps.exclude = [
          '@cornerstonejs/dicom-image-loader',
          '@cornerstonejs/codec-charls',
          '@cornerstonejs/codec-libjpeg-turbo-8bit',
          '@cornerstonejs/codec-openjpeg',
          '@cornerstonejs/codec-openjph',
        ];
        viteConf.optimizeDeps.include = ['dicom-parser'];
      },
```

With that, `init({})` returns, and I see some web worker activity in my network tab, but no decoding seems to occur, at least not successfully.

**Comment by sedghi** [comment]
I have seen this being reported elsewhere too, so i would like to have a fix for it at least. do you have a bare minimum repo to reprodcue?

**Comment by sgielen** [comment]
If I also ensure that the `@originjs/vite-plugin-commonjs` plugin is loaded, I progress a little bit further, where suddenly requests are done from the web worker to the URL `http://localhost:8080/@fs/Users/sjors/[....]/src/node_modules/@cornerstonejs/dicom-image-loader/dist/esm/shared/decoders/@cornerstonejs/codec-charls/decodewasm`

Of course, this is a 404

If, just to confirm I'm on the right path, I do create the directory `node_modules/@cornerstonejs/dicom-image-loader/dist/esm/shared/decoders/@cornerstonejs/codec-charls` and copy `codec-charls/dist/charlswasm_decode.wasm` to `decodewasm`, Vite fails with `[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.`

**Comment by dasaevc** [comment]
I have the same issue when trying to test the [angular-cornerstone3d](https://github.com/cornerstonejs/angular-cornerstone3d) project. It seems to require the decodeImageFrameWorker.js file but It's not included in the build. I've tried adding It in the assets section and, although the error doesn't appear, the loader seems not to be working.

**Comment by sedghi** [comment]
@dasaevc please don't mix things out, angular runs fine (at least for me) and decodes fine but still some weird zone promise that is a separate issue, lets [track it in here  ](https://github.com/cornerstonejs/cornerstone3D/issues/1533)

**Comment by dasaevc** [comment]
@sedghi probably I didn't explain myself well but I have tried again from scratch.
- Cloning the [angular-cornerstone3d](https://github.com/cornerstonejs/angular-cornerstone3d) project
- Going to the cloned folder
- Running `npm install`
- Running `npm run start`
- Opening http://localhost:4200
- No image is rendered
- In the network tab of developer tools I see some missing network files
![image](https://github.com/user-attachments/assets/5db8e783-a27b-4c6b-b77b-8a15486e6cc9)
- I right click in the decodeImageFrameWorker.js?worker_file&type=module item and select Open in new tab on the context menu
- It opens the URL http://localhost:4200/@fs/D:/Dev/Angular/angular-cornerstone3d/.angular/cache/18.2.10/angular-cornerstone3d/vite/decodeImageFrameWorker.js?worker_file&type=module but It returns the 404 status with the next message: `Cannot GET /@fs/D:/Dev/Angular/angular-cornerstone3d/.angular/cache/18.2.10/angular-cornerstone3d/vite/decodeImageFrameWorker.js`

I don't know if I am missing some steps. To be honest I haven't worked with vite in the past.

**Comment by zhoualibaba** [comment]
@sedghi I have a similar problem when i use vite.
![图片](https://github.com/user-attachments/assets/46c0c627-83df-4180-b964-277469fb5f7f)
Request URL:    http://xxx/node_modules/.vite/deps/decodeImageFrameWorker.js?type=module&worker_file
Request Method:   GET
Status Code:   504 Outdated Optimize Dep

**Comment by zhoualibaba** [comment]
@sgielen This new [vite.config.ts](https://github.com/cornerstonejs/vue-cornerstone3d/blob/main/vite.config.ts#L50-L59) help me

**Comment by sgielen** [comment]
I initially produced a minimum reproduction scenario using Quasar CLI. After that, @sedghi worked on it, adding fixes to Cornerstone3D and my scenario, such that it now works and my application does, as well. The final version is hosted here: https://github.com/cornerstonejs/quasar-cornerstone3d

For me, that application now also works well. I'll try to summarize the fixes in this comment, hoping to help everyone else having this issue. I don't understand much of the stack magic going on with modules and web workers, so perhaps others can elaborate where my explanation is falling short.

- Update from Vite 2 to Vite 5, which seems to have various module improvements.
  - In the case of Quasar, this means updating from `@quasar/app-vite` v1 to v2 (the example repo uses [`^2.0.0-beta.12`](https://github.com/cornerstonejs/quasar-cornerstone3d/compare/796a8f1..3b7ab60#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R31))
  - This also means `quasar.config.js` is now a module, which comes [with some syntax changes](https://github.com/cornerstonejs/quasar-cornerstone3d/compare/796a8f1..3b7ab60#diff-8b8d9829edb0b54005392ad1afe4754faa79c151b7a1fbf4c6907c391bcd00daR11-R14) (i.e. use `import` instead of `require`, use `export default` instead of `module.exports`)
- Update to [Cornerstone3D 2.1.5+](https://github.com/cornerstonejs/quasar-cornerstone3d/compare/796a8f1..3b7ab60#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R18-R20).
- Using the `@originjs/vite-plugin-commonjs` Vite plugin ([yarn](https://github.com/cornerstonejs/quasar-cornerstone3d/compare/796a8f1..3b7ab60#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R18-R20), [import](https://github.com/cornerstonejs/quasar-cornerstone3d/compare/796a8f1..3b7ab60#diff-8b8d9829edb0b54005392ad1afe4754faa79c151b7a1fbf4c6907c391bcd00daR12) and [configuration](https://github.com/cornerstonejs/quasar-cornerstone3d/compare/796a8f1..3b7ab60#diff-8b8d9829edb0b54005392ad1afe4754faa79c151b7a1fbf4c6907c391bcd00daR76))
   - In the Quasar case this is in `quasar.config.js` -> `extendViteConf`; without Quasar it will be in `vite.config.ts`, [example is here](https://github.com/cornerstonejs/vue-cornerstone3d/blob/main/vite.config.ts).
- Setting `optimizeDeps` to exclude `@cornerstonejs/dicom-image-loader` and include `dicom-parser` in [Vite configuration](https://github.com/cornerstonejs/quasar-cornerstone3d/compare/796a8f1..3b7ab60#diff-8b8d9829edb0b54005392ad1afe4754faa79c151b7a1fbf4c6907c391bcd00daR79-R82).
  - Again, in Quasar this will be in `quasar.config.js`, otherwise `vite.config.ts`, see links above.

I believe this is the full list, but in case something is missing, the full set of changes to the example is here: https://github.com/cornerstonejs/quasar-cornerstone3d/compare/796a8f1..3b7ab60

After these changes, `cornerstoneDICOMImageLoader.init({});` runs normally and images can be decoded and rendered.

**Comment by sgielen** [comment]
Closing this issue since the above fixes it for me - but if someone else is still having issues lik the above, I'll reopen to track further solutions here

**Comment by daemon29** [comment]
How to fix this issue with Angular CLI?

**Comment by sgielen** [comment]
> Hi @sgielen Do you know how to fix this issue with Angular CLI?

I see https://github.com/cornerstonejs/angular-cornerstone3d/issues/1 is about this. I've left a comment there with some suggestions to try. Could you try them and report back there?
