### ISSUE TITLE
[Bug] 2.1.5 cannot load images with loadAndCacheImage

### ISSUE THREAD

**Issue by Sergey1888888** [cornerstonejs/cornerstone3D#1539]
### Describe the Bug

Image promise is always in pending state. I try to load image with loadAndCacheImage. I think problem with:
```
function handleImageLoadPromise(
  imagePromise: Promise<IImage>,
  imageId: string
): void {
  Promise.resolve(imagePromise)
    .then((image: IImage) => {
      ensureVoxelManager(image);
      triggerEvent(eventTarget, Events.IMAGE_LOADED, { image });
    })
    .catch((error) => {
      const errorDetails: EventTypes.ImageLoadedFailedEventDetail = {
        imageId,
        error,
      };
      triggerEvent(eventTarget, Events.IMAGE_LOAD_FAILED, errorDetails);
    });
}
```
Because then and catch don't work

### Steps to Reproduce

1. Load image with loadAndCacheImage
2. Promise is always in pending state

### The current behavior

Promise is always in pending state

### The expected behavior

Promise is in fullfilled state

### OS

Windows 10

### Node version

v18.18.2

### Browser

Chrome 130

**Comment by sedghi** [comment]
which framework is this? any error in the console? any error in the network?

**Comment by Sergey1888888** [comment]
React. No errors. Promise is always in pending state.

**Comment by qiaozhi-4** [comment]
I think we have a problem with the vue+nuxt3 I use
https://github.com/cornerstonejs/cornerstone3D/issues/1524

**Comment by virtualman333** [comment]
> which framework is this? any error in the console? any error in the network?

i have same problem in vue3+vite. 
And "cornerstoneDICOMImageLoader.wadouri.fileManager“ is not work,too.
i think dicom-image-loader maybe have some problem,but i have not find it

**Comment by sedghi** [comment]
@Sergey1888888
@virtualman333 

 I need a reproducible repo if you can make, see the react vite recipe here, hopefully it helps

https://github.com/cornerstonejs/vite-react-cornerstone3d

see the rest here 

There are vue recipes too

**Comment by Sergey1888888** [comment]
@sedghi Thanks. It works only after I added these lines
![image](https://github.com/user-attachments/assets/65193fc2-8914-4f2e-9bc2-026a3fc343c9)

But I think you need add it to documentation too.

**Comment by arlagonix** [comment]
@Sergey1888888 Thanks a lot, that advice helped my college a lot!
