### ISSUE TITLE
[Bug] Error executing method 'decodeTask' on worker 'dicomImageLoader': Error: No JPEG Baseline decoder loaded     at decodeJPEGBaseline12BitAsync (decodeJPEGBaseline12Bit-js.js:20:15)

### ISSUE THREAD

**Issue by woaihengniu** [cornerstonejs/cornerstone3D#1541]
### Describe the Bug

The library I use is "@cornerstonejs/core": "^2.1.5",
"@cornerstonejs/dicom-image-loader": "^2.1.5",
I used wadouri to render MPR, but I couldn't render it successfully.
I got an Uncaught (in promise) TypeError with an uncompressed image: Cannot destructure 
![$ZPQAOKNJ}THXUQ% UHXY5M](https://github.com/user-attachments/assets/b6c402cd-9b2e-4fdc-8a0b-224bde7f1610)
property 'imagePositionPatient' of '_metaData__WEBPACK_IMPORTED_MODULE_3__.get(...) ' as it is undefined.

I made a mistake using a compressed image
![NT$LR(V`HV`N`IOW8L(L7J3](https://github.com/user-attachments/assets/5d8a34dc-3cc2-40e5-99e6-8edfc967f201)
When I returned the version of the library to 1.86, I could build MPR by rendering uncompressed images in wadouri mode, but compressed images could not be rendered to build MPR.
When I returned the version of the library to 1.23, any type of image can be rendered, can you see what the problem is

### Steps to Reproduce

1.Initialize cornerstone
2.Initialize cornerstoneDICOMImageLoader
3.Register volume loader
4.Load volume

### The current behavior

Undecoded image

### The expected behavior

Perfectly rendered image

### OS

win10

### Node version

v18.20.4

### Browser

Microsoft Edge  128.0.2739.79

**Comment by woaihengniu** [comment]
![~_I1F7)(1Q~PIKTF`%E~`$I](https://github.com/user-attachments/assets/5f961d9d-f2e0-4e06-9da4-e37ba94e87ac)

**Comment by woaihengniu** [comment]
![0L( 5NX8R8FIUKDFMVG NAQ](https://github.com/user-attachments/assets/bb1b1665-dd5b-419b-82b3-6c309f5c5af9)

**Comment by sedghi** [comment]
can i get a reproducible example? a mini repo with only necessary elements to show this bug

**Comment by woaihengniu** [comment]
> can i get a reproducible example? a mini repo with only necessary elements to show this bug

https://github.com/woaihengniu/test

**Comment by zhoualibaba** [comment]
@sedghi  I have a similar problem in 'dicomImageLoader' when i use wadouri
![img_v3_02gb_3547f4d4-e049-4628-abd3-1c9962e3fcag](https://github.com/user-attachments/assets/6dbb67ad-c1a6-4f52-a30e-cdc1fc399fd3)
![img_v3_02gb_dc23aa2d-a398-44d3-859a-517e4da6d66g](https://github.com/user-attachments/assets/02e76471-aec0-4959-922d-6e73000df4f1)

**Comment by 934556826** [comment]
me too, also use wadouri
![image](https://github.com/user-attachments/assets/d5a0667d-bea9-4be5-8480-8de1a09d04cf)

**Comment by sedghi** [comment]
@woaihengniu i can't access these images over public internet, so i can't debug

http://192.168.1.244:8285/path/image/DataPool/lossless/00250196_lossy.img

**Comment by woaihengniu** [comment]
> 我无法通过公共 Internet 访问这些图像，因此无法调试
> 
> http://192.168.1.244:8285/path/image/DataPool/lossless/00250196_lossy.img

The image address is the Intranet, and the files are in the src/dicom folder

**Comment by sedghi** [comment]
This loads fine for me 

```
<script setup>
import { RenderingEngine, Enums, volumeLoader, setVolumesForViewports } from '@cornerstonejs/core'

import initcornerstone from '../cornerstoneinit/initcornerstone.js'
const { ViewportType } = Enums;


// Instantiate a rendering engine
const imageIds = ['wadouri:https://ohif-assets.s3.us-east-2.amazonaws.com/dicom/1-01.dcm', 'wadouri:https://ohif-assets.s3.us-east-2.amazonaws.com/dicom/1-02.dcm']

async function load () {
    await initcornerstone();
    const content = document.getElementById('content');
    const element = document.createElement('div');
    element.style.width = '500px';
    element.style.height = '500px';
    content.appendChild(element);

    const renderingEngineId = 'myRenderingEngine';
    const renderingEngine = new RenderingEngine(renderingEngineId);

    const viewportId = 'CT_AXIAL';


    const volumeName = 'CT_VOLUME_ID';
    const volumeLoaderScheme = 'cornerstoneStreamingImageVolume';
    const volumeId = `${volumeLoaderScheme}:${volumeName}`;

    const viewportInput = [{
        viewportId,
        type: ViewportType.ORTHOGRAPHIC,
        element,
        defaultOptions: {
            orientation: Enums.OrientationAxis.AXIAL,
        },
    }];
    renderingEngine.setViewports(viewportInput);

    const volume = await volumeLoader.createAndCacheVolume(volumeId, {
        imageIds,
    });
    volume.load();
    setVolumesForViewports(renderingEngine, [{ volumeId }], [viewportId]);
    renderingEngine.renderViewports([viewportId]);
}


load();

</script>

<template>
    <div id="content"></div>
</template>

<style scoped>
#content {
    width: 500px;
    height: 500px;
    border: 1px solid red;
}
</style>

```

vue.config.js
```
const { defineConfig } = require("@vue/cli-service")
const CompressionWebpackPlugin = require("compression-webpack-plugin")
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin")
const version = new Date().getTime()

module.exports = defineConfig({
  transpileDependencies: true,
  productionSourceMap: true,
  chainWebpack: (config) => {
    //remove VUE_PROD_HYDRATION_MISMATCH_DETAILS__ warning
    config.plugin("define").tap((definitions) => {
      Object.assign(definitions[0], {
        __VUE_OPTIONS_API__: "true",
        __VUE_PROD_DEVTOOLS__: "false",
        __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: "false",
      })
      return definitions
    })
  },
  configureWebpack: {
    devtool: "source-map",
    experiments: {
      asyncWebAssembly: true,
    },
    output: {
      filename: `js/[name].[hash:8].js?v=${version}`,
      chunkFilename: `js/[name].[hash:8].js?v=${version}`,
    },
    resolve: {
      fallback: {
        fs: false,
      },
    },
    module: {
      rules: [
        {
          test: /\.wasm$/,
          type: "asset/resource",
        },
      ],
    },
    plugins: [
      new NodePolyfillPlugin(),
      new CompressionWebpackPlugin({
        filename: "[path].gz[base]",
        algorithm: "gzip",
        test: /\.js$|\.css$|\.html$/,
        threshold: 10240,
        minRatio: 0.8,
      }),
    ],
    optimization: {
      runtimeChunk: {
        name: "runtime",
      },
      splitChunks: {
        chunks: "all",
        maxInitialRequests: Infinity,
        minSize: 20000,
        maxSize: 250000,
        cacheGroups: {
          vendor: {
            test: /[\\/]node_modules[\\/]/,
            name: "vendors",
            priority: 10,
            chunks: "all",
          },
        },
      },
    },
  },
})

```

![CleanShot 2024-11-05 at 07 49 59@2x](https://github.com/user-attachments/assets/a2c7f0b5-00e9-4cbe-a470-69aa9fe41827)

**Comment by woaihengniu** [comment]
> const imageIds = ['wadouri:https://ohif-assets.s3.us-east-2.amazonaws.com/dicom/1-01.dcm', 'wadouri:https://ohif-assets.s3.us-east-2.amazonaws.com/dicom/1-02.dcm']
hi  I can render using these examples you gave me but the compressed image will not render is it not decoded successfully? The picture is my interrupt point to check the error location ,The transfer syntax I used is (1.2.840.10008.1.2.4.51)
![W$0NW%6EF~J`A)))MK 45FY](https://github.com/user-attachments/assets/e75ed675-6953-4ce2-bdbd-1b1369bf5d70)

**Comment by sedghi** [comment]
I can't help you without your anonymized data. Unfortunately, I can't debug without it.

**Comment by sedghi** [comment]
This still does not work http://192.168.1.244:8285/path/image/DataPool/lossless/00250196_lossy.img

**Comment by woaihengniu** [comment]
> 这仍然不起作用 http://192.168.1.244:8285/path/image/DataPool/lossless/00250196_lossy.img

 ['wadouri:http://60.205.216.219:82/20230118\\0029B45D.img', 'wadouri:http://60.205.216.219:82/20230118\\0029B45E.img', 'wadouri:http://60.205.216.219:82/20230118\\0029B45F.img',
                 'wadouri:http://60.205.216.219:82/20230118\\0029B460.img', 'wadouri:http://60.205.216.219:82/20230118\\0029B461.img', 'wadouri:http://60.205.216.219:82/20230118\\0029B462.img']

**Comment by zhoualibaba** [comment]
@sedghi  I still have this problem
![图片](https://github.com/user-attachments/assets/b9e78307-6cd5-4788-8cc8-12050c879e69)
![图片](https://github.com/user-attachments/assets/6a67e273-893a-4957-9b55-bfbc5dbce6a7)
![图片](https://github.com/user-attachments/assets/1848aeff-ddba-45c5-a1eb-f25a4f2f102a)

I found that if the meta info include "Compress Pegasus JPEG Lossless",it will occur this error.  
"./data-stream.js"
![图片](https://github.com/user-attachments/assets/715b652b-dc60-4e5c-8044-93911f4a520f)

**Comment by woaihengniu** [comment]
> @sedghi I still have this problem ![图片](https://private-user-images.githubusercontent.com/17982206/383377952-b9e78307-6cd5-4788-8cc8-12050c879e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTg0ODMsIm5iZiI6MTczMDg1ODE4MywicGF0aCI6Ii8xNzk4MjIwNi8zODMzNzc5NTItYjllNzgzMDctNmNkNS00Nzg4LThjYzgtMTIwNTBjODc5ZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAxNTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZGUyOTEyNzY3MDEyZWFhZDNjYmM4NWZlNDMyM2ExNWZhYjVkOWZhMDVhMTZhYTAyN2Q1M2EwZGU2OGYxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AbWP3sUVuGkpRhJteLItY5TdkrLIfFNP5-Sysp1yNBQ) ![图片](https://private-user-images.githubusercontent.com/17982206/383377954-6a67e273-893a-4957-9b55-bfbc5dbce6a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTg0ODMsIm5iZiI6MTczMDg1ODE4MywicGF0aCI6Ii8xNzk4MjIwNi8zODMzNzc5NTQtNmE2N2UyNzMtODkzYS00OTU3LTliNTUtYmZiYzVkYmNlNmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAxNTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YWZjZWNlYjk3ZWUwZThhODM1MTdlNWQ2ZjFlMjc1ZTQwZjdhYmY1NDY5ZjY5Y2I4MWNlMTViNzIxYWJmY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zX5hUqs2nIOTQkNCWga3VB4ywpj3PSS74OWcaVDv2R0) ![图片](https://private-user-images.githubusercontent.com/17982206/383377953-1848aeff-ddba-45c5-a1eb-f25a4f2f102a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTg0ODMsIm5iZiI6MTczMDg1ODE4MywicGF0aCI6Ii8xNzk4MjIwNi8zODMzNzc5NTMtMTg0OGFlZmYtZGRiYS00NWM1LWExZWItZjI1YTRmMmYxMDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAxNTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MjUyMDFhMTAyYTA5NmIyZWY4ZWE2ZDcyMjRkNGEwMWI1MzVlY2UyYmUzMjNlMTQwZmU2ZWY5NmJlZDUyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V4Z9UJPKHwh7skb5q9HzsBsTHJU5-vnYVR1QgwDtNDA)
> 
> I found that if the meta info include "Compress Pegasus JPEG Lossless",it will occur this error. "./data-stream.js" ![图片](https://private-user-images.githubusercontent.com/17982206/383378152-715b652b-dc60-4e5c-8044-93911f4a520f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTg0ODMsIm5iZiI6MTczMDg1ODE4MywicGF0aCI6Ii8xNzk4MjIwNi8zODMzNzgxNTItNzE1YjY1MmItZGM2MC00ZTVjLTgwNDQtOTM5MTFmNGE1MjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAxNTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZGQ3ZjUyZjgzODA3Mjg2YjNlY2Y0ZTBiNmNhOTlhNTllNzA5YzExMzlmN2UxZjllOTlhOTAxOWZjMjdmYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ChJBNR9Btn_J49YgNrfL8S2IcVMXxikTSIN9vXPPYlY)

Yes, the transfer syntax is ((0002,0010) TransferSyntaxUID 1.2.840.10008.1.2.4.70) still cannot be decoded

**Comment by 934556826** [comment]
Latest vue-cornerstone3d
src\components\Viewport.vue

`<script setup lang="ts">
import { ref, onMounted } from "vue"
import {
  RenderingEngine,
  Enums,
  type Types,
  volumeLoader,
  cornerstoneStreamingImageVolumeLoader,
} from "@cornerstonejs/core"
import { init as csRenderInit, cache } from '@cornerstonejs/core';
import { init as csToolsInit } from '@cornerstonejs/tools';
import { init as dicomImageLoaderInit } from '@cornerstonejs/dicom-image-loader';
import wadors from '@cornerstonejs/dicom-image-loader/wadors';
import { api } from 'dicomweb-client';

// Add interface for function parameters
interface ImageMetadataParams {
  StudyInstanceUID: string;
  SeriesInstanceUID: string;
  SOPInstanceUID?: string | null;
  wadoRsRoot: string;
  client?: api.DICOMwebClient | null;
}

// Add type definitions
type InstanceMetadata = {
  [key: string]: {
    Value: string[];
  };
};

type WADORSMetaData = {
  [key: string]: any;
};

// Create refs
const elementRef = ref<HTMLDivElement | null>(null)
const running = ref(false)

// Setup function
const setup = async () => {
  if (running.value) {
    return
  }
  running.value = true
  await csRenderInit()
  await csToolsInit()
  dicomImageLoaderInit({ maxWebWorkers: 1 })


  // CharLS
  // const imageIds = [
  //   "wadouri:https://raw.githubusercontent.com/cornerstonejs/cornerstone3D/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEGLSLosslessTransferSyntax_1.2.840.10008.1.2.4.80.dcm",
  // ]

  // JPEG Lossless
  const imageIds = [
    "wadouri:https://raw.githubusercontent.com/cornerstonejs/cornerstone3D/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEGProcess14SV1TransferSyntax_1.2.840.10008.1.2.4.70.dcm"
  ]

  // Instantiate a rendering engine
  const renderingEngineId = "myRenderingEngine"
  const renderingEngine = new RenderingEngine(renderingEngineId)
  const viewportId = "CT_STACK"

  const viewportInput = {
    viewportId,
    type: Enums.ViewportType.STACK,
    element: elementRef.value as HTMLDivElement,
  }

  renderingEngine.enableElement(viewportInput)

  // Get the viewport
  const viewport = <Types.IStackViewport>renderingEngine.getViewport(viewportId)

  viewport.setStack(imageIds).then(
    () => {
      viewport.render();
    },
    function (err) {
      throw err;
    }
  );

  // Define a volume in memory
  // const volumeId = "streamingImageVolume"
  // const volume = await volumeLoader.createAndCacheVolume(volumeId, {
  //   imageIds,
  // })

  // // Set the volume to load
  // volume.load()

  // // Set the volume on the viewport
  // viewport.setVolumes([{ volumeId }])

  // // Render the image
  // viewport.render()
}

// Run setup on mount
onMounted(() => {
  setup()
})
</script>

<template>
  <div ref="elementRef" style="width: 512px; height: 512px; background-color: #000"></div>
</template>
`
![image](https://github.com/user-attachments/assets/a14ce458-afc8-4f12-a53d-de0da3dbdd3d)
![image](https://github.com/user-attachments/assets/952f056e-1148-4c1d-af6b-488ef878e9c1)

**Comment by 934556826** [comment]
> @zhoualibaba I need data to debug, annonimized

Latest vue-cornerstone3d
src\components\Viewport.vue


`<script setup lang="ts">
import { ref, onMounted } from "vue"
import {
  RenderingEngine,
  Enums,
  type Types,
  volumeLoader,
  cornerstoneStreamingImageVolumeLoader,
} from "@cornerstonejs/core"
import { init as csRenderInit, cache } from '@cornerstonejs/core';
import { init as csToolsInit } from '@cornerstonejs/tools';
import { init as dicomImageLoaderInit } from '@cornerstonejs/dicom-image-loader';
import wadors from '@cornerstonejs/dicom-image-loader/wadors';
import { api } from 'dicomweb-client';

// Add interface for function parameters
interface ImageMetadataParams {
  StudyInstanceUID: string;
  SeriesInstanceUID: string;
  SOPInstanceUID?: string | null;
  wadoRsRoot: string;
  client?: api.DICOMwebClient | null;
}

// Add type definitions
type InstanceMetadata = {
  [key: string]: {
    Value: string[];
  };
};

type WADORSMetaData = {
  [key: string]: any;
};

// Create refs
const elementRef = ref<HTMLDivElement | null>(null)
const running = ref(false)

// Setup function
const setup = async () => {
  if (running.value) {
    return
  }
  running.value = true
  await csRenderInit()
  await csToolsInit()
  dicomImageLoaderInit({ maxWebWorkers: 1 })


  // CharLS
  // const imageIds = [
  //   "wadouri:https://raw.githubusercontent.com/cornerstonejs/cornerstone3D/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEGLSLosslessTransferSyntax_1.2.840.10008.1.2.4.80.dcm",
  // ]

  // JPEG Lossless
  const imageIds = [
    "wadouri:https://raw.githubusercontent.com/cornerstonejs/cornerstone3D/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEGProcess14SV1TransferSyntax_1.2.840.10008.1.2.4.70.dcm"
  ]

  // Instantiate a rendering engine
  const renderingEngineId = "myRenderingEngine"
  const renderingEngine = new RenderingEngine(renderingEngineId)
  const viewportId = "CT_STACK"

  const viewportInput = {
    viewportId,
    type: Enums.ViewportType.STACK,
    element: elementRef.value as HTMLDivElement,
  }

  renderingEngine.enableElement(viewportInput)

  // Get the viewport
  const viewport = <Types.IStackViewport>renderingEngine.getViewport(viewportId)

  viewport.setStack(imageIds).then(
    () => {
      viewport.render();
    },
    function (err) {
      throw err;
    }
  );
}

// Run setup on mount
onMounted(() => {
  setup()
})
</script>

<template>
  <div ref="elementRef" style="width: 512px; height: 512px; background-color: #000"></div>
</template>
`



![image](https://github.com/user-attachments/assets/661e5a1d-05cb-4a91-8e7c-e2b6104ca6de)
![image](https://github.com/user-attachments/assets/e58c7d74-72c7-4de5-9f86-907291f785f5)

**Comment by 934556826** [comment]
> can you upgrade cs3d version once again? i think this should work now

Are you referring to version 2.1.17? I have tried it and it is already the latest version
`"@cornerstonejs/core": "^2.1.17",
    "@cornerstonejs/dicom-image-loader": "^2.1.17",
    "@cornerstonejs/tools": "^2.1.17",`

**Comment by sedghi** [comment]
If does not work then give me anonymized data please

**Comment by 934556826** [comment]
Thank you very much. I really hope to upgrade to 2.0, but this is troubling me
I just modified the code in src\components\Viewport.vue on the latest version of vue-cornerstone3d [](https://github.com/cornerstonejs/vue-cornerstone3d)
You can copy the following code into Viewport.vue and run it to reproduce this bug.

<script setup lang="ts">
import { ref, onMounted } from "vue"
import {
  RenderingEngine,
  Enums,
  type Types,
  volumeLoader,
  cornerstoneStreamingImageVolumeLoader,
} from "@cornerstonejs/core"
import { init as csRenderInit, cache } from '@cornerstonejs/core';
import { init as csToolsInit } from '@cornerstonejs/tools';
import { init as dicomImageLoaderInit } from '@cornerstonejs/dicom-image-loader';
import wadors from '@cornerstonejs/dicom-image-loader/wadors';
import { api } from 'dicomweb-client';

// Add interface for function parameters
interface ImageMetadataParams {
  StudyInstanceUID: string;
  SeriesInstanceUID: string;
  SOPInstanceUID?: string | null;
  wadoRsRoot: string;
  client?: api.DICOMwebClient | null;
}

// Add type definitions
type InstanceMetadata = {
  [key: string]: {
    Value: string[];
  };
};

type WADORSMetaData = {
  [key: string]: any;
};

// Create refs
const elementRef = ref<HTMLDivElement | null>(null)
const running = ref(false)

// Setup function
const setup = async () => {
  if (running.value) {
    return
  }
  running.value = true
  await csRenderInit()
  await csToolsInit()
  dicomImageLoaderInit({ maxWebWorkers: 1 })


  // CharLS
  // const imageIds = [
  //   "wadouri:https://raw.githubusercontent.com/cornerstonejs/cornerstone3D/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEGLSLosslessTransferSyntax_1.2.840.10008.1.2.4.80.dcm",
  // ]

  // JPEG Lossless
  const imageIds = [
    "wadouri:https://raw.githubusercontent.com/cornerstonejs/cornerstone3D/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEGProcess14SV1TransferSyntax_1.2.840.10008.1.2.4.70.dcm"
  ]

  // Instantiate a rendering engine
  const renderingEngineId = "myRenderingEngine"
  const renderingEngine = new RenderingEngine(renderingEngineId)
  const viewportId = "CT_STACK"

  const viewportInput = {
    viewportId,
    type: Enums.ViewportType.STACK,
    element: elementRef.value as HTMLDivElement,
  }

  renderingEngine.enableElement(viewportInput)

  // Get the viewport
  const viewport = <Types.IStackViewport>renderingEngine.getViewport(viewportId)

  viewport.setStack(imageIds).then(
    () => {
      viewport.render();
    },
    function (err) {
      throw err;
    }
  );
}

// Run setup on mount
onMounted(() => {
  setup()
})
</script>

<template>
  <div ref="elementRef" style="width: 512px; height: 512px; background-color: #000"></div>
</template>

**Comment by 934556826** [comment]
Thank you very much. I really hope to upgrade to 2.0, but this is troubling me
I just modified the code in src\components\Viewport.vue on the latest version of vue-cornerstone3d
[https://github.com/cornerstonejs/vue-cornerstone3d](url)
You can copy the following code into Viewport.vue and run it to reproduce this bug.

```
<script setup lang="ts">
import { ref, onMounted } from "vue"
import {
  RenderingEngine,
  Enums,
  type Types,
  volumeLoader,
  cornerstoneStreamingImageVolumeLoader,
} from "@cornerstonejs/core"
import { init as csRenderInit, cache } from '@cornerstonejs/core';
import { init as csToolsInit } from '@cornerstonejs/tools';
import { init as dicomImageLoaderInit } from '@cornerstonejs/dicom-image-loader';
import wadors from '@cornerstonejs/dicom-image-loader/wadors';
import { api } from 'dicomweb-client';

// Add interface for function parameters
interface ImageMetadataParams {
  StudyInstanceUID: string;
  SeriesInstanceUID: string;
  SOPInstanceUID?: string | null;
  wadoRsRoot: string;
  client?: api.DICOMwebClient | null;
}

// Add type definitions
type InstanceMetadata = {
  [key: string]: {
    Value: string[];
  };
};

type WADORSMetaData = {
  [key: string]: any;
};

// Create refs
const elementRef = ref<HTMLDivElement | null>(null)
const running = ref(false)

// Setup function
const setup = async () => {
  if (running.value) {
    return
  }
  running.value = true
  await csRenderInit()
  await csToolsInit()
  dicomImageLoaderInit({ maxWebWorkers: 1 })


  // CharLS
  // const imageIds = [
  //   "wadouri:https://raw.githubusercontent.com/cornerstonejs/cornerstone3D/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEGLSLosslessTransferSyntax_1.2.840.10008.1.2.4.80.dcm",
  // ]

  // JPEG Lossless
  const imageIds = [
    "wadouri:https://raw.githubusercontent.com/cornerstonejs/cornerstone3D/main/packages/dicomImageLoader/testImages/CTImage.dcm_JPEGProcess14SV1TransferSyntax_1.2.840.10008.1.2.4.70.dcm"
  ]

  // Instantiate a rendering engine
  const renderingEngineId = "myRenderingEngine"
  const renderingEngine = new RenderingEngine(renderingEngineId)
  const viewportId = "CT_STACK"

  const viewportInput = {
    viewportId,
    type: Enums.ViewportType.STACK,
    element: elementRef.value as HTMLDivElement,
  }

  renderingEngine.enableElement(viewportInput)

  // Get the viewport
  const viewport = <Types.IStackViewport>renderingEngine.getViewport(viewportId)

  viewport.setStack(imageIds).then(
    () => {
      viewport.render();
    },
    function (err) {
      throw err;
    }
  );
}

// Run setup on mount
onMounted(() => {
  setup()
})
</script>

<template>
  <div ref="elementRef" style="width: 512px; height: 512px; background-color: #000"></div>
</template>
```

**Comment by sedghi** [comment]
@934556826 I can render your code in the latest version of the lib 

![CleanShot 2024-11-11 at 13 15 44@2x](https://github.com/user-attachments/assets/a92ad445-7646-44c2-ba73-5e5d06f5ad06)

See if it works

**Comment by zhoualibaba** [comment]
@sedghi Thank you for your reply. It solved my problem
