### ISSUE TITLE
[Feature Request] use named export for submodules

### ISSUE THREAD

**Issue by Ragnar-Oock** [cornerstonejs/cornerstone3D#1542]
### What feature or change would you like to see made?

Currently if I want to import something from the the `wadouri` submodule of `@cornerstonejs/dicom-image-loader` I need to write the following :
```js
// import the default export of the submodule
import WADOURI from '@cornerstonejs/dicom-image-loader/wadouri';
// desctructure the default export to get the parts I need
const { getEncapsulatedImageFrame, getUncompressedImageFrame } = WADOURI;
```

Ideally I would be able to use named import/exports to only import the parts of the module I need in my code, like so :
```js
import { getEncapsulatedImageFrame, getUncompressedImageFrame } from '@cornerstonejs/dicom-image-loader/wadouri';
```

This is currently not possible because of how the index file of the wadouri submodule ([`packages/dicomImageLoader/src/imageLoader/wadouri/index.ts`](https://github.com/cornerstonejs/cornerstone3D/blob/a3934ba53f46d7cb5d23151d83f69bea9fe90009/packages/dicomImageLoader/src/imageLoader/wadouri/index.ts)), with a single `export default` that holds all the things the submodule exposes. I suppose this is a left over of the previously CommonJS based organization.

Using ESM syntax it would be possible to expose all the parts of the module directly as named exports and simplify the code of the other index files like this one by using the `export .. from` syntax (see [MDN page on that topic](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#re-exporting_aggregating)).

<details><summary>Example of implementation</summary>
<p>

```javascript
export { default as dataSetCacheManager } from './dataSetCacheManager';
export { default as fileManager } from './fileManager';
export { default as getEncapsulatedImageFrame } from './getEncapsulatedImageFrame';
export { default as getUncompressedImageFrame } from './getUncompressedImageFrame';
export { default as loadFileRequest } from './loadFileRequest';
export { default as getPixelData } from './getPixelData';
export {
	loadImageFromPromise,
	getLoaderForScheme,
	loadImage,
} from './loadImage';
export { default as parseImageId } from './parseImageId';
export { default as unpackBinaryFrame } from './unpackBinaryFrame';
export { default as register } from './register';

import {
	getImagePixelModule,
	getLUTs,
	getModalityLUTOutputPixelRepresentation,
	getNumberValues,
	metaDataProvider,
	metadataForDataset,
} from './metaData/index';

export const metaData = {
	getImagePixelModule,
	getLUTs,
	getModalityLUTOutputPixelRepresentation,
	getNumberValues,
	metaDataProvider,
	metadataForDataset,
};
// Or if we don't want to duplicate the import of the metadata module
// export * as metaData from './metaData/index';

``` 

</p>
</details> 

The proposed change would break imports like `import WADO_URI from '@cornerstonejs/dicom-image-loader/wadouri';` but that could be replaced by `import * as WADO_URI from '@cornerstonejs/dicom-image-loader/wadouri';` if library user don't want to change their code too much.

### Why should we prioritize this feature?

This change would be a continuation of the DX improvements started with 2.0 to align the `@cornerstone3d/*` libs to modern JS standards.

PS. If this change is approved I can open a PR to apply those changes for the 3.0 milestone (as it would break imports of many public facing modules)

**Comment by sedghi** [comment]
Feel free to submit a PR i will review
