### ISSUE TITLE
[Bug] Cannot decache an image with a shared cache key. You need to manually decache the volume first.

### ISSUE THREAD

**Issue by Sergey1888888** [cornerstonejs/cornerstone3D#1548]
### Describe the Bug

Try to purge cache when I leave my page with images. Call cache.purgeCache() and get error in console: 
`Cannot decache an image with a shared cache key. You need to manually decache the volume first.`
I've tried to purge volume(I have no volumes) before purge all cache and error still appears.

### Steps to Reproduce

1. Load some images with loadAndCacheImage
2. Try to purge cache

### The current behavior

Error `Cannot decache an image with a shared cache key. You need to manually decache the volume first.` appears and cache is not purged.

### The expected behavior

Cache is purged.

### OS

Windows 10

### Node version

18.18.2

### Browser

Chrome 130

**Comment by sedghi** [comment]
I see the issue, i will fix it
