### ISSUE TITLE
colorLUT and fillAlpha problem

### ISSUE THREAD

**Issue by zhoualibaba** [cornerstonejs/cornerstone3D#155]
The color i got is not linear, fillAlphe 0.99/1 changed a lot.I think i got the wrong color.I wonder if it's my fault.
When i use setToolGroupSpecificConfig like this
![image](https://user-images.githubusercontent.com/17982206/181703093-ebec9cda-3727-4b80-a6b7-e4cb09f4d331.png)
I got the color like this.
@sedghi The colorLut[1] is transparent. The colorLUT[2]/[3] are completely opaque.FillAlphe has been changed to 1.
The segmentation from left to right use colorIndex 1,2,3.
![image](https://user-images.githubusercontent.com/17982206/181702753-08df31d0-d16d-4394-b5ad-3023732b88e0.png)

it seems that colorLUT[1] behave differently。
When i change the colorLUTArray.
![image](https://user-images.githubusercontent.com/17982206/181704216-08ce6a3f-62f5-4f69-bb2f-61720e6ce26e.png)
The color has changed like this 
![image](https://user-images.githubusercontent.com/17982206/181704376-9b832ac0-4007-48df-9a2e-4ff86502ef57.png)
@sedghi 
When i change the colorLut[1] to [77,228,121,255],it seems that colorLUT[1] is transparent.
![image](https://user-images.githubusercontent.com/17982206/181704408-1b77806c-4f45-4282-b824-2d502cc2e0da.png)

**Comment by sedghi** [comment]
Yeah it is a known issue, you can read more [here](https://github.com/Kitware/vtk-js/pull/2093)

**Comment by zhoualibaba** [comment]
@sedghi Thank you for your reply.
So there is no way to have the color act linearly to the opacity.
I want to know why the colorLUT[1] behave differently.

**Comment by sedghi** [comment]
So no for linear behaviour (as I understand). But colorLUT[1] should not be different than others. I didn't see that in your original post, can you edit your original post and add a bit more explanation?

**Comment by zhoualibaba** [comment]
@sedghi I have edited my original post .
It seems that the colorLUT[0] affects the colorLUT[1].I try to change the colorLUT[2] from [77, 228, 121, 255] to [77, 228, 121, 0] ,the colorLUT[3] has also changed.
![image](https://user-images.githubusercontent.com/17982206/182270448-d0f0aa05-845e-4ab0-9277-ddf184efe49c.png)
![image](https://user-images.githubusercontent.com/17982206/182270471-90d8486b-c3fd-47b5-99b4-2024db63131a.png)

**Comment by sedghi** [comment]
Do you still see this issue?

**Comment by zhoualibaba** [comment]
Thank you for your reply.
I see that most of this problem has been solved，but the previous color still affects the next color a little.LIke this
![image](https://user-images.githubusercontent.com/17982206/212216360-a8c4b05b-fd76-4cd7-8c25-f963c38a2985.png)
![image](https://user-images.githubusercontent.com/17982206/212216381-1245f2c8-8d23-4346-b17c-31739055af5b.png)
When i change the colorLut[2],the colorLut[3] still changed a little.
