### ISSUE TITLE
[Bug] Rotation is not changing with setCamera

### ISSUE THREAD

**Issue by Sergey1888888** [cornerstonejs/cornerstone3D#1550]
### Describe the Bug

I try to change rotation with `setCamera({rotation: 90})` and nothing happend. `getCamera().rotation` still equals to 0.

### Steps to Reproduce

1. viewport.setCamera({rotation: 90})
2. viewport.getCamera().rotation

### The current behavior

Rotation is not changed.

### The expected behavior

Rotation is changed.

### OS

Windows 10

### Node version

18.18.2

### Browser

Chrome 130

**Comment by Sergey1888888** [comment]
`setCamera` doesn't call `setRotation`. But `setViewPresentation` do it. Maybe adding `setRotation` in `setCamera` method is the solution.

**Comment by sedghi** [comment]
Good catch, yes, we should do that in setCamera , can you create a PR?

**Comment by Sergey1888888** [comment]
Yes

**Comment by sedghi** [comment]
@Sergey1888888 nevermind i did it
