### ISSUE TITLE
[Bug] webWorkerManager.js:100  Error executing method 'decodeTask' on worker 'dicomImageLoader': Error: No JPEG Lossless decoder loaded

### ISSUE THREAD

**Issue by woaihengniu** [cornerstonejs/cornerstone3D#1558]
### Describe the Bug

Lossless compression dicom transfer protocol is ((0002,0010) TransferSyntaxUID 1.2.840.10008.1.2.4.70) cannot decode images properly
![$XD$KIMECSXD CX RLSDL_A](https://github.com/user-attachments/assets/8cd47fe8-a2f9-4d83-a0ff-d79b47dd1564)
![$AOB4_PDYZ2PCVM`BN0%H5I](https://github.com/user-attachments/assets/9f398e30-6dbf-44b2-85c2-467f6dbfe201)
The lossy dicom transfer protocol ((0002,0010) TransferSyntaxUID 1.2.840.10008.1.2.4.51) decodes and renders the image as normal

### Steps to Reproduce

1.Initialize cornerstone
2.Initialize cornerstoneDICOMImageLoader
3.Register volume loader
4.Load volume

### The current behavior

Undecoded image

### The expected behavior

Perfectly rendered image

### OS

win10

### Node version

v18.20.4

### Browser

Microsoft Edge  128.0.2739.79

**Comment by sedghi** [comment]
Excuse me? is this the same as this one that i published a fix? https://github.com/cornerstonejs/cornerstone3D/issues/1541

**Comment by sedghi** [comment]
Did you try the lastest main branch?

**Comment by woaihengniu** [comment]
> Excuse me? is this the same as this one that i published a fix? #1541

hi,It is the same problem, but the decoding method is different, this image is lossless compression, I have updated to the latest version 2.1.16

**Comment by sedghi** [comment]
Can you send me data again?

**Comment by woaihengniu** [comment]
> Can you send me data again?

Hi,  The original image is uncompressed   let temp1 = ["wadouri:http://60.205.216.219:8057/Raw/IM0.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM1.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM2.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM3.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM4.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM5.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM6.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM7.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM8.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM9.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM10.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM11.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM12.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM13.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM14.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM15.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM16.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM17.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM18.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM19.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM20.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM21.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM22.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM23.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM24.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM25.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM26.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM27.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM28.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM29.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM30.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM31.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM32.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM33.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM34.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM35.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM36.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM37.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM38.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM39.dcm"
]
Lossy compression  
let temp1 = ["wadouri:http://60.205.216.219:8057/Raw/IM0_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM1_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM2_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM3_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM4_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM5_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM6_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM7_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM8_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM9_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM10_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM11_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM12_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM13_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM14_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM15_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM16_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM17_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM18_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM19_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM20_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM21_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM22_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM23_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM24_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM25_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM26_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM27_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM28_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM29_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM30_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM31_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM32_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM33_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM34_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM35_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM36_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM37_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM38_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM39_lossy.dcm"
]
Lossless compression  let temp1 = ["wadouri:http://60.205.216.219:8057/Raw/IM0_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM1_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM2_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM3_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM4_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM5_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM6_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM7_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM8_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM9_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM10_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM11_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM12_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM13_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM14_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM15_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM16_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM17_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM18_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM19_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM20_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM21_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM22_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM23_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM24_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM25_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM26_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM27_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM28_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM29_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM30_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM31_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM32_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM33_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM34_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM35_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM36_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM37_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM38_lossless.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM39_lossless.dcm"
]

I'm using volume to render lossy compression but the original image is not quite the same, it's a little white.
Lossless compression cannot be rendered using volume

**Comment by sedghi** [comment]
Ok PR created
