### ISSUE TITLE
[Bug] Crosshair rotation image distortion

### ISSUE THREAD

**Issue by woaihengniu** [cornerstonejs/cornerstone3D#1563]
### Describe the Bug

I am using the mpr feature and after I add CrosshairsTool, the coronal and sagittal graphs distort when rotating the axial image if the layer thickness is not expanded。I don't know if that's normal
This is the image just rendered
![}UKKNEQWWITWIWSGO 16%4B](https://github.com/user-attachments/assets/787441a3-c409-4218-8c78-23019f4108e7)
     
This is the image I rotated without the spread thickness
![~2NU1LWJ 7O`A 4JIGK6HPX](https://github.com/user-attachments/assets/133a7f05-02c1-4724-a207-14a5f4c30fec)

### Steps to Reproduce

1. The image is loaded
2. Rotation axis bitmap

### The current behavior

The shape of sagittal bitmap and coronal map changed when the layer thickness was not developed

### The expected behavior

Images are displayed normally when optional

### OS

win10

### Node version

v18.20.4

### Browser

Microsoft Edge  128.0.2739.79

**Comment by sedghi** [comment]
Hmmm, can you share the anonymized data?

**Comment by woaihengniu** [comment]
> 嗯，你能分享匿名数据吗？

let temp1 = ["wadouri:http://60.205.216.219:8057/Raw/IM0_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM1_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM2_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM3_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM4_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM5_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM6_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM7_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM8_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM9_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM10_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM11_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM12_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM13_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM14_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM15_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM16_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM17_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM18_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM19_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM20_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM21_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM22_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM23_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM24_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM25_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM26_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM27_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM28_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM29_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM30_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM31_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM32_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM33_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM34_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM35_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM36_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM37_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM38_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM39_lossy.dcm"
]

**Comment by woaihengniu** [comment]
> 是的，你是对的，如果你在再次修复后进行修改，那就是 Werid
> 
> 调试：尝试使用更多切片？尝试使用无损
Hi, I would like to ask whether the sagittal and coronal bitmaps are deformed normally or abnormally after the mpr is built and CrosshairsTool is added without the spread layer thickness of the rotation axis bitmap? If it is abnormal, is there a modification plan recently displayed

**Comment by sedghi** [comment]
Nothing is deformed; it's just the camera placement at that location.

**Comment by woaihengniu** [comment]
> 没有任何东西是变形的;这只是该位置的摄像机位置。

ok thanks

**Comment by sedghi** [comment]
I'm fixing the crosshairs now
