### ISSUE TITLE
[Bug] Root level imports cannot be tree shaken 

### ISSUE THREAD

**Issue by mcullifer** [cornerstonejs/cornerstone3D#1565]
### Describe the Bug

Root level imports such as the `init()` functions from `@cornerstonejs/core` and `@cornerstonejs/tools`, `getConfiguration()`, `setConfiguration()`, `addTool()`, `cursors` (from cornerstone tools, I just need the  `setCursorForElement()` function but I have to import all of `@cornerstonejs/tools` to get it) cannot be tree shaken because you can only import them from the root barrel file (index.ts).

In the context of my web application this makes it very difficult to optimize load times and lazy load different portions of the library as they're used because these functions are necessary for initializing cornerstone in the first place. So anything that uses some aspect of cornerstone ends up importing the entire cornerstone library.

Maybe I'm doing something wrong, but I don't think so because this is just how barrel files work. This is all running in a sveltekit project.

### Steps to Reproduce

1. Import necessary functions to create a viewport (core.init(), tools.init(), any root level only export)
2. View chunk download size in network tab

### The current behavior

![image](https://github.com/user-attachments/assets/5ac7039a-d619-4f6d-8be3-2b82391cd825)
Here is an example of my network tab when running my sveltekit app. I have a portion that renders a stack viewport which needs to call a function I have made for initializing cornerstone. Because `init()`, `destroy()`, `addTool()`, etc. are only available as imports from the root level I end up importing all of cornerstone.

The image is from dev mode so this is not minified. Even after building however cornerstone is nearly 1MB each for core and tools which is significantly larger than the rest of my application. I only need a few pieces - just basic tools like mousewheel, pan, length, etc on StackViewports.

### The expected behavior

These functions that are necessary to make a basic stackviewport as well as some other root level only imports like `cursors` from `@cornerstonejs/tools` should be put in their own submodule or added to `/utilities`. Anything that can let the user direct import exactly what they need instead of having to import all of `@cornerstonejs/core` and `@cornerstonejs/tools`

### OS

Windows 11

### Node version

20.18.0

### Browser

chromium 130.0.6723.117

**Comment by sedghi** [comment]
You don't need anymore if you are in the new cornerstone3D 2.0 https://www.cornerstonejs.org/docs/migration-guides/2x/general#package-exports

**Comment by mcullifer** [comment]
@sedghi This was on v2.1.17

**Comment by sedghi** [comment]
Your bundler should be able to tree shake the rest. The type of import doesn't matter; I suspect your setup isn't configured to tree shake properly.

**Comment by mcullifer** [comment]
Interesting. I'm using Vite with a standard config and I only seem to have issues with Cornerstone, but I can keep looking to see if there's any config options I can use. I'm also unable to build due to [this issue](https://github.com/cornerstonejs/cornerstone3D/issues/1378#issuecomment-2224321261) which I fixed using the alias before, but since the UMD build is not longer in cornerstone 2.0 this fix no longer works.

**Comment by sedghi** [comment]
We have new recipes for Vite and other tools, and as far as I know, they all work. https://www.cornerstonejs.org/docs/migration-guides/2x/general#frameworks

**Comment by sedghi** [comment]
If you have a simple example for Cornerstone3D 2.0 and Svelte, I'd love to include it in our examples. Would you mind creating one to contribute? I can create a repo and you create a PR?

**Comment by mcullifer** [comment]
I can do that yes. 
Also I am encountering 1 other issue with dicom-image-loader. There seems to be something off with [jpegLossless.d.ts](https://github.com/cornerstonejs/cornerstone3D/blob/ed3bf870f465ac9d7768fd9cafcd593f132c344c/packages/dicomImageLoader/src/codecs/jpegLossless.d.ts#L1-L2). There's duplicate identifiers and `jpeg` is not defined it seems. Not sure if it's related though since it's just a type definition file?

```
[plugin:vite:import-analysis] Failed to resolve import "./data-stream.js" from "node_modules/@cornerstonejs/dicom-image-loader/dist/esm/codecs/jpegLossless.js?v=770d6c09". Does the file exist?

3  |    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
4  |  };
5  |  import * as __require_for_vite_krF8kH from "./data-stream.js";
   |                                              ^
6  |  import * as __require_for_vite_KXxQJp from "./huffman-table.js";
7  |  import * as __require_for_vite_5Yn1oA from "./quantization-table.js";
```

**Comment by sedghi** [comment]
Ok feel free to create a PR for this https://github.com/cornerstonejs/svelte-cornerstone3d
I have seen jpeglossless issue, does it showup during build or simply can't decode jpeg lossless?

**Comment by sedghi** [comment]
@mcullifer checkout this branch  https://github.com/cornerstonejs/cornerstone3D/pull/1568

```
cd packages/dicomImageLoader
yarn build:esm
```
copy those drag and drop it in your app

let me know if it works

**Comment by mcullifer** [comment]
Still getting an error I'm double checking to make sure I built everything right.
```
Failed to resolve import "jpeg-lossless-decoder-js" from "node_modules/@cornerstonejs/dicom-image-loader/dist/esm/shared/decoders/decodeJPEGLossless.js?v=d93fdc72". Does the file exist?
9  |      }
10 |      return new Promise((resolve, reject) => {
11 |          import('jpeg-lossless-decoder-js').then(({ Decoder }) => {
   |                 ^
12 |              const decoder = new Decoder();
13 |              local.jpeg = decoder;
```

The node module is definitely installed. I see it in the node_modules folder. And it builds without errors. Is it because this import statement and the path it ends up resolving to?

when I hover over it in VSCode it shows
```
Could not find a declaration file for module "jpeg-lossless-decoder-js" ../../cornerstone3D/node_modules/jpeg-lossless-decoder-js/release/cjs/lossless.cjs implicitly has an type.
```

**Comment by sedghi** [comment]
Noice

**Comment by sedghi** [comment]
I wonder why it doesn't install it upon npm install, since it is listed as dependency

**Comment by mcullifer** [comment]
Yeah maybe it's because of some caching or something and it's ignoring it idk

**Comment by mcullifer** [comment]
@sedghi Would you be able to add an empty readme or something to https://github.com/cornerstonejs/svelte-cornerstone3d  so there's an initial commit? I'm unable to fork and create a PR since it doesn't have a main/master branch
