### ISSUE TITLE
[Bug]   The image I rendered using compressed lossy images is not quite the same as the original

### ISSUE THREAD

**Issue by woaihengniu** [cornerstonejs/cornerstone3D#1569]
### Describe the Bug

Hi,The image I rendered using compressed lossy images is not quite the same as the original, but I used some image viewer tools to open the image and the original basically nothing. Is this due to the compressed image? 
This is the effect of my  uncompressed image rendering
![TT}Q{~JG$3$72 XQ`M7(L$Q](https://github.com/user-attachments/assets/0719179f-2cf2-4e19-907a-fe957010a8e3)

This is an image rendered using a compressed image

![%Z8FQ5 MMR~K DHRAYMK@84](https://github.com/user-attachments/assets/b5e234b0-615d-498e-95a6-df1850b47ce1)

The images displayed are a little different

Below is the data

let temp1 = ["wadouri:http://60.205.216.219:8057/Raw/IM0_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM1_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM2_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM3_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM4_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM5_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM6_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM7_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM8_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM9_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM10_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM11_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM12_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM13_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM14_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM15_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM16_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM17_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM18_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM19_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM20_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM21_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM22_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM23_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM24_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM25_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM26_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM27_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM28_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM29_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM30_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM31_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM32_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM33_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM34_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM35_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM36_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM37_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM38_lossy.dcm",
    "wadouri:http://60.205.216.219:8057/Raw/IM39_lossy.dcm"
]

### Steps to Reproduce

The image is loaded

### The current behavior

The rendered image is different from the original

### The expected behavior

The rendered image is the same as the original

### OS

win10

### Node version

v18.20.4

### Browser

Microsoft Edge  128.0.2739.79

**Comment by sedghi** [comment]
Seems like it is the volume viewport only, not the stack viewport, i'm looking at it now
