### ISSUE TITLE
[Bug] Loading SEG on new OHIF viewer gives "Something went wrongfalse"

### ISSUE THREAD

**Issue by prerakmody** [cornerstonejs/cornerstone3D#1572]
### Describe the Bug

In the new OHIF viewer (3.8/3.9?), I uploaded some of my data and it is only able to show one segmentation. When I try to load the second segmentation, I get a "Something went wrongfalse" error on the screen and "Error: getVolume: volumeId must not be undefined" in the console.

### Steps to Reproduce

1. I first checked the validity of my .dcms (CT + SEG + SEG) in 3D Slicer  ([download data here](https://drive.google.com/drive/folders/1eg9rQlDdHJXqTrg5yZzSpo1AjDh-jtH9?usp=sharing))
![image](https://github.com/user-attachments/assets/66537b68-d658-4933-957d-75b3e4d52683)
2. I then drag-dropped my .dcms to [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic).
   - I was able to view the first segmentation
   - But when I click on the second segmentation I get the following error
 
![image](https://github.com/user-attachments/assets/c7eecb59-ac88-41fd-8bbd-9aefa8f18ebe)
   - So when I click on "Show details" I just get a black page.
   - Checking the console, I saw a "Error: getVolume: volumeId must not be undefined" message
 
![image](https://github.com/user-attachments/assets/974f11f5-48cf-43c7-8b62-05b71b209298)

### The current behavior

 - It does not show me the second segmentation (no matter in which order I load them into the viewer)

 - It shows me an error in the OHIF viewer and also in the console.

### The expected behavior

It should also load the second segmentation.

### OS

Windows 11

### Node version

N/A

### Browser

Chrome 130.0.6723.117

**Comment by sedghi** [comment]
Seems like they each can load separately, but not together

**Comment by sedghi** [comment]
I can see the issue, i'm fixing it
