### ISSUE TITLE
[Bug] `cornerstone3D.getConfiguration()` shows different GPU on Firefox when compared to Chrome/Edge/Opera

### ISSUE THREAD

**Issue by prerakmody** [cornerstonejs/cornerstone3D#1573]
### Describe the Bug

 - I have an interface for editing a segmentation with the brush and eraser tools. 
 - I noticed that it is slow/laggy on Firefox but is performant on Chrome/Edge/Opera (on the same system)
   - I have ensured that Hardware acceleration is enabled on all browsers  
 - So I checked the output of `cornerstone3D.getConfiguration().gpuTier` and Firefox shows me a different GPU than the one I have on my system.

### Steps to Reproduce

1. Run `cornerstone3D.getConfiguration()` on Firefox (v132.01) and compare output with Chrome(v130.0.6723.117)/Edge(v130.0.2849.80)/Opera(v114.0.5282.10.2)

### The current behavior

For Chrome/Edge/Opera, I get "Nvidia GeForce RTX 3090"
![image](https://github.com/user-attachments/assets/323e5f6c-1f42-48ab-bfd5-8461d212c71a)

For Firefox I get "nvidia evga geforce gtx 980" 
 - Weirdly, I get the same output for another machine I tested this on too
![image](https://github.com/user-attachments/assets/d5436620-75c7-4e09-a9f9-c1c46cbcaa24)

### The expected behavior

All browsers on the same machine should have the same GPU information for `cornerstone3D.getConfiguration()`

### OS

Windows 11

### Node version

N/A

### Browser

Chrome 130.0.6723.117

**Comment by sedghi** [comment]
I've noticed that on Firefox too; it seems to be a WebGL implementation issue. We don't have the resources to fix it, but you could report it to the Firefox team to see if they're willing to investigate. I suspect other apps might have issues as well.

**Comment by prerakmody** [comment]
Thats a deep rabbit hole to go down to, so I guess we stay out of it.
For anybody referencing this in the future, here are some links
 - [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1693745)
 - [UNMASKED_RENDERER_WEBGL](https://deviceandbrowserinfo.com/learning_zone/articles/webgl_renderer_values)
