### ISSUE TITLE
[Feature Request] Introduce a `lineWidth` feature for `PlanarFreehandROITool` 

### ISSUE THREAD

**Issue by prerakmody** [cornerstonejs/cornerstone3D#1574]
### What feature or change would you like to see made?

Request
 - As seen in the image below, I would like to show the yellow colored `PlanarFreehandROITool` with a customizable lineWidth.

Why
 - I am working on an AI-based interactive contour refinement project. My neural net takes an input the coordinates of the `PlanarFreehandROITool` tool. Its essentially a visual cue to correct the auto-contours (red) to look like the gold-standard (green)

![image](https://github.com/user-attachments/assets/be8bdd81-383e-45ed-a791-7b88479f9dae)

### Why should we prioritize this feature?

I am not sure its really useful for others, but seems to be an easy enough addition (I think).
I tried the following but to no avail
```python
const toolGroupContours      = cornerstone3DTools.ToolGroupManager.createToolGroup("toolGroupIdContours");
const planarFreeHandRoiTool  = cornerstone3DTools.PlanarFreehandROITool;

cornerstone3DTools.addTool(planarFreeHandRoiTool);
toolGroupContours.addTool(planarFreeHandRoiTool.toolName);

toolGroupContours.setToolConfiguration(planarFreeHandRoiTool.toolName, {calculateStats: false, linewidth:5});
```

**Comment by sedghi** [comment]
You can use this tool that is designed for segmentation and is configurable 

[https://www.cornerstonejs.org/live-examples/planarfreehandcontoursegmentationtool](https://www.cornerstonejs.org/live-examples/planarfreehandcontoursegmentationtool)

**Comment by prerakmody** [comment]
Thanks for the suggestion
 - But making a contour is not what I wish to do. I just want to make a scribble as a visual cue for an AI-model to take as input. 
 - This scribble then serves to correct the deep segmentation models errors.
 - So `PlanarFreehandROITool` seems to me the best option for my use case. However, I would like to have configurable `lineWidth`. Its currently too thin (as per feedback from my user testing)

## Examples
In these images check how one can make scribbles to speed up segmentation.

1. ![image](https://github.com/user-attachments/assets/20c86e50-4d4a-4a5c-b0fa-3a59b52d0926)
   - Ref: [ScribbleSup: Scribble-Supervised Convolutional Networks for Semantic Segmentation](https://arxiv.org/abs/1604.05144)

2. ![image](https://github.com/user-attachments/assets/94df0fda-d0bf-4b6f-b15e-4da62c2eecb2)
    - Ref: [ScribblePrompt: Fast and Flexible Interactive Segmentation for Any Medical Image](https://arxiv.org/abs/2312.07381)

---
4. And this is my webapp
[cornerstone3D-AI-scribble-demonstration.webm](https://github.com/user-attachments/assets/64bdd2ab-990e-4933-bc69-53ff7723a1c5)
   - In this video we have two contours - ground truth (green) and predicted (red). We need to modify the predicted contour (red) to look like the ground truth contour (green).

**Comment by sedghi** [comment]
Close this If it works for you too thanks

**Comment by prerakmody** [comment]
Hi,
The reference you provided helped.
Thought it made all annotations (for e.g. the ReferenceLines) also thicker.
So I decided to capture the `cornerstone3DTools.Enums.Events.ANNOTATION_ADDED` using `cornerstone3D.eventTarget.addEventListener`

See code below
```javascript
import * as cornerstone3D from '@cornerstonejs/core';
import * as cornerstone3DTools from '@cornerstonejs/tools';

function setMouseAndKeyboardEvents(){
  cornerstone3D.eventTarget.addEventListener(cornerstone3DTools.Enums.Events.ANNOTATION_ADDED, function(evt) {
        if (evt.detail.annotation.metadata.toolName == cornerstone3DTools.PlanarFreehandROITool.toolName){
            annotationHelpers.setAnnotationStyle(evt.detail.annotation.annotationUID, {lineWidth: config.SCRIBBLE_LINE_WIDTH});
        }
   });
}
export {setMouseAndKeyboardEvents};
```

**Comment by sedghi** [comment]
Then can we close this?

**Comment by prerakmody** [comment]
Yes, its already marked as closed, I think.
