### ISSUE TITLE
[Bug] rendering lag use @cornerstonejs/tools 2.2.1

### ISSUE THREAD

**Issue by yangsongtao1** [cornerstonejs/cornerstone3D#1577]
### Describe the Bug

I built on the example from https://github.com/cornerstonejs/vue-cornerstone3d and added the rectangle tool to draw rectangles. draw about 40 rectangles and then pan the view, it becomes very laggy. However, when I use version 1.30.1, it does not lag.

### Steps to Reproduce

1、Add RectangleROITool and PanTool
2、Draw approximately 40 rectangle frames.
3、Pan the view.

### The current behavior

rendering lag

### The expected behavior

I found it smooth to draw 40 rectangles using version 1.30.1, and I hope it can be just as smooth in version 2.x.

### OS

macos 13.6.9

### Node version

20.8.1

### Browser

chrome 130.0.6723.71

**Comment by sedghi** [comment]
40 is too much, isn't it?

**Comment by yangsongtao1** [comment]
> 40 is too much, isn't it?

When drawing 40 rectangles, the performance is very laggy, and even with around 20 rectangles, it is not very smooth. Since the number of shapes is determined by the user, and we cannot control how many they draw, we want to understand if there can be optimizations in this area. The previous version we used, 1.30.1, was very smooth, but now upgrading the version leads to a poor user experience.

**Comment by sedghi** [comment]
Not much has changed in that area, i"m not sure what is causing the issue
