### ISSUE TITLE
[Bug] An error occurred building the MPR     TypeError: Cannot destructure property 'imagePositionPatient' of '_metaData__WEBPACK_IMPORTED_MODULE_3__.get(...)' as it is undefined.

### ISSUE THREAD

**Issue by woaihengniu** [cornerstonejs/cornerstone3D#1579]
### Describe the Bug

Hi, I had an error while building the MPR
![R1P$D$}HA(H@OLHE4)GFJKT](https://github.com/user-attachments/assets/0b95a47b-63e0-4e4f-ba64-592ec947a64e)

But I have no problem constructing this sequence of MPR when I use some other tools, I don't know what the reason is, can you help me to look at it
![$C84PYL9J9AJ}I6 `YX5 ~0](https://github.com/user-attachments/assets/67e75395-cba0-48ec-bcaf-5133705bacd2)

This is the data
let temp1 = ["wadouri:http://60.205.216.219:82/20211125\\0029C381.img", "wadouri:http://60.205.216.219:82/20211125\\0029C38C.img", "wadouri:http://60.205.216.219:82/20211125\\0029C395.img", "wadouri:http://60.205.216.219:82/20211125\\0029C396.img", "wadouri:http://60.205.216.219:82/20211125\\0029C397.img", "wadouri:http://60.205.216.219:82/20211125\\0029C398.img", "wadouri:http://60.205.216.219:82/20211125\\0029C399.img", "wadouri:http://60.205.216.219:82/20211125\\0029C39A.img", "wadouri:http://60.205.216.219:82/20211125\\0029C39B.img", "wadouri:http://60.205.216.219:82/20211125\\0029C377.img", "wadouri:http://60.205.216.219:82/20211125\\0029C378.img", "wadouri:http://60.205.216.219:82/20211125\\0029C379.img", "wadouri:http://60.205.216.219:82/20211125\\0029C37A.img", "wadouri:http://60.205.216.219:82/20211125\\0029C37B.img", "wadouri:http://60.205.216.219:82/20211125\\0029C37C.img", "wadouri:http://60.205.216.219:82/20211125\\0029C37D.img", "wadouri:http://60.205.216.219:82/20211125\\0029C37E.img", "wadouri:http://60.205.216.219:82/20211125\\0029C37F.img", "wadouri:http://60.205.216.219:82/20211125\\0029C380.img", "wadouri:http://60.205.216.219:82/20211125\\0029C382.img", "wadouri:http://60.205.216.219:82/20211125\\0029C383.img", "wadouri:http://60.205.216.219:82/20211125\\0029C384.img", "wadouri:http://60.205.216.219:82/20211125\\0029C385.img", "wadouri:http://60.205.216.219:82/20211125\\0029C386.img", "wadouri:http://60.205.216.219:82/20211125\\0029C387.img", "wadouri:http://60.205.216.219:82/20211125\\0029C388.img", "wadouri:http://60.205.216.219:82/20211125\\0029C389.img", "wadouri:http://60.205.216.219:82/20211125\\0029C38A.img", "wadouri:http://60.205.216.219:82/20211125\\0029C38B.img", "wadouri:http://60.205.216.219:82/20211125\\0029C38D.img", "wadouri:http://60.205.216.219:82/20211125\\0029C38E.img", "wadouri:http://60.205.216.219:82/20211125\\0029C38F.img", "wadouri:http://60.205.216.219:82/20211125\\0029C390.img", "wadouri:http://60.205.216.219:82/20211125\\0029C391.img", "wadouri:http://60.205.216.219:82/20211125\\0029C392.img", "wadouri:http://60.205.216.219:82/20211125\\0029C393.img", "wadouri:http://60.205.216.219:82/20211125\\0029C394.img"];

### Steps to Reproduce

1. Initialize cornerstone
2. load images
3. Build mpr

### The current behavior

Unable to build MPR

### The expected behavior

The mpr was successfully built

### OS

win10

### Node version

v18.20.4

### Browser

Microsoft Edge  128.0.2739.79

**Comment by woaihengniu** [comment]
> 如果 MPR 失败，通常意味着由于元数据不一致而无法创建卷。您可以将其拖放到 [OHIF](https://viewer-dev.ohif.org/localbasic) 查看器中，https://viewer-dev.ohif.org/localbasic 检查图标。如果它是一个 cube，则表示它是 mprable
> 
> <img alt="CleanShot 2024-11-12 在 09.17.50@2x.png" width="120" height="66" src="https://camo.githubusercontent.com/1bba2163b2c52b9fdf029c65f443552202ffb1880a608e3282f27797bec9895e/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65306236343061392d336664382d343531332d626338342d6166323539323165356463382f38363638656130642d316563392d346166312d623764322d6234653266393532646461342f36356665663664342d343037392d346537382d623965372d3835376532623636613332323f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c325577596a59304d4745354c544e6d5a4467744e4455784d793169597a67304c57466d4d6a55354d6a466c4e57526a4f4338344e6a59345a5745775a4330785a574d354c5452685a6a4574596a646b4d6931694e4755795a6a6b314d6d526b595451764e6a566d5a5759325a4451744e4441334f5330305a5463344c5749355a5463744f4455335a544a694e6a5a684d7a49794969776961574630496a6f784e7a4d784e4449784d5449314c434a6c654841694f6a4d7a4d7a41784f5467784d54493166512e6972426832525531304e4a49645f59684752595362357468594f395431555061752d6573333552725a774d20">
> 
> 但如果是堆栈，则意味着它不能进入 MPR
> 
> <img alt="CleanShot 2024-11-12 于 09.18.22@2x.png" width="62" height="50" src="https://camo.githubusercontent.com/638bdef88086e3724b7e08b8efbe02177822ecb54ff911ee681eca904e5ac68f/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65306236343061392d336664382d343531332d626338342d6166323539323165356463382f31616533366363312d643865612d346432652d393039622d3337633666393461346535622f32643832656338372d646333392d346363622d386465612d3636623230366236303262363f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c325577596a59304d4745354c544e6d5a4467744e4455784d793169597a67304c57466d4d6a55354d6a466c4e57526a4f4338785957557a4e6d4e6a4d53316b4f4756684c54526b4d6d55744f5441355969307a4e324d325a6a6b305954526c4e5749764d6d51344d6d566a4f4463745a474d7a4f53303059324e694c54686b5a5745744e6a5a694d6a4132596a59774d6d49324969776961574630496a6f784e7a4d784e4449784d5449314c434a6c654841694f6a4d7a4d7a41784f5467784d54493166512e32726b384d7736784e794c314a31745554794a306e4f48376a54624244374a474f59537874713565504d4120">


I was able to build when I was using version 1.23, and now after upgrading to the latest version many sequences failed to build successfully reporting the current error

This is an image I just rendered using OHIF, and I think it's buildable
![NE$YHRIV}6K11~F1SK~H1_V](https://github.com/user-attachments/assets/14e43029-23c5-4a47-b19c-30b6e3773ed0)

**Comment by woaihengniu** [comment]
> If MPR fails, it usually means the volume cannot be created due to inconsistencies in the metadata. You can drag and drop it into the OHIF viewer at https://viewer-dev.ohif.org/localbasic to check the icon. If it's a cube, it indicates it is mprable
> 
> <img alt="CleanShot 2024-11-12 at 09.17.50@2x.png" width="120" height="66" src="https://camo.githubusercontent.com/1bba2163b2c52b9fdf029c65f443552202ffb1880a608e3282f27797bec9895e/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65306236343061392d336664382d343531332d626338342d6166323539323165356463382f38363638656130642d316563392d346166312d623764322d6234653266393532646461342f36356665663664342d343037392d346537382d623965372d3835376532623636613332323f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c325577596a59304d4745354c544e6d5a4467744e4455784d793169597a67304c57466d4d6a55354d6a466c4e57526a4f4338344e6a59345a5745775a4330785a574d354c5452685a6a4574596a646b4d6931694e4755795a6a6b314d6d526b595451764e6a566d5a5759325a4451744e4441334f5330305a5463344c5749355a5463744f4455335a544a694e6a5a684d7a49794969776961574630496a6f784e7a4d784e4449784d5449314c434a6c654841694f6a4d7a4d7a41784f5467784d54493166512e6972426832525531304e4a49645f59684752595362357468594f395431555061752d6573333552725a774d20">
> 
> but if is it stack it means it can't go mpr
> 
> <img alt="CleanShot 2024-11-12 at 09.18.22@2x.png" width="62" height="50" src="https://camo.githubusercontent.com/638bdef88086e3724b7e08b8efbe02177822ecb54ff911ee681eca904e5ac68f/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65306236343061392d336664382d343531332d626338342d6166323539323165356463382f31616533366363312d643865612d346432652d393039622d3337633666393461346535622f32643832656338372d646333392d346363622d386465612d3636623230366236303262363f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c325577596a59304d4745354c544e6d5a4467744e4455784d793169597a67304c57466d4d6a55354d6a466c4e57526a4f4338785957557a4e6d4e6a4d53316b4f4756684c54526b4d6d55744f5441355969307a4e324d325a6a6b305954526c4e5749764d6d51344d6d566a4f4463745a474d7a4f53303059324e694c54686b5a5745744e6a5a694d6a4132596a59774d6d49324969776961574630496a6f784e7a4d784e4449784d5449314c434a6c654841694f6a4d7a4d7a41784f5467784d54493166512e32726b384d7736784e794c314a31745554794a306e4f48376a54624244374a474f59537874713565504d4120">

I saw the icon you said, is it possible to build only if the metadata is the same? I saw the OHIF, which can also be built. Is there any configuration that can ignore this verification
![VX4LM(UN)SSLQCT8JJ{``RX](https://github.com/user-attachments/assets/e1f1c1d5-4f76-474a-a029-d589ed657d3b)

**Comment by sedghi** [comment]
Try latest OHIF it should have fixed it

**Comment by woaihengniu** [comment]
> Try latest OHIF it should have fixed it
Hi,I see the error "imagePositionPatient" is undefined, but I have a value for this property.
Is there the latest version of OHIF online? The OHIF address you replied to me above I found that the data can still be built MPR successfully.
This is the data, can you take a look at the metadata is there a problem, I want to know what is the difference from the old version why the MPR failed to build.
[images.zip](https://github.com/user-attachments/files/17760351/images.zip)
