### ISSUE TITLE
[Bug] Error occured when imageLoader.loadImage. Cannot read properties of undefined (reading 'samplesPerPixel')

### ISSUE THREAD

**Issue by SooyoonJi** [cornerstonejs/cornerstone3D#1584]
### Describe the Bug

I'm currently working on a migration to Cornerstone 3D 2.0
But error occured when I use imageLoader.loadImage in my codes.
My code work at cornerston3D 1.82.4 version. And I'm trying to migrate with 2.2.4 version

### Steps to Reproduce

- Receive a dicom files with the API and create an objectURL with it.
- make image ids with objectURL.  It looks like this.(wadors:blob:http://localhost:5173/7650fdd5-28b8-4ee4-abca-d2af7ab5d78b).
- In the version 1.82.4 that I was using in the project before, I used wadouri instead of wadors, but in the version 2.2.4 the browser does not do anything, so if I change it to wadors and then load image, the following error occurs.

below is my codes.

```
import * as cornerstone3DCore from '@cornerstonejs/core'
import cornerstoneDICOMImageLoader from '@cornerstonejs/dicom-image-loader'

async render(imageIds: string[], elements: HTMLDivElement[]) {
   let maxWebWorkers = 1
   if (navigator.hardwareConcurrency) {
       maxWebWorkers = Math.min(navigator.hardwareConcurrency, 7)
   }
   cornerstoneDICOMImageLoader.init({ maxWebWorkers })
   cornerstone3DCore.volumeLoader.registerUnknownVolumeLoader(
       cornerstone3DCore.cornerstoneStreamingImageVolumeLoader
   )

   this.renderingEngine = new cornerstone3DCore.RenderingEngine(this.renderingEngineId)
   const result = await Promise.all(imageIds.map((id: string) => cornerstone3DCore.imageLoader.loadImage(id)))
   const volume = await cornerstone3DCore.volumeLoader.createAndCacheVolume(this.volumeId, { imageIds })
   this.setViewports(elements)
   volume.load()
}
```

### The current behavior

when I call loadImage function, error occured. 

<img width="844" alt="image" src="https://github.com/user-attachments/assets/67467179-61c8-492a-808a-035a7d67fffe">

### The expected behavior

Is there any problem with my way?

### OS

macOS sonoma 14.0

### Node version

20.14

### Browser

chomre 129.0.6668.101

**Comment by sedghi** [comment]
you cannot just change wadouri to wadors, you should continue using wadouri, if you have dcm files hosted somewhere, i will fix the example for wadouri but this one right now works fine as i see https://www.cornerstonejs.org/live-examples/dicomimageloaderwadouri

But these two for some reason are broken

https://www.cornerstonejs.org/live-examples/volumebasicwadouri
https://www.cornerstonejs.org/live-examples/wadouri.html

**Comment by sedghi** [comment]
The issue for those two examples are our old server is down, so ... 

  const wadoURIRoot = `https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado?requestType=WADO&studyUID=${studyUID}&seriesUID=${seriesUID}&contentType=application%2Fdicom`;
