### ISSUE TITLE
[Bug] @cornerstonejs 2.0 strange renderer behavior

### ISSUE THREAD

**Issue by AlexMold** [cornerstonejs/cornerstone3D#1586]
### Describe the Bug

Hi guys,

Appreciate your work. Help me please with found bug or wrong/insufficient implementation.

I've implemented the React app, which allows you to upload and render .dcm files.
However, faced with strange behavior, all scan projections were distinguished perfectly, but on images, **vertical lines** appeared that interfered with scan discovery.

### Steps to Reproduce

Attaching the gist and video	

### The current behavior

And seems like the coronal view shifted a bit to right

https://gist.github.com/AlexMold/ad292158b27a35c04be93a9a1548cffc

https://www.loom.com/share/c8c7e90e4c434665a03590b245bc33fe?sid=76d064f5-ef24-40f1-a6a3-8cdc1d4bd781the 

### The expected behavior

without any lines, clear as at OHIF ;)

### OS

macOS

### Node version

20.13

### Browser

latest Chrome, latest Firefox

**Comment by sedghi** [comment]
Hmm, weird 
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by AlexMold** [comment]
Sure thing
no problem, it's my mri
https://drive.google.com/file/d/1Us-coz4HPNy9XZgipw-qxPpZfWCduTcm/view?usp=sharing

**Comment by sedghi** [comment]
This looks correct in viewer.ohif.org/localbasic

https://github.com/user-attachments/assets/0318ca16-912d-4ed0-a9f0-e7cd19842239

**Comment by AlexMold** [comment]
I supposed so ;)
The gist of the code mostly is copy of examples
https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/tools/examples/labelmapRendering/index.ts

**Comment by sedghi** [comment]
I suspect your series includes more than one display set, and OHIF can group them into reconstructive display sets. However, Cornerstone, being a rendering library, doesn't have this capability, which explains the situation.

You can look here for how to group them [https://github.com/OHIF/Viewers/blob/master/extensions/default/src/getSopClassHandlerModule.js](https://github.com/OHIF/Viewers/blob/master/extensions/default/src/getSopClassHandlerModule.js)

**Comment by AlexMold** [comment]
Thanks, I will try to figure out what it doesn't mean )
I thought that distinguishing `DisplayMode` would be good enough.
```
export enum DisplayMode {
  STACK = "CT_STACK",
  VOLUME = "CT_VOLUME",
}

export const ViewportMapping = {
  CD: DisplayMode.STACK, //	Color flow Doppler 	768 x 576	8	0,442 MB
  CR: DisplayMode.STACK, //	Computed radiography 	3520 x 4280	12	30 MB	2
  DSA: DisplayMode.STACK, //	Digital Subtraction Angiography 	512 x 512	8	 	15-40
  DX: DisplayMode.STACK, //	Digital Radiography 	2048 x 2048	12	 	2
  MG: DisplayMode.STACK, //	Mammography 	4608 x 5200	14	45,7 MB	1
  US: DisplayMode.STACK, //	Ultrasound 	512 x 512	8	0,262 MB	20-240
  XA: DisplayMode.STACK, //	X-Ray Angiography 	512 x 512	16

  CT: DisplayMode.VOLUME, //	Computed tomography 	512 x 512	16	0,524 MB	40-3000
  MR: DisplayMode.VOLUME, //	Magnetic Resonance 	256 x 256	16	0,131 MB	60-3000
  NM: DisplayMode.VOLUME, //	Nuclear Medicine 	256 x 256	 	0,128 MB
  PET: DisplayMode.VOLUME, //	Positron Emission Tomography - PET 	128 x 128	 	32 MB
};
```
Obviously, I was wrong (

🙇‍♂️

**Comment by sedghi** [comment]
No you need to look at the metadata of the series and try to separate the groups

**Comment by AlexMold** [comment]
Did I understand correctly that in this case, I need to abandon the automatic determination of projections of images using the viewport 
```
[
    {
        viewportId: viewportIds[0],
        type: ViewportType.ORTHOGRAPHIC,
        element: element1,
        defaultOptions: {
            orientation: Enums.OrientationAxis.AXIAL,
            background: <Types.Point3>[0.2, 0, 0.2]
        }
    },
    {
        viewportId: viewportIds[1],
        type: ViewportType.ORTHOGRAPHIC,
        element: element2,
        defaultOptions: {
            orientation: Enums.OrientationAxis.SAGITTAL,
            background: <Types.Point3>[0.2, 0, 0.2]
        }
    },
    {
        viewportId: viewportIds[2],
        type: ViewportType.ORTHOGRAPHIC,
        element: element3,
        defaultOptions: {
            orientation: Enums.OrientationAxis.CORONAL,
            background: <Types.Point3>[0.2, 0, 0.2]
        }
    }
];
```

and render all three views as a stack, and only by hand dividing it into groups `Axial | Sagittal | Coronal`?

**Comment by lcampos-vida** [comment]
> Did I understand correctly that in this case, I need to abandon the automatic determination of projections of images using the viewport and render all three views as a stack, and only by hand dividing it into groups `Axial | Sagittal | Coronal`?

@AlexMold It is not about orientation (axial, sagittal or coronal) but series. After loading the instances metadata OHIF converts each DICOM series (StudyInstanceUID + SeriesInstanceUID) into one or more `displaySets`. Take a look at the link shared by Alireza at line 154 ([getDisplaySetFromSeries](https://github.com/OHIF/Viewers/blob/master/extensions/default/src/getSopClassHandlerModule.js#L154)) where you can see how each series is split into displaySets. A new displaySet is created for each [MultiFrame instance](https://github.com/OHIF/Viewers/blob/master/extensions/default/src/getSopClassHandlerModule.js#L177), [CR/MG/DX](https://github.com/OHIF/Viewers/blob/master/extensions/default/src/getSopClassHandlerModule.js#L186) and another one for the remaining images.

After that you can load the series as volumes in any orientation, if they are reconstructable, or as a stack.

**Comment by AlexMold** [comment]
@lscoder Thanks for the clarification
Now I'm trying to understand what the term `reconstructable` means at all 😃 
And for what do you guys use [splitImageIdsBy4DTags](https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/core/src/utilities/splitImageIdsBy4DTags.ts#L179) in making [display volume info](https://github.com/OHIF/Viewers/blob/master/extensions/default/src/getSopClassHandlerModule.js#L36) ?

**Comment by lscoder** [comment]
@AlexMold A volume is reconstructable if the slices have the same orientation, if they are evenly spaced with no missing slice. If you organize all slices in space they need to form a "cuboid". If any slice is rotated/shifted it is not reconstructable anymore.

You can take a look at [isDisplaySetReconstructable.js](https://github.com/OHIF/Viewers/blob/d8ef36ed24466988586e19b855d2bbb86f8c657a/platform/core/src/utils/isDisplaySetReconstructable.js#L13)

[splitImageIdsBy4DTags](https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/core/src/utilities/splitImageIdsBy4DTags.ts#L179) is responsible for splitting 4D series (3D + time) into groups if any of [these tags](https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/core/src/utilities/splitImageIdsBy4DTags.ts#L5-L13) is available. If you are not working with 4D datasets you should not worry about it.

You can find an example of a 4D dataset [here](https://viewer.ohif.org/dynamic-volume?StudyInstanceUIDs=2.25.232704420736447710317909004159492840763). It takes some time to load because the dataset is a bit large. I recommend you to stop Cine and loop though it using the controls from the left panel. There are 40 frames where each frame is a 3D volume in a different time. Cine loops though frames/time and the scrollbar scrolls through position.
