### ISSUE TITLE
[Bug] Cannot add SplineROI dynamically 

### ISSUE THREAD

**Issue by tokyobordel** [cornerstonejs/cornerstone3D#1593]
### Describe the Bug

I need to add SplineROI dynamically to my canvas. An error occurs when using annotationHydration: 
`TypeError: Cannot destructure property 'instance' of 'annotation.data.spline' as it is undefined. `
As I understand it, when using annotationHydration, part of the data required to render the spline is not created, and more specifically, the "spline" field in the "data". How can I add this annotation if I know the node points?

### Steps to Reproduce

1. Try to add "SplineROI" annotation through annotationHydration

### The current behavior

`TypeError: Cannot destructure property 'instance' of 'annotation.data.spline' as it is undefined. `

### The expected behavior

Annotation added and rendered

### OS

Windows 10

### Node version

20.15.1

### Browser

Chrome 130.0.6723.70

**Comment by daker** [comment]
@tokyobordel maybe try to add a simple reproduction code

**Comment by daker** [comment]
i am also facing similar issues but with RectangleROITool and CircleROITool #1607

**Comment by tokyobordel** [comment]
@daker, it seems, at the moment dynamic addition only works for Probe and Length. I see that the necessary data for building complex annotations (like splines, rectangles, circles, etc.) is not added to annotationHydration https://github.com/cornerstonejs/cornerstone3D/blob/79887f9681ce363798c1f1454bbe0c670fdabded/packages/tools/src/utilities/annotationHydration.ts#L24-L48

**Comment by tokyobordel** [comment]
@daker, it seems, at the moment dynamic addition only works for Probe and Length. I see that the necessary data for building complex annotations (like splines, rectangles, circles, etc.) is not added to annotationHydration https://github.com/cornerstonejs/cornerstone3D/blob/79887f9681ce363798c1f1454bbe0c670fdabded/packages/tools/src/utilities/annotationHydration.ts#L24-L48

**Comment by daker** [comment]
@sedghi do you know if RectangleROITool, CircleROITool and SplineROI work with annotationHydration ?

**Comment by sedghi** [comment]
Hmmm i don't know, probably not? I will look into this

**Comment by lscoder** [comment]
> @daker, fast example:
> 
> ```
> cornerstoneTools.utilities.annotationHydration(viewport, 'SplineROI', [
>   [21.36147540983606, 0.00008000000002539309, -1230.2434426229509] as Types.Point3,
>   [78.3254098360656, 0.00008000000002539309, -1157.3631147540982] as Types.Point3,
>   [-25.550000000000008, 0.00008000000002539309, -1159.038524590164] as Types.Point3,
> ]);
> cornerstoneTools.utilities.triggerAnnotationRenderForViewportIds([
>   viewport.id,
> ]);
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/151533918/387223417-c76668b5-905b-4016-90a1-44f2db78c6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDAzMDEsIm5iZiI6MTczMjA0MDAwMSwicGF0aCI6Ii8xNTE1MzM5MTgvMzg3MjIzNDE3LWM3NjY2OGI1LTkwNWItNDAxNi05MGExLTQ0ZjJkYjc4YzZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxODEzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjc0OGMwOTNlNTdiZjExYjBmNmUxODJmOWVjNzJmZmUxNTIxZjc5ZTM4OWMyYmZkN2M2ZDlmMjBhZjRiMzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pPSJdJc2DJYpFxdWjW0dLGiKbPb8VPBW-zYf_MHoRn0)

The `SplineROI` creates a spline instance in memory ([here](https://github.com/cornerstonejs/cornerstone3D/blob/8575aed359ecd7ca55caaa9b104deef54e44c7fb/packages/tools/src/tools/annotation/SplineROITool.ts#L882)) and it may be missing. The in-memory spline is created using those control points, it splits each curve between two points into line segments and it uses those very small line segments to calculate if a point is close to the spline. I think it needs to be changed in order to create that in-memory spline if it does not exist yet.

**Comment by sedghi** [comment]
Thanks Leo, @IbrahimCSAE will take a look into it

**Comment by IT-Highmore** [comment]
> @sedghi do you know if RectangleROITool, CircleROITool and SplineROI work with annotationHydration ?

@daker  Haha, I have used RectangleROITool work with annotationHydration, it works. 
The version at that time was 1.77.11，maybe you can have a try?

**Comment by sedghi** [comment]
Please refer to the PR for details on the new static method available on the tool for hydration.https://github.com/cornerstonejs/cornerstone3D/pull/1624
