### ISSUE TITLE
[Bug] Umd distribution no longer being included in the release packages

### ISSUE THREAD

**Issue by plt-joey** [cornerstonejs/cornerstone3D#1594]
### Describe the Bug

Every version of the library since `2.0.0-beta.27` has been missing `dist/umd` from the release packages, despite there being no documented removal of it (that I could find) and the 2.0.0 migration guide stating that it should still exist.

![image](https://github.com/user-attachments/assets/330a949e-07fd-411e-991c-6682fa8c11df)
![image](https://github.com/user-attachments/assets/82092052-53e9-4f43-abbf-d21d4dd69a6d)

![umd](https://github.com/user-attachments/assets/c5fcd177-6119-4e25-89e8-e9cd667a2773)

### Steps to Reproduce

1. navigate to https://www.npmjs.com/package/@cornerstonejs/core
2. click the `code` tab
3. navigate to `/dist`, note the lack of `umd`
4. click the `versions` tab
5. go to any version before `2.0.0-beta.27`
6. check `/dist` again
7. go to version `2.0.0-beta.27`
8. check `/dist` again

### The current behavior

The `umd` distribution is missing from the library, contradicting the documentation.

### The expected behavior

Either:
1. The `umd` distribution is re-added to the published package
2. The documentation is updated to reflect that it has been removed

### OS

Windows 10

### Node version

v18.20.4

### Browser

Chrome 130.0.6723.117

**Comment by sedghi** [comment]
Yes that is intentional, use ESM, it works
