### ISSUE TITLE
[Bug] `colorLUIOrIndex` in `RepresentationPublicInput` doesn't appear to work properly.

### ISSUE THREAD

**Issue by stada526** [cornerstonejs/cornerstone3D#1604]
### Describe the Bug

The `colorLUIOrIndex` property in `RepresentationPublicInput` doesn't appear to work properly.

### Steps to Reproduce

In `labelmapSegmentColorChange/index.ts`, specify the `colorLUTOrIndex` as shown below.
 (By the way, this file hasn't been fully updated to align with version2.)

```ts
  await segmentation.addSegmentationRepresentations(viewportId1, [
    {
      segmentationId: segmentationId1,
      type: csToolsEnums.SegmentationRepresentations.Labelmap,
      config: {
        colorLUTOrIndex: [
          [
            [0, 0, 0, 0],
            [250, 152, 180, 255],
            [125, 250, 20, 255],
          ],
        ],
      },
    },
  ]);
```

### The current behavior

No matter which color look up table is provided to `addSegmentationRepresentations`, the initial colors of the segments don't change.

### The expected behavior

The initial colors of the segments should change according to the `colorLUIOrIndex` configuration.

### OS

maxOS 15.1

### Node version

v21.7.1

### Browser

Chrome 130.0.6723.117

**Comment by stada526** [comment]
@sedghi 
Thank you for addressing this issue! I appreciate it 🙏
However, there still seems to be an issue with `colorLUIOrIndex` property in `RepresentationPublicInput`.

In `labelmapSegmentColorChange/index.ts`, specify the colorLUTOrIndex as shown below.
```ts
  await segmentation.addSegmentationRepresentations(viewportId1, [
    {
      segmentationId: segmentationId1,
      type: csToolsEnums.SegmentationRepresentations.Labelmap,
      config: {
        colorLUTOrIndex: [
          [0, 0, 0, 0],
          [0, 0, 255, 255],
          [255, 255, 0, 255],
        ],
      },
    },
  ]);

  await segmentation.addSegmentationRepresentations(viewportId2, [
    {
      segmentationId: segmentationId1,
      type: csToolsEnums.SegmentationRepresentations.Labelmap,
      config: {
        colorLUTOrIndex: [
          [0, 0, 0, 0],
          [0, 255, 0, 255],
          [255, 0, 255, 255],
        ],
      },
    },
  ]);
```

In this case, the first color lookup table appears to work properly, but the second one doesn't.
In version 1 of Cornerstone.js, the both work properly.
Could you check this issue again when you have time?

**Comment by sedghi** [comment]
Damn it, ok i will look
