### ISSUE TITLE
[Bug] [@cornerstonejs/tools==2.2.10] Issue with adding surface representation of labelmap to viewport

### ISSUE THREAD

**Issue by prerakmody** [cornerstonejs/cornerstone3D#1608]
### Describe the Bug

This is the same issue as https://github.com/cornerstonejs/cornerstone3D/issues/1606 but with `v2.2.10`
I am attempting to replicate [polysegwasmvolumelabelmaptosurface](https://www.cornerstonejs.org/live-examples/polysegwasmvolumelabelmaptosurface) using 

```javascript
await cornerstone3DTools.segmentation.addSegmentationRepresentations(config.viewport3DId, [
    {
        segmentationId:mySegmentationId,
        type: cornerstone3DTools.Enums.SegmentationRepresentations.Surface,
        options: {polySeg: {enabled: true,},},
    },
]);
```

I get this error
![image](https://github.com/user-attachments/assets/58bffeb9-e4b8-4d9e-9189-30d685657972)

Note that my segmentations are loading
![image](https://github.com/user-attachments/assets/655c57e8-a7fe-4fcc-a0e1-6b98460a3436)

### Steps to Reproduce

Follow the 5 steps below
```javascript
// --------------------- Step 1 - fetch the DICOM data ---------------------
const client = new dicomWebClient.api.DICOMwebClient({
    url: searchObj.wadoRsRoot
});

const arrayBuffer = await client.retrieveInstance({
    studyInstanceUID: searchObj.StudyInstanceUID,
    seriesInstanceUID: searchObj.SeriesInstanceUID,
    sopInstanceUID: searchObj.SOPInstanceUID
});
const dicomData = dcmjs.data.DicomMessage.readFile(arrayBuffer);
dataset         = dcmjs.data.DicomMetaDictionary.naturalizeDataset(dicomData.dict); 
dataset._meta   = dcmjs.data.DicomMetaDictionary.namifyDataset(dicomData.meta);

if (dataset.Modality === config.MODALITY_SEG){
    // --------------------- Step 2 - Load pixel array ---------------------
    const generateToolState = await cornerstoneAdapters.adaptersSEG.Cornerstone3D.Segmentation.generateToolState(
        imageIds,
        arrayBuffer,
        cornerstone3D.metaData
    );  

    // --------------------- Step 3 - Create c3D segmentation volume (and addSegmentations() and addSegmentationRepresentations()) ---------------------
    const derivedVolume = await cornerstone3D.volumeLoader.createAndCacheDerivedLabelmapVolume(config.volumeIdCT, {volumeId: segmentationId,});
    cornerstone3DTools.segmentation.addSegmentations([{ segmentationId:mySegmentationId, representation: { type: cornerstone3DTools.Enums.SegmentationRepresentations.Labelmap, data: { volumeId: mySegmentationId, }, }, },]);
    config.viewPortIdsAll.forEach((viewPortId) => {
        cornerstone3DTools.segmentation.addSegmentationRepresentations(viewPortId, [{segmentationId:mySegmentationId, type: cornerstone3DTools.Enums.SegmentationRepresentations.Labelmap, }],);
    }); 

    // --------------------- Step 4 - Set the labelmap data ---------------------
    await derivedVolume.voxelManager.setCompleteScalarDataArray(new Uint8Array(generateToolState.labelmapBufferArray[0]));

    // --------------------- Step 5 - Add the segmentation to the 3D viewer ---------------------
    await cornerstone3DTools.segmentation.addSegmentationRepresentations(config.viewport3DId, [
        {
            segmentationId:mySegmentationId,
            type: cornerstone3DTools.Enums.SegmentationRepresentations.Surface,
            options: {polySeg: {enabled: true,},},
        },
    ]);
}
```

Also, in my `webpack.config.js`
```javascript
module.exports = {
    ...,
    module: {
        rules: [
            {
            test: /\.wasm$/,
            use: ['wasm-loader'], //to deal with "Can't resolve 'a' in ./node_modules/@icr/polyseg-wasm/dist"
            type: 'javascript/auto',
            },
        ],
        unknownContextCritical: false,
    },
    ....
}
```

### The current behavior

I get an error in polySegConverters.js which eventually traces to ICRPolySeg.js.
This seems to be the error
```javascript
function isDataURI(filename){return filename.startsWith(dataURIPrefix)}
```
Here, `filename=ICRPolySeg.wasm and dataURIPrefix=data:application/octet-stream;base64,`

I have `@icr/polyseg-wasm@0.4.0` and `wasm-loader@1.3.0`

![image](https://github.com/user-attachments/assets/9070dc35-a733-4e1a-87e8-7fa5a9f1d9ae)

### The expected behavior

The surface of the labelmap should show up.

### OS

Linux (Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux)

### Node version

23.2.0

### Browser

Chrome 130.0.6723.117

**Comment by sedghi** [comment]
Our demo works, i'm wondering what you are doing differently https://www.cornerstonejs.org/live-examples/polysegwasmvolumelabelmaptosurface

**Comment by sedghi** [comment]
Also it works in OHIF, see its webpack config https://github.com/OHIF/Viewers/

**Comment by prerakmody** [comment]
Thanks for the reference to OHIF. I had to change my `webpack.config.js` and now it works.
For future readers, to reference wasm files in `webpack.config.js`, you need to do this
```javascript
module.exports = {
    ...,
    module: {
        rules: [
            {
            test: /\.wasm$/,
            type: 'asset/resource',
            },
        ],
        unknownContextCritical: false,
    },
    ....
}
```

I was using `wasm-loader` with `type: 'javascript/auto'`, but I should have just done `type: 'asset/resource'`

<img width="510" alt="image" src="https://github.com/user-attachments/assets/5f6fb958-1c17-4e62-95c2-58a00bd34913">

**Comment by sedghi** [comment]
Would you like to contribute to the project by adding this information to our migration guides?

**Comment by prerakmody** [comment]
Sure! 
On this [page (../docs/migration-guides/2x/5-tools.md)](https://github.com/cornerstonejs/cornerstone3D/blob/v2.2.15/packages/docs/docs/migration-guides/2x/5-tools.md?plain=1)?

The only thing I changed (rectified?) was the `webpack.config.js` file.

**Comment by sedghi** [comment]
I was thinking on this page [https://www.cornerstonejs.org/docs/getting-started/vue-angular-react-etc](https://www.cornerstonejs.org/docs/getting-started/vue-angular-react-etc) 

Yes just have a before and after
