### ISSUE TITLE
[Bug][v2.2.15] Too many warning messages on `cornerstone3D.volumeLoader.createAndCacheVolume()`

### ISSUE THREAD

**Issue by prerakmody** [cornerstonejs/cornerstone3D#1613]
### Describe the Bug

I get `Warning` messages for 
 - `cornerstone3D.volumeLoader.createAndCacheVolume()` 
 - `cornerstone3D.setVolumesForViewports()`
 - `cornerstone3D.volumeLoader.createAndCacheDerivedLabelmapVolume()`
 - `cornerstone3DTools.segmentation.addSegmentationRepresentations()`

functions. There does not seem to be any effect on the functionality. See images below

 - `cornerstone3D.volumeLoader.createAndCacheVolume()` 
 <img width="864" alt="image" src="https://github.com/user-attachments/assets/6ec7479c-cc81-4b34-985c-ecc74ec07047">

- `cornerstone3D.setVolumesForViewports()`
<img width="516" alt="image" src="https://github.com/user-attachments/assets/f6366214-448d-424a-915e-31b421bd8a61">

 - `cornerstone3D.volumeLoader.createAndCacheDerivedLabelmapVolume()`
<img width="760" alt="image" src="https://github.com/user-attachments/assets/09c0705f-e228-496f-b812-96ecad08eafb">

- `cornerstone3DTools.segmentation.addSegmentationRepresentations()`
<img width="510" alt="image" src="https://github.com/user-attachments/assets/9c83fd62-e675-43c6-b13f-fb3f944fafb3">

### Steps to Reproduce

- For `cornerstone3D.volumeLoader.createAndCacheVolume()`  and `cornerstone3D.setVolumesForViewports()`
```javascript

// Step 0 - Define variables
const searchObjCT = {
  StudyInstanceUID:'',
  SeriesInstanceUID:'',
  SOPInstanceUID:'',
  wadoRsRoot:'',,
}
const config.volumeIdCT = ''
const imageIdsCT = await createImageIdsAndCacheMetaData(searchObjCT)
const renderingEngine = cornerstone3D.getRenderingEngine(renderingEngineId);
const viewportIds = []

// Step 2 - Load volume
const volumeCT   = await cornerstone3D.volumeLoader.createAndCacheVolume(volumeIdCT, {imageIds:imageIdsCT}); // I get warning message for this
volumeCT.load();

// Step 3 - Set to viewport
await cornerstone3D.setVolumesForViewports(renderingEngine, [{ volumeId:volumeIdCT}, ], viewportIds, true); // I also get warning message for this
```

- For `cornerstone3D.volumeLoader.createAndCacheDerivedLabelmapVolume()` and `cornerstone3DTools.segmentation.addSegmentationRepresentations()` refer to https://github.com/cornerstonejs/cornerstone3D/issues/1608

### The current behavior

I get warning messages that clog up up my console

### The expected behavior

I should not be getting any warning messages

### OS

Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux

### Node version

23.2.0

### Browser

Brave (Version 1.66.118)

**Comment by sedghi** [comment]
Yeah i need to figure out how to silent them, it is not important though
