### ISSUE TITLE
[Feature Request] a annotation tool for measuring 3D spheres

### ISSUE THREAD

**Issue by Gscdae** [cornerstonejs/cornerstone3D#1616]
### What feature or change would you like to see made?

I would like to have an annotation tool for measuring 3D spheres, with underlying metrics, like a combination of CircleROITool and SphereScissorsTool

### Why should we prioritize this feature?

The current measurements are all based on a certain plane, and none of them are related to the volume in 3D

**Comment by sedghi** [comment]
We have lablemap tools that can have statistics, does that help? [https://www.cornerstonejs.org/live-examples/labelmapsegmentationtools](https://www.cornerstonejs.org/live-examples/labelmapsegmentationtools)  (the example does not show stats but you can get it)

Having said that it is not hard at all, you can implement it, take a look at more sophisticated tools like [https://www.cornerstonejs.org/docs/examples](https://www.cornerstonejs.org/docs/examples)
