### ISSUE TITLE
[Bug] Use mobile browser to open 3D Volume Rendering is a black block is not supported by mobile phone open

### ISSUE THREAD

**Issue by woaihengniu** [cornerstonejs/cornerstone3D#1618]
### Describe the Bug

I was opening 3D Volume Rendering with Google Browser on my phone and it was a black block that couldn't render
![微信图片_20241126172702](https://github.com/user-attachments/assets/b2657150-0e38-4bac-bb52-87af147354da)

Open the provided example is also a black block, is it not supported to open the mobile browser?
![微信图片_20241126172710](https://github.com/user-attachments/assets/a6452f02-1e57-424e-87f9-9ee2140e6874)

### Steps to Reproduce

1. Initialize components
2. Load the image
3. Render the image

### The current behavior

The mobile browser cannot open 3D Volume Rendering

### The expected behavior

3D Volume Rendering can be used normally with Google Chrome on Android phones

### OS

win10

### Node version

v18.20.4

### Browser

Microsoft Edge  128.0.2739.79

**Comment by sedghi** [comment]
Which phone is this? Our tests that pass are the Pixel 8 and iPhone 14. And we certainly cannot test all phones

**Comment by woaihengniu** [comment]
> Pixel 8



> 这是哪款手机？我们通过的测试是 Pixel 8 和 iPhone 14。我们当然无法测试所有手机

I use vivo mobile phone Android system

**Comment by sedghi** [comment]
What happened @woaihengniu , did it work?

**Comment by woaihengniu** [comment]
> What happened @woaihengniu , did it work?

Still can't render, iPhone13Plus can render, Android machine can not
