### ISSUE TITLE
[Bug] Can't dynamically create annotation on CR images

### ISSUE THREAD

**Issue by tokyobordel** [cornerstonejs/cornerstone3D#1621]
### Describe the Bug

Can't dynamically create annotation on CR images. I get the following error: 
`Uncaught TypeError: Cannot read properties of undefined (reading '0') at Module.subtract (vec3.js:122:1)  at calculateDistanceToImage (annotationHydration.js:78:5) at eval (annotationHydration.js:70:1)`
This is because my images don't have IPP. Is there a solution for such cases?

### Steps to Reproduce

```
const ann = cornerstoneTools.utilities.annotationHydration(viewport, "Probe", coords);

cornerstoneTools.utilities.triggerAnnotationRenderForViewportIds([
   viewport.id,
]);

viewport.render();
```

### The current behavior

`Uncaught TypeError: Cannot read properties of undefined (reading '0') at Module.subtract (vec3.js:122:1)  at calculateDistanceToImage (annotationHydration.js:78:5) at eval (annotationHydration.js:70:1)`

### The expected behavior

Annotation added to canvas

### OS

Windows 10

### Node version

20.15.1

### Browser

Chrome 130.0.6723.70

**Comment by sedghi** [comment]
Is it only happening for the CR?

**Comment by sedghi** [comment]
Please refer to the PR for details on the new static method available on the tool for hydration.https://github.com/cornerstonejs/cornerstone3D/pull/1624
