### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot destructure property 'viewport' of 'enabledElement' as it is undefined

### ISSUE THREAD

**Issue by tokyobordel** [cornerstonejs/cornerstone3D#1634]
### Describe the Bug

I'm developing an app in React. Sometimes my viewport gets hidden (removed entirely from the DOM, then restored by clicking a button). If I had more than one SplineROIAnnotation in the viewport before it got hidden, I get the following error:
```
Uncaught TypeError: Cannot destructure property 'viewport' of 'enabledElement' as it is undefined.
    at SplineROITool._calculateCachedStats (SplineROITool.js:427:21)
    at invokeFunc (debounce.js:24:1)
    at trailingEdge (debounce.js:70:1)
    at timerExpired (debounce.js:63:1)
```
The error occurs when I call setStack:
![image](https://github.com/user-attachments/assets/466fcdd1-6e9d-4f57-910b-c1c23c5a4589)
![image](https://github.com/user-attachments/assets/55ef130d-47ea-46b4-8cda-78e5b30a519f)
Surprisingly, apart from the error message, the viewport renders fine, loading all the annotations that were supplied.
Is there a way to make the _calculateCachedStats method be ignored?

### Steps to Reproduce

1. Put 2 SplineROI on canvas
2. Hide canvas (remove from DOM)
3. Show canvas

### The current behavior

```
Uncaught TypeError: Cannot destructure property 'viewport' of 'enabledElement' as it is undefined.
    at SplineROITool._calculateCachedStats (SplineROITool.js:427:21)
    at invokeFunc (debounce.js:24:1)
    at trailingEdge (debounce.js:70:1)
    at timerExpired (debounce.js:63:1)
```

### The expected behavior

No error

### OS

Windows 10

### Node version

20.15.1

### Browser

Chrome 130.0.6723.70

**Comment by daker** [comment]
As workaround set 

```js
toolGroup.setToolConfiguration(SplineROITool.toolName, {
    calculateStats: false,
});
```

https://github.com/cornerstonejs/cornerstone3D/blob/1e0cd54783c405d4a72e2b23d7d519873d0c71da/packages/tools/src/tools/annotation/SplineROITool.ts#L1125C29-L1127

**Comment by IbrahimCSAE** [comment]
> ### Describe the Bug
> I'm developing an app in React. Sometimes my viewport gets hidden (removed entirely from the DOM, then restored by clicking a button). If I had more than one SplineROIAnnotation in the viewport before it got hidden, I get the following error:
> 
> ```
> Uncaught TypeError: Cannot destructure property 'viewport' of 'enabledElement' as it is undefined.
>     at SplineROITool._calculateCachedStats (SplineROITool.js:427:21)
>     at invokeFunc (debounce.js:24:1)
>     at trailingEdge (debounce.js:70:1)
>     at timerExpired (debounce.js:63:1)
> ```
> 
> The error occurs when I call setStack: ![image](https://private-user-images.githubusercontent.com/151533918/390801088-466fcdd1-6e9d-4f57-910b-c1c23c5a4589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTQ2ODAsIm5iZiI6MTczMzQ5NDM4MCwicGF0aCI6Ii8xNTE1MzM5MTgvMzkwODAxMDg4LTQ2NmZjZGQxLTZlOWQtNGY1Ny05MTBiLWMxYzIzYzVhNDU4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNDEzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjhhMTI3NzMyMTZhY2ZkMzY3YmU1M2JkMjRjZDFjYzgwOWIwN2IzMDQ2OTA5ZDY3MDEzNGRjOWU0MjA5NDdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w2THbKfnj1y_mL887kRmy5Act0ZApH4GxSNBPyjqPWk) ![image](https://private-user-images.githubusercontent.com/151533918/390802064-55ef130d-47ea-46b4-8cda-78e5b30a519f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTQ2ODAsIm5iZiI6MTczMzQ5NDM4MCwicGF0aCI6Ii8xNTE1MzM5MTgvMzkwODAyMDY0LTU1ZWYxMzBkLTQ3ZWEtNDZiNC04Y2RhLTc4ZTViMzBhNTE5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNDEzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjZkZjVlMmY5YzBiOTNkOTYyZWZmNzA2YzAzZDVlNTJhZTFjZDc1N2E0ZGEyOTRmM2JmY2Y0Y2Y5YTdmYTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A5x3eYZa3SJ1QTXdjCJdvyiS6Uw_-wOdRfzXGQ0mg74) Surprisingly, apart from the error message, the viewport renders fine, loading all the annotations that were supplied. Is there a way to make the _calculateCachedStats method be ignored?
> 
> ### Steps to Reproduce
> 1. Put 2 SplineROI on canvas
> 2. Hide canvas (remove from DOM)
> 3. Show canvas
> 
> ### The current behavior
> ```
> Uncaught TypeError: Cannot destructure property 'viewport' of 'enabledElement' as it is undefined.
>     at SplineROITool._calculateCachedStats (SplineROITool.js:427:21)
>     at invokeFunc (debounce.js:24:1)
>     at trailingEdge (debounce.js:70:1)
>     at timerExpired (debounce.js:63:1)
> ```
> 
> ### The expected behavior
> No error
> 
> ### OS
> Windows 10
> 
> ### Node version
> 20.15.1
> 
> ### Browser
> Chrome 130.0.6723.70


like @daker mentioned, if you set calculateStats: false, then the _calculateCachedStats method won't be called which is what you are asking for
