### ISSUE TITLE
[Feature Request] delete Annotation v 1.84

### ISSUE THREAD

**Issue by VladimirKondratenko** [cornerstonejs/cornerstone3D#1635]
### What feature or change would you like to see made?

Good time, sorry, but i have question, i sent on email and open topic and without some answer. How i can delete annotation from one screen? Because nothing is happening in my code. When i using annotation.state.removeAllAnnotations() all worked, but cleared from all screens
https://community.ohif.org/t/how-i-can-delete-annotation-from-one-screen/2066

### Why should we prioritize this feature?

it's important for our project

**Comment by sedghi** [comment]
Did you call a render on viewport?

**Comment by VladimirKondratenko** [comment]
yes, because annotation.state.removeAll Annotations() it's worked for me, but removed Annotation not worked, i dont have ideas
![image](https://github.com/user-attachments/assets/de04733e-2cef-4caf-9c30-e3f85fe380d4)

**Comment by VladimirKondratenko** [comment]
UPD
![image](https://github.com/user-attachments/assets/2577d091-c941-4c00-b6b1-76c6e7efccb3)
![image](https://github.com/user-attachments/assets/9630946f-545b-414e-8b41-ab1cd17aa32d)

**Comment by sedghi** [comment]
`removeAnnotation` accepts `annotationUID` as a parameter. So, how do you filter annotations for a viewport (is that what you mean by screen)?

You can use `getAnnotations` like this:

```js
const annotations = getAnnotations(toolName, viewport.element);
```

Then, loop through them and delete each one individually.

Why don't we have a direct method? That's a good question. Maybe you can help us create one.
