### ISSUE TITLE
It is planned to use cornerstone-web-image-loader to load PNG, and the metadataprovider conversion has been completed. No error is reported, but the image shows gray blocks. I hope I can get ideas

### ISSUE THREAD

**Issue by David2k13** [cornerstonejs/cornerstone3D#164]
It is planned to use cornerstone-web-image-loader to load PNG, and the metadataprovider conversion has been completed. No error is reported, but the image shows gray blocks. I hope I can get ideas
![image](https://files.catbox.moe/anqmk1.png)

**Comment by sedghi** [comment]
Can you write a comprehensive detailed issue regarding the problem? I don't understand it.
