### ISSUE TITLE
[Bug] 图片显示不出来

### ISSUE THREAD

**Issue by yulecc** [cornerstonejs/cornerstone3D#1646]
### Describe the Bug

我按照cornerstone3D Render Stack of Images示例，实现的代码，但是图片显示不出来，我的项目是用vite创建的react项目

### Steps to Reproduce

await csRenderInit()
await csToolsInit()
dicomImageLoaderInit({maxWebWorkers:1})

然后，我没有去调用createImageIdsAndCacheMetaData获取imagesId,
我是通过请求后端服务，获取到一个dcm文件的url: api/123.dcm, 于是我拼接成了一个字符串:
const imageId = 'wadouri:http://api/123.dcm'
在浏览器地址栏直接输入http://api/123.dcm，可以把这个dcm文件下载下来。
然后：
const renderingEngineId = 'myRenderingEngine';
const renderingEngine = new RenderingEngine(renderingEngineId);

const viewportId = 'CT_AXIAL_STACK';
const viewportInput = {
  viewportId,
  element,
  type: Enums.ViewportType.STACK,
};
renderingEngine.enableElement(viewportInput);
const viewport = renderingEngine.getViewport(viewportId);
viewport.setStack([imageId]);

  viewport.render();
这就是我最终的代码，但是图片却显示不出来

### The current behavior

图片显示不出来

### The expected behavior

图片显示出来

### OS

windows 10

### Node version

20

### Browser

chrome 130

**Comment by topstop3416** [comment]
WADO-URI Response
https://dicom.nema.org/dicom/2013/output/chtml/part18/sect_6.3.html

**Comment by yulecc** [comment]
yes, this is a problem, dcm image not display, then i just lower it to version 1. x , dicom image can display

**Comment by yulecc** [comment]
the viewport.setStak always return a pending promise on 2.x

**Comment by sedghi** [comment]
checkout our example [https://www.cornerstonejs.org/live-examples/wadouri.html](https://www.cornerstonejs.org/live-examples/wadouri.html)

**Comment by fancyoung** [comment]
I fix this problem by add `@originjs/vite-plugin-commonjs` plugin.

https://www.cornerstonejs.org/docs/getting-started/vue-angular-react-etc/

more detail in my issue https://github.com/cornerstonejs/cornerstone3D/issues/1664
