### ISSUE TITLE
[Bug] VoxelManager throw error if call getRange before end of image loading

### ISSUE THREAD

**Issue by salimkanoun** [cornerstonejs/cornerstone3D#1647]
### Describe the Bug

`        voxelManager.getRange = () => {
            let minValue = Infinity;
            let maxValue = -Infinity;
            for (const imageId of imageIds) {
                const image = cache.getImage(imageId);
                if (image.minPixelValue < minValue) {
                    minValue = image.minPixelValue;
                }
                if (image.maxPixelValue > maxValue) {
                    maxValue = image.maxPixelValue;
                }
            }
            return [minValue, maxValue];
        };`

As this function might be called before all image are stored in the cache (for instance progressive loading), this function throws an error if called before finishing load all images

`TypeError: Cannot read properties of undefined (reading 'minPixelValue')
    at o.getRange (VoxelManager.js:424:27)`

Maybe we shoud add  
   const image = cache.getImage(imageId);
if(!image) continue 

So the get Range does not break and return the range of currently loaded images ? 

What do you think @sedghi / @wayfarer3130  ?

### Steps to Reproduce

Call getRange before full volume loading

### The current behavior

throws error

### The expected behavior

should at least not throw error

### OS

Linux

### Node version

20

### Browser

Chrome latest

**Comment by VladimirKondratenko** [comment]
have you tried checking on undefined you variables?

**Comment by salimkanoun** [comment]
this is in the internal cornestone API

**Comment by sedghi** [comment]
what is the stack trace? who is calling it soon?
