### ISSUE TITLE
[Bug] Segments Not Displayed After v2.4.0 in SegmentationVolume Example

### ISSUE THREAD

**Issue by stada526** [cornerstonejs/cornerstone3D#1658]
### Describe the Bug

In the following example, pressing the ‘Load SEG’ button doesn’t display any segments.
https://www.cornerstonejs.org/live-examples/segmentationvolume

It seems that the segments are loaded, but none of them are displayed.

I did some research to determine when this issue started. As a result, I found that this issue has been present since v2.4.0. In versions up to v2.3.3, the segments were rendered correctly.

My app is implemented based on the code from this example, so it doesn't work correctly with versions after v2.4.0. I would greatly appreciate it if this issue could be resolved.

### Steps to Reproduce

1. In [this example](https://www.cornerstonejs.org/live-examples/segmentationvolume), press 'Load DICOM' button.
2. After the volume has been rendered, press 'Load SEG' button.

### The current behavior

No segments are displayed

### The expected behavior

Loaded segments are displayed.

### OS

maxOS 15.1

### Node version

v21.7.1

### Browser

Chrome 130.0.6723.117

**Comment by sedghi** [comment]
Thanks i will check it out
