### ISSUE TITLE
[Bug] Brushing Doesn’t Work After Loading DICOM and DICOM-SEG in SegmentationVolume Example

### ISSUE THREAD

**Issue by stada526** [cornerstonejs/cornerstone3D#1661]
### Describe the Bug

In the following example, brushing doesn't work after loading DICOM and DICOM-SEG.
https://www.cornerstonejs.org/live-examples/segmentationvolume

This issue occurs In both cases: when loading via ‘Load DICOM’ and 'Load SEG' buttons, and when loading via 'Import DICOM' and 'Import SEG' buttons.

Additionally, the brush cursor looks like a double circle instead of a single circle.

In versions up to v2.3.3, this issue was not present.

https://github.com/user-attachments/assets/22e652e5-c80e-4d9d-add3-cc441bc79a3c

### Steps to Reproduce

1. In [this example](https://www.cornerstonejs.org/live-examples/segmentationvolume), press 'Load DICOM' button.
2. After the volume has been rendered, press 'Load SEG' button.
3. Try drawing segment 

### The current behavior

Brush doesn't work.

### The expected behavior

Brush works.

### OS

maxOS 15.1

### Node version

v21.7.1

### Browser

Chrome 130.0.6723.117

**Comment by sedghi** [comment]
It's probably just a simple bug.
