### ISSUE TITLE
[Bug] dicom can't be rendered when upgrade from 1.8 to 2.4+

### ISSUE THREAD

**Issue by fancyoung** [cornerstonejs/cornerstone3D#1664]
### Describe the Bug

I have a render problem when I upgrade cornerstone3d (with dicom-image-loader) from 1.8+ to 2.4.0+
The image was load, but can't be rendered.
It seems stoped on `await viewport.setStack(stack)` and  can't goto next step.

I believe it might be something like `createAndCacheDerivedImage`, which returns an `IImage` directly in v2, rather than a `Promise<IImage>`. However, I have been unable to locate it.  I didn't  use `createAndCacheDerivedImage` directly.

### Steps to Reproduce

I wrote a demo to reproduce this: https://github.com/fancyoung/cs-demo-bug

```
  const renderingEngineId = 'myRenderingEngine';
  const renderingEngine = new RenderingEngine(renderingEngineId);
  
  // Create a stack viewport
  const viewportId = 'CT_STACK';
  const viewportInput = {
    viewportId,
    type: Enums.ViewportType.STACK,
    element,
  };
  
  renderingEngine.enableElement(viewportInput);
  
  // Get the stack viewport that was created
  const viewport = renderingEngine.getViewport(viewportId);
  const imageIds = ['wadouri:/dicom.dcm'];
  console.log('->', imageIds)
  await viewport.setStack(imageIds);
  console.log('-->> never show')
  viewport.render();
```

### The current behavior

It stoped at line `await viewport.setStack(imageIds)`, and `viewport.render()` never be called.

### The expected behavior

render the image.

### OS

macOS

### Node version

v18.19.0

### Browser

Chrome 129

**Comment by sedghi** [comment]
please follow our example, which works fine [https://www.cornerstonejs.org/live-examples/wadouri.html](https://www.cornerstonejs.org/live-examples/wadouri.html)

**Comment by fancyoung** [comment]
I find out is cause by commonJS (from dicom-parser ?). Should use `@originjs/vite-plugin-commonjs` plugin converting commonJS to esm, then it works:

```
import { viteCommonjs } from "@originjs/vite-plugin-commonjs"

export default defineConfig({
  plugins: [viteCommonjs()],
  optimizeDeps: {
    exclude: ["@cornerstonejs/dicom-image-loader"],
    include: ["dicom-parser"],
  },
})
```

I use svelte, there is another strange thing, the converting plugin can not working with `plugins: [sveltekit(), viteCommonjs()]`. Then I use `@sveltejs/vite-plugin-svelte` instead of `@sveltejs/kit/vite`, it works.

**Comment by yulecc** [comment]
thanks very much

**Comment by sedghi** [comment]
@fancyoung Would you like to contribute to our project? It would be a wonderful gift from you to us. Could you create a PR to add the Svelte config to that page and possibly cross-link it in our migration guides?

**Comment by fancyoung** [comment]
> @fancyoung Would you like to contribute to our project? It would be a wonderful gift from you to us. Could you create a PR to add the Svelte config to that page and possibly cross-link it in our migration guides?

My pleasure, I'd be happy to contribute. Just to confirm, should I place the Svelte config in https://www.cornerstonejs.org/docs/getting-started/vue-angular-react-etc or https://github.com/cornerstonejs/svelte-cornerstone3d? And where exactly would you like it linked in the migration guides?

**Comment by sedghi** [comment]
I think if we put it in here https://www.cornerstonejs.org/docs/getting-started/vue-angular-react-etc it would be enough
and for migration guides maybe inside this one https://www.cornerstonejs.org/docs/migration-guides/2x/general#frameworks

**Comment by fancyoung** [comment]
I have submitted a pull request for the migration config docs related to this issue. You can review it here: https://github.com/cornerstonejs/cornerstone3D/pull/1681
