### ISSUE TITLE
[Bug] Segments fail to render in MIP viewport unless drawn at center of normal viewport

### ISSUE THREAD

**Issue by stada526** [cornerstonejs/cornerstone3D#1667]
### Describe the Bug

I'm not sure if this should be a bug or feature request...

When setting the viewport to MIP (Maximum Intensity Projection), I encountered an issue where the volume is displayed in the MIP mode, but the segment is not.

To reproduce and debug this behavior, I slightly modified the example code for `labelmapSegmentationTools`. Here is the code. https://github.com/stada526/cornerstone3D/pull/1

In this reproduction example, one viewport is set to display normally in the axial plane, while another is set to MIP in the sagittal plane. When drawing a segment in the normally displayed viewport, I expected the segment to appear in the MIP viewport regardless of where it was drawn. However, in reality, the segment only appears in the MIP viewport when it is drawn in the center of the normally displayed viewport.

For debugging purposes, a 'Debug' button has been added to this example to log the actor information for the MIP viewport via `console.log`. Upon investigation, I noticed that only the segment’s actor had an `undefined` `slabThickness`, which I suspected was the cause. To test this, I modified the ‘Debug’ button’s processing to assign the same `slabThickness` value to the segment’s actor as the volume.

However, even after updating the `slabThickness`, the segment still did not appear in the MIP viewport.

https://github.com/user-attachments/assets/0ae08d4a-1392-4c73-bc52-c35c1ea81230

### Steps to Reproduce

Refer to this sample code https://github.com/stada526/cornerstone3D/pull/1

### The current behavior

Segments are not displayed in MIP mode.

### The expected behavior

Segments are displayed in MIP mode.

### OS

maxOS 15.1

### Node version

v21.7.1

### Browser

Chrome 130.0.6723.117

**Comment by sedghi** [comment]
This is actually getting fixed very soon, expect the SEG on MIP to be a lot better

**Comment by stada526** [comment]
Sounds great! I really appreciate it.

**Comment by sedghi** [comment]
it will be built on top of this https://github.com/Kitware/vtk-js/pull/3103

**Comment by sedghi** [comment]
The PR for rendering one label map on MIP is available. We can theoretically handle four and expand it later.

**Comment by stada526** [comment]
@sedghi 

Hi, thank you for the great work! Exciting!

I have a few questions:
- What do you mean by "four" and "one"? Do they refer to the number of segmentations? In the new example, I saw "one" segmentation registered which contains two segments.
- If so, why the number of segmentations are limited up to four in this feature?
- Do you have a sense of when "four" can be achieved?

**Comment by sedghi** [comment]
- Yes, number of segmentations to be overlayed. Each segmentation can have 256 segments. 
- The limit is for webgl and how many textures we can bind at at time 
- After these PRs are merged https://github.com/Kitware/vtk-js/pull/3137 and https://github.com/Kitware/vtk-js/pull/3132

**Comment by stada526** [comment]
I understand. I really appreciate it 🙏
