### ISSUE TITLE
[Bug] ImageCPRMapper doesn't display anything in the viewport

### ISSUE THREAD

**Issue by daker** [cornerstonejs/cornerstone3D#1677]
### Describe the Bug

I am trying to use `vtkImageCPRMapper` and i am not sure if it's a bug or a missing feature
and if if it can be fixed by registering the mapper in https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/core/src/RenderingEngine/vtkClasses/vtkStreamingOpenGLViewNodeFactory.js#L115

### Steps to Reproduce

```js
const imageData = axialViewport.getImageData();
const centerline = vtkPolyData.newInstance();
const actor = vtkImageSlice.newInstance();
const mapper = vtkImageCPRMapper.newInstance();
mapper.useStraightenedMode();
mapper.setImageData(imageData.imageData);
mapper.setProjectionMode(ProjectionMode.AVERAGE);
mapper.setProjectionSlabNumberOfSamples(100);
mapper.setProjectionSlabThickness(20);
[...]
cprViewport.addActor({ uid: "cprActor", actor});
cprViewport.resetCamera();
cprViewport.render();
```

### The current behavior

The camera changes but nothing is displayed in the viewport

### The expected behavior

The vtkImage is displayed

### OS

Windows 11

### Node version

latest

### Browser

131.0.6778.108

**Comment by sedghi** [comment]
I want to explore this further, but off the top of my head, we have completely disabled the VTK interactor style here. I remember the CPRMapper relied on that at least for manipulation. right? Rendering should work most likely. 

if not that certainly one of these

![CleanShot 2024-12-06 at 14 24 51@2x](https://github.com/user-attachments/assets/9744a41e-db6c-4d2b-aa5a-fc26e8109239)

**Comment by daker** [comment]
I want to use it to generate a pseudo pano following a spline, basically supply the polydata(spline points with normals) and the volume as input to the mapper the get the vtkimagedata to be displayed in the stack viewport.

The code inside generate a the centerline(spline/polydata) from a controls points with the normals/Orientation

> Did you try registering the mapper int he NodeFactory?

Yes i did, but it does error

```js
ImageCPRMapper.js:133 Uncaught TypeError: Cannot read properties of null (reading 'setMinificationFilter')
    at publicAPI.updateBufferObjects (ImageCPRMapper.js:133:1)
    at publicAPI.renderPieceStart (ImageCPRMapper.js:96:1)
    at publicAPI.renderPiece (ImageCPRMapper.js:90:1)
    at publicAPI.render (ImageCPRMapper.js:73:1)
    at publicAPI.opaquePass (ImageCPRMapper.js:53:1)
    at publicAPI.apply (ViewNode.js:41:1)
    at publicAPI.traverse (ViewNode.js:32:1)
    at ImageSlice.js:50:1
    at Array.forEach (<anonymous>)
    at publicAPI.traverseOpaquePass (ImageSlice.js:49:1)
```

i had to set the scalars manually but it stucks somewhere, the console log here is never displayed

```js
const scalarData = volumeViewport.getImageData()?.scalarData;
console.log('get scalars');
const scalarArray = vtkDataArray.newInstance({
      name: 'Pixels',
      numberOfComponents: 1,
      // @ts-expect-error
      values: scalarData,
 });
```

![image](https://github.com/user-attachments/assets/0b8fb8d3-0957-4dbc-a2f8-c92882218b52)

i can send you an example by email, is that ok for you ?

**Comment by sedghi** [comment]
Yes send me over email, i can look next week ar.sedghi@gmail.com

**Comment by aodong8808** [comment]
Hello, daker.
May I ask if your issue has been resolved and if you could share it? I have also encountered the same problem!
Thank you, looking forward to your reply!

**Comment by daker** [comment]
Are you using the latest version ? try replacing

`const scalarData = volumeViewport.getImageData()?.scalarData;`

with

`const scalarData = volume.voxelManager.getCompleteScalarDataArray();`

**Comment by aodong8808** [comment]
> 您使用的是最新版本吗？尝试替换
> 
> `const scalarData = volumeViewport.getImageData()?.scalarData;`
> 
> 和
> 
> `const scalarData = volume.voxelManager.getCompleteScalarDataArray();`

Thank you very much, your reply is very helpful, I have successfully rendered it,

**Comment by maituduy** [comment]
@daker hello darker, i want to implement CPR into cornerstone also, could you send me an example? i struggle with this now.

**Comment by abarbermate** [comment]
Hi @daker!
Can you please share some more information about how you implement CPR using cornerstone.js and vtk.js?
I also want to create this functionality in my master thesis for a cephalometric annotation/analysis tool, that helps to predic landmarks.
You can reach me at [mate1024@gmail.com](mailto:mate1024@gmail.com).

**Comment by Sotatek-LinhNguyen14** [comment]
Hello @daker I'm also looking to implement CPR using cornerstone.js and vtk.js, can we discuss it further?
you can reach me at linhgt65@gmail.com
