### ISSUE TITLE
[Bug] Segmentation renders incorrectly in examples

### ISSUE THREAD

**Issue by napest** [cornerstonejs/cornerstone3D#1679]
### Describe the Bug

When I open the same [study](https://upload.3opinion.ru/index.php/s/nHHFtcDxj3nbwwL) in OHIF and other viewers, I see all segments. 

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/2f6f4a45-83e0-49c8-9a2d-da55f5aba0f1">

When I open the same files with [DICOM SEG VOLUME example](https://www.cornerstonejs.org/live-examples/segmentationvolume) **not all segments render**, and some others render **incorrectly**.

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/fff10e52-6774-404f-9394-783a0f4b32ee">

### Steps to Reproduce

1. Download the archive with [files](https://upload.3opinion.ru/index.php/s/nHHFtcDxj3nbwwL)
2. Open the files in OHIF, here I open MPR for example
3. Open the [example](https://www.cornerstonejs.org/live-examples/segmentationvolume)
4.  Press Import DICOM and choose all files in folder: series_CT_1.2.826.0.1.3680043.8.498.85426739863189145594064966122050708687
5. Press Import SEG and choose output_seg/seg.dcm
6. You will see not all segments and no errors in console

### The current behavior

Not all segments render and some render incorrectly

### The expected behavior

All segments render as in OHIF

### OS

macOS 14.3

### Node version

-

### Browser

Chrome latest

**Comment by sedghi** [comment]
In your case there are overlapping segments

![CleanShot 2024-12-05 at 15 21 05@2x](https://github.com/user-attachments/assets/390fdd50-90cf-4b35-a182-ed86f98084cf)

I cleaned up the example so it works. It was unnecessarily complex. Check the PR.

**Comment by napest** [comment]
thank you so much!

**Comment by napest** [comment]
@sedghi thank you for the fixes!
When I open https://www.cornerstonejs.org/live-examples/segmentationstack example and press "Import dicom" and choose one DICOM file, console shows error 
<img width="730" alt="image" src="https://github.com/user-attachments/assets/535a70bb-4539-441a-89f6-2fa031956fa1">
When I choose several dicom files, it says 
<img width="722" alt="image" src="https://github.com/user-attachments/assets/5e1e8371-f26f-4d0b-b65e-ef552affb1e5">

In Volume viewport example https://www.cornerstonejs.org/live-examples/segmentationvolume I press Import DICOM and choose some CT files, and nothing happens (tried all browsers)
