### ISSUE TITLE
[bug]我想知道2.0版本是不是不支持8bit 的数据了？有没有人知道？谢谢！

### ISSUE THREAD

**Issue by 15581818780** [cornerstonejs/cornerstone3D#1685]
### Describe the Bug

![Uploading 截屏2024-12-04 09.55.09.png…]()

### Steps to Reproduce

一个8bit的nii.gz文件尝试加载

### The current behavior

![Uploading 截屏2024-12-04 09.55.09.png…]()

### The expected behavior

希望可以支持8bit的nii.gz文件，或者提供一些解决方案

### OS

Macos

### Node version

16.1.0

### Browser

chrome 131

**Comment by sedghi** [comment]
can you translate your issue in english?
