### ISSUE TITLE
[Feature Request] nifti-volume-loader should be configurable to include custom (auth) headers in requests (`beforeSend`) 

### ISSUE THREAD

**Issue by nagychris** [cornerstonejs/cornerstone3D#1688]
### What feature or change would you like to see made?

**Current behavior**
When using https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/nifti-volume-loader, it is currently not possible to configure any headers for the requests to retrieve the nifti volumes.

**Expected behavior** 
nifti-volume-loader can be configured when registering it (e.g. in a `beforeSend` method similar to [dicomImageLoader](https://github.com/cornerstonejs/cornerstone3D/blob/84ad5c1363ab6e3000e465006ba5700f3714fb1f/packages/dicomImageLoader/src/imageLoader/internal/options.ts#L9)), allowing for custom headers, e.g., for authentication towards the server. 

### Why should we prioritize this feature?

Without this feature it is impossible to use the nifti-volume-loader in our project, because we require authentication towards a server that contains the nifti files. This will be the case for a lot of production applications with proper data security measures, especially in the medical domain and its patient privacy concerns.

**Comment by IbrahimCSAE** [comment]
Thanks, this is a good one, i will add it this week.
