### ISSUE TITLE
[Feature Request] Retain Original Metadata When Exporting DICOM-SEG Files

### ISSUE THREAD

**Issue by stada526** [cornerstonejs/cornerstone3D#1695]
### What feature or change would you like to see made?

When exporting segmentation information in DICOM-SEG format, I would like the feature to retain the metadata information from the original DICOM-SEG file.

I reviewed the example code below, but I noticed that this approach results in the loss of the original metadata information:
https://www.cornerstonejs.org/live-examples/segmentationvolume

### Why should we prioritize this feature?

A common use case involves fetching a DICOM-SEG file from a DICOMWeb server, modifying the segmentation information using Cornerstone.js features like the brush tool, and re-uploading the modified file back to the DICOMWeb server.

In such cases, losing the original metadata information can cause significant issues. Retaining this information is crucial to ensure seamless workflows.

**Comment by sedghi** [comment]
You can look at the OHIF export, that is more comprehensive 

here https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone-dicom-seg/src/commandsModule.ts#L106
