### ISSUE TITLE
[Bug] Viewport stretched during window resize

### ISSUE THREAD

**Issue by MustafaEminn** [cornerstonejs/cornerstone3D#1697]
### Describe the Bug

I have resizable area. Images are stretched during resize until I trigger renderingEngine.resize().

https://github.com/user-attachments/assets/eeef5fd8-9cde-4e0d-aa19-ec49194d1dd7

### Steps to Reproduce

1. Load and image to viewport
2. Resize window

### The current behavior

The image stretches until trigger resize.

### The expected behavior

Image could stay as it is until resized.

### OS

Windows 10

### Node version

20

### Browser

Chrome 131.0.6778.110

**Comment by sedghi** [comment]
You need to call a resize on the renderingEngine. 

Something like `renderingEngine.resize()`

**Comment by MustafaEminn** [comment]
> You need to call a resize on the renderingEngine.
> 
> Something like `renderingEngine.resize()`

I'm doing this already. But I have debounce to reduce overload. Previous version the viewport image was not stretching.

**Comment by sedghi** [comment]
call a render? 

Maybe give me the example code you are trying

**Comment by MustafaEminn** [comment]
When panel resized I'm waiting till user finished resizing to reduce calling render. It could freeze the UI. Image shown as stretched until `this.renderingEngine.resize()` called. Is it performant to run `render()` for every pixel change?

```
const RESIZE_DEBOUNCE_MS = 300;
debounce(() => {
  this.renderingEngine.resize();
}, RESIZE_DEBOUNCE_MS);
```

**Comment by sedghi** [comment]
If you can give me the full code i can look

**Comment by MustafaEminn** [comment]
Sorry, I can not share the full code

**Comment by sedghi** [comment]
Anyway, your answer is something similar to what i said, call resize
