### ISSUE TITLE
[Feature Request] Segmentation example with Stack - Volume swap

### ISSUE THREAD

**Issue by napest** [cornerstonejs/cornerstone3D#1705]
### What feature or change would you like to see made?

We'd like to get an example, where rendered segmentation could be switched from stack to volume and vice versa. 
For instance, there is an example https://www.cornerstonejs.org/live-examples/segmentationvolume 
It would be great if there was a button, which converted stack to volume viewport and back, and the segmentation stayed in place.

### Why should we prioritize this feature?

Now if we switch stack viewport to volume, segmentation doesn't show on it

**Comment by sedghi** [comment]
Hi, these are just examples, and not real application, and we don't have plan to add features to it, see the philosophy of our docs [here](https://docs.divio.com/documentation-system/)
