### ISSUE TITLE
[Bug] When I browse 3D images, the image does not display on my mobile phone, there will be a gray area; but most mobile phones can do it, PC is also ok;

### ISSUE THREAD

**Issue by zhr6675** [cornerstonejs/cornerstone3D#1713]
### Describe the Bug

https://[v1.cornerstonejs.org/live-examples/volumeViewport3D](https://v1.cornerstonejs.org/live-examples/volumeViewport3D)

When accessing this address, the mobile phone will be abnormal

![Screenshot_20241218_111856_com tencent mobileqq](https://github.com/user-attachments/assets/789841ff-9964-4db4-92a3-066ba0ddfe70)
![Screenshot_20241218_112736_com tencent mobileqq](https://github.com/user-attachments/assets/86907c4e-c28d-4cc9-a965-5aba1462f67b)

![Screenshot_20241218_112948_com tencent mobileqq](https://github.com/user-attachments/assets/7a0ec3a1-7596-410e-93b6-f99dbd90813e)

### Steps to Reproduce

No demos of the cornerstone can be previewed   

Model: HONOR V30P.
 System: HarmonyOS 4.2.0. 
 Processor: HUAWEI Kirin 990 5G

### The current behavior

All stack, volume and 3d volume cannot be previewed, they are all gray squares

### The expected behavior

You can preview the volume and 3d volume normally

### OS

HarmonyOS 4.2.0

### Node version

18.20.2

### Browser

Wechat browser 8.0.54

**Comment by daker** [comment]
@sedghi i can confirm that cornerstone3d rendering is broken on mobile for stack and 3d, i am using a Pixel phone and it used to work a few weeks ago

**Comment by daker** [comment]
the v1 link is rendering correctly

**Comment by zhr6675** [comment]
> 我可以确认 Cornerstone3D 渲染在移动设备上的 Stack 和 3D 渲染已损坏，我使用的是 Pixel 手机，几周前它曾经可以工作

Yes, only on my device, not on other devices; the error prompt is "Failed to load OES_texture_float_linear. Texture filtering is not available for * 32F internal formats."

**Comment by zhr6675** [comment]
Yes, only on my device, not on other devices; the error prompt is "Failed to load OES_texture_float_linear. Texture filtering is not available for * 32F internal formats."

> @sedghi i can confirm that cornerstone3d rendering is broken on mobile for stack and 3d, i am using a Pixel phone and it used to work a few weeks ago

Yes, only on my device, not on other devices; the error prompt is "Failed to load OES_texture_float_linear. Texture filtering is not available for * 32F internal formats."

**Comment by sedghi** [comment]
@zhr6675 Are you testing the latest? since i see you sent a v1 link, test this one 

https://www.cornerstonejs.org/live-examples/volumeviewport3d
https://www.cornerstonejs.org/live-examples/stackbasic

@daker Our tests passes right now on pixel 7 and iphone 
https://github.com/cornerstonejs/cornerstone3D/blob/main/playwright.config.ts#L35-L59

**Comment by iconsys** [comment]
Tested with below link on OnePlus 7T & Android 12. 8 GB RAM, Chrome Browser

https://www.cornerstonejs.org/live-examples/volumeviewport3d

Getting

![WhatsApp Image 2024-12-19 at 09 39 35_8a779020](https://github.com/user-attachments/assets/40f43db3-dec8-496b-85c6-24fbb4e895bc)

**Comment by daker** [comment]
@iconsys same thing for me, can you also check the stackbasic demo ?

**Comment by sedghi** [comment]
Does this example run in your device 

[https://kitware.github.io/vtk-js/examples/VolumeMapperBlendModes.html](https://kitware.github.io/vtk-js/examples/VolumeMapperBlendModes.html)

**Comment by daker** [comment]
@sedghi it doesn't work on latest chrome but works on FF mobile, someone made PR #3194

**Comment by sedghi** [comment]
Does our example render fine in FF?

**Comment by daker** [comment]
> Does our example render fine in FF?

Yes ![Screenshot_20241219-224819.png](https://github.com/user-attachments/assets/99063a34-7f30-4185-95b1-7ae52b1efd43)

**Comment by sedghi** [comment]
Hahaha (laughing through the pain)

**Comment by zhr6675** [comment]
> 此示例是否在您的设备中运行
> 
> https://kitware.github.io/vtk-js/examples/VolumeMapperBlendModes.html

I don't have an image here, just a white 3D shadow

**Comment by pcanas** [comment]
@sedghi how was this issue solved? We are still running into similar problems

**Comment by zhr6675** [comment]
> [@sedghi](https://github.com/sedghi) how was this issue solved? We are still running into similar problems这个问题是如何解决的？我们仍然遇到类似的问题

![Image](https://github.com/user-attachments/assets/51aacc42-5977-4c5e-9008-7c5ddafe5449)

node_modules\@kitware\vtk.js\Rendering\OpenGL\RenderWindow.js

publicAPI.getDefaultTextureInternalFormat

// useHalfFloat tells us if the texture can be accurately
  // rendered with 16 bits or not.
  const norm16Ext = model.context.getExtension('EXT_texture_norm16');
  let type = norm16Ext ? model.context.R32F : model.context.R16F;
  switch (numComps) 
    case 1:
      return useHalfFloat ? model.context.R16F : type;

**Comment by daker** [comment]
@pcanas there was a fix to check if webgl extensions are available, you can use https://debug.ohif.org to check your device.

**Comment by pcanas** [comment]
> [@pcanas](https://github.com/pcanas) there was a fix to check if webgl extensions are available, you can use https://debug.ohif.org to check your device.

@daker is there any way to force a valid device not to have the webgl extensions, for debugging purposes? Thanks!
