### ISSUE TITLE
How to use the Freehand Scissors Tool in 3D

### ISSUE THREAD

**Issue by tineke01** [cornerstonejs/cornerstone3D#172]
How to use the Freehand Scissors Tool in 3D

**Comment by tineke01** [comment]
If you can add more tools to the 3D version

**Comment by sedghi** [comment]
Not implemented yet, we only have one 3D tool -> sphere tool

**Comment by tineke01** [comment]
分割工具的分割图层可以渲染在mip上吗

**Comment by tineke01** [comment]
现在我想渲染一个ct重建的立体模型，这个功能是可以实现的吗

**Comment by sedghi** [comment]
You can use our freehand tool, however, we will ship a lot of new spline tools soon 

https://www.cornerstonejs.org/live-examples/planarfreehandroitool
