### ISSUE TITLE
can't identify what's causing memory leak

### ISSUE THREAD

**Issue by IbrahimCSAE** [cornerstonejs/cornerstone3D#188]
Hello,

I'm using cornerstone3D for a project I'm working on, and I have a viewer component that uses it, I'm trying to clear memory when I unmount the component, here's the unmount function I use:

```

  unmounted() {
    // delete tool group
    cornerstone3DTools.ToolGroupManager.destroyToolGroup(this.toolGroupId);
    // remove Tools
    cornerstone3DTools.removeTool(cornerstone3DTools.WindowLevelTool);
    cornerstone3DTools.removeTool(cornerstone3DTools.PanTool);
    cornerstone3DTools.removeTool(cornerstone3DTools.ZoomTool);
    cornerstone3DTools.removeTool(cornerstone3DTools.StackScrollMouseWheelTool);
    cornerstone3DTools.removeTool(cornerstone3DTools.CrosshairsTool);
    // purge cache
    cornerstone3D.cache.purgeCache();
    // destory render engine
    this.renderingEngine.destroy();
    // register regular cornerstone to the image loader again
    cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
  },

```

However, even with this function running when the component is unmounted, there's massive memory leak. Is there something I'm missing? am I not clearing memory the right way? if there's a function I should call that I'm not, please point that out to me as I can't figure out what to do.

I'm using old cornerstone in other components, and the cornerstone.imageCache.purgeCache(); does the job there, I don't know why it's not doing it's job in cornerstone3D

![Screenshot_5](https://user-images.githubusercontent.com/93064150/186650913-ecdd9b77-11e8-419b-b93d-4232576e3d6c.png)
![Screenshot_6](https://user-images.githubusercontent.com/93064150/186651614-33fe5075-2cc6-46bb-af88-cda0734c3d7e.png)
![Screenshot_7](https://user-images.githubusercontent.com/93064150/186651618-15e5a5b1-048c-4342-9efc-320f7b6b9f05.png)

**Comment by sedghi** [comment]
There is a `destory` exported for CornerstoneTools3D, use that

**Comment by IbrahimCSAE** [comment]
> There is a `destory` exported for CornerstoneTools3D, use that

It still doesn't fix the huge leaks happening, I think it's from Cornerstone3D itself, not the tools.

The leaks are usually huge like 400MB+ , and If I keep mounting and unmounting the component the leaks keep getting bigger and bigger until it crashes.

**Comment by IbrahimCSAE** [comment]
```
    createVolume: async function (series) {
      // set the volume name to the series instance UID, this is used to identify the volume in the cache and we can set it to anything we would like to.
      let volumeName = series.seriesInstanceUID;
      // choose the loader scheme
      let volumeLoaderScheme = "cornerstoneStreamingImageVolume";
      // generate an ID from the scheme + volume name
      let volumeId = `${volumeLoaderScheme}:${volumeName}`;
      // set the volumeId to the volumeId variable
      this.volumeId = volumeId;
      // create a volume and cache it using the volumeId and the imageIds, this is where the cached metadata comes in play and we can use it to generate the volume.
      const ctVolume = await cornerstone3D.volumeLoader.createAndCacheVolume(
        volumeId,
        { imageIds: series.imageIds }
      );
      return // i returned here and the memory problem doesn't happen anymore
      // load the volume
      ctVolume.load();
    },
```

it seems to me that ctVolume.load() is what causes the problem, whatever resources that allocates, don't seem to get cleaned up.

Is there something like ctVolume.unload() that I can use? if not then how do I go about clearing this manually?

**Comment by sedghi** [comment]
Yes it seems like there is a leak. the load just start the loading, `createAndCacheVolume` does not load the images in yet

**Comment by sedghi** [comment]
This might be related 

https://github.com/OHIF/Viewers/issues/3207
