### ISSUE TITLE
Invoke  some functions of @cornerstonejs/core cache will cause page crash

### ISSUE THREAD

**Issue by zixiCat** [cornerstonejs/cornerstone3D#194]
When I invoke some functions like `cache.setMaxCacheSize` or `cache.removeVolumeLoadObject`, the page of Edge browser will crash, but not in Electron app
Has anyone ever had this problem?

**Comment by sedghi** [comment]
I guess Chrome also crashes too?

**Comment by zixiCat** [comment]
@sedghi idk, sometimes it works, curious

**Comment by sedghi** [comment]
I can't reproduce it in main anymore, can you check again?
