### ISSUE TITLE
Start/end positions and count include entirely black images when the frame orientation is not coronal, sagittal or axial

### ISSUE THREAD

**Issue by wayfarer3130** [cornerstonejs/cornerstone3D#211]
If the image normal is not one of (1,0,0), (0,1,0), (0,0,1) or the negative thereof, then the calculation of the min/max frames is such that there are a number of extra frames at the beginning and end that cause the entire frame to be black.  Specifically, if the initial orientation is "acquisition", then first frame should be the start or end of the series normally.

**Comment by sedghi** [comment]
Fixed in main
