### ISSUE TITLE
Using MagnifyTool seems to break all annotation tools

### ISSUE THREAD

**Issue by IbrahimCSAE** [cornerstonejs/cornerstone3D#262]
For some reason it looks like something is wrong with the MagnifyTool, when you use it once, then disable it, and try to use any tools that render annotations, none of them work.

https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170126083429.2

Try using Magnify, then Probe for example. Probe won't work.
Try using Magnify, then Angle tool or Rectangle Tool, they both don't work.

It's not an OHIF problem it's something wrong with the tools cuz it happens in my project too, maybe some event listener isn't getting removed the right way.

**Comment by IbrahimCSAE** [comment]
It seems to break Crosshairs too.

**Comment by sedghi** [comment]
Hey @IbrahimCSAE I can't reproduce this. I tried Magnify and then annotation tools after and they worked, can you record your screen maybe?

**Comment by IbrahimCSAE** [comment]
> Hey @IbrahimCSAE I can't reproduce this. I tried Magnify and then annotation tools after and they worked, can you record your screen maybe?

Bug in OHIF : https://streamable.com/emwjpr

Timeline :-

1- Probe, Rectangle and Angle all working before using Magnify
2- Used Magnify for a little bit
3- Probe, Rectangle, Angle not rendering new interactions anymore


Bug outside of OHIF showcasing other tools like Crosshair breaking : https://streamable.com/1bss8t

Timeline:-

1- Used Probe, and Crosshairs, work fine
2- Used Magnify or a little bit
3- Probe doesn't render for new interactions, Crosshairs don't render in MPR anymore

Crosshairs still works but without an rendering, so it looks like something breaks rendering of new things, but it doesn't break the actual functionality, it just isn't being rendered.

**Comment by IbrahimCSAE** [comment]
> Hey @IbrahimCSAE I can't reproduce this. I tried Magnify and then annotation tools after and they worked, can you record your screen maybe?

@sedghi from what I can tell is that something happens and the functions in the file triggerAnnotationRender.js no longer trigger, It's like the MagnifyTool does something that prevents all the tools from using the rendering functions in triggerAnnotationRender.js , or they use it but the functions ends up returning instead of rendering.

I don't know if that's right or not but that's what I could figure out so far.

**Comment by IbrahimCSAE** [comment]
It also looks like the bug affects the pre existing annotations, if you scroll away from them, and comeback, they won't be rendered again.

Pre existing annotations not being re-rendered on stack scroll : https://streamable.com/okotac

**Comment by sedghi** [comment]
Interesting, I still can't reproduce it all the time. I guess it is related to how quick you do the magnify? see below

[f98ec252-f9d8-4236-bd3b-ab4041baa8a2.webm](https://user-images.githubusercontent.com/7490180/198281598-5d01609b-adea-4b9e-bbf3-c3410277bde2.webm)

**Comment by IbrahimCSAE** [comment]
> Interesting, I still can't reproduce it all the time. I guess it is related to how quick you do the magnify? see below
> 
>  f98ec252-f9d8-4236-bd3b-ab4041baa8a2.webm

Yeah It looks like it's related to how quick you magnify, It doesn't happen all the time for me as well. It only happens when I do rapid actions with the magnify tool.

**Comment by sedghi** [comment]
My guess that it is happening here https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/tools/src/utilities/triggerAnnotationRender.ts#L121

That for some reason we can't get into the rendering loop, since last one hasn't finished? so there might be a bug for clean up of that

**Comment by IbrahimCSAE** [comment]
> My guess that it is happening here https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/tools/src/utilities/triggerAnnotationRender.ts#L121
> 
> That for some reason we can't get into the rendering loop, since last one hasn't finished (_animationFrameSet is still true)? so there might be a bug for clean up of that

![Screenshot_14](https://user-images.githubusercontent.com/93064150/198285934-96a34910-78c6-42a3-9d41-4678c4743b28.png)

Yeah you are right, when the bug happens it's stuck on true

**Comment by sedghi** [comment]
You can use AdvancedMagnifyTool for this purpose https://www.cornerstonejs.org/live-examples/advancedmagnifytool
