### ISSUE TITLE
Disabling image smoothing

### ISSUE THREAD

**Issue by hakkelt** [cornerstonejs/cornerstone3D#352]
As far as I understood, it was possible in the previous versions to turn off the native canvas interpolation/smoothing by changing the "pixelReplication" value on the viewport, but it seems to be no longer supported (at least, I could not find the way in the documentation).

Is it possible somehow to disable smoothing? I would like to use cornerstone to develop an application for viewing MR images of mice and rats. The resolution of the images is usually relatively low, and displaying with native resolution is frequently not desirable.

**Comment by sedghi** [comment]
It is through https://www.cornerstonejs.org/api/core/class/stackviewport/#setProperties

**Comment by hakkelt** [comment]
Thanks a lot! I was searching with the wrong keywords... But now it works like charm. :)

Anyway, there is a tricky thing with setting these properties: When calling setProperties before setStack is finished (either calling setProperties before setStack, or calling setStack without await), it silently ignores the new properties. For instance, this code fails to do what I expect from it:
```javascript
    viewport.setStack([ ... ]); // missing await!
    viewport.setProperties({
      interpolationType: InterpolationType.NEAREST
    });
```
I think it might be a good idea to show a warning when trying to set properties too early (e.g. when getActor returns undefined in viewport.setProperties).

**Comment by sedghi** [comment]
yeah I think you should await the setStack first or do `viewport.setStack().then(()=> .setProp`

**Comment by hakkelt** [comment]
Thanks.
Also, a related question: IVolumeViewport's setProperties doesn't seem to accept the interpolationType key, while the same worked with IStackViewport. I figured out that it is not a limitation of vtkjs, as I could get smoothing disabled with this workaround:
```javascript
viewport.getActors()[0].actor.getProperty().setInterpolationType(InterpolationType.NEAREST)
```
Is it intentional? Or did I miss something?

**Comment by sedghi** [comment]
Now we have support in the latest build, please check
