### ISSUE TITLE
New color image volume example

### ISSUE THREAD

**Issue by sedghi** [cornerstonejs/cornerstone3D#361]
We already have an example to show how to render color web images here

https://www.cornerstonejs.org/live-examples/webloader

The task is to create a new example to show volume reconstruction of the color images via our volume loader. Something similar to this 3 viewports axial, sag, coronal

![image](https://user-images.githubusercontent.com/7490180/212182993-07a25143-3a86-43a3-8393-4339fce39b09.png)

The color images are located in our s3 bucket here 

https://cs3d-jpg-example.s3.us-east-2.amazonaws.com/a_vm1460.png

and it goes up to a_vm1517.png

**Comment by David2k13** [comment]
Can you help me look at it?
 https://github.com/cornerstonejs/cornerstone3D/issues/2559
