### ISSUE TITLE
How to Resize canvas after element size changed?

### ISSUE THREAD

**Issue by kadeem220** [cornerstonejs/cornerstone3D#368]
![image](https://user-images.githubusercontent.com/66702038/212685416-0fe2b6b7-6efe-43a9-a370-a9c28f4c601d.png)

I can't find a way to reset/re-render the viewport. When I change my layout, the size of an element changes and the image gets rendered with the old properties of the element. I tried calling resize or reset on the viewport but did not do the trick. I wouldn't want to recreate the element and want a better solution to this. In the old version of cornerstone I would use .resize() and it would do the job. Not sure what I am doing wrong or if there is a way to update the element for the viewport after it changes.
Many thanks in advance.

**Comment by sedghi** [comment]
You can check OHIF code here https://github.com/OHIF/Viewers/blob/v3-stable/extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx#L340-L347

**Comment by HussainHaider** [comment]
There is a function  `renderingEngine.resize(true, false)`. [See details here](https://www.cornerstonejs.org/api/core/class/renderingengine/#resize)

**Comment by Congritulation** [comment]
> There is a function `renderingEngine.resize(true, false)`. [See details here](https://www.cornerstonejs.org/api/core/class/renderingengine/#resize)

thank u for your help. I've done this in my project
