### ISSUE TITLE
WebAssembly.Memory(): could not allocate memory

### ISSUE THREAD

**Issue by daker** [cornerstonejs/cornerstone3D#46]
I have two graphic cards on my workstation, the one plugged with the monitor is Intel HD 530. While trying the examples Chrome crashes and FF is really slow and complains that page is slowing the browser.

Chrome version: 100.0.4896.60

```js
CornerstoneRender: Using detect-gpu to get the GPU benchmark: {device: undefined, fps: 55, gpu: 'intel mesa intel hd graphics 530', isMobile: false, tier: 2, …}
device: undefined
fps: 55
gpu: "intel mesa intel hd graphics 530"
isMobile: false
tier: 2
type: "BENCHMARK"
[[Prototype]]: Object
12:52:54.544 init.ts:55 CornerstoneRender: using GPU rendering
12:52:54.545 dicomweb-client.es.js:1086 retrieve metadata of series 1.3.6.1.4.1.14519.5.2.1.7009.2403.226151125820845824875394858561
12:52:54.823 dicomweb-client.es.js:1086 retrieve metadata of series 1.3.6.1.4.1.14519.5.2.1.7009.2403.879445243400782656317561081015
12:52:57.905 RenderingEngine.ts:103 [Violation] 'requestAnimationFrame' handler took 1818ms
12:52:59.093 index.worker.min.worker.js:1 Uncaught RangeError: WebAssembly.Memory(): could not allocate memory
    at o (index.worker.min.worker.js:1:81364)
    at I (index.worker.min.worker.js:1:154829)
    at ke (index.worker.min.worker.js:1:168400)
    at Object.initialize (index.worker.min.worker.js:1:169326)
    at index.worker.min.worker.js:1:153529
    at Array.forEach (<anonymous>)
    at index.worker.min.worker.js:1:153503
    at self.onmessage (index.worker.min.worker.js:1:153665)
```
is it supposed to fallback to CPU?

![image](https://user-images.githubusercontent.com/878518/161250917-2992eb2f-5386-4439-8868-5de114861e75.png)

**Comment by swederik** [comment]
I think this isn't a GPU issue exactly, but more likely the example is spinning up too many web workers which are consuming too much memory on your system and crashing chrome. How many cores does your computer have? (`navigator.hardwareConcurrency`)?

This PR should hopefully fix it (https://github.com/cornerstonejs/cornerstone3D-beta/pull/47). The docs will be updated shortly, it's still building, and then maybe you could re-test it?

Firefox slowness is a known issue, I think. I believe it's this: https://bugzilla.mozilla.org/show_bug.cgi?id=1602299
It's an issue with the copy from the off-screen to on-screen canvases being slow on Firefox.

**Comment by daker** [comment]
> I think this isn't a GPU issue exactly, but more likely the example is spinning up too many web workers which are consuming too much memory on your system and crashing chrome. How many cores does your computer have? (`navigator.hardwareConcurrency`)?

```js
navigator.hardwareConcurrency
> 8
```

**Comment by swederik** [comment]
The live example should be updated now. If that didn't fix it, I'm not sure what the problem is.

Are you on Windows?

**Comment by JamesAPetts** [comment]
We are investigatin this, seems to be examples on all Windows machines.

**Comment by daker** [comment]
> The live example should be updated now. If that didn't fix it, I'm not sure what the problem is.

Some works, some not, for ex this one snaps : https://www.cornerstonejs.org/live-examples/multivolumeapi

> Are you on Windows?
Yes Win 10 20H2

**Comment by daker** [comment]
> We are investigatin this, seems to be examples on all Windows machines.

For examples those make Chrome snap with error code: SBOX_FATAL_MEMORY_EXCEEDED
https://www.cornerstonejs.org/live-examples/multivolumeapi
https://www.cornerstonejs.org/live-examples/multivolumecanvastoworld
https://www.cornerstonejs.org/live-examples/stackcanvastoworld

**Comment by jpambrun** [comment]
I have the same issue. I have 16 core and all example try to load 7 worker each consuming 2 GB of RAM. Even the trivial one image sample[1] crashed about 50% of the time. 

[1] https://www.cornerstonejs.org/live-examples/stackbasic

**Comment by sedghi** [comment]
@jpambrun windows?

**Comment by swederik** [comment]
Can you try this link?

https://6246f5ad453f451f7bc3aa19--cs3d-docs.netlify.app/live-examples/petct

It disables the codec initialization on startup for now.

We had tested on windows before and never had these issues. I wonder if the OpenJPEG codec initialization's high memory usage is related to this commit: https://github.com/cornerstonejs/codecs/commit/c71c3584273497e859737c5db9f008490d77c845

**Comment by jpambrun** [comment]
The 1GB heap is defined here for j2k
https://github.com/cornerstonejs/codecs/blob/main/packages/openjpeg/src/CMakeLists.txt#L35

**Comment by jpambrun** [comment]
The other part of the issue is here:
https://github.com/cornerstonejs/cornerstone3D-beta/blob/a0eefdc34e171ac35375fe58c5da75575ed6d46e/utils/demo/helpers/initCornerstoneWADOImageLoader.js#L18


You allow up to 7 workers (if number of cores allows) and each take 2GB of memory (OpegJpeg + another codec?). On the other hand, chrome 100 on windows allows only for ~14GB or memory to be used in typed array (used to be 8GB in chrome 99-). So it crashed very often.

**Comment by JamesAPetts** [comment]
Yeah we've used 7 max in old cornerstone since time immemorial, it seems recent changes to the codecs have blew up RAM usage on initialisation.

**Comment by toropok** [comment]
Hi,

We have same issue on Samsung Galaxy Tab A SM-T515 Android (11) Chrome (105.0.5195.136):

```
Uncaught RangeError: WebAssembly.Memory(): could not allocate memory
    at B (1fee6cb6-8d13-4e2d-9908-ca27015f5a78:formatted:4505:52)
    at H (1fee6cb6-8d13-4e2d-9908-ca27015f5a78:formatted:9397:24)
    at LA (1fee6cb6-8d13-4e2d-9908-ca27015f5a78:formatted:10136:56)
    at Object.initialize (1fee6cb6-8d13-4e2d-9908-ca27015f5a78:formatted:10163:17)
    at 1fee6cb6-8d13-4e2d-9908-ca27015f5a78:formatted:9293:38
    at Array.forEach (<anonymous>)
    at 1fee6cb6-8d13-4e2d-9908-ca27015f5a78:formatted:9292:36
    at self.onmessage (1fee6cb6-8d13-4e2d-9908-ca27015f5a78:formatted:9304:22)
```

is there any workarounds for mobile devices?

**Comment by sedghi** [comment]
Can you try again on the latest main branch and let us know if this is still an issue?

**Comment by daker** [comment]
I don't see the issue anymore 👍🏼
