### ISSUE TITLE
Can not remove display of contour

### ISSUE THREAD

**Issue by zixiCat** [cornerstonejs/cornerstone3D#466]
I have tried using `segmentation.state.getSegmentationRepresentations`  and `segmentation.state.removeSegmentationRepresentation` , and then rendered related viewport or renderingEngine, but they didn't work as expected. Is there any way to solve that?

**Comment by sedghi** [comment]
hmmm interesting, I will look at it tomorrow.

**Comment by zixiCat** [comment]
sry for typo mistake @sedghi 
`segmentation.state.getSegmentationRepresentations` → `segmentation.state.removeSegmentation`

**Comment by sedghi** [comment]
Most likely working now in main, can you check again and re-open if necessary?

**Comment by kubanm3** [comment]
I have similar problem. I am removing segmentationRepresentation and it looks like it is just changed into normal annotation. Colors change in to those that are used to display normal annotation. SEGMENTATION_REPRESENTATION_REMOVED is triggered. Yet it is still visible. After removing it I am alse rendering view again.

![image](https://github.com/user-attachments/assets/6ffaae8b-e230-4779-b3e2-e48a942d1383)

Using removeSegmentationsFromToolGroup and removeSegmentation gives the same effect. 

Cornerstone version 1.70.12.
