### ISSUE TITLE
covertMultiframeImageIds ERROR

### ISSUE THREAD

**Issue by zhoualibaba** [cornerstonejs/cornerstone3D#489]
@sedghi  When I use the function covertMultiframeImageIds to make imageIds(wadouri, multiframe in one dicom), I found that it lost the first image when i use viewport.setStack.
I changed this 
![ecc38f67223e40f3e66d30df13f26e8](https://user-images.githubusercontent.com/17982206/225800709-a1e1a880-9707-4fce-a21b-e3e424d65104.jpg)
 to 
![f43e2e4f58b85c51d0711ec5664063d](https://user-images.githubusercontent.com/17982206/225800781-7dd3e2fb-3c63-4443-b9e1-066965c0099c.jpg)
,it solved.

**Comment by sedghi** [comment]
@rodrigobasilio2022

**Comment by sedghi** [comment]
I think this is fixed in main branch, please re-open if not
