### ISSUE TITLE
Is possible to read the contour information when using brush?

### ISSUE THREAD

**Issue by alex644715** [cornerstonejs/cornerstone3D#496]
I cannot read the contour or segmentations information when I using brush tools, and didn't find the information in cache. Is any way to read the information?

I'm using the brush example that demo provided.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/61206468/226293836-d7784a00-50a7-4d80-a0b3-2fa74c3139df.png">

**Comment by sedghi** [comment]
right now, no, our tools only act on labelmaps currently, we have plans to be able to convert labelmaps to contours and vice versa
