### ISSUE TITLE
How to add orientation label to viewport?

### ISSUE THREAD

**Issue by yllan** [cornerstonejs/cornerstone3D#583]
How can I add orientation labels, such as PR, AL, S, and I in the leftmost plane, to the viewports?

<img width="1258" alt="CleanShot 2023-04-28 at 13 19 50@2x" src="https://user-images.githubusercontent.com/76055/235060718-f536d6e4-146d-4889-8692-510fc9bc6d16.png">

Is there an existing tool for that or I need to write one?

If I need to write one myself, I think I need to know the following points to achieve this task:
1. Listen for the matrix change event, retrieve the current matrix, and calculate the label for each plane's viewport.
2. Find a method to add an overlay to the viewport, similar to what other tools have done.

Any thoughts?

**Comment by sedghi** [comment]
OHIF has a component for that you can take a look [here](https://github.com/OHIF/Viewers/blob/v3-stable/extensions/cornerstone/src/Viewport/Overlays/ViewportOrientationMarkers.tsx)

**Comment by simonalo** [comment]
Is there a way to display the viewport with a default orientation ? For example, in axial orientation, I would like to display the image with A at the bottom and R at the right (in the screenshot, it should apply a flipVertically to the middle viewport).

**Comment by MYWpro** [comment]
![image](https://github.com/cornerstonejs/cornerstone3D/assets/91541200/f8dadd01-3338-40ee-9b1f-4fe59400291c)
How can I add this information in the viewport?
