### ISSUE TITLE
[Bug] zoomtool in mobile

### ISSUE THREAD

**Issue by longuto** [cornerstonejs/cornerstone3D#643]
### Describe the Bug

when i try the zoomtool with MouseBindings.Primary in mobile.   it's move the canvas.  it's zoom ok  in web

my english is not good, see the video

### Steps to Reproduce

see the video

https://github.com/cornerstonejs/cornerstone3D/assets/21220020/4d1878a4-5439-41ee-8c33-4dd4932e6650

### The current behavior

see the video

### The expected behavior

see the video

### OS

win10 64

### Node version

16.15.1

### Browser

chrome 113.0.5672.93

**Comment by sedghi** [comment]
Use touch instead of mouse https://www.cornerstonejs.org/live-examples/stackmanipulationtoolstouch

**Comment by longuto** [comment]
thank for your answer.  i solve it like this. 
![Dingtalk_20230621110029](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/83616516-2671-4474-b745-814b05b88673)
