### ISSUE TITLE
[Bug] use LengthTool in volumeViewport, It report imagePositionPatient not found

### ISSUE THREAD

**Issue by longuto** [cornerstonejs/cornerstone3D#644]
### Describe the Bug

[Bug] use LengthTool in volumeViewport render, It report imagePositionPatient not found 

see the picture
![Dingtalk_20230608142753](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/48d338d6-1cfb-42ee-a4b1-9e326b123d7d)
![Dingtalk_20230608142954](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/e8bb6920-a557-4c78-b10a-080ead174c70)
![Dingtalk_20230608143131](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/27151ad3-a157-420f-9cf8-a99e67f23d72)
![Dingtalk_20230608143328](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/e537d7de-d6a0-4eda-b346-86d33a0c5ebe)

### Steps to Reproduce

1. use volumeViewport 
2. use wadours

### The current behavior

use Lengthtool , it is error

### The expected behavior

normal

### OS

Window 10

### Node version

16.5.1

### Browser

chrome 112.0.5615.138

**Comment by longuto** [comment]
it happen in OrientationAxis.AXIAL ,  and it is normal in OrientationAxis.SAGITTAL and OrientationAxis.CORONAL

**Comment by zhoualibaba** [comment]
Can you show how you load dicom and metadata.I think this is not a common bug.

**Comment by jlopes90** [comment]
It's not an error, you need to load all the "imageIds" because the metadata is saved.

**Comment by longuto** [comment]
i use dicom-image-loader,  and i donot know where it save the metadata.  init  dicom-image-loader use the picture method。
![微信截图_20230609193058](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/e526b269-5527-4f14-b786-bfd23485cf21)


in the axial viewport , i found it not the first imageId have no metadata, it is Occurring in the middle.  see the method
![微信截图_20230609193544](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/bd8e23e8-b503-4001-ace5-6914afa1106d)

**Comment by longuto** [comment]
tell me , where the dicom-image-loader save the metadata


i solve it with a not good method .  see the picture
![微信截图_20230609193945](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/1498232c-ad99-4777-af06-d6be3f8bb9c0)

**Comment by jlopes90** [comment]
For example:

```javascript
const imageIds =  ['example1', 'example2'];

// "loadAndCacheImages" loads the image and stores metadata
const promises = libCornerstone.imageLoader.loadAndCacheImages(imageIds); 

Promise.all(imagesPromises).then(async function () {

    const volume = await libCornerstone.volumeLoader.createAndCacheVolume(volumeId, {
      imageIds: target.imageIds
    });

    volume.load();

    await viewport.setVolumes([{ volumeId }]);

    viewport.render();
});
```

**Comment by longuto** [comment]
@jlopes90 thank for answer.    i want to know where the metadata saved  in  wadouri (means https:XXX.dcm request  endwiths .dcm  not frames/1).  like the picture
![微信截图_20230610112455](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/c09fb6b4-489f-46bb-865c-6b994d7bdf8c)
