### ISSUE TITLE
[Bug] Distorted PNG in image stack in 0.44.0 and newer

### ISSUE THREAD

**Issue by stemps** [cornerstonejs/cornerstone3D#662]
### Describe the Bug

When displaying a stack of PNG images using 3d rendering, the image is distorted.

![d6ef7b05afb6dd6c4d8fbb1aeefc0a944e969e6d_2_515x499](https://github.com/cornerstonejs/cornerstone3D/assets/630990/dc9c1cf8-344d-414e-a027-a1f6d5af6dfb)

The issue occurs in cornerstone v0.44.0 and newer. Forcing CPU rendering removes the issue.

See also the discussion on https://community.ohif.org/t/distorted-image-stack-after-update-from-0-31-2-to-current-1-2-4/839.

I provided a [sample project](https://github.com/stemps/cornerstonejs-playground/tree/distorted-image-stack) (branch `distorted-image-stack`) that reproduces the issue.

### Steps to Reproduce

1. Check out sample project (https://github.com/stemps/cornerstonejs-playground/tree/distorted-image-stack)
2. run `npm install` and `npm run start`
3. open http://localhost:8080

### The current behavior

Image is distorted

### The expected behavior

Image should display correctly

### OS

reproduced on Windows 10 and MacOS

### Node version

18.12.1

### Browser

reproduced on multiple browsers

**Comment by jbocce** [comment]
I was able to reproduce this issue.

**Comment by sedghi** [comment]
Are you using Orthanc? there seem to be a bug that we reported that and they fixed it https://discourse.orthanc-server.org/t/orthanc-convert-ybr-to-rgb-but-does-not-change-metadata/3533

DCM4CHEE most likely has the same bug

**Comment by stemps** [comment]
@sedghi no, we're not using Orthanc. We are serving the stack images as regular static web resources.

**Comment by sedghi** [comment]
Oh sorry, I see that you are using the old web-image-loader, until we properly publish a new package see this file for the new loader 

https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/core/examples/webLoader/registerWebImageLoader.ts

**Comment by stemps** [comment]
Yes, using the provided image loader fixes the issue 👍 . Thanks a lot!
