### ISSUE TITLE
[Bug] When display a dicom  in a viewport  refers to the example of stackBasic, the image is not displaying as expected

### ISSUE THREAD

**Issue by sumilying** [cornerstonejs/cornerstone3D#663]
### Describe the Bug

the  part code of this example :

const {
    RenderingEngine,
    Types,
    Enums,
    setVolumesForViewports,
    volumeLoader,
    getRenderingEngine,
    imageLoader
} = cornerstone;

/***
 *
 * @param imageId      //exp:'wadouri:' + url
 */
function errorDisplay(imageId){
    imageLoader.loadAndCacheImage(imageId).then((image) => {

            const content = document.getElementById('testImgElement');
            const element = document.createElement('div');
            element.id = 'cornerstone-element';
            element.style.width = '300px';
            element.style.height = '300px';
            content.appendChild(element);
            const renderingEngineId = 'myRenderingEngine';
            const renderingEngine = new RenderingEngine(renderingEngineId);
            // Create a stack viewport
            const viewportId = 'CT_STACK';
            const viewportInput = {
                viewportId,
                type: ViewportType.STACK,
                element,
                defaultOptions: {
                    background: <Types.Point3>[0.2, 0, 0.2],
                },
            };
            renderingEngine.enableElement(viewportInput);
            // Get the stack viewport that was created
            const viewport = <Types.IStackViewport>(
                renderingEngine.getViewport(viewportId)
            );
            // Define a stack containing a single image
            const stack = [imageId];
            // Set the stack on the viewport
            viewport.setStack(stack);
            viewport.render();

            console.log('ctVoiRange',ctVoiRange)
            // Set the VOI of the stack
            viewport.setProperties({ voiRange: ctVoiRange });

        } ).catch((err) => {
        console.log('err', err)

    });
}

### Steps to Reproduce

1 the test file
   
[dicom.zip](https://github.com/cornerstonejs/cornerstone3D/files/11787404/dicom.zip)

2   Obtain an accessible URL for this file

3  call    the  function up there  -> errorDisplay(...)

4 get the display like this 
![canvas](https://github.com/cornerstonejs/cornerstone3D/assets/13536833/38db24f1-6b61-45f2-a872-e037a9be3ad4)

### The current behavior

 
![display_err](https://github.com/cornerstonejs/cornerstone3D/assets/13536833/eaa878e5-6e22-415d-9e9a-b02c5d3d9932)

at first , I thought it was because I didn't set the window width and the window level, so I conducted a detailed inspection and did provide the correct   value. However, the display results are still abnormal.

### The expected behavior

![display_suc](https://github.com/cornerstonejs/cornerstone3D/assets/13536833/1969ebcb-cdfe-4740-9c6f-823de332895d)

### OS

Windows 10

### Node version

v16.20.0

### Browser

chrome  :114.0.5735.134

**Comment by sedghi** [comment]
I can't reproduce this in stackbasic and orthanc server.

![image](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/a0d4b621-5a8f-47b7-9506-fe13a9526263)

Neither the local example shows this bug try drag and drop here https://www.cornerstonejs.org/live-examples/local.html

**Comment by sumilying** [comment]
Finally, the problem was discovered。if  use   imageLoader.loadAndCacheImage(imageId)    (  loader import form the cornerstone ) to load the image before render, the render result will like that .  if  not load by this ,it will render right.
