### ISSUE TITLE
How to export and import segmentation in volume?

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D#664]
"adapters" has no segmentation, I've been looking at how it works but it's too complicated for me :S

**Comment by sedghi** [comment]
I'm almost done with exporting segmentations and will create a PR soon. The [import](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone-dicom-seg/src/getSopClassHandlerModule.js) is done at OHIF here, although probably I will move it to adapters soon

**Comment by Benjamin-JZ** [comment]
> I'm almost done with exporting segmentations and will create a PR soon. The [import](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone-dicom-seg/src/getSopClassHandlerModule.js) is done at OHIF here, although probably I will move it to adapters soon

hi,i want to ask you that exporting segmentations is done? :)

**Comment by longuto** [comment]
@sedghi  How did the contourSets data come from

**Comment by longuto** [comment]
@sedghi i know the data structure, I want to know  How data is obtained from other software。 because i saw these data in OHIF.
![Dingtalk_20230727091702](https://github.com/cornerstonejs/cornerstone3D/assets/21220020/ec3873a9-e459-4dbd-bd56-b54d3b62e3f4)

**Comment by jlopes90** [comment]
I was looking at how imports done by "ohif" work. And I couldn't get it to work or something is missing in the code. If anyone knows how it works, can you create a new example?

**Comment by jlopes90** [comment]
I have already managed to present the segmentation

**Comment by jlopes90** [comment]
Here is the code just to show how it works

```javascript
//
const { viewport } = libCornerstone.getEnabledElement(element);

//
await libCornerstone.imageLoader.loadAndCacheImages(imageIds);

//
const volume = await libCornerstone.volumeLoader.createAndCacheVolume(volumeId, {
    imageIds: imageIds
});

//
volume.load();

//
await viewport.setVolumes([{ volumeId }]);

//
viewport.render();

//
const result = libCornerstone.adapters.segmentation.generateToolState(viewport.imageIds, arrayBuffer);

//
const derivedVolume = await libCornerstone.volumeLoader.createAndCacheDerivedVolume(volume.volumeId, {
    volumeId: segmentationId
});
const derivedVolumeScalarData = derivedVolume.getScalarData();
derivedVolumeScalarData.set(new Uint8Array(result.labelmapBufferArray[0]));

//
libCornerstoneTools.segmentation.addSegmentation(segmentationId);
//
await libCornerstoneTools.segmentation.addSegmentationRepresentation(toolGroupId, segmentationId);
```

**Comment by dima9911** [comment]
@jlopes90 how can i get segmentations in arrayBuffer format? is it SEG file?

**Comment by jlopes90** [comment]
@dima9911

Export the file is dicom with segmentation.

How to search for arraybuffer in segmentation, it is stored in the cache

```
var segmentations = cornerstoneTools.segmentation.state.getSegmentations();
var volumeSegmentation = cornerstone.cache.getVolume(segmentations[0].segmentationId);
var arrayBuffer = volumeSegmentation.getScalarData();
```

**Comment by l5769389** [comment]
> I'm almost done with exporting segmentations and will create a PR soon. The [import](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone-dicom-seg/src/getSopClassHandlerModule.js) is done at OHIF here, although probably I will move it to adapters soon


can you show me a demo how to load dicom segment?

**Comment by dima9911** [comment]
@jlopes90 libCornerstone.adapters do not exist. 

my version: "@cornerstonejs/core": "^1.65.3"

**Comment by dima9911** [comment]
@jlopes90

i import @cornerstonejs/adapters and find function generalToolState.

but when use this, catch some error in _adapters.es.js_ at 1660 row. **generalImageModule** from metaData is undefined. 

![image](https://github.com/cornerstonejs/cornerstone3D/assets/10125278/97133853-42bb-4118-a484-541b7a3a81a5)


but for example **imagePlaneModule** works well
<img width="1088" alt="Снимок экрана 2024-03-27 в 16 29 17" src="https://github.com/cornerstonejs/cornerstone3D/assets/10125278/656ebf95-ea4e-4144-b61f-25d52792c43b">

**Comment by jlopes90** [comment]
@dima9911 https://github.com/cornerstonejs/cornerstone3D/issues/847

PR https://github.com/cornerstonejs/cornerstone3D/pull/1165

**Comment by dima9911** [comment]
@jlopes90 can i used this with clear cornerstone? 

i want to import SEG dcm file (as array buffer) for my volume viewport

**Comment by jlopes90** [comment]
@dima9911 

There is a way you can do it like this:

```javascript
import * as libCornerstone from '@cornerstonejs/core';
import * as libCornerstoneDicomImageLoader from '@cornerstonejs/dicom-image-loader';

function metaDataProvider(type, imageId) {
    if (Array.isArray(imageId)) {
        return;
    }

    //
    const imageUri = libCornerstone.utilities.imageIdToURI(imageId);

    //
    const dataSet = libCornerstoneDicomImageLoader.wadouri.dataSetCacheManager.get(imageUri);
    //
    if (!dataSet) {
        return;
    }

    // ------------------------------------------------------------------------

    // TODO
    if (type === 'generalImageModule') {
        return {
            sopInstanceUid: dataSet.string('x00080018')
        };
    }
}

libCornerstone.metaData.addProvider(metaDataProvider, 1);
```

**Comment by l5769389** [comment]
> @jlopes90 @sedghi can i used it with clear cornerstone without OHIF?
> 
> i want to import SEG dcm file (as array buffer) for my volume viewport

see my demo https://github.com/cornerstonejs/cornerstone3D/issues/1170#issuecomment-2021841681

**Comment by jlopes90** [comment]
PR #1177

I just made a new example Segmentation Volume 

Here is a demo example (deploy):
https://deploy-preview-1177--cornerstone-3d-docs.netlify.app/live-examples/segmentationVolume

**Comment by l5769389** [comment]
> I just made a new Segmentation Volume example, see here #1177

thank you!!

**Comment by dima9911** [comment]
@sedghi @jlopes90 thank you very much for this example its safe me.

the last question for this: how i can clear brush (all strategies for example circularBrush) state? 

**brush set tool disabled, derivedVolume.destroy, removeSegmentation, removeSegmentationRepresentation and then volumeViewport.render does nothing.** 
segments do not clear. 

case: before import new Seg file, clear previous

**Comment by jlopes90** [comment]
@dima9911 updated pr https://github.com/cornerstonejs/cornerstone3D/pull/1177/commits/97f43780854cde279367d089ec5017c2541b0cf7

**Comment by su-yunhe** [comment]
I want to provide a way to import and render segmentation using Labelmap.
```javascript
const segmentationVolume = cornerstone.cache.getVolume(segmentationId)
    const scalarData = segmentationVolume.scalarData

    for (let i = 0; i < arrays.length; i++) {
      const array = arrays[i]
      const value = i + 1
      for (let j = 0; j < array.length; j++) {
        const index = array[j]
        scalarData[index] = value
      }
    }
```
Where, arrays is the index corresponding to non-zero coordinates of a segmentation file.

The correspondence between coordinates and index is
```
index = tIndex + zIndex + yIndex + xIndex
tIndex = img.nx * img.ny * img.nz * t
zIndex = img.nx * img.ny * z
yIndex = img.nx * y
xIndex = x
```
Read each coordinate value of the nifti file and store the index corresponding to the coordinate that is not 0 in arrays to render.
<img width="1812" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/112183083/6468eec7-2873-4b86-b41f-54376835f93f">
<img width="346" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/112183083/9e92ab6f-eed1-4d1c-bf29-82c13dee4409">

**Comment by StevexLi** [comment]
@su-yunhe 

I 've tried your solution and it works pretty well. Thanks.

<img width="246" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/111101139/1a9f0975-0a42-4b89-8222-c74a7b129ef7">

**Comment by dima99112** [comment]
@jlopes90 hi

you have an error at your example 
<img width="1001" alt="Снимок экрана 2024-12-02 в 21 43 08" src="https://github.com/user-attachments/assets/9c948052-ecdd-46c4-8fd2-3f2c5216f481">



`csToolsSegmentation.activeSegmentation.getActiveSegmentationRepresentation is not a function`

any idea for fix it?

**Comment by dima99112** [comment]
@sedghi hello. your examples for export segmentation do not work: stack, volume - i have error
![Uploading image.png…]()

can u fix it?

**Comment by dima99112** [comment]
@sedghi i catch this error. what is this problem? 

seg file successfully imported. but cant exported
<img width="805" alt="Снимок экрана 2024-12-06 в 17 50 19" src="https://github.com/user-attachments/assets/feadae04-d362-4fcc-a3a7-931a4c61c40e">

**Comment by dima99112** [comment]
@sedghi 

pls see bug report with import seg

https://www.cornerstonejs.org/live-examples/segmentationvolume example after click "load seg"

<img width="987" alt="Снимок экрана 2024-12-10 в 11 17 09" src="https://github.com/user-attachments/assets/596d801b-db4f-47bc-bde4-6df0c15ce2f1">

u can see many segments with differect colors at dicoms, but i get one segment with name "Segment 1"
