### ISSUE TITLE
[Bug] Error while scrolling in Stack Viewport after switching back from Volume Viewport 

### ISSUE THREAD

**Issue by idemopacs** [cornerstonejs/cornerstone3D#669]
### Describe the Bug

Error while scrolling in Stack Viewport after switching back from Volume Viewport 

It shows below error 

StackViewport.ts:1813 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'photometricInterpretation')
    at StackViewport.successCallback (StackViewport.ts:1813:85)
    at StackViewport.ts:1853:29

### Steps to Reproduce

1. Open link - [https://www.cornerstonejs.org/live-examples/stacktovolumewithannotations](url)  
2. Click on - Switch StackViewport to Volume Viewport button
3. Click again on same button to view Stack Viewport
4. Scroll images using Mouse wheel in Stack Viewport to reproduce error

### The current behavior

Getting error and then image scrolling stops

StackViewport.ts:1813 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'photometricInterpretation')
    at StackViewport.successCallback (StackViewport.ts:1813:85)
    at StackViewport.ts:1853:29

### The expected behavior

No error should come

### OS

Windows 10

### Node version

v16.17.1

### Browser

Chrome 114.0.5735.134

**Comment by idemopacs** [comment]
![image](https://github.com/cornerstonejs/cornerstone3D/assets/92505215/cde3e589-e1d8-47ac-ba10-084ece53b9f3)

**Comment by idemopacs** [comment]
This is working fine in 1.2.0. Above issue is seen in 1.2.6.

**Comment by sedghi** [comment]
I can't reproduce this anymore, can you try again?

**Comment by idemopacs** [comment]
This issue of stack scrolling is resolved in current version 1.4.1
But facing new issue in this current version,  WindowLevel of some images getting changed in stack viewport after switching back from volume viewport.

Steps to Reproduce :- 

- Open link - [https://www.cornerstonejs.org/live-examples/stacktovolumewithannotations](https://github.com/cornerstonejs/cornerstone3D/issues/url)
- Click on - Switch StackViewport to Volume Viewport button
- Click again on same button to view Stack Viewport
- Scroll images using Mouse wheel in Stack Viewport
- while scrolling we can see changed window level  for some of images

Please see attached image.
![issue](https://github.com/cornerstonejs/cornerstone3D/assets/92505215/e8733c3a-2c8d-4042-bfa8-1c433059ce9b)

**Comment by sedghi** [comment]
@idemopacs can you create a separate issue for this? Thanks

**Comment by idemopacs** [comment]
@sedghi ,
Getting stack scrolling issue (mentioned above) with latest build v1.9.0. 
After resolving issue #684 , stack scrolling issue is  reoccurring.
