### ISSUE TITLE
[Bug] StackViewport not pulling metaData from provider list

### ISSUE THREAD

**Issue by kmcgurty** [cornerstonejs/cornerstone3D#671]
### Describe the Bug

I believe this is the same bug as #669 but I thought I'd provide a little more information. After adding a `provider` (for eg. hardcodedMetaDataProvider), `StackViewport.setStack` never queries the list of metadata providers. If I put a `console.log` at [this line](https://github.com/cornerstonejs/cornerstone3D/blob/4b9c08e09216daac428c258bcb123a1ed53eb3c0/packages/core/examples/webLoader/hardcodedMetaDataProvider.ts#L3) of `hardcodedMetaDataProvider.ts`, it never appears.

### Steps to Reproduce

It's easily viewable on the current `WebLoader` demo.

1. https://www.cornerstonejs.org/live-examples/webloader
2. View console, and notice that the image hasn't loaded
![image](https://github.com/cornerstonejs/cornerstone3D/assets/5951498/e1e9e4e6-ee9a-4ea8-9553-00a3a05fe54c)

### The current behavior

1. Initialize CornerstoneCore
2. Add a meta data provider with CornerstoneCore.metaData.addProvider(HardcodedMetaDataProvider, 1)
3. Register image loader, initialize renderingEngine and viewport
4. Attempt to load an image with `stackViewport.setStack(url)`
5. Step 4 fails to load the image, because the metadata is undefined

### The expected behavior

The last version this works on is version `0.47.0` of the `@cornerstonejs/core` . If I downgrade to that version, it loads as expected. As soon as it's upgraded to `1.1.0` it breaks.

### OS

Windows 10

### Node version

20.3.1 (Current)

### Browser

Chrome 114.0.5735.134

**Comment by sedghi** [comment]
I can successfully run the webImageLoader and cannot reproduce this. 

![image](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/f740900d-7573-4d18-819c-688e9f59a34b)

`yarn run example webloader`
