### ISSUE TITLE
[Bug] cornerstone.init is not a function

### ISSUE THREAD

**Issue by Benjamin-JZ** [cornerstonejs/cornerstone3D#675]
### Describe the Bug

I following the demo from 'https://www.cornerstonejs.org/docs/tutorials/basic-volume',But When i use  const renderingEngine = new RenderingEngine(renderingEngineId);  '@cornerstonejs/core is not initialized, run init() first' this Error show here.
so i add cornerstone.init() but new error coming the Error 'Uncaught (in promise)  TypeError: cornerstone.init is not a function' show in the Console.

### Steps to Reproduce

above

### The current behavior

above

### The expected behavior

new object success

### OS

Window11

### Node version

16.20.0

### Browser

edge

**Comment by Benjamin-JZ** [comment]
my code:
import {
  init,
  RenderingEngine,
  Types,
  Enums,
  volumeLoader,
  getRenderingEngine,
  utilities,
  CONSTANTS,
} from '@cornerstonejs/core';

  cornerstone.init();


  cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
  cornerstoneWADOImageLoader.external.dicomParser = dicomParser;

  const { ViewportType } = Enums;
  const renderingEngineId = 'myRenderingEngine';
  const viewportId = 'CT_SAGITTAL_STACK';

  // Define a unique id for the volume
  const volumeName = 'CT_VOLUME_ID'; // Id of the volume less loader prefix
  const volumeLoaderScheme = 'cornerstoneStreamingImageVolume'; // Loader id which defines which volume loader to use
  const volumeId = `${volumeLoaderScheme}:${volumeName}`; // VolumeId with loader id + volume id

    // Get Cornerstone imageIds and fetch metadata into RAM
  const imageIds = [
    'dicomweb:https://d3t6nz73ql33tx.cloudfront.net/1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463',
    'dicomweb:https://d3t6nz73ql33tx.cloudfront.net/1.3.6.1.4.1.14519.5.2.1.7009.2403.226151125820845824875394858561'
  ];
  // const wadoRsRoot = 'https://d3t6nz73ql33tx.cloudfront.net/dicomweb';

  // const imageId = `dicomweb:${StudyInstanceUID}:${SeriesInstanceUID}`;


  
    const content = document.getElementById('content');
  
    const viewportGrid = document.createElement('div');
    viewportGrid.style.display = 'flex';
    viewportGrid.style.flexDirection = 'row';

**Comment by sedghi** [comment]
I can't replicate this. I copy pasted the final code in the template location and run `yarn run example tutorial` and it run fine. Here is my final tutorial code which is located here  (packages/tools/examples/tutorial/index.ts)

```js
/**
 * WARNING
 * DO NOT REMOVE ANY OF THE BELOW IMPORT STATEMENTS
 * SOME ARE USED FOR SOME OF THE TUTORIALS, AND WILL BREAK IF REMOVED
 */

import {
  RenderingEngine,
  Types,
  Enums,
  setVolumesForViewports,
  volumeLoader,
} from '@cornerstonejs/core';
import {
  addTool,
  BrushTool,
  SegmentationDisplayTool,
  BidirectionalTool,
  ToolGroupManager,
  WindowLevelTool,
  ZoomTool,
  segmentation,
  Enums as csToolsEnums,
} from '@cornerstonejs/tools';
import {
  initDemo,
  createImageIdsAndCacheMetaData,
  setTitleAndDescription,
} from '../../../../utils/demo/helpers';

// This is for debugging purposes
console.warn(
  'Click on index.ts to open source code for this example --------->'
);

// ============================= //
// ======== Set up page ======== //
setTitleAndDescription(
  'Tutorial Playground',
  'The playground for you to copy paste the codes in the tutorials and run it'
);

const { ViewportType } = Enums;
/**
 * Runs the demo
 */
async function run() {
  // Init Cornerstone and related libraries
  await initDemo();
  // Get Cornerstone imageIds and fetch metadata into RAM
  const imageIds = await createImageIdsAndCacheMetaData({
    StudyInstanceUID:
      '1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463',
    SeriesInstanceUID:
      '1.3.6.1.4.1.14519.5.2.1.7009.2403.226151125820845824875394858561',
    wadoRsRoot: 'https://d3t6nz73ql33tx.cloudfront.net/dicomweb',
  });

  const content = document.getElementById('content');

  const viewportGrid = document.createElement('div');
  viewportGrid.style.display = 'flex';
  viewportGrid.style.flexDirection = 'row';

  // element for axial view
  const element1 = document.createElement('div');
  element1.style.width = '500px';
  element1.style.height = '500px';

  // element for sagittal view
  const element2 = document.createElement('div');
  element2.style.width = '500px';
  element2.style.height = '500px';

  viewportGrid.appendChild(element1);
  viewportGrid.appendChild(element2);

  content.appendChild(viewportGrid);

  const renderingEngineId = 'myRenderingEngine';
  const renderingEngine = new RenderingEngine(renderingEngineId);

  // note we need to add the cornerstoneStreamingImageVolume: to
  // use the streaming volume loader
  const volumeId = 'cornerstoneStreamingImageVolume: myVolume';

  // Define a volume in memory
  const volume = await volumeLoader.createAndCacheVolume(volumeId, {
    imageIds,
  });

  const viewportId1 = 'CT_AXIAL';
  const viewportId2 = 'CT_SAGITTAL';

  const viewportInput = [
    {
      viewportId: viewportId1,
      element: element1,
      type: ViewportType.ORTHOGRAPHIC,
      defaultOptions: {
        orientation: Enums.OrientationAxis.AXIAL,
      },
    },
    {
      viewportId: viewportId2,
      element: element2,
      type: ViewportType.ORTHOGRAPHIC,
      defaultOptions: {
        orientation: Enums.OrientationAxis.SAGITTAL,
      },
    },
  ];

  renderingEngine.setViewports(viewportInput);

  // Set the volume to load
  volume.load();

  setVolumesForViewports(
    renderingEngine,
    [{ volumeId }],
    [viewportId1, viewportId2]
  );

  // Render the image
  renderingEngine.renderViewports([viewportId1, viewportId2]);
}

run();

```
