### ISSUE TITLE
[Bug]: Unable to view 3d colored dicom on volume viewport.

### ISSUE THREAD

**Issue by schopdekar** [cornerstonejs/cornerstone3D#680]
### Unable to view 3d colored dicom on volume viewport.

When I am trying to render 3d color dicom data using volume viewport I am receiving warnings stating "WebGL: INVALID_OPERATION: texSubImage3D: ArrayBufferView not big enough for request"

I have attached dummy color dicom as I cannot upload the patient data here. It should look something like this:
![image](https://github.com/cornerstonejs/cornerstone3D/assets/134197565/8580a522-9c64-46b0-b7d6-cf78de62617d)

Issue screenshot:
![image](https://github.com/cornerstonejs/cornerstone3D/assets/134197565/f9e456c1-bd55-4fb9-85b0-93039ff3704b)

Dummy Data:
[dummy.dcm.zip](https://github.com/cornerstonejs/cornerstone3D/files/11979996/dummy.dcm.zip)

### Steps to Reproduce

1. Use Volume Viewport API example code.
2. Upload the dummy dicom in your dicom web-server eg. orthanc
3. Use the studyInstanceUID and seriesInstanceUID for loading the metadata and the volume.
4. Run the file.
5. Change the view to axial if you don't receive the error upfront.

### The current behavior

Viewport is not rendering anything

### The expected behavior

Viewport should render the given 3d color dicom

### OS

macOS

### Node version

v16.15.0

### Browser

Chrome 114.0.5735.198

**Comment by sedghi** [comment]
I have some related fixes though https://github.com/cornerstonejs/cornerstone3D/pull/683

**Comment by schopdekar** [comment]
@sedghi 
I have sent you the data via email

**Comment by sedghi** [comment]
I haven't received it yet, maybe message me on slack with the link to the data

**Comment by schopdekar** [comment]
@sedghi My colleague Aryan has send the data to you on slack, yesterday.

**Comment by schopdekar** [comment]
@sedghi 
Hey, this piece of code change solved the issue. Works fine now.
