### ISSUE TITLE
[Bug] Window width/level getting changed in stack viewport after switching back from Volume viewport 

### ISSUE THREAD

**Issue by idemopacs** [cornerstonejs/cornerstone3D#684]
### Describe the Bug

Window width/level getting changed in stack viewport after switching back from Volume viewport.
(using latest version - 1.4.1)

### Steps to Reproduce

1. Open link - [https://www.cornerstonejs.org/live-examples/stacktovolumewithannotations]
2. Click on - Switch Stack Viewport to Volume Viewport button
3. Click again on same button to view Stack Viewport
4. Window width/level getting changed for some images in stack viewport 

### The current behavior

Window width/level getting changed for some images in stack viewport 

### The expected behavior

Window width/level should not change 

### OS

Windows 10

### Node version

v16.17.1

### Browser

Chrome 114.0.5735.134

**Comment by idemopacs** [comment]
Hello @sedghi ,
This issue is resolved with latest released patch v1.9.0, but the original issue of stack scrolling mentioned here #669 reoccurring.
You can check in this example https://www.cornerstonejs.org/live-examples/stacktovolumewithannotations

Thanks

**Comment by sedghi** [comment]
Yeah I see that I will look

**Comment by idemopacs** [comment]
@sedghi, is there any solution for this issue ?

**Comment by sedghi** [comment]
it is fixed in latest

https://www.cornerstonejs.org/live-examples/stacktovolumewithannotations

**Comment by idemopacs** [comment]
It is resolved in latest build.
Thanks.
