### ISSUE TITLE
[Bug] The browser memory usage keeps increasing

### ISSUE THREAD

**Issue by laoniu2020** [cornerstonejs/cornerstone3D#685]
### Describe the Bug

Hi,

I test MPR feture, when I change the volume, the browser memory usage keeps increasing.

### Steps to Reproduce

When load another series, I use:
`ct_volume.cancelLoading()
cache.purgeCache()` 
to clear memory, but memory usage is still growing.

I use the following code to create a volume:
`ct_volume = await volumeLoader.createAndCacheVolume(volumeId, {
imageIds: imageIds,
})
ct_volume.load()`

### The current behavior

memory usage is still growing

### The expected behavior

the old volume memory will be removed

### OS

Windows 11

### Node version

18.12.1

### Browser

Chrome 114.0.5735.199

**Comment by sedghi** [comment]
Thanks for the report, I will investigate this as this is critical

**Comment by sedghi** [comment]
I can't replicate this
As you see I'm running the `yarn run example volumeapi` and take a snapshot and after purgeCache it is cleaned

![image](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/19f00f3f-f274-4567-92d9-53140898395a)
