### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by David2k13** [cornerstonejs/cornerstone3D#689]
### Describe the Bug

If the order of imageIds is incorrect, AXIAL SAGITTAL CORONAL is also incorrect, which means that the order of imageIds determines the order of AXIAL SAGITTAL CORONAL
![1](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/a2751966-32b7-4c54-b223-ee4934a438c7)

### Steps to Reproduce

volumeLoader.createAndCacheVolume('ctVolumeId', {
    imageIds: [2,5.1,4,3....],
  });

### The current behavior

   The AXIAL SAGITTAL CORONAL image sequence is displayed  incorrect

### The expected behavior

   The AXIAL SAGITTAL CORONAL image sequence is displayed correctly

### OS

windows 10

### Node version

14.17.6

### Browser

114.0.5735.199

**Comment by sedghi** [comment]
we do sortImageIds based on imageposition patient for the volume viewports, if that is correct you should not see this problem which makes me think it is not correct

**Comment by David2k13** [comment]
I'm sorry
make corrections:
、、、
volumeLoader.createAndCacheVolume('ctVolumeId', {
imageIds: [2,5.1,4,3....],
});
、、、
I want to know if I need to sort it myself, but the beta version does not need to sort it myself. I have upgraded from the beta to the latest version

**Comment by sedghi** [comment]
No you don't need to sort yourself
