### ISSUE TITLE
[Bug] The @kitware/vtk.js is Slightly lagging

### ISSUE THREAD

**Issue by Am-pang** [cornerstonejs/cornerstone3D#697]
### Describe the Bug

now @The version of vtk.js that Cornerstonejs/core relies on is 27.3.1. When I use vtk, I will encounter an error of "Cannot read properties of null (reading 'requestDevice')", which will not occur when I use 28.3.3. So can you upgrade the version of the library or tell me what solution is available

### Steps to Reproduce

use the vtk.js@27.3.1

### The current behavior

The error prompt is "Cannot read properties of null (reading 'requestDevice')"

### The expected behavior

show teh models correctly

### OS

deppin

### Node version

1.4.1

### Browser

1

**Comment by Am-pang** [comment]
> Sure, I can investigate that

how is it going？

**Comment by sedghi** [comment]
I'm creating a beta branch and I will do it there

**Comment by Am-pang** [comment]
> I'm creating a beta branch and I will do it there

Thanks!

**Comment by Am-pang** [comment]
> I'm creating a beta branch and I will do it there

It seems that my problem has not been solved yet

**Comment by sedghi** [comment]
can you create a PR with the bump for vtk.js to the `beta` branch?
