### ISSUE TITLE
[Bug] The invert tool does not work when switching between images in some series

### ISSUE THREAD

**Issue by mauricio-cdr** [cornerstonejs/cornerstone3D#701]
### Describe the Bug

The invert tool stops working when changing images in a series

Additionally, when changing images, the window level tool is no longer applied to the images.

Reviewing the code and doing a couple of tests locally, I noticed that the error seems to come from entering this function
 ```packages/core/src/RenderingEngine/StackViewport.ts. ```
 
![Captura de Pantalla 2023-07-20 a la(s) 13 17 55](https://github.com/cornerstonejs/cornerstone3D/assets/17281855/349812d3-4c9c-42e1-b223-d23d28da9904)

For that particular series, the function returns that they do not have the same data and does not reuse the actor.

### Steps to Reproduce

Can be reproduced easily in the viewer, with the first series of images
1. Go to https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.99.1071.26968527900428638961173806140069
2. In the first serie select invert tool and apply it
3. Scroll into image serie
4. Try to use invert tool again

### The current behavior

When selecting a series, applying the invert tool and changing images the invert tool stops working correctly

Bug with invert tool

https://github.com/cornerstonejs/cornerstone3D/assets/17281855/b58310cd-31fc-45ea-9d08-6c85d5e602a5

Bug with windowLevel tool

https://github.com/cornerstonejs/cornerstone3D/assets/17281855/af1d138e-0bfa-4688-9322-29917903891b

### The expected behavior

Changes made by the window level and invert tools remain on the series when changing images

### OS

macOs12.3 , Windows 10, Linux Mint

### Node version

18.13.0

### Browser

Chrome 90+

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by mauricio-cdr** [comment]
Also in viewer-dev.ohif.org I can replicate the error
https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.99.1071.26968527900428638961173806140069

**Comment by mauricio-cdr** [comment]
I can even apply it with the live-examples/stackapi example by changing the series that it has by default for one of type SCOUT

**Comment by sedghi** [comment]
thanks for the report, i'll look
