### ISSUE TITLE
[Bug] If the size (width and height) of the Viewport is relatively large, the operation smoothness of the ZoomTool tool decreases

### ISSUE THREAD

**Issue by abluobo** [cornerstonejs/cornerstone3D#709]
### Describe the Bug

If the size (width and height) of the Viewport is relatively large, the operation smoothness of the ZoomTool tool decreases

### Steps to Reproduce

1. Launch petCt case
`yarn run example petCt`
2. Modify Viewport Size
```
viewportGrid.style.width = '200vw';
viewportGrid.style.height = '200vh';
```
3. Right click to zoom in and out on the viewport

### The current behavior

Reduced smoothness of ZoomTool operation

### The expected behavior

ZoomTool tool operation smoothness remains unchanged

### OS

windows 10

### Node version

16.14.0

### Browser

Version 114.0.5735.199 (Official Build) (64-bit)

**Comment by sedghi** [comment]
do you have a recording of this behaviour?

**Comment by abluobo** [comment]
```
viewportGrid.style.width = '95vw';
viewportGrid.style.height = '80vh';
```
https://github.com/cornerstonejs/cornerstone3D/assets/72963274/2738efa7-a612-4ed0-8a66-da27f88a1f65

```
viewportGrid.style.width = '200vw';
viewportGrid.style.height = '200vh';
```
https://github.com/cornerstonejs/cornerstone3D/assets/72963274/cb594f46-0a99-4394-af62-850c6a260672


If you cannot play the video, you can download and view it

![image](https://github.com/cornerstonejs/cornerstone3D/assets/72963274/b5b4b5cb-895f-4250-b04f-4b0d12837eb7)

**Comment by sedghi** [comment]
interesting, thanks for the report. I will investigate

**Comment by abluobo** [comment]
@sedghi   How can this problem be solved?

**Comment by sedghi** [comment]
I can't reproduce it really, can you try in firefox, safari or edge ?

https://github.com/cornerstonejs/cornerstone3D/assets/7490180/0a293bcb-33b7-4786-82cf-03dfff874478
