### ISSUE TITLE
[Feature Request] When using stack to render images，The images are not displayed in order

### ISSUE THREAD

**Issue by tineke01** [cornerstonejs/cornerstone3D#711]
### What feature or change would you like to see made?

I think it is necessary to sort the whole set of images according to ‘’imageposition‘’ when rendering, and then render

### Why should we prioritize this feature?

This ensures that the images are rendered in the correct order

**Comment by sedghi** [comment]
The definition of stack viewport is not entailed to sorting. You can use it on any mixture of data (a stack of CT, PT, MG, etc. if you need it). However, if you need sorting you can look into `packages/streaming-image-volume-loader/src/helpers/sortImageIdsAndGetSpacing.ts` before you feed the imageIds
