### ISSUE TITLE
[Feature Request] configuration for ROI tools to select what text lines we want to display

### ISSUE THREAD

**Issue by shikamu** [cornerstonejs/cornerstone3D#727]
### What feature or change would you like to see made?

I'm currently mostly using the EllipticalROITool quite a lot and it's always display the area, the mean, the max and the std dev. 
I'm only interested in displaying the area and currently I don't know an easy way to not render these extra lines.
It would be great to be able to pass some extra options when adding the tool to a toolGroup for example, and we'd be able to specify whether we'd want to render each line, by default everything would be true to preserve the current behaviour.

Something like this:
```
toolGroup.addTool(EllipticalROITool.toolName, {
  configuration: {
    displayStdDev: false,
    displayMean: false,
    displayMax: false,
    displayArea: true
  }
})
```

### Why should we prioritize this feature?

I can't image this feature being critical but at the same time it should be fairly easy to implement because all support for configuration is already in place, it would just be a matter of reading the configuration before adding the lines to the returned text lines.

Additionally I can't imagine that everyone want these lines to be displayed at all time and it would be nice to be able to choose what we see.

**Comment by sedghi** [comment]
This is kind of similar to this https://github.com/cornerstonejs/cornerstone3D/pull/723 so i'm wondering whether you can achive it with removing the calculators you don't need

**Comment by shikamu** [comment]
@sedghi for now I created a Custom `EllipticalROITool` which inherits from `EllipticalROITool` and I override `_getTextLines` and it does the job for me. It's even better because it allows me to define other text lines that I wanted to show.

**Comment by shikamu** [comment]
This can indeed be done with #723, configuration was added to "override" the internal `_getTextLines`:
```
          toolGroup.setToolConfiguration(EllipticalROITool.toolName, {
            getTextLines: CustomTextLines,
            statsCalculator: NoStatsCalculator
          })
```

**Comment by VladimirKondratenko** [comment]
Good time, could you help me with example CustomTextLines. How it's will be look? 

  toolGroup.addTool(EllipticalROITool.toolName);
  toolGroup.setToolConfiguration(EllipticalROITool.toolName, {
    getTextLines: CustomTextLines,
    statsCalculator: NoStatsCalculator,
  });
  
  CustomTextLines? CustomTextLines { 
      displayStdDev: false,
      displayMean: false,
      displayMax: false,
      displayArea: true,
  },

**Comment by shikamu** [comment]
Hi Vladimir,

I'm still using a fairly old version of cornerstone3D (1.53.0) so I don't know whether this will work for you, but this is what it looks like for us:
```
export const CustomTextLines = (data: any, targetId: string): string[] => {
  return [data.label]
}
```

in the end it turned out we only wanted to display the label, which is part of the `data` object that is passed to the function.

Also for the sake of completeness here's what our NoStatsCalculator looks like:
```
export class NoStatsCalculator extends Calculator {
  /**
   * This callback is used when we verify if the point is in the annotion drawn so we can get every point
   * in the shape to calculate the statistics
   * @param value of the point in the shape of the annotation
   */
  // eslint-disable-next-line @typescript-eslint/no-empty-function, @typescript-eslint/no-unused-vars
  static statsCallback = ({ value: newValue }): void => {}

  /**
   * Basic function that calculates statictics for a given array of points.
   * @param points
   * @returns An object that contains :
   * max : The maximum value of the array
   * mean : mean of the array
   * stdDev : standard deviation of the array
   * stdDevWithSumSquare : standard deviation of the array using sum²
   */

  static getStatistics = (): Statistics[] => {
    return []
  }
}
```

**Comment by VladimirKondratenko** [comment]
Thanks [shikamu](https://github.com/shikamu), already saw in the library part of the code with options and did, Maybe it will be useful to someone. My code and link with description from library with fuction
![image](https://github.com/user-attachments/assets/c3488984-51cb-4e39-9e08-93fbab58d1fc)
https://github.com/cornerstonejs/cornerstone3D/blob/071727c804c1177f17afdd0d8ceca553a7aa0c6e/packages/tools/examples/stackAnnotationToolsSpecificConfiguration/index.ts
