### ISSUE TITLE
How to restore CrosshairsTool

### ISSUE THREAD

**Issue by David2k13** [cornerstonejs/cornerstone3D#728]
### What feature or change would you like to see made?

use
 viewport.resetCamera();
The center point has been restored, but the angle and range have not been restored
![image](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/50ea9700-15f3-40ee-806f-5b357d067048)

### Why should we prioritize this feature?

The center point has been restored, but the angle and range have not been restored，He is incomplete

**Comment by sedghi** [comment]
If you store the camera and just apply it the crosshairs when get re-enabled would jump
