### ISSUE TITLE
[Feature Request] I hope there is an icon for the function point on CrosshairsTool

### ISSUE THREAD

**Issue by David2k13** [cornerstonejs/cornerstone3D#729]
### What feature or change would you like to see made?

I hope there is an icon for the function point on CrosshairsTool
![image](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/00bc7678-3ea8-4278-bb3e-fa1c6bc0ac59)

### Why should we prioritize this feature?

Can better distinguish between rotation and thickness

**Comment by sedghi** [comment]
We will revamp crosshairs soon and will add this feature
