### ISSUE TITLE
In the use of drawing, can I select the already drawn line segment and press the delete key to delete it

### ISSUE THREAD

**Issue by vincent1996** [cornerstonejs/cornerstone3D#732]
### What feature or change would you like to see made?

In the use of drawing, can I select the already drawn line segment and press the delete key to delete it

### Why should we prioritize this feature?

At present, I only found in the help document that pressing the ESC key during the drawing process terminated the drawing, and did not select or delete the completed drawing.

There is removeAnnotation in annotation.state. Do I need to use this method to implement it myself? Is there a method to obtain the annotationUID and what are the selected events for the drawing results

**Comment by sedghi** [comment]
I have not tried it but we have selection utilities and we have keyboard bindings so ....
