### ISSUE TITLE
[Bug] Circular dependencies in Tools package

### ISSUE THREAD

**Issue by salimkanoun** [cornerstonejs/cornerstone3D#742]
### Describe the Bug

Hi there,

when trying to build a project using CS3D with Vite I have several warnings (see at the end of the message). 
The build production has errors trying to call an unset variable which seems consistent with the warning "will likely lead to broken execution order"

This issue is also very similar to https://github.com/cornerstonejs/cornerstone3D/pull/337

So it sounds there a circular dependency limited to some cornerstone tools that are listed here, but didn't found the reason yet.

`Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/base/AnnotationTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/base/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/StackScrollTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/MIPJumpToClickTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/LengthTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/CrosshairsTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.a
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/ReferenceLinesTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/ProbeTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/RectangleROITool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/EllipticalROITool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/CircleROITool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/BidirectionalTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/PlanarFreehandROITool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/ArrowAnnotateTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/AngleTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/annotation/CobbAngleTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/MagnifyTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/ReferenceCursors.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/ScaleOverlayTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "default" of module "node_modules/@cornerstonejs/tools/dist/esm/tools/segmentation/RectangleScissorsTool.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/tools/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "*" of module "node_modules/@cornerstonejs/tools/dist/esm/store/SynchronizerManager/index.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/store/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "*" of module "node_modules/@cornerstonejs/tools/dist/esm/store/ToolGroupManager/index.js" was reexported through module "node_modules/@cornerstonejs/tools/dist/esm/store/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@cornerstonejs/tools/dist/esm/index.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.`

### Steps to Reproduce

Build the project with Vite

### The current behavior

warning on export of package

### The expected behavior

should not have warnings

### OS

Linux

### Node version

18.16

### Browser

Not applicable

**Comment by salimkanoun** [comment]
The good news is that i found a tool to find the circular dep :  https://github.com/acrazing/dpdm

The bad news is that it founds 313 circular deps, here somes

`  250) packages/tools/src/types/index.ts -> packages/tools/src/types/ISynchronizerEventHandler.ts -> packages/tools/src/store/index.ts -> packages/tools/src/store/addEnabledElement.ts -> packages/tools/src/eventListeners/index.ts -> packages/tools/src/eventListeners/annotations/index.ts -> packages/tools/src/eventListeners/annotations/annotationSelectionListener.ts -> packages/tools/src/utilities/index.ts -> packages/tools/src/utilities/getAnnotationNearPoint.ts -> packages/tools/src/tools/index.ts -> packages/tools/src/tools/annotation/AngleTool.ts`

`packages/tools/src/store/index.ts -> packages/tools/src/store/addEnabledElement.ts -> packages/tools/src/eventListeners/index.ts -> packages/tools/src/eventListeners/annotations/index.ts -> packages/tools/src/eventListeners/annotations/annotationSelectionListener.ts -> packages/tools/src/utilities/index.ts -> packages/tools/src/utilities/getAnnotationNearPoint.ts -> packages/tools/src/tools/index.ts -> packages/tools/src/tools/annotation/EllipticalROITool.ts`

**Comment by sedghi** [comment]
still good news that there are tools for this.
Let's focus on one `annotationSelectionListener` what is circular dep here? I still don't understand

**Comment by sedghi** [comment]
Do you know what is happening here Salim? regarding the circular dependencies

**Comment by salimkanoun** [comment]
Still didn't get the time to look at it but will do asap

**Comment by sedghi** [comment]
I'm working on cornerstone3D 2.x and have made progress in removing circular dependencies and publishing the types for the DICOM image loader. I'm trying to make it work with Vite, but there are numerous issues with Vite in `dev` mode, which are not directly related to Cornerstone. Multiple mentions of Vite problems with `import.meta.url`, web workers, and WebAssembly can be found on the Vite GitHub repository:

https://github.com/vitejs/vite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+import.meta.url

I have started a template project for Vite, React, and cornerstone3D beta 2.x here. I appreciate your help in making it work.

https://github.com/cornerstonejs/vite-react-cornerstone3d
