### ISSUE TITLE
[Bug] Issue with Volume viewport resetCamera() method

### ISSUE THREAD

**Issue by idemopacs** [cornerstonejs/cornerstone3D#744]
### Describe the Bug

Volume viewport resetCamera(resetPan, resetZoom, resetToCenter) method resets only Pan and Zoom , it does not resets window width/center.
To reset these values in Stack viewport  resetProperties() method is available but same is not available for Volume viewport.

### Steps to Reproduce

1. Load Series images into Volume viewport  [https://www.cornerstonejs.org/live-examples/resetcamera](https://www.cornerstonejs.org/live-examples/resetcamera)
2. Change window level of volume viewport
3. click Reset 

### The current behavior

Reset button is not resetting window level to original value

### The expected behavior

Window level to should reset to original value.
In stack viewport resetProperties() method is available, no such method is available for Volume viewport  
### OS

Windows 10

### Node version

v16.17.1

### Browser

Chrome 114.0.5735.134

**Comment by idemopacs** [comment]
With latest build resetProperties() method for Volume viewport is available. It is resetting window level.
Thanks @sedghi @jbocce .
 Is there any method available to reset angle and range (#728)  ?

**Comment by David2k13** [comment]
> 在最新版本中，可以使用卷视口的 resetProperties（） 方法。它正在重置窗口级别。谢谢 。有没有可用的方法来重置角度和范围 （#728） ？
Is there a solution? I've been looking for it for a long time
