### ISSUE TITLE
How do I clear LengthTool [Bug] 

### ISSUE THREAD

**Issue by xyy7260** [cornerstonejs/cornerstone3D#746]
### Describe the Bug

How to delete distance measurement using LengthTool?

package.js
```
    "react": "^18.2.0",
  "@cornerstonejs/calculate-suv": "1.0.3",
    "@cornerstonejs/core": "^1.10.3",
    "@cornerstonejs/dicom-image-loader": "^1.10.3",
    "@cornerstonejs/streaming-image-volume-loader": "^1.10.3",
    "@cornerstonejs/tools": "^1.10.0",
```

### Steps to Reproduce

[cornerstonejs use method](	https://github.com/cornerstonejs/cornerstoneTools/issues/1013)

### The current behavior

cornerstone3D did not

### The expected behavior

I hope there is this method

### OS

mac

### Node version

19

### Browser

chrome

**Comment by sedghi** [comment]
what do you mean delete distsance?

**Comment by xyy7260** [comment]
@sedghi  
<img width="952" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/23183393/07fb6f41-994b-4c1d-9c2a-300420c904a1">

**Comment by xyy7260** [comment]
[Annotation Visibility](https://www.cornerstonejs.org/live-examples/annotationvisibility)

**Comment by jianghuaw** [comment]
I guest you want to delete the measurement. In OHIF, you can right click on the measurement and there is a menu item "Delete measurement". I guess you can refer to it.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/13652642/9848f5cd-3ecd-4302-951b-584b1b5b3b02)

**Comment by bearxy** [comment]
const manager = cornerstoneTools.annotation.state.getAnnotationManager(currentViewPort..element) 
manager.removeAllAnnotations()

测试没有啥问题。
