### ISSUE TITLE
Custom headers in supported loaders for Auth

### ISSUE THREAD

**Issue by marp98** [cornerstonejs/cornerstone3D#752]
### What feature or change would you like to see made?

ability to add custom headers to the dicom-image-loader and volume loader to support things like JWT tokens for authentication

### Why should we prioritize this feature?

I am trying to build a simple web service using cornerstone and orthanc. The orthanc server requires authentication to protect the data and in the frontend I’m loading images using the volume loader with the @cornerstonejs/streaming-image-volume-loader. The webImageLoader allows for custom headers but the volume loader and the dicom-image-loader look like they don’t. Are there ways to add custom headers to support something like JWT auth or does anyone have a recommendation on how to add auth to the system in another way?

It's easier to add authentication when building web apps that need access to protected dicom servers. 

thanks!

**Comment by sedghi** [comment]
You can take benefit from beforeSend hook in the image loader
