### ISSUE TITLE
[Bug] 能不能出个稳定版本

### ISSUE THREAD

**Issue by xiongtongzi** [cornerstonejs/cornerstone3D#753]
### Describe the Bug

更新版本就为了调换一下参数位置，是不是SB

### Steps to Reproduce

更新版本就为了调换一下参数位置，是不是SB

### The current behavior

更新版本就为了调换一下参数位置，是不是SB

### The expected behavior

更新版本就为了调换一下参数位置，是不是SB

### OS

window10

### Node version

16.14

### Browser

谷歌

**Comment by Yoruchiaki** [comment]
如果你如果不尊重开源社区就请不要使用，如果对项目不满意你可以选择其他开源项目，这里不是你大放厥词的地方。

If you do not respect the open source community, please do not use it. If you are not satisfied with the project, you can choose other open source projects. This is not the place for you to speak up.

オープンソースコミュニティを尊重しない場合は使用しないでください。プロジェクトに満足していない場合は、他のオープンソースプロジェクトを選択することができます。ここはあなたが言いふらしている場所ではありません。

Si vous ne respectez pas la communauté open source, ne l'utilisez pas, et si vous n'êtes pas satisfait du projet, vous pouvez choisir d'autres projets open source, ce n'est pas l'endroit pour vous de le dire.

Wenn Sie die Open-Source-Community nicht respektieren, verwenden Sie sie bitte nicht. Wenn Sie mit dem Projekt nicht zufrieden sind, können Sie andere Open-Source-Projekte wählen. Dies ist nicht der Ort für Sie, um sich zu äußern.
