### ISSUE TITLE
[Bug] MIP Presets: Saturation Issue in 3D Viewport

### ISSUE THREAD

**Issue by focusaway** [cornerstonejs/cornerstone3D#797]
### Describe the Bug

I'm currently working on implementing the 3D viewport and, upon reviewing the different presets available, I've noticed that the MIP appears overly saturated.

While researching this issue, I came across a reference to 'blendMode' in an official VTK example [here](https://examples.vtk.org/site/Cxx/VolumeRendering/FixedPointVolumeRayCastMapperCT/). In this example, the MIP mode is set to use the Maximum Intensity blendMode, which caught my attention.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/56932461/524c8f07-153a-4e43-a0d5-a5856c1468c3)

Subsequently, I searched vtk.js for a similar reference and found an example where applying the same blendMode seems to produce a much better result, at least from my perspective [here](https://kitware.github.io/vtk-js/examples/VolumeMapperBlendModes/index.html).
![image](https://github.com/cornerstonejs/cornerstone3D/assets/56932461/2ef2e111-f340-4cbc-a99b-0f9678f88026)

After seeing this, I made a local adjustment in the Cornerstone example related to the 3D viewport, where I applied this blendMode, and it appears to work as expected. So, my question is, should we have the capability to specify a blendMode for each preset, or is there a better approach to achieve these results?

### Steps to Reproduce

1. Go to the 3D viewport example at https://www.cornerstonejs.org/live-examples/volumeviewport3d.
2. Choose the CT-MIP option.
3. Interact by viewing from different perspectives. You will see a high level of saturation and lack of detail.

### The current behavior

The visualization appears overly saturated, making it difficult to discern body details.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/56932461/51e11620-c899-435f-b70e-a6210e16387b)

### The expected behavior

By applying the mentioned blendMode (Maximum Intensity), more details become visible.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/56932461/aff5e116-3700-4e98-877e-80ccc4ef376b)

![image](https://github.com/cornerstonejs/cornerstone3D/assets/56932461/28095a27-86bc-4171-a528-baca2335d456)

### OS

Ubuntu GNU/Linux

### Node version

18.17.1

### Browser

Chrome Version 116.0.5845.187

**Comment by sedghi** [comment]
Hmmm, yeah maybe preset configuration is confusing, preset only take care of colors, and don't affect the blendmode, so exactly like what you did you should explicitly set it to MIP, and that is by design. You can achieve mip via crosshairs too just FYI (if you modify the knobs)

https://www.cornerstonejs.org/live-examples/crosshairs
