### ISSUE TITLE
[Bug] createZoomPanSynchronizer doesn't work in CPU Rendering

### ISSUE THREAD

**Issue by Sergey1888888** [cornerstonejs/cornerstone3D#812]
### Describe the Bug

StackViewports has synchronizer createZoomPanSynchronizer. When getShouldUseCPURendering function return true this synchronizer doesn't work and error in console appears 'Synchronizer, for: CORNERSTONE_CAMERA_MODIFIED TypeError: renderer.getActiveCamera is not a function'. The createZoomPanSynchronizer callback uses getPan and getZoom, but they are not defined in the StackViewport class, they are taken from the Viewport class, where there is no CPU support and the camera is taken from the getVtkActiveCamera function, which generates an error in the console.
I think you need to override the getPan and getZoom methods in the StackViewport class so that they can use the CPU mode camera getter methods.

### Steps to Reproduce

1. Create synchronizer with createZoomPanSynchronizer method for multiple StackViewport.
2. Enable cpu rendering.
3. Try to move or zoom image in StackViewport.
4. Error appears in console and StackViewports not synchronized.

### The current behavior

Pan and zoom synchronizer doesn't work in CPU rendering mode and error in console appears.

### The expected behavior

Pan and zoom synchronizer work in CPU rendering mode.

### OS

Windows 10

### Node version

16.17.0

### Browser

Chrome 117.0.5938.134

**Comment by mivan08** [comment]
I have this issue in my end as well.
The synchronizer is working in GPU mode.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/143872547/5d61826a-401a-4d7e-a8d7-ccd1f98e5927)
![image](https://github.com/cornerstonejs/cornerstone3D/assets/143872547/dfa7f175-2f7e-4ad1-882a-c1d0a5d67f66)

**Comment by mivan08** [comment]
Could you please let me know the solution of this issue asap?
This is very urgent task for us.
Thanks.

**Comment by Sergey1888888** [comment]
> Could you please let me know the solution of this issue asap? This is very urgent task for us. Thanks.

I just wrote my own synchronizer. You can use their synchronizer as a basis(tools/src/synchronizers), but in the callback replace their getters and setters with camera getters and setters, take the necessary data from there and change the camera, rather than using setZoom, setPan.

For example in `packages/tools/src/synchronizers/callbacks/zoomPanSyncCallback.ts`:
Their code:
```
const srcZoom = sViewport.getZoom(); // Do the zoom first, as the pan is relative to the zoom level
tViewport.setZoom(srcZoom);
```
Changed code:
```
const sCamera = sViewport.getCamera();
const tCamera = tViewport.getCamera();
tViewport.setCamera({...tCamera, parallelScale: sCamera.parallelScale});
```
