### ISSUE TITLE
[Bug] SharedArrayBuffer is NOT supported in your browser

### ISSUE THREAD

**Issue by VijayanRamachandran** [cornerstonejs/cornerstone3D#813]
### Describe the Bug

Hi,

I am trying to render dcm files as volume ( WADO urls ) using Cornerstone3D library in angular application as in below code snippet, i am facing **Error: SharedArrayBuffer is NOT supported in your browser**,

**Version Information:**
"@cornerstonejs/core": "^1.18.0",
"@cornerstonejs/dicom-image-loader": "^1.18.0",
"@cornerstonejs/streaming-image-volume-loader": "^1.18.0",
"@cornerstonejs/tools": "^1.18.0",

**OS**: Windows 10 21H2 ( 19044.3448 )
**Node Version**: v18.18.0
**Browser Information**: **Google Chrome - Version 117.0.5938.132 (Official Build) (64-bit)**
**Angular Version**
![Angular-CLI-Version](https://github.com/cornerstonejs/cornerstone3D/assets/25306014/4cebde38-3f6b-49d7-be0e-bebcd6a39e3d)

Can you please help us by hinting if any steps or configuration i am missing either code wise or for browser ?
Hope this above specified chrome browser version supports SharedArrayBuffer ?

### Steps to Reproduce

**Code Snippet** 
public async RenderVolume( seriesInstanceUrls: string[], imageSegment: any ) {

    const renderingEngineId = 'Cornerstone3DRenderingEngine-Volume';
    const renderingEngine = await new RenderingEngine(renderingEngineId); 
    
    const viewportInput = { 
                            viewportId: 'CT_SAGITTAL_STACK', 
                            type: ViewportType.ORTHOGRAPHIC, 
                            element: imageSegment, 
                            defaultOptions: {
                              orientation: Enums.OrientationAxis.SAGITTAL,
                            },
                          };
    renderingEngine.enableElement(viewportInput);

    const viewport = <Types.IVolumeViewport>( await renderingEngine.getViewport('CT_SAGITTAL_STACK') );

    const volumeName = 'CT_VOLUME_ID'; 
    const volumeLoaderScheme = 'cornerstoneStreamingImageVolume';
    const volumeId = `${volumeLoaderScheme}:${volumeName}`;
        
    const volume = await volumeLoader.createAndCacheVolume(volumeId, { imageIds: seriesInstanceUrls });
    // await volume.load();
    await viewport.setVolumes([ { volumeId, callback: this.setCtTransferFunctionForVolumeActor } ]);
    await viewport.render();
  }  

  setCtTransferFunctionForVolumeActor({ volumeActor }) {
    const windowWidth = 400;
    const windowCenter = 40;

    const lower = windowCenter - windowWidth / 2.0;
    const upper = windowCenter + windowWidth / 2.0;

    volumeActor
      .getProperty()
      .getRGBTransferFunction(0)
      .setMappingRange(lower, upper);
  }

### The current behavior

**Error**
"ERROR Error: Uncaught (in promise): Error: SharedArrayBuffer is NOT supported in your browser see https://developer.chrome.com/blog/enabling-shared-array-buffer/
Error: SharedArrayBuffer is NOT supported in your browser see https://developer.chrome.com/blog/enabling-shared-array-buffer/"

### The expected behavior

Application should render images as volume.

### OS

Windows 10 21H2 ( 19044.3448 )

### Node version

v18.18.0

### Browser

Google Chrome - Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by sedghi** [comment]
see here https://docs.ohif.org/deployment/cors

**Comment by VijayanRamachandran** [comment]
Hi @sedghi ,

Thanks for pointing to right direction by sharing above link.

Yes now we could render volume in our angular app and app is working as expected. 

Regards,
Vijayan Ramachandran

**Comment by Vishal-Isharani** [comment]
@VijayanRamachandran How did you load the necessary WASM file for the `dicom-image-loader` package? Can you assist me with this?
