### ISSUE TITLE
[Bug] Modality unit Bugs

### ISSUE THREAD

**Issue by sedghi** [cornerstonejs/cornerstone3D#817]
### Describe the Bug

The happened after the recent `getModalityUnit` change. 

The issue is couple of things 

- First the getModalityUnit is called on the targetId which can be the CT and we are checking `isSUVCalculated` on CT and it does not have `scaling.PT`
- Also the referenceImageId might be the CT if drawn on CT first, then it means that later in the 

const petSeriesModule = metaData.get('petSeriesModule', imageId);
  return petSeriesModule?.units || 'unitless';

which is wrong, since a CT image ID will not have `petSeriesModule`

 

### Steps to Reproduce

yarn run example petCt

add probe tool to all toogroups

### The current behavior

It wrongly show the modality raw

### The expected behavior

should say suv

### OS

macos

### Node version

18

### Browser

chrome

**Comment by abby0127** [comment]
Why the function 'getModalityUnit' sometimes return 'raw' and sometimes 'SUV' when the modality is PT?

**Comment by sedghi** [comment]
Fixed in main
