### ISSUE TITLE
iOS memory limit problem

### ISSUE THREAD

**Issue by articu** [cornerstonejs/cornerstone3D#839]
### Describe the Bug

Web app built with cornerstone3D library in iPhone and iPad keep refreshing.

iOS have certain memory limit for an app/webpage. Now my webpage with more than 300 dicom image files would refresh constantly because of exceeding the memory limit of iOS. This problem does not exist in Android, Windows, and Mac. It only occur in iPhone and iPad.

### Steps to Reproduce

In iPhone and iPad, open any webpage built with cornerstone3D library with more than 300 dicom image files in on series.

### The current behavior

My webpage with more than 300 dicom image files would refresh constantly because of exceeding the memory limit of iOS.

### The expected behavior

My webpage do not refresh.

### OS

iOS 14.8

### version of @cornerstonejs/core

0.28.0

### Node version

16.14.0

### Browser

Safari 15.1.0

**Comment by sedghi** [comment]
Are you using volume viewports and volume rendering or simply render images?

**Comment by articu** [comment]
@sedghi  Only render images.   Can you please help me ?    It is a extremely serious problem in production and a lot of our users are affected by this problem. Thank you very much.

**Comment by sedghi** [comment]
are you on ios 17?

**Comment by articu** [comment]
@sedghi  I have tested in iOS14.8,  16.6.1,  17.0.3.      The problem occurred in all of these versions.

**Comment by sedghi** [comment]
Can you test again with latest iOS?

**Comment by sedghi** [comment]
I created this PR which would be good enough for a lot of use cases (except the PT Scaled data)

https://github.com/cornerstonejs/cornerstone3D/pull/1212

**Comment by articu** [comment]
@sedghi  Thank you very much. I have tested again using latest cornerstone3D with latest iOS. It is better, but the refresh problem still exist.  More than 300 dicom image files would trigger the page refresh before. Now more than 600 dicom image files would trigger the page refresh. 

Can cornerstone add disk cache instead of only memory cache so that memory is no longer an issue?  Large image series is very common in real world application. Thank you.

**Comment by pcanas** [comment]
@articu we are also running into this issue. Could you please help us on how you set up the memory profiling with iOS? We think it is a memory issue but we would like to confirm it.

**Comment by sedghi** [comment]
@pcanas check this out maybe you can give us more info https://docs.ohif.org/development/android-ios-debugging

**Comment by Congritulation** [comment]
> @sedghi Thank you very much. I have tested again using latest cornerstone3D with latest iOS. It is better, but the refresh problem still exist. More than 300 dicom image files would trigger the page refresh before. Now more than 600 dicom image files would trigger the page refresh.
> 
> Can cornerstone add disk cache instead of only memory cache so that memory is no longer an issue? Large image series is very common in real world application. Thank you.

if you just show images,not VR.try to release you image cache,it could be ok.

**Comment by sedghi** [comment]
Check out new Cornerstone3D 2.0, it has a lot of memory optimizations, see if that helps

https://www.cornerstonejs.org/docs/migration-guides/intro

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)
