### ISSUE TITLE
[Bug] generateToolState metadataProvider 'generalImageModule' using OHIF

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D#847]
https://github.com/cornerstonejs/cornerstone3D/blob/c527923a8a1afd65e76f9335ac4cc0bc3a0e924b/packages/adapters/src/adapters/Cornerstone/Segmentation_4X.js#L358-L368

`generalImageModule` is made by OHIF.

Is it necessary to create `generalImageModule` or is it to correct `generalImageModule` to `sopCommonModule` or something like that?

**Comment by sedghi** [comment]
We should add it to DicomImageLoader if it lives only in OHIF

**Comment by jlopes90** [comment]
https://github.com/cornerstonejs/cornerstone3D/pull/1165
