### ISSUE TITLE
[Bug] parameter 'position' cannot be greater than or equal to 'byteArray' length attempt to read past end of buffer

### ISSUE THREAD

**Issue by David2k13** [cornerstonejs/cornerstone3D#850]
### Describe the Bug

[Bug] I saw that in 1.23.3, transferPixelData=true was added, and after PurgeCache destroy, the renderingEngine reported an error again. In 1.23.2, no error was reported

### Steps to Reproduce

1. cache.purgeCache()
    destroyTools()
    ToolGroupManager.destroyToolGroup();
    ctVoiSynchronizer.destroy()
    renderingEngine.destroy()
    renderingEngine = undefined
    ctVoiSynchronizer = undefined
2. new RenderingEngine()
    volumeLoader.createAndCacheVolume()
3. error: dicomParser.ByteStream: parameter 'position' cannot be greater than or equal to 'byteArray' length
             Uncaught (in promise) littleEndianByteArrayParser.readUint16: attempt to read past end of buffer

### The current behavior

![image](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/07e10921-8739-47ff-b93c-20b553247065)

### The expected behavior

 no error was reported

### OS

windows 10

### Node version

16.14.0

### Browser

 118.0.5993.71

**Comment by idemopacs** [comment]
I am also facing the same issue after upgrading to V1.23.3 , in V1.23.2 everything working properly.

![error](https://github.com/cornerstonejs/cornerstone3D/assets/92505215/5a571c6a-245f-4911-9101-20047f35fefa)

**Comment by frolic06** [comment]
Same issue for me, this seems to be linked to #667 and the addition of : `transferPixelData: true`

**Comment by David2k13** [comment]
> Same issue for me, this seems to be linked to #667 and the addition of : `transferPixelData: true`



> Same issue for me, this seems to be linked to #667 and the addition of : `transferPixelData: true`

yes

**Comment by abby0127** [comment]
Same issue for me,have you guys solved it yet?

**Comment by David2k13** [comment]
> Same issue for me,have you guys solved it yet?

Returned to V1.23.2

**Comment by abby0127** [comment]
V1.23.2 has same issue

**Comment by David2k13** [comment]
> V1.23.2 has same issue

"@cornerstonejs/core": "^1.23.3",
"@cornerstonejs/streaming-image-volume-loader": "1.23.2",
 "@cornerstonejs/tools": "^1.23.3",

**Comment by sedghi** [comment]
can someone give us a reproducible example? I mean mini repo to reproduce or something with more details?

**Comment by David2k13** [comment]
> can someone give us a reproducible example? I mean mini repo to reproduce or something with more details?



> > > V1.23.2 has same issue
> > 
> > 
> > "@cornerstonejs/core": "^1.23.3", "@cornerstonejs/streaming-image-volume-loader": "1.23.2", "@cornerstonejs/tools": "^1.23.3",
> 
> It works!



> Same issue for me, this seems to be linked to #667 and the addition of : `transferPixelData: true`



> I am also facing the same issue after upgrading to V1.23.3 , in V1.23.2 everything working properly.升级到 V1.23.3 后，我也遇到了同样的问题，在 V1.23.2 中一切正常。
> 
> ![error](https://private-user-images.githubusercontent.com/92505215/278289998-5a571c6a-245f-4911-9101-20047f35fefa.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTgyODcsIm5iZiI6MTcxNzA1Nzk4NywicGF0aCI6Ii85MjUwNTIxNS8yNzgyODk5OTgtNWE1NzFjNmEtMjQ1Zi00OTExLTkxMDEtMjAwNDdmMzVmZWZhLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA4MzMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MDEwZjE0Y2EwNGVjMzFkM2Y1ZjlkZGRhMmI4OWJiZmRmZmUyYWY1ZTI4YmU3ZWE0OTU4MzFlNmEyMzUwZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mj_NeoCD_Lheo4HC5e0gPJHWZz-ftECjRy6xTR3c3S0)


Interim plan：

destroy(){
    destroyTools();
    ToolGroupManager.destroyToolGroup();
    ctVoiSynchronizer.destroy();
    renderingEngine.destroy();
    cornerstoneWADOImageLoader.wadouri.dataSetCacheManager.purge();
    renderingEngine = undefined;
    ctVoiSynchronizer = undefined;
}

I guess who destroyed the dataSetCacheManager dataSet

**Comment by David2k13** [comment]
> I am also facing the same issue after upgrading to V1.23.3 , in V1.23.2 everything working properly.
> 
> ![error](https://private-user-images.githubusercontent.com/92505215/278289998-5a571c6a-245f-4911-9101-20047f35fefa.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTgyODcsIm5iZiI6MTcxNzA1Nzk4NywicGF0aCI6Ii85MjUwNTIxNS8yNzgyODk5OTgtNWE1NzFjNmEtMjQ1Zi00OTExLTkxMDEtMjAwNDdmMzVmZWZhLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA4MzMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MDEwZjE0Y2EwNGVjMzFkM2Y1ZjlkZGRhMmI4OWJiZmRmZmUyYWY1ZTI4YmU3ZWE0OTU4MzFlNmEyMzUwZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mj_NeoCD_Lheo4HC5e0gPJHWZz-ftECjRy6xTR3c3S0)



> > Same issue for me, this seems to be linked to #667 and the addition of : `transferPixelData: true`
> 
> > Same issue for me, this seems to be linked to #667 and the addition of : `transferPixelData: true`
> 
> yes



> > > V1.23.2 has same issue
> > 
> > 
> > "@cornerstonejs/core": "^1.23.3", "@cornerstonejs/streaming-image-volume-loader": "1.23.2", "@cornerstonejs/tools": "^1.23.3",
> 
> It works!



> can someone give us a reproducible example? I mean mini repo to reproduce or something with more details?

Interim plan：
destroy(){
    destroyTools();
    ToolGroupManager.destroyToolGroup();
    ctVoiSynchronizer.destroy();
    renderingEngine.destroy();
    cornerstoneWADOImageLoader.wadouri.dataSetCacheManager.purge();
    renderingEngine = undefined;
    ctVoiSynchronizer = undefined;
}
I guess who destroyed the dataSetCacheManager dataSet

**Comment by David2k13** [comment]
> I am also facing the same issue after upgrading to V1.23.3 , in V1.23.2 everything working properly.
> 
> ![error](https://private-user-images.githubusercontent.com/92505215/278289998-5a571c6a-245f-4911-9101-20047f35fefa.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTgyODcsIm5iZiI6MTcxNzA1Nzk4NywicGF0aCI6Ii85MjUwNTIxNS8yNzgyODk5OTgtNWE1NzFjNmEtMjQ1Zi00OTExLTkxMDEtMjAwNDdmMzVmZWZhLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA4MzMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MDEwZjE0Y2EwNGVjMzFkM2Y1ZjlkZGRhMmI4OWJiZmRmZmUyYWY1ZTI4YmU3ZWE0OTU4MzFlNmEyMzUwZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mj_NeoCD_Lheo4HC5e0gPJHWZz-ftECjRy6xTR3c3S0)



> Same issue for me, this seems to be linked to #667 and the addition of : `transferPixelData: true`



> Same issue for me,have you guys solved it yet?



> can someone give us a reproducible example? I mean mini repo to reproduce or something with more details?

Interim plan：
destroy(){
    ...
    cornerstoneDICOMImageLoader.wadouri.dataSetCacheManager.purge();
}

I guess who destroyed the dataSetCacheManager dataSet
