### ISSUE TITLE
[Bug] Updating the version to 1.26.0, thrown an error

### ISSUE THREAD

**Issue by abby0127** [cornerstonejs/cornerstone3D#854]
### Describe the Bug

import @cornerstonejs/core reporting errors

### Steps to Reproduce

import * as cornerstone3D from '@cornerstonejs/core'

console.log(cornerstone3D )
![image](https://github.com/cornerstonejs/cornerstone3D/assets/53502925/9ae444fa-6787-4cbd-8cce-7815ee28046e)

### The current behavior

![image](https://github.com/cornerstonejs/cornerstone3D/assets/53502925/95a13123-15bd-46bb-ac40-81ba2d5a239f)

### The expected behavior

/

### OS

Windows 10

### Node version

1.26.0

### Browser

Google Chrome latest

**Comment by pedrokohler** [comment]
I'm also getting the same issue
