### ISSUE TITLE
[Feature Request] More display mode for image fusion

### ISSUE THREAD

**Issue by Qwd2017** [cornerstonejs/cornerstone3D#855]
### What feature or change would you like to see made?

In the fused viewport, we can observe two images at the same time, and control the display area and proportion of the image through a parameter

### Why should we prioritize this feature?

it's better for observation

**Comment by sedghi** [comment]
Can you explain what you like to achieve, we have fusion already

https://www.cornerstonejs.org/live-examples/petct

**Comment by Qwd2017** [comment]
@sedghi Hi, it's some tools to observe fused images. For example, one tool can split the fused viewport into quadrants . Diagonally opposite quadrants show a pair of fixed or moved images. You can move the quadrants by dragging their cross points

**Comment by sedghi** [comment]
Do you have screenshots?

**Comment by Qwd2017** [comment]
@sedghi Sorry, I just saw your reply. Screenshots as follows
![1](https://github.com/cornerstonejs/cornerstone3D/assets/31121045/70895923-4aec-423d-8f8b-a26284da1ef5)

**Comment by sedghi** [comment]
Oh, I see. No, we don't have such tools, and I don't think we can create it easily since WebGL is involved.

**Comment by daemon29** [comment]
> [@sedghi](https://github.com/sedghi) Sorry, I just saw your reply. Screenshots as follows ![1](https://github.com/cornerstonejs/cornerstone3D/assets/31121045/70895923-4aec-423d-8f8b-a26284da1ef5)

Hi @Qwd2017, how do you implement Diagonally opposite quadrants  like that in the image?
