### ISSUE TITLE
[Bug] Clicking viewport causes error when using "Magnify Tool" 

### ISSUE THREAD

**Issue by articu** [cornerstonejs/cornerstone3D#866]
### Describe the Bug

Clicking viewport caused error when using "Magnify Tool".

### Steps to Reproduce

1. Open the link [https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.32722.99.99.62087908186665265759322018723889952421](url)

2. Follow the steps shown in video below.

https://github.com/cornerstonejs/cornerstone3D/assets/9844530/b44ae6d6-f799-4c28-ba24-8fd0d6c78221

### The current behavior

The console showed StackViewport.ts:1956 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getActiveCamera').

### The expected behavior

No error in console.

### OS

macOS 12.0.1

### Node version

/

### Browser

Chrome Version 119.0.6045.105 (Official Build) (arm64)

**Comment by sedghi** [comment]
Can you test on viewer-dev.ohif.org ?
