### ISSUE TITLE
Unnecessary render of textBox for annotation tools

### ISSUE THREAD

**Issue by sedghi** [cornerstonejs/cornerstone3D#87]
There is an unnecessary rendering of other annotations textBoxes 

https://user-images.githubusercontent.com/7490180/165985609-59775653-2f07-4556-b25b-c3bce80f9619.mp4

**Comment by sedghi** [comment]
@jbocce can you see if this is still an issue?

**Comment by jbocce** [comment]
This is no longer an issue.
