### ISSUE TITLE
[Feature Request] How group series?

### ISSUE THREAD

**Issue by agkairos** [cornerstonejs/cornerstone3D#884]
### What feature or change would you like to see made?

Hi! As shown in this example, how to group the series? each grouped series has its own number of images.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/11198681/7fc22d29-62d9-4436-8656-26123adc1b39)

### Why should we prioritize this feature?

Important information for everyone

**Comment by sedghi** [comment]
That is an app level concern
