### ISSUE TITLE
[Bug] Volumes are gray when SharedArrayBuffer is enabled and the volume is loaded through wadouri

### ISSUE THREAD

**Issue by sgielen** [cornerstonejs/cornerstone3D#886]
### Describe the Bug

As discovered in #832, all volumes are displayed as gray when SharedArrayBuffer is enabled and the volume was loaded through wadouri.

I did find out in #832 that the volume is gray because `handleArrayBufferLoad` returns before loading any data, but as I understood from @sedghi's response the code is not supposed to end up there and therefore the fix is wrong. Therefore, I am filing this as a separate issue.

### Steps to Reproduce

A reproduction scenario is available at: https://sjorsgielen.nl/cornerstone3d/wadouri-sharedarraybuffer.zip

Unpack this .zip file, run `yarn install` and `yarn dev`, then browse to the indicated port.
The volume will be displayed as gray (at least for me).

If SharedArrayBuffer is disabled by setting `shouldUseSharedArrayBuffer` to `false` near the top of `src/main.ts`, then the volume renders normally. Similarly, if `useVolume` is false, a stack viewport is used instead of a volume viewport, which also renders correctly.

### The current behavior

The volume is displayed as gray.

### The expected behavior

The volume is displayed normally.

### OS

macOS 14.0

### Node version

20.8.1

### Browser

Safari 17.0

**Comment by sedghi** [comment]
This seems to be another scaling issue, for some reason there are multiple scales happen for different parts of the image 
which results in this patterns

![CleanShot 2024-01-10 at 08 44 32](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/49c654d7-f731-4cf6-9fb9-154e14d564d1)

even with one web worker

![image](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/3444352e-5f4d-48c3-b782-c49ad3d791dd)

if you window level you can see the data is there but at different values (intensities i.e., scales)

![image](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/825c97f3-1063-46bf-b777-480b46b5fc47)

**Comment by sedghi** [comment]
The simplest way to reproduce this is to use OHIF link to Cornerstone3D and use dicomjson below

http://localhost:3000/viewer/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json&hangingprotocolid=mpr

**Comment by sgielen** [comment]
SharedArrayBuffer was removed from Cornerstone3D 2.0, so this isn't an issue, anymore.
