### ISSUE TITLE
[Bug] Volume renders incorrectly when webWorkerManager is initialized before rendering

### ISSUE THREAD

**Issue by sgielen** [cornerstonejs/cornerstone3D#888]
### Describe the Bug

If `cornerstoneDICOMImageLoader.webWorkerManager.initialize` is called before rendering the first volume, the volume is rendered incorrectly.

### Steps to Reproduce

A reproduction scenario is available at: https://sjorsgielen.nl/cornerstone3d/webworkermanager-init.zip

Unpack this .zip file, run yarn install and yarn dev, then browse to the indicated port.

### The current behavior

The volume will be extremely bright (at least for me).
If `initWebWorkers` is set to `false` at the top of `src/main.ts`, it is rendered normally.

### The expected behavior

It does not matter whether the web workers are initialized ahead-of-time or not.

### OS

macOS 14.0

### Node version

20.8.1

### Browser

Safari 17.0

**Comment by sedghi** [comment]
This relates to the same issue you're experiencing with other matters, specifically regarding wadouri, scaling, and metadata concerns.

Let's begin by addressing the scaling problem, and then we can tackle the other issues. Currently, I'm a bit short on time to prioritize this, but I'm more than happy to assist you with reviewing and providing guidance.

**Comment by sgielen** [comment]
Thank you @sedghi! I am currently away for a few weeks, but when I get back, I would like to continue with these. With the scaling issue, do you mean #887? If so, I will start with that one when I am back.

**Comment by sgielen** [comment]
I can't reproduce this anymore now that I'm on Cornerstone3D 2.0, so I believe this has been fixed since then. Probably since the prescaling was enabled by default on main.
