### ISSUE TITLE
[Feature Request] Request to add FreehandScissorsTool and Segmentation Tools for custom click to draw graphics

### ISSUE THREAD

**Issue by 1321442780** [cornerstonejs/cornerstone3D#890]
### What feature or change would you like to see made?

Request to add FreehandScissorsTool and Segmentation Tools for custom click to draw graphics.Similar to the effect of the Cornerstone (legacy) tool, which is currently not available in the new version, this tool will be more commonly used

### Why should we prioritize this feature?

Doctors often use these two tools during reuse, which is very convenient to use,Thanks.

**Comment by sedghi** [comment]
This is in cooking, we will have contour segmentation very soon
