### ISSUE TITLE
[Bug] ToolGroupSpecific configuration for changing segment color is changing color across other toolgroup

### ISSUE THREAD

**Issue by jithenece** [cornerstonejs/cornerstone3D#895]
### Describe the Bug

- Changing color of a segment using segmentation representation of specific toolgroup also changes colors of segments of other toolgroup. 
- Below seems to change color in segmentations of other tool groups too
`segmentation.config.color.setColorForSegmentIndex(
    toolGroupId1,
    segmentationRepresentationToolGroupId1[0],
    1,
    [0, 0, 255, 255]
  );
 `

### Steps to Reproduce

1. Clone the cornerstone3D repo
2. Use the [labelmapToolGroupSpecificConfiguration/index.ts](https://github.com/jithenece/cornerstone3D/blob/change-segment-color/packages/tools/examples/labelmapToolGroupSpecificConfiguration/index.ts) to replace below file path
`packages/tools/examples/labelmapToolGroupSpecificConfiguration/index.ts`
4. Run the example using
`yarn install`
`yarn run example labelmapToolGroupSpecificConfiguration`
5. Observe the page by commenting the promise statement in line number 334

### The current behavior

- Modifying segment color of a segmentation representation of a one tool group should not modify other tool groups.
- Currently it seems to modify colors on the same toolgroup if we add sleep  and other toolgroup without any sleep timer in the code

### The expected behavior

- changing color config of a segment should not impact other segment of different segmentation representation of same or different toolgroup
- for the example on labelmapToolGroupSpecificConfiguration, the color should be blue for one of the inner circle. instead it seems to make blue on other inner circle.

### OS

macOS 14.1.1

### Node version

14.16.0

### Browser

Chrome 119.0.6045.159

**Comment by sedghi** [comment]
Yes, it appears to be a problem. I believe the issue also occurs with the same toolgroup. For example, if you change the color of a segment in segmentation 1, it will also change in segmentation 2 within the same toolGroup. This is actually a more significant issue than the one you mentioned. Rest assured, I will address and resolve it.

By the way, I'm interested to know why you have two toolGroups. What is your specific use case?

**Comment by jithenece** [comment]
Thanks @sedghi for checking on this.

I had 4 viewports. One viewport using CT to show only tumor segmentation. Other 3 viewport using PT/CT to show tumor and organ segmentations. Using a single toolgroup, it seems we cannot achieve this. so I had to create two different toolgroups for different viewport combinations. Please let me know if there are better ways to implement this.

**Comment by sedghi** [comment]
check the latest and see if the problem occurs
