### ISSUE TITLE
[Feature Request] I I want to use script tags to reference cornerstone, I don't know what to do

### ISSUE THREAD

**Issue by David2k13** [cornerstonejs/cornerstone3D#899]
### What feature or change would you like to see made?

use

<script src="http://unpkg.com/vtk.js@27.3.1/vtk.js">
<script src="https://unpkg.com/@cornerstonejs/core@1.30.1/dist/umd/index.js"></script>

but  get =>Uncaught TypeError: Cannot read properties of undefined (reading 'BlendMode')
![image](https://github.com/cornerstonejs/cornerstone3D/assets/22017991/33cd5a81-b559-4dd7-bd20-6d4dd8014129)
Vtk.js is missing, but I don't know how to call multiple files in one dependency

### Why should we prioritize this feature?

I don't know how to get him to work, script-tag environment

**Comment by sedghi** [comment]
There is no script tag anymore

**Comment by David2k13** [comment]
> There is no script tag anymore

Understood
