### ISSUE TITLE
[Bug] TypeError: fflate.decompressSync is not a function

### ISSUE THREAD

**Issue by ChesneyB** [cornerstonejs/cornerstone3D#900]
### Describe the Bug

Hello everyone, I'm trying to replicate the NiftiBasic example in a react with typescript project described here: https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/nifti-volume-loader/examples/niftiBasic/index.ts

When i add the code and install the latest packages : 
`"dependencies": {
    "@cornerstonejs/core": "^1.29.0",
    "@cornerstonejs/nifti-volume-loader": "^1.29.0",
    "@cornerstonejs/tools": "^1.29.0",
    "@microsoft/teams-js": "1.12.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^5.0.1"
  },`

I keep getting the error from nifti.js saying :
nifti.js:143 Uncaught (in promise) TypeError: fflate.decompressSync is not a function

### Steps to Reproduce

1. Install packages
2. copy code from nifti basic example
3. run the code
4. error returns

### The current behavior

.

### The expected behavior

The error to not appear and the image to load.

### OS

macOS 14

### Node version

16

### Browser

Chrome

**Comment by TomWartm** [comment]
Hi, Is there a solution for this issue?

**Comment by ShilpaP17** [comment]
I also faced same issue. For me root cause is 'react-scripts' plugin . so I started new react project with my webpack configuration.

**Comment by ChesneyB** [comment]
> Hi, Is there a solution for this issue?

I have yet to find a solution for this problem...

**Comment by ShilpaP17** [comment]
> Hi, Is there a solution for this issue?

You can try this without 'react-scripts' plugin. for me this was the root cause. You can either eject react scripts ad have your own webpack configuration or start new sample with  webpack configuration from scratch.

**Comment by sedghi** [comment]
I have nifti work in a vite env so you can take a look [https://github.com/cornerstonejs/vite-react-cornerstone3d/blob/main/src/Nifti.tsx](https://github.com/cornerstonejs/vite-react-cornerstone3d/blob/main/src/Nifti.tsx)
