### ISSUE TITLE
[Bug] One remaining circular dependency

### ISSUE THREAD

**Issue by salimkanoun** [cornerstonejs/cornerstone3D#901]
### Describe the Bug

Reported it for records, will look at it asap

`Export "default" of module ".yarn/cache/@cornerstonejs-core-npm-1.30.1-f0f5e594e2-c5f862d85f.zip/node_modules/@cornerstonejs/core/dist/esm/cache/classes/ImageVolume.js" was reexported through module ".yarn/cache/@cornerstonejs-core-npm-1.30.1-f0f5e594e2-c5f862d85f.zip/node_modules/@cornerstonejs/core/dist/esm/cache/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.`

### Steps to Reproduce

While building a project incuding cornerstone with vite / rollup

### The current behavior

cicular dep alert

### The expected behavior

should not have circular deps

### OS

Linux

### Node version

20

### Browser

Chrome

**Comment by sedghi** [comment]
I'm working on cornerstone3D 2.x and have made progress in removing circular dependencies and publishing the types for the DICOM image loader. I'm trying to make it work with Vite, but there are numerous issues with Vite in `dev` mode, which are not directly related to Cornerstone. Multiple mentions of Vite problems with `import.meta.url`, web workers, and WebAssembly can be found on the Vite GitHub repository:

https://github.com/vitejs/vite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+import.meta.url

I have started a template project for Vite, React, and cornerstone3D beta 2.x here. I appreciate your help in making it work.

https://github.com/cornerstonejs/vite-react-cornerstone3d
