### ISSUE TITLE
[Bug] Uncaught runtime errors:Cannot read properties of undefined (reading 'tier') 

### ISSUE THREAD

**Issue by Benjamin-JZ** [cornerstonejs/cornerstone3D#903]
### Describe the Bug

![image](https://github.com/cornerstonejs/cornerstone3D/assets/110522612/59ce6095-81b8-451c-8e36-153bceb285a5)

![image](https://github.com/cornerstonejs/cornerstone3D/assets/110522612/6aa0fe0e-4019-47ef-95af-caf94786b858)

### Steps to Reproduce

I useing the Original @cornerstone3D module. this bug show interface when i trying to reproduce demo.
you can see the following picture . i have no idea for this.I am following the  tutorial code.
below code:
    async function run() {

      await initDemo();
            const imageIds = await createImageIdsAndCacheMetaData({
        StudyInstanceUID:
          '1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463',
        SeriesInstanceUID:
          '1.3.6.1.4.1.14519.5.2.1.7009.2403.226151125820845824875394858561',
        wadoRsRoot: 'https://d3t6nz73ql33tx.cloudfront.net/dicomweb',
      });
      // Final code
      const content = document.getElementById('content');
      const element = document.createElement('div');
      element.style.width = '500px';
      element.style.height = '500px';
      content.appendChild(element);
      const renderingEngineId = 'myRenderingEngine';
      const viewportId = 'CT_AXIAL_STACK';
      const renderingEngine = new RenderingEngine(renderingEngineId);

      const viewportInput = {
        viewportId,
        element,
        type: ViewportType.STACK,
      };
      addTool(StackScrollMouseWheelTool);
      const toolGroupId = 'myToolGroup';
      const toolGroup = ToolGroupManager.createToolGroup(toolGroupId);
      renderingEngine.enableElement(viewportInput);
      const viewport = renderingEngine.getViewport(viewportInput.viewportId);
      toolGroup.addTool(StackScrollMouseWheelTool.toolName);
      toolGroup.setToolActive(StackScrollMouseWheelTool.toolName, {
        bindings: [
          {
            mouseButton: csToolsEnums.MouseBindings.Auxiliary, // Scroll
          },
        ],
      });
      toolGroup.addViewport(viewportId, renderingEngineId);
      viewport.setStack(imageIds, 60);
      viewport.render();
    }
    run();
### The current behavior
you see ,I can scroll the imageIds stack, But this Error still happen.
![image](https://github.com/cornerstonejs/cornerstone3D/assets/110522612/1162be2b-4009-48e3-a677-235daf68016a)

![image](https://github.com/cornerstonejs/cornerstone3D/assets/110522612/7d841c13-2bfe-4ee1-92a8-5b706430faf3)

### The expected behavior

avoid this situation?

### OS

windows

### Node version

16

### Browser

edge

**Comment by clyy21** [comment]
I am also having the same problem 
![6b16312a78606432d29e3715a065cef](https://github.com/cornerstonejs/cornerstone3D/assets/87967038/e5d32c67-6921-4c5e-b2c4-547647e44dfb)
