### ISSUE TITLE
[Bug] dicom-image-loader: createImage uses now undefined options.decodeConfig

### ISSUE THREAD

**Issue by abustany** [cornerstonejs/cornerstone3D#916]
### Describe the Bug

Commit 85fd19396762f54c6806fdbebf0235139a67629a removed the `decodeConfig` member from `option.ts` (see the [diff](https://github.com/cornerstonejs/cornerstone3D/commit/85fd19396762f54c6806fdbebf0235139a67629a#diff-e57248382b32a7b27c5f623a355ac3b70d23e1f2a06ec86d2aba5c41ae91130d) ), however that code is still [used in createImage.ts](https://github.com/cornerstonejs/cornerstone3D/blob/v1.34.0/packages/dicomImageLoader/src/imageLoader/createImage.ts#L145), at least in version 1.34.0.

### Steps to Reproduce

1. Upgrade to Cornerstone 1.34
2. Load a DICOM image (in my case through a stack viewport)

### The current behavior

Error: `createImage.ts:155 Uncaught (in promise) TypeError: Cannot destructure property 'use16BitDataType' of 'l2' as it is undefined.`

### The expected behavior

The image should load

### OS

Linux

### Node version

18.16.1

### Browser

Chromium 119.0.6045.159, Firefox 120.0b9

**Comment by abustany** [comment]
For now I can workaround this bug doing the following in my Cornerstone init routine - not sure how safe that is:
```typescript
  cornerstoneDICOMImageLoader.internal.setOptions({
    strict: false,
    decodeConfig: {
      convertFloatPixelDataToInt: true,
      use16BitDataType: false,
    },
  });
```

**Comment by wayfarer3130** [comment]
@sedghi - yes, that was touched by Chris I think.  There was an issue with having it in the decoder rather than in the params on the individual decode that was causing problems.

**Comment by sedghi** [comment]
@abustany Can you create a PR for this and revert the changes?

**Comment by abustany** [comment]
sure, will do

**Comment by abustany** [comment]
ah I missed that #926 also reverts the changes :see_no_evil: oh well, feel free to close #929 then, if #926 gets merged first.
