### ISSUE TITLE
[Feature Request] Is there a way to calculate the intersection of a polygon and a line

### ISSUE THREAD

**Issue by tineke01** [cornerstonejs/cornerstone3D#921]
### What feature or change would you like to see made?

Is there a way to calculate the intersection of a polygon and a line

### Why should we prioritize this feature?

Is there a way to calculate the intersection of a polygon and a line

**Comment by sedghi** [comment]
@lscoder might now, we might have a utility for it

**Comment by tineke01** [comment]
I have solved the problem,Two methods were used,1.getClosestIntersectionWithPolyline & intersectLine
