### ISSUE TITLE
[Bug] PT Image display error

### ISSUE THREAD

**Issue by katiton** [cornerstonejs/cornerstone3D#925]
### Describe the Bug

[1.000000-PET AC-81015.zip](https://github.com/cornerstonejs/cornerstone3D/files/13544781/1.000000-PET.AC-81015.zip)
PT Image display error

### Steps to Reproduce

The image file is as above, and the problem is as follows.
I don't know how to fix it.

### The current behavior

![image](https://github.com/cornerstonejs/cornerstone3D/assets/78404277/53114aac-b18b-4ee5-941a-4382ae7ce3e9)

### The expected behavior

![)3SDAO {(WPIC@XDY3L`G2X](https://github.com/cornerstonejs/cornerstone3D/assets/78404277/513fee7c-fd89-42b0-9031-82ce62dd9438)

### OS

win11

### Node version

16.20.2

### Browser

Microsoft Edge 119.0.2151.93

**Comment by sedghi** [comment]
This looks fine when you drag and drop it in our local example https://www.cornerstonejs.org/live-examples/local.html
 so it means your metadata provider is wrong

**Comment by katiton** [comment]
I'm using the same data source to view the image on OHIF and RadiAnt, it shows as normal.
That means the image is not corrupted.

**Comment by sedghi** [comment]
Did you try drag and drop in the link above?

**Comment by katiton** [comment]
Put it in the live-examples，it looks like this
![W$I%F1K35}_YWC3DVKZ)4TM](https://github.com/cornerstonejs/cornerstone3D/assets/78404277/51f7b454-4628-485c-90a4-935b1c7ac62a)

**Comment by sedghi** [comment]
which slice? maybe i"m not putting the same slice, since when I tried one random one it was fine, which filename?

**Comment by katiton** [comment]
1-001
[1-001.zip](https://github.com/cornerstonejs/cornerstone3D/files/13555228/1-001.zip)

**Comment by sedghi** [comment]
I can't reproduce this bug anymore, can you verify as well?

**Comment by katiton** [comment]
After i  added `calculate-suv` to provider, the image was right
