### ISSUE TITLE
List of points of segmentation

### ISSUE THREAD

**Issue by Sergey1888888** [cornerstonejs/cornerstone3D#947]
### What feature or change would you like to see made?

Is it possible to get list of points of segmentation using https://www.cornerstonejs.org/live-examples/labelmapsegmentationtools?
I need it to save segmentation. If it impossible, can you add this feature?

### Why should we prioritize this feature?

Useful for saving segmentations.

**Comment by Sergey1888888** [comment]
@sedghi Can you help, please?

**Comment by sedghi** [comment]
you have that in the cache, use `cache.getVolume(volumeId)` of the labelmap to get the volume, there you have the scalarData

**Comment by Sergey1888888** [comment]
Is it possible to set saved segmentation or points of segmentation to viewport?

**Comment by Sergey1888888** [comment]
> you have that in the cache, use `cache.getVolume(volumeId)` of the labelmap to get the volume, there you have the scalarData

I mean, how can I save the segmentation that I did using, for example, CircularBrush? To be able to later insert this saved segmentation using addSegmentations. I don't understand where scalarData is being inserted and it's like it's not what is needed. Or is there no way to save a labelmap now? Because contour is easy and clear how to save and display, but it's not exactly what I need.

**Comment by Sergey1888888** [comment]
I figured out how to do it. Thank you @sedghi!
