### ISSUE TITLE
https://unpkg.com/detect-gpu@5.0.37/dist/benchmarks/d-nvidia.json

### ISSUE THREAD

**Issue by xunchangchang** [cornerstonejs/cornerstone3D#949]
### Describe the Bug

May I ask what this request file is for? It always takes a long time to request and may even fail. How can I solve this problem

### Steps to Reproduce

Just enter the page

### The current behavior

![image](https://github.com/cornerstonejs/cornerstone3D/assets/87689435/2dbda542-d611-4376-a5ff-af366c6c2725)

### The expected behavior

How to terminate this request, or how to make the request speed faster

### OS

Window 10

### Node version

v16.14.0

### Browser

Chrome 120.0.6099.71

**Comment by html5shiv** [comment]
I have also encountered this problem，hope the official solution

**Comment by html5shiv** [comment]
import { init as csRenderInit } from '@cornerstonejs/core';
  await csRenderInit({
    detectGPUConfig: { benchmarksURL: '../../../node_modules/detect-gpu/dist/benchmarks' },
  });


like this, you can change config and import local file

**Comment by sedghi** [comment]
This is for GPU tier identification to decide whether to GPU render vs CPU render
