### ISSUE TITLE
[Bug] renderingEngine.render() not work.

### ISSUE THREAD

**Issue by Benjamin-JZ** [cornerstonejs/cornerstone3D#952]
### I want to Display some segmentation corresponding this Series.

> **I originally intended to through the modify the underlying float32Array and then call renderingEngine.render to finish this thing.**
> **But result was  it doesn't work like as I think.**
> below was **some detail**.

### Steps to Reproduce

here was add and enable code:
```
      addTool(SegmentationDisplayTool);
      toolGroup.addTool(SegmentationDisplayTool.toolName);
      toolGroup.setToolEnabled(SegmentationDisplayTool.toolName);
      //after modify code...
      renderingEngine.render();
```
![image](https://github.com/cornerstonejs/cornerstone3D/assets/110522612/800be70f-f792-4cb9-b2c8-ed84f78579dd)

**I think I already correctly and rightly useing the document code.**
**I can't understand what happen it didn't work.**

**I will really appreciate that if someone help me!**

### The current behavior

I have checked the underlying Array info.It does change.
and The change will appear when I useing the BrushTool through the left keys to draw image.like following picture 
![image](https://github.com/cornerstonejs/cornerstone3D/assets/110522612/e0456f2d-8df6-4914-8f0a-1c74c2dfb343)

above was I can provide useful infomation presently.

### The expected behavior

after change,the new segment status can display without click event.
Thanks!

### OS

win

### Node version

16

### Browser

chrome

**Comment by CYB3RL1F3** [comment]
Look like having the same problem but maybe it's not the root cause, maybe it's a misusage of the library. Do you understand anything about this documentation and example? ahahah
I put some geometrics to have points, then I create segmentations and segmentations representations, and then call this and nothing works ahahah!
