### ISSUE TITLE
Documentation is not clear and impossible to understand/ How to draw segmentations ?

### ISSUE THREAD

**Issue by CYB3RL1F3** [cornerstonejs/cornerstone3D#953]
### Describe the Bug

Hello,

Sorry for the noob question if it appears like this but I'm really misunderstanding how to properly draw segmentations on the image.

I have a set of points to draw a segmentation, but there is nothing that explicitely explain how I can put my points, or I don't understand anything...

Can someone simply explain me from scratch how I can apply my array of { x , y } to a visible segmentations with color (fill and stroke), etc ?

As well how to link segmentation representations, segmentations, tool, view... I tried lots of thing following the documentation but nothing appears on the image. I'd like to work it both for stack and volume views.

Thank you.

### Steps to Reproduce

Just explain me how it works concretely. The documentation examples are buggy with undeclared and unexplained variables, and the examples are working but the code is not given......

### The current behavior

Documentation is impossible to understand

### The expected behavior

A concise explaination about how to draw segmentations from scratch with examples without undeclared variables, imports etc...

### OS

Mac OS 

### Node version

20.0.0

### Browser

Chrome

**Comment by CYB3RL1F3** [comment]
I would love to get the code for this example for example:

https://www.cornerstonejs.org/live-examples/contourrendering

**Comment by Sergey1888888** [comment]
You can read code if open console and click on index.ts
![image](https://github.com/cornerstonejs/cornerstone3D/assets/46000753/e6285597-5a33-413c-8ba7-8dd37b2c728a)

Or you can clone cornerstone3D and there are examples folder.

**Comment by CYB3RL1F3** [comment]
Thx. But it doesn't help completely.
In your example you're working with contours and I did the same but it doesn't work by my side and I can't understand why...

I'd like a tutorial, not just code, but a complete explaination of each steps , with example of codes, how to have this result. From scratch. Talk to us like if we were total ignorant... :/ 

Here are snippets of my code I coded following your tutorial and example of code. NOT WORKING!!!! 
What misses??? Can you explain to me what misses??

```
useEffect(() => {
    const effect = async () => {
      if (!viewport || !renderingEngine || toolGroup || !isReady) return;
      // Define tool groups to add the segmentation display tool to
      const toolGrp = initTools(toolGroupId); // THIS CONTAINS new ToolGroup and toolGroup.addTool(SegmentationDisplayTool) and more...
      if (!toolGrp) return;
      toolGrp.setToolEnabled(SegmentationDisplayTool.toolName);
      toolGrp.setToolActive(SegmentationDisplayTool.toolName);

      toolGrp.addViewport(viewport.id, renderingEngine.id);

      setToolGroup?.(toolGrp);

      const segmentationVolume = await volumeLoader.createAndCacheDerivedVolume(
        volumeId,
        {
          volumeId: segmentationId
        }
      );
      setSegmentationVolumes((volumes) => ({
        ...volumes,
        [segmentationId]: segmentationVolume
      }));

        if (!segmentations?.length) return;
        const geometryIds = await segmentations.reduce<Promise<string[]>>(
          async (segs, segmentation) => {
            const acc = await segs;
            const { color, slices, id } = segmentation;
            if (_segmentation.state.getSegmentation(id)) {
              return acc;
            }
            if (!slices?.[sliceId]?.contours) return [];
            const geometryIds = await Promise.all(
              slices[sliceId].contours
                ?.map(async (contour, index) => {
                  const c = contour[index];
                  if (!c) return "";
                  const points =
                    getSegmentationPoints(slices, sliceId, index)?.map(
                      (point) => [point.x, point.y, sliceId] as Point3
                    ) || [];
                  const { r, g, b } = hexToRgb(color.fill);

                  const geometryData: ContourSetData = {
                    id: `${id}:${Math.round(c.x)}:${Math.round(c.y)}`,
                    frameOfReferenceUID: v4(),
                    color: [r, g, b],
                    data: slices.map((slice, index) => ({
                      points,
                      color: [r, g, b],
                      type: ContourType.CLOSED_PLANAR,
                      segmentIndex: index
                    }))
                  };
                  const geometry = await geometryLoader.createAndCacheGeometry(
                    geometryData.id,
                    {
                      type: GeometryType.CONTOUR,
                      geometryData
                    }
                  );
                  // geometry.data.frameOfReferenceUID
                  return geometry.id;
                })
                .filter(async (value) => !!(await value))
            );

            return geometryIds;
          },
          Promise.resolve([])
        );

        if (geometryIds?.length) {
          // _segmentation.addSegmentations(segmentationInputArray);
          const segmentationId = "SEGMENTATION_ID_" + sliceId;
          const segmentation: SegmentationPublicInput = {
            segmentationId,
            representation: {
              type: Enums.SegmentationRepresentations.Contour,
              data: {
                geometryIds
              } satisfies ContourSegmentationData
            }
          };
          const existingSegmentation =
            _segmentation.state.getSegmentation(segmentationId);
          if (existingSegmentation) {
            _segmentation.state.removeSegmentation(segmentationId);
          }
          _segmentation.state.addSegmentation(segmentation);
          
          const ids = await _segmentation.addSegmentationRepresentations(
            toolGroupId,
            [
              {
                segmentationId,
                type: Enums.SegmentationRepresentations.Contour
              }
            ],
            {
              renderInactiveSegmentations: false,
              representations: {
                CONTOUR: {
                  outlineWidthActive: 1,
                  outlineWidthInactive: 1,
                  outlineOpacity: 0.7,
                  outlineOpacityInactive: 1,
                  renderOutline: true,
                  renderFill: true,
                  fillAlpha: 1,
                  fillAlphaInactive: 1
                }
              }
            }
          );

          _segmentation.state.addSegmentationRepresentation(toolGroupId, {
            segmentationId,
            segmentationRepresentationUID: ids[0],
            type: Enums.SegmentationRepresentations.Contour,
            active: true,
            segmentsHidden: new Set([]),
            colorLUTIndex: 0,
            config: {}
          });

          _segmentation.activeSegmentation.setActiveSegmentationRepresentation(
            toolGroupId,
            ids[0]
          );
          
          console.log(
            "STATE >> ",
            _segmentation.state.getSegmentationRepresentations(toolGroupId),
            _segmentation.state.getSegmentations(),
            _segmentation.activeSegmentation.getActiveSegmentationRepresentation(
              toolGroupId
            )
          );
        }
      };

      setToolReady(true);
    };
    
    effect();
    }
 
 ```

Also, I'd like those contours to be editable with the brush tool. Is it possible? I tried to add annotation with the points but same s**t...

I also tried with labelmap but I don't understand how I can add labelmap... I have some labelmaps array but I don't know how to add them in the state of segmentation...

It's a real pain point, your library is very very difficult to understand and use... :/ Need real help :( thanks!

**Comment by CYB3RL1F3** [comment]
I got this error : 

updateContourSets.ts:75 Uncaught (in promise) TypeError: Cannot destructure property 'data' of 'geometry' as it is undefined.
    at geometryIds.reduce.contourSets (updateContourSets.ts:75:21)
    at Array.reduce (<anonymous>)
    at updateContourSets (updateContourSets.ts:72:63)
    at addOrUpdateContourSets (addOrUpdateContourSets.ts:21:3)
    at Object.render2 [as render] (contourDisplay.ts:85:3)
    at SegmentationDisplayTool.ts:157:44
    at Array.map (<anonymous>)
    at SegmentationDisplayTool.renderSegmentation (SegmentationDisplayTool.ts:142:73)

**Comment by Sergey1888888** [comment]
@sedghi

**Comment by CYB3RL1F3** [comment]
How can I use labelmap instead? A tutorial?
I have the labelmap data available as well in my data (not only points). I just don't understand how I can use them to generate segmentations, and also I'd like to make them editable with brush. Thanks

**Comment by sedghi** [comment]
There are at least 10+ examples on how to use labelmaps, look here  https://www.cornerstonejs.org/docs/examples
In the source code, each of them has examples/ folder for the source code
