### ISSUE TITLE
[Feature Request] Customize Segmentation Tools for drawing irregular shapes with a click and fill color.

### ISSUE THREAD

**Issue by 1321442780** [cornerstonejs/cornerstone3D#954]
### What feature or change would you like to see made?

He can have the same functionality as BrushTool, where users can customize and click to draw irregular shapes.

### Why should we prioritize this feature?

Currently, through our research, users prefer this feature as it is more convenient and efficient.

**Comment by sedghi** [comment]
What kind of shapes? Can you provide video of what you have tried else where?
