### ISSUE TITLE
[Bug] Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by duan-jy** [cornerstonejs/cornerstone3D#956]
### Describe the Bug

Class extends value undefined is not a constructor or null
![1702954910746](https://github.com/cornerstonejs/cornerstone3D/assets/52345567/830c2fb6-33da-4d50-9542-1cdc6bfd40c7)

### Steps to Reproduce

The previous version 1.28.3 was normal, but I encountered this issue after upgrading to the latest 1.41.0

### The current behavior

It should be normal

### The expected behavior

It should be normal

### OS

Windows 10

### Node version

17.0.1

### Browser

Chrome 120.0.6099.72

**Comment by sedghi** [comment]
Weird, can you try latest latest?

**Comment by lambacini** [comment]
i encountered the same problem when i used vite (with angular 17) instead of webpack
(I tried with the 1.42.0) 

![image](https://github.com/cornerstonejs/cornerstone3D/assets/943188/c887d66f-7af0-4356-88d9-01814ec94701)

**Comment by sedghi** [comment]
This is weird, do you have a mini repo to reproduce the bug?
