### ISSUE TITLE
[Feature Request] Contour tools

### ISSUE THREAD

**Issue by Sergey1888888** [cornerstonejs/cornerstone3D#965]
### What feature or change would you like to see made?

Will there be segmentation tools with contour instead of labelmap?
I don't quite understand what the difference is between contour and labelmap? Except that the contour uses Geometry and the labelmap uses Volume.

### Why should we prioritize this feature?

Can you make tools with contour too?

**Comment by sedghi** [comment]
There is a big push for this right now. You can try this example, and lot more coming very soon

https://www.cornerstonejs.org/live-examples/planarfreehandcontoursegmentationtool

![CleanShot 2024-01-10 at 08 58 21](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/f25f97dc-c2da-413f-a720-8de8b7049dc8)
