### ISSUE TITLE
[Bug] viewport.setProperties({ invert }) works differently with StackViewport and VolumeViewport

### ISSUE THREAD

**Issue by vnosikov** [cornerstonejs/cornerstone3D#975]
### Describe the Bug

Setting invert via `setProperties` works differently in `StackViewport` and `VolumeViewport`.

In StackViewport `viewport.setProperties({ invert: true })` set an invert value of a viewport to true

In StackViewport `viewport.setProperties({ invert: false })` set an invert value of a viewport to false

In VolumeViewport `viewport.setProperties({ invert: true })` toggles an invert value of a viewport (so true becomes false and vice versa) 

In VolumeViewport `viewport.setProperties({ invert: false })` does nothing

Looks like `VolumeViewport` implements it incorrectly. In any case I'd expect the same behavior in different viewports.

### Steps to Reproduce

The easiest way to reproduce this bug is to open official examples and use commands from a console

https://www.cornerstonejs.org/live-examples/volumeapi for VolumeViewport
https://www.cornerstonejs.org/live-examples/stackapi for StackViewport

1. Open https://www.cornerstonejs.org/live-examples/volumeapi, open console
2. `cornerstone.getRenderingEngines()[0].getViewports()[0].setProperties({ invert: true});`
3. `cornerstone.getRenderingEngines()[0].getViewports()[0].render()`
4. Notice that the colors are inverted
5. `cornerstone.getRenderingEngines()[0].getViewports()[0].setProperties({ invert: false});`
6. `cornerstone.getRenderingEngines()[0].getViewports()[0].render()`
7. Notice that nothing has changed
8. `cornerstone.getRenderingEngines()[0].getViewports()[0].setProperties({ invert: true});`
9. `cornerstone.getRenderingEngines()[0].getViewports()[0].render()`
10. Notice that the colors are inverted back to normal

### The current behavior

VolumeViewport `setProperties({ invert: true })` toggles invert value instead of setting it to true
VolumeViewport `setProperties({ invert: true })` does nothing at all

### The expected behavior

The expected behavior can be seen with StackViewport

1. Open https://www.cornerstonejs.org/live-examples/stackapi, open console
2. `cornerstone.getRenderingEngines()[0].getViewports()[0].setProperties({ invert: true});`
3. `cornerstone.getRenderingEngines()[0].getViewports()[0].render()`
4. Notice that the colors are inverted
5. `cornerstone.getRenderingEngines()[0].getViewports()[0].setProperties({ invert: false});`
6. `cornerstone.getRenderingEngines()[0].getViewports()[0].render()`
7. Notice that the colors are inverted back to normal
8. `cornerstone.getRenderingEngines()[0].getViewports()[0].setProperties({ invert: true});`
9. `cornerstone.getRenderingEngines()[0].getViewports()[0].render()`
10. Notice that the colors are inverted again

### OS

Ubuntu 22.04

### Node version

20.10.0

### Browser

Firefox 119.0.1

**Comment by sedghi** [comment]
Hmmm, good catch

**Comment by html5shiv** [comment]
niu bi
