### ISSUE TITLE
[Bug] Segmentation no display  when patient position is FFS

### ISSUE THREAD

**Issue by robustNan** [cornerstonejs/cornerstone3D#977]
### Describe the Bug

Hello, I found  a display fault when the patient position is FFS, which has an orientation cosine of [1, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1], there is a problem with segmentation not rendering. My viewport type is 'orthographic', I tried setting the viewport orientation to 'axial' and { viewPlaneNormal: [0, 0, -1], viewUp: [0, 1, 0] }, but neither had any effect. I've also browsed labelmapDisplay.ts doesn't seem to see anything that would be affected by orientation

### Steps to Reproduce

1. volumeLoader.createAndCacheVolume //series volume
2. volumeLoader.createAndCacheDerivedVolume //segmentation volume

### The current behavior

![axial](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/5304a327-7565-4843-b208-399f0fc96985)
patient position is FFS, viewport orientation is 'axial'

![custom-viewup](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/7cdbe210-d25e-4ecf-91fc-3bbf02ab81c6)
patient position is FFS, viewport orientation is { viewPlaneNormal: [0, 0, -1], viewUp: [0, 1, 0] }

![normal](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/143dc898-a161-4925-93e1-a03fc6d8cfeb)
patient position is HFS,  viewport orientation is 'axial'

### The expected behavior

display segmentation

### OS

windows 11

### Node version

16.20.2

### Browser

Chrome 120.0.6099.130, Microsoft Edge 120.0.2210.91

**Comment by sedghi** [comment]
If you have the data to share maybe we can take a look

Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by robustNan** [comment]
@sedghi I would be happy to provide the data. I sent the file to your gmail because the zip was too big. If there are any questions about the data feel free to contact me and I will respond promptly!

**Comment by robustNan** [comment]
I upgraded the version to 1.44.1 and tried the series provided in #961 , and it still doesn't show the contour. I think maybe there is a problem with my code
[code.zip](https://github.com/cornerstonejs/cornerstone3D/files/13901166/code.zip)

![normal](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/a24fef94-1055-4f50-aeca-574ae49f2e04)

**Comment by sedghi** [comment]
Unfortunately, I don't have the bandwidth to review your code at the moment. However, could you please check if there are any errors? Also, please make sure you are using the latest version.

**Comment by robustNan** [comment]
I found the reason why Segmentation is not rendering properly in my code, the fillAlpha value I set was too small, when I changed it to 0.1 everything became normal (include FFS and FFP). But I can't understand why the fillAlpha affects the display of the outLine?
![image](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/ba4bec04-9c6a-464c-9c78-f77bf6fd9790)
![image](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/6070f974-c688-44be-8a60-0163082e35ed)
![image](https://github.com/cornerstonejs/cornerstone3D/assets/31467519/fca2ad91-7089-4818-85d3-2342471b9632)
