### ISSUE TITLE
[Bug]Window Level Tool  is not working properly

### ISSUE THREAD

**Issue by idemopacs** [cornerstonejs/cornerstone3D#979]
### Describe the Bug

Window level tool not working properly on some images with original voiRange value like {lower: -0.36, upper: 1.02}.
Getting error in console : 'attempt to set zero width color range'
[image.zip](https://github.com/cornerstonejs/cornerstone3D/files/13818101/image.zip)

### Steps to Reproduce

1. Open attached image here -[https://www.cornerstonejs.org/live-examples/local]
2. Change window level by dragging mouse over the image

### The current behavior

Window level is not changing properly.
Getting error in browser console -  'attempt to set zero width color range'

### The expected behavior

Window level should apply properly

### OS

Windows 10

### Node version

v16.17.1

### Browser

Chrome 114.0.5735.134

**Comment by sedghi** [comment]
I don't see any issue here https://www.cornerstonejs.org/live-examples/local.html
Can you record a video?
