### ISSUE TITLE
[Bug] Random viewports show black screen

### ISSUE THREAD

**Issue by Sergey1888888** [cornerstonejs/cornerstone3D#994]
### Describe the Bug

After the [1.43.0](https://github.com/cornerstonejs/cornerstone3D/compare/v1.42.1...v1.43.0) update, specifically due to the vtk.js update to 29.3.0, bugs began to appear.
I have several viewports displayed and some of them have stopped displaying images. As I noticed, in those viewports that do not have an image, there is not a single actor, not even defaultActor. It's possible that this is the problem.
What could be causing this?

### Steps to Reproduce

1. Create several StackViewports.
2. Add images to it.

### The current behavior

Random StackViewports show black screen.

### The expected behavior

All StackViewports show images.

### OS

Windows 10

### Node version

18.18.2

### Browser

Chrome 120.0.6099.216

**Comment by Sergey1888888** [comment]
And in CPU rendering all viewports works fine.

**Comment by sedghi** [comment]
How many viewports should I create to reproduce? can you create a minimal example?

**Comment by Sergey1888888** [comment]
I have 8. I will try to create an example.

**Comment by Sergey1888888** [comment]
@sedghi  It depends on the image. I can't upload my image, but this bug due to this [commit](https://github.com/Kitware/vtk-js/commit/3cc3abb871cabb79831d26bb268990549ef6ca59)

**Comment by Sergey1888888** [comment]
After image.getPixelData() some images have type `Uint8ClampedArray` and them always go to this throwing exception in commit above.

**Comment by Sergey1888888** [comment]
I don't quite understand how `image.getPixelData()` defines the type. Some images have `Int16Array`, some `Uint8Array` and some `Float32Array`.

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by Sergey1888888** [comment]
Sorry, I wasn't allowed to send image 😢

**Comment by sedghi** [comment]
@Sergey1888888 What happened?

**Comment by Sergey1888888** [comment]
We found out that something was wrong with the processed images
